import { pgEnum, timestamp, varchar } from 'drizzle-orm/pg-core';

// ============================================================================
// ENUM TYPES FOR ENRICHMENT COLUMNS
// ============================================================================

export const dataSourceEnum = pgEnum('data_source', ['real', 'mock', 'enriched']);
export const dataQualityEnum = pgEnum('data_quality', ['high', 'medium', 'low']);

// ============================================================================
// ENRICHMENT COLUMN DEFINITIONS
// ============================================================================

/**
 * Columns to add to existing tables for data enrichment tracking.
 * These columns enable distinguishing between real user data, mock seed data,
 * and AI-enriched synthetic data.
 */

export const enrichmentColumns = {
	/**
	 * Source of the data:
	 * - 'real': Generated by actual user activity
	 * - 'mock': Synthetic seed data for testing/demos
	 * - 'enriched': AI-generated or algorithmically enriched data
	 */
	dataSource: varchar('data_source', { length: 20 }).notNull().default('real'),

	/**
	 * Timestamp when the data was enriched (null for real/mock data)
	 */
	enrichedAt: timestamp('enriched_at'),

	/**
	 * Quality rating of the data:
	 * - 'high': Verified, high-confidence data
	 * - 'medium': Reasonably accurate, may need review
	 * - 'low': Low confidence, requires validation
	 */
	dataQuality: varchar('data_quality', { length: 10 }).notNull().default('high'),
};

// ============================================================================
// TARGET TABLES FOR ENRICHMENT COLUMNS
// ============================================================================

/**
 * List of table names that should receive enrichment columns.
 * These tables track user activity, learning progress, and engagement data
 * that benefit from source/quality tracking.
 */
export const enrichmentTargetTables = [
	'quiz_results',
	'study_sessions',
	'topic_mastery',
	'user_progress',
	'flashcard_reviews',
	'notifications',
	'calendar_events',
	'ai_conversations',
	'channels',
	'channel_members',
] as const;

export type EnrichmentTargetTable = (typeof enrichmentTargetTables)[number];
export type DataSource = 'real' | 'mock' | 'enriched';
export type DataQuality = 'high' | 'medium' | 'low';
