export { FAQSection } from './FAQSection';
export { FeaturesSection } from './FeaturesSection';
export { FinalCTASection } from './FinalCTASection';
export { HeroSection } from './HeroSection';
export { HowItWorksSection } from './HowItWorksSection';
export { PricingSection } from './PricingSection';
export { StatsSection } from './StatsSection';
export { SubjectsSection } from './SubjectsSection';
export { TestimonialsSection } from './TestimonialsSection';
