export const maleFirstNames = [
	'Amara',
	'Themba',
	'Luka',
	'Kabelo',
	'Siyabonga',
	'Thabo',
	'Mziwabisa',
	'Bandile',
	'Nkosinathi',
	'Sizwe',
	'Mandla',
	'Bongani',
	'Lindani',
	'Lerato',
	'Tshiamo',
	'Obakeng',
	'Omafipana',
	'Othusitse',
	'O Diret',
	'Kagiso',
	'Retselisitsoe',
	'Tumelo',
	'Kamogelo',
	'Karabo',
	'Neo',
	'Ethan',
	'Liam',
	'Noah',
	'Mason',
	'James',
	'Benjamin',
	'Lucas',
	'Michael',
	'Ethan',
	'Jacob',
	'Alexander',
	'Daniel',
	'William',
	'Jakob',
	'Samuel',
	'Joseph',
	'David',
	'Luke',
	'Matthew',
	'Andrew',
	'Timothy',
];

export const femaleFirstNames = [
	'Amara',
	'Nia',
	'Zuri',
	'Aaliyah',
	'Zoe',
	'Chloe',
	'Sophia',
	'Isabella',
	'Mia',
	'Charlotte',
	'Amelia',
	'Harper',
	'Evelyn',
	'Abigail',
	'Emily',
	'Elizabeth',
	'Sofia',
	'Avery',
	'Ella',
	'Scarlett',
	'Grace',
	'Chloe',
	'Victoria',
	'Riley',
	'Aria',
	'Lily',
	'Aurora',
	'Zoey',
	'Penelope',
	'Layla',
	'Clara',
	'Raelynn',
	'Kehinde',
	'Folake',
	'Adaeze',
	'Anita',
	'Nneka',
	'Chidinma',
	'Temi',
	'Adaora',
	'Ivory',
	'Onyekachi',
	'Uchechi',
	'Chiamaka',
	'Ngozi',
];

export const neutralFirstNames = [
	'Amara',
	'Kea',
	'Rori',
	'Daley',
	'Talbot',
	'Skyler',
	'River',
	'Phoenix',
	'Hayden',
	'Cameron',
	'Casey',
	'Avery',
	'Jordan',
	'Alexis',
	'Quinn',
	'Reese',
	'Robin',
	'Parker',
	'Blake',
	'Morgan',
	'Jamie',
	'Dakota',
	'Finley',
	'Emery',
	'Sage',
	'Phoenix',
];

export const surnames = [
	'Khumalo',
	'Ndlovu',
	'Mokoena',
	'Dlamini',
	'Ngubane',
	'Sibanda',
	'Mthethwa',
	'Buthelezi',
	'Mkhize',
	'Zulu',
	'Nsimini',
	'Mabuya',
	'Shabalala',
	'Nkosi',
	'Mthembu',
	'Radebe',
	'Van der Merwe',
	'Smith',
	'Johnson',
	'Williams',
	'Brown',
	'Jones',
	'Davis',
	'Miller',
	'Wilson',
	'Moore',
	'Taylor',
	'Anderson',
	'Thomas',
	'Jackson',
	'White',
	'Harris',
	'Martin',
	'Thompson',
	'Garcia',
	'Martinez',
	'Robinson',
	'Clark',
	'Rodriguez',
	'Lee',
	'Walker',
	'Hall',
	'Allen',
	'Young',
	'Hernandez',
	'King',
	'Wright',
	'Lopez',
	'Hill',
	'Scott',
	'Green',
	'Adams',
	'Baker',
	'Gonzalez',
	'Nelson',
	'Carter',
	'Mitchell',
	'Perez',
	'Roberts',
	'Turner',
	'Phillips',
	'Campbell',
	'Parker',
	'Evans',
	'Edwards',
	'Collins',
];

export const subjects = [
	{ slug: 'mathematics', name: 'Mathematics', weight: 25 },
	{ slug: 'physics', name: 'Physical Sciences', weight: 20 },
	{ slug: 'english', name: 'English FAL', weight: 18 },
	{ slug: 'history', name: 'History', weight: 12 },
	{ slug: 'life-sciences', name: 'Life Sciences', weight: 10 },
	{ slug: 'geography', name: 'Geography', weight: 8 },
	{ slug: 'accounting', name: 'Accounting', weight: 4 },
	{ slug: 'economics', name: 'Economics', weight: 3 },
];

export const topicsBySubject: Record<string, string[]> = {
	mathematics: [
		'Quadratic Equations',
		'Algebraic Expressions',
		'Functions',
		'Calculus',
		'Probability',
		'Statistics',
		'Geometry',
		'Trigonometry',
		'Number Patterns',
		'Finance',
		'Exponential Equations',
		'Linear Programming',
		'Differentiation',
		'Integration',
	],
	physics: [
		'Newton Laws',
		'Momentum',
		'Work and Energy',
		'Waves',
		'Sound',
		'Light',
		'Electricity',
		'Electromagnetism',
		'Heat',
		'Optics',
		'Dynamics',
		'Kinematics',
	],
	english: [
		'Comprehension',
		'Essay Writing',
		'Summary',
		'Poetry Analysis',
		'Novel Study',
		'Language Structures',
		'Visual Literacy',
		'Transactional Writing',
	],
	history: [
		'World War I',
		'World War II',
		'Cold War',
		'Civil Rights Movement',
		'Decolonization',
		'Apartheid',
		'Industrial Revolution',
		'French Revolution',
	],
	'life-sciences': [
		'Cell Biology',
		'Genetics',
		'Evolution',
		'Ecology',
		'Photosynthesis',
		'Cell Respiration',
		'Human Reproduction',
		'Plant Reproduction',
	],
	geography: [
		'Map Work',
		'Climate',
		'Ecosystems',
		'Hydrology',
		'Geomorphology',
		'Urbanization',
		'Population',
		'Climate Change',
	],
	accounting: [
		'Financial Statements',
		'Budgeting',
		'Cost Accounting',
		'Inventory',
		'Bank Reconciliation',
		'Fixed Assets',
		'Partnerships',
		'Companies',
	],
	economics: [
		'Supply and Demand',
		'Market Structures',
		'Inflation',
		'Unemployment',
		'GDP',
		'International Trade',
		'Monetary Policy',
		'Fiscal Policy',
	],
};

export const topics = Object.keys(topicsBySubject);

export const difficulties = ['easy', 'medium', 'hard'] as const;
export const difficultyWeights = [0.3, 0.5, 0.2];

export const sessionTypes = ['quiz', 'flashcard', 'past-paper', 'ai-tutor', 'video-call'] as const;
export const sessionTypeWeights = [0.4, 0.25, 0.2, 0.1, 0.05];

export const achievementTemplates = [
	{
		id: 'first-perfect-score',
		title: 'Perfect Score',
		description: 'Answered all questions correctly in a quiz',
		icon: 'award',
	},
	{
		id: 'streak-7',
		title: 'Week Warrior',
		description: 'Maintained a 7-day study streak',
		icon: 'flame',
	},
	{
		id: 'streak-30',
		title: 'Month Master',
		description: 'Maintained a 30-day study streak',
		icon: 'crown',
	},
	{
		id: 'topics-10',
		title: 'Topic Explorer',
		description: 'Mastered 10 different topics',
		icon: 'compass',
	},
	{
		id: 'questions-100',
		title: 'Century Club',
		description: 'Answered 100 questions',
		icon: 'trophy',
	},
	{
		id: 'questions-500',
		title: 'Quiz Pro',
		description: 'Answered 500 questions',
		icon: 'star',
	},
	{
		id: 'questions-1000',
		title: 'Quiz Master',
		description: 'Answered 1000 questions',
		icon: 'medal',
	},
	{
		id: 'accuracy-80',
		title: 'Sharp Shooter',
		description: 'Achieved 80% average accuracy',
		icon: 'target',
	},
	{
		id: 'accuracy-90',
		title: 'Precision Expert',
		description: 'Achieved 90% average accuracy',
		icon: 'crosshair',
	},
	{
		id: 'first-buddy',
		title: 'Social Butterfly',
		description: 'Connected with a study buddy',
		icon: 'users',
	},
	{
		id: 'first-channel',
		title: 'Team Player',
		description: 'Joined a study channel',
		icon: 'message-circle',
	},
	{
		id: 'flashcard-50',
		title: 'Flashcard Fanatic',
		description: 'Created 50 flashcards',
		icon: 'cards',
	},
	{
		id: 'study-plan',
		title: 'Planner',
		description: 'Created a study plan',
		icon: 'calendar',
	},
	{
		id: 'exam-ready',
		title: 'Exam Ready',
		description: 'Completed all practice exams',
		icon: 'clipboard-check',
	},
];
