import type { QuizData } from './types';

export const ACCOUNTING_QUIZ: QuizData = {
	'acc-p1-2023-nov': {
		title: 'NSC Accounting P1 November 2023',
		subject: 'Accounting',
		year: 2023,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'acc-2023-p1-q1',
				question:
					'Which GAAP principle states that personal affairs must be kept separate from business?',
				options: [
					{ id: 'A', text: 'Business Entity Rule' },
					{ id: 'B', text: 'Going Concern' },
					{ id: 'C', text: 'Prudence' },
					{ id: 'D', text: 'Matching' },
				],
				correctAnswer: 'A',
				hint: 'The business is a separate legal person.',
				topic: 'Concepts',
				subtopic: 'GAAP Principles',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q2',
				question: 'Depreciation is calculated on:',
				options: [
					{ id: 'A', text: 'Fixed Assets' },
					{ id: 'B', text: 'Current Assets' },
					{ id: 'C', text: 'Liabilities' },
					{ id: 'D', text: 'Income' },
				],
				correctAnswer: 'A',
				hint: 'Wear and tear on long-term assets.',
				topic: 'Financial Accounting',
				subtopic: 'Adjustments',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q3',
				question: 'Cost of Sales is calculated as:',
				options: [
					{ id: 'A', text: 'Opening Stock + Purchases - Closing Stock' },
					{ id: 'B', text: 'Opening Stock - Purchases + Closing Stock' },
					{ id: 'C', text: 'Sales - Gross Profit' },
					{ id: 'D', text: 'Sales + Expenses' },
				],
				correctAnswer: 'A',
				hint: 'Standard periodic inventory formula.',
				topic: 'Financial Accounting',
				subtopic: 'Inventory',
				difficulty: 'medium',
			},
			{
				id: 'acc-2023-p1-q4',
				question: 'Which ratio measures liquidity?',
				options: [
					{ id: 'A', text: 'Current Ratio' },
					{ id: 'B', text: 'Debt-Equity Ratio' },
					{ id: 'C', text: 'Return on Equity' },
					{ id: 'D', text: 'Solvency Ratio' },
				],
				correctAnswer: 'A',
				hint: 'Ability to pay short-term debts.',
				topic: 'Financial Analysis',
				subtopic: 'Ratios',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q5',
				question: 'In the Cash Flow Statement, interest paid is shown under:',
				options: [
					{ id: 'A', text: 'Operating Activities' },
					{ id: 'B', text: 'Investing Activities' },
					{ id: 'C', text: 'Financing Activities' },
					{ id: 'D', text: 'Notes' },
				],
				correctAnswer: 'A',
				hint: 'It is a cost of operations.',
				topic: 'Companies',
				subtopic: 'Cash Flow Statement',
				difficulty: 'medium',
			},
			{
				id: 'acc-2023-p1-q6',
				question: 'VAT standard rate in South Africa is:',
				options: [
					{ id: 'A', text: '15%' },
					{ id: 'B', text: '14%' },
					{ id: 'C', text: '10%' },
					{ id: 'D', text: '20%' },
				],
				correctAnswer: 'A',
				hint: 'Increased to 15% in 2018.',
				topic: 'VAT',
				subtopic: 'Calculations',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q7',
				question: 'Bad debts recovered is recorded in:',
				options: [
					{ id: 'A', text: 'Cash Receipts Journal' },
					{ id: 'B', text: 'Cash Payments Journal' },
					{ id: 'C', text: 'Debtors Journal' },
					{ id: 'D', text: 'Creditors Journal' },
				],
				correctAnswer: 'A',
				hint: 'Money is coming IN.',
				topic: 'Financial Accounting',
				subtopic: 'Journals',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q8',
				question: 'The source document for a credit sale is:',
				options: [
					{ id: 'A', text: 'Duplicate Invoice' },
					{ id: 'B', text: 'Original Invoice' },
					{ id: 'C', text: 'Receipt' },
					{ id: 'D', text: 'Cheque Counterfoil' },
				],
				correctAnswer: 'A',
				hint: 'We keep the duplicate.',
				topic: 'Financial Accounting',
				subtopic: 'Source Documents',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q9',
				question: 'Inventory valuation method FIFO stands for:',
				options: [
					{ id: 'A', text: 'First-In-First-Out' },
					{ id: 'B', text: 'Final-In-First-Out' },
					{ id: 'C', text: 'First-In-Final-Out' },
					{ id: 'D', text: 'Fast-In-Fast-Out' },
				],
				correctAnswer: 'A',
				hint: 'Oldest stock sold first.',
				topic: 'Inventory',
				subtopic: 'Valuation Methods',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q10',
				question: 'If Solvency Ratio (Assets : Liabilities) is 0.8 : 1, the business is:',
				options: [
					{ id: 'A', text: 'Insolvent' },
					{ id: 'B', text: 'Solvent' },
					{ id: 'C', text: 'Liquid' },
					{ id: 'D', text: 'Profitable' },
				],
				correctAnswer: 'A',
				hint: 'Liabilities exceed assets.',
				topic: 'Financial Analysis',
				subtopic: 'Solvency',
				difficulty: 'medium',
			},
			{
				id: 'acc-2023-p1-q11',
				question: 'Retained Income represents:',
				options: [
					{ id: 'A', text: 'Profits kept in the business' },
					{ id: 'B', text: 'Profits paid to shareholders' },
					{ id: 'C', text: 'Money owed to creditors' },
					{ id: 'D', text: 'Share Capital' },
				],
				correctAnswer: 'A',
				hint: 'Accumulated profits.',
				topic: 'Companies',
				subtopic: 'Equity',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q12',
				question: 'Manufacturing Cost accounts include:',
				options: [
					{ id: 'A', text: 'Direct Material, Direct Labour, Factory Overhead' },
					{ id: 'B', text: 'Sales, Cost of Sales' },
					{ id: 'C', text: 'Admin, Distribution' },
					{ id: 'D', text: 'Assets, Liabilities' },
				],
				correctAnswer: 'A',
				hint: 'The three cost components.',
				topic: 'Manufacturing',
				subtopic: 'Cost Accounts',
				difficulty: 'medium',
			},
			{
				id: 'acc-2023-p1-q13',
				question: 'A break-even point is where:',
				options: [
					{ id: 'A', text: 'Total Revenue = Total Costs' },
					{ id: 'B', text: 'Total Revenue > Total Costs' },
					{ id: 'C', text: 'Total Revenue < Total Costs' },
					{ id: 'D', text: 'Profit is maximum' },
				],
				correctAnswer: 'A',
				hint: 'No profit, no loss.',
				topic: 'Manufacturing',
				subtopic: 'Break-even Analysis',
				difficulty: 'medium',
			},
			{
				id: 'acc-2023-p1-q14',
				question: 'Which of these is a Fixed Cost?',
				options: [
					{ id: 'A', text: 'Factory Rent' },
					{ id: 'B', text: 'Raw Materials' },
					{ id: 'C', text: 'Direct Labour' },
					{ id: 'D', text: 'Sales Commission' },
				],
				correctAnswer: 'A',
				hint: 'Rent stays same regardless of production.',
				topic: 'Manufacturing',
				subtopic: 'Costs',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q15',
				question: 'Audit Reports express an opinion on:',
				options: [
					{ id: 'A', text: 'Fair presentation of financial statements' },
					{ id: 'B', text: 'Future profitability' },
					{ id: 'C', text: 'Staff performance' },
					{ id: 'D', text: 'Marketing strategy' },
				],
				correctAnswer: 'A',
				hint: 'Are the books correct and fair?',
				topic: 'Auditing',
				subtopic: 'Reports',
				difficulty: 'medium',
			},
		],
	},
};
