import type { QuizData } from './types';

export const ACCOUNTING_QUIZ: QuizData = {
	'acc-p1-2023-nov': {
		title: 'NSC Accounting P1 November 2023',
		subject: 'Accounting',
		year: 2023,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'acc-2023-p1-q1',
				question:
					'Which GAAP principle states that personal affairs must be kept separate from business?',
				options: [
					{ id: 'A', text: 'Business Entity Rule' },
					{ id: 'B', text: 'Going Concern' },
					{ id: 'C', text: 'Prudence' },
					{ id: 'D', text: 'Matching' },
				],
				correctAnswer: 'A',
				hint: 'The business is a separate legal person.',
				topic: 'Concepts',
				subtopic: 'GAAP Principles',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q2',
				question: 'Depreciation is calculated on:',
				options: [
					{ id: 'A', text: 'Fixed Assets' },
					{ id: 'B', text: 'Current Assets' },
					{ id: 'C', text: 'Liabilities' },
					{ id: 'D', text: 'Income' },
				],
				correctAnswer: 'A',
				hint: 'Wear and tear on long-term assets.',
				topic: 'Financial Accounting',
				subtopic: 'Adjustments',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q3',
				question: 'Cost of Sales is calculated as:',
				options: [
					{ id: 'A', text: 'Opening Stock + Purchases - Closing Stock' },
					{ id: 'B', text: 'Opening Stock - Purchases + Closing Stock' },
					{ id: 'C', text: 'Sales - Gross Profit' },
					{ id: 'D', text: 'Sales + Expenses' },
				],
				correctAnswer: 'A',
				hint: 'Standard periodic inventory formula.',
				topic: 'Financial Accounting',
				subtopic: 'Inventory',
				difficulty: 'medium',
			},
			{
				id: 'acc-2023-p1-q4',
				question: 'Which ratio measures liquidity?',
				options: [
					{ id: 'A', text: 'Current Ratio' },
					{ id: 'B', text: 'Debt-Equity Ratio' },
					{ id: 'C', text: 'Return on Equity' },
					{ id: 'D', text: 'Solvency Ratio' },
				],
				correctAnswer: 'A',
				hint: 'Ability to pay short-term debts.',
				topic: 'Financial Analysis',
				subtopic: 'Ratios',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q5',
				question: 'In the Cash Flow Statement, interest paid is shown under:',
				options: [
					{ id: 'A', text: 'Operating Activities' },
					{ id: 'B', text: 'Investing Activities' },
					{ id: 'C', text: 'Financing Activities' },
					{ id: 'D', text: 'Notes' },
				],
				correctAnswer: 'A',
				hint: 'It is a cost of operations.',
				topic: 'Companies',
				subtopic: 'Cash Flow Statement',
				difficulty: 'medium',
			},
			{
				id: 'acc-2023-p1-q6',
				question: 'VAT standard rate in South Africa is:',
				options: [
					{ id: 'A', text: '15%' },
					{ id: 'B', text: '14%' },
					{ id: 'C', text: '10%' },
					{ id: 'D', text: '20%' },
				],
				correctAnswer: 'A',
				hint: 'Increased to 15% in 2018.',
				topic: 'VAT',
				subtopic: 'Calculations',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q7',
				question: 'Bad debts recovered is recorded in:',
				options: [
					{ id: 'A', text: 'Cash Receipts Journal' },
					{ id: 'B', text: 'Cash Payments Journal' },
					{ id: 'C', text: 'Debtors Journal' },
					{ id: 'D', text: 'Creditors Journal' },
				],
				correctAnswer: 'A',
				hint: 'Money is coming IN.',
				topic: 'Financial Accounting',
				subtopic: 'Journals',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q8',
				question: 'The source document for a credit sale is:',
				options: [
					{ id: 'A', text: 'Duplicate Invoice' },
					{ id: 'B', text: 'Original Invoice' },
					{ id: 'C', text: 'Receipt' },
					{ id: 'D', text: 'Cheque Counterfoil' },
				],
				correctAnswer: 'A',
				hint: 'We keep the duplicate.',
				topic: 'Financial Accounting',
				subtopic: 'Source Documents',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q9',
				question: 'Inventory valuation method FIFO stands for:',
				options: [
					{ id: 'A', text: 'First-In-First-Out' },
					{ id: 'B', text: 'Final-In-First-Out' },
					{ id: 'C', text: 'First-In-Final-Out' },
					{ id: 'D', text: 'Fast-In-Fast-Out' },
				],
				correctAnswer: 'A',
				hint: 'Oldest stock sold first.',
				topic: 'Inventory',
				subtopic: 'Valuation Methods',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q10',
				question: 'If Solvency Ratio (Assets : Liabilities) is 0.8 : 1, the business is:',
				options: [
					{ id: 'A', text: 'Insolvent' },
					{ id: 'B', text: 'Solvent' },
					{ id: 'C', text: 'Liquid' },
					{ id: 'D', text: 'Profitable' },
				],
				correctAnswer: 'A',
				hint: 'Liabilities exceed assets.',
				topic: 'Financial Analysis',
				subtopic: 'Solvency',
				difficulty: 'medium',
			},
			{
				id: 'acc-2023-p1-q11',
				question: 'Retained Income represents:',
				options: [
					{ id: 'A', text: 'Profits kept in the business' },
					{ id: 'B', text: 'Profits paid to shareholders' },
					{ id: 'C', text: 'Money owed to creditors' },
					{ id: 'D', text: 'Share Capital' },
				],
				correctAnswer: 'A',
				hint: 'Accumulated profits.',
				topic: 'Companies',
				subtopic: 'Equity',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q12',
				question: 'Manufacturing Cost accounts include:',
				options: [
					{ id: 'A', text: 'Direct Material, Direct Labour, Factory Overhead' },
					{ id: 'B', text: 'Sales, Cost of Sales' },
					{ id: 'C', text: 'Admin, Distribution' },
					{ id: 'D', text: 'Assets, Liabilities' },
				],
				correctAnswer: 'A',
				hint: 'The three cost components.',
				topic: 'Manufacturing',
				subtopic: 'Cost Accounts',
				difficulty: 'medium',
			},
			{
				id: 'acc-2023-p1-q13',
				question: 'A break-even point is where:',
				options: [
					{ id: 'A', text: 'Total Revenue = Total Costs' },
					{ id: 'B', text: 'Total Revenue > Total Costs' },
					{ id: 'C', text: 'Total Revenue < Total Costs' },
					{ id: 'D', text: 'Profit is maximum' },
				],
				correctAnswer: 'A',
				hint: 'No profit, no loss.',
				topic: 'Manufacturing',
				subtopic: 'Break-even Analysis',
				difficulty: 'medium',
			},
			{
				id: 'acc-2023-p1-q14',
				question: 'Which of these is a Fixed Cost?',
				options: [
					{ id: 'A', text: 'Factory Rent' },
					{ id: 'B', text: 'Raw Materials' },
					{ id: 'C', text: 'Direct Labour' },
					{ id: 'D', text: 'Sales Commission' },
				],
				correctAnswer: 'A',
				hint: 'Rent stays same regardless of production.',
				topic: 'Manufacturing',
				subtopic: 'Costs',
				difficulty: 'easy',
			},
			{
				id: 'acc-2023-p1-q15',
				question: 'Audit Reports express an opinion on:',
				options: [
					{ id: 'A', text: 'Fair presentation of financial statements' },
					{ id: 'B', text: 'Future profitability' },
					{ id: 'C', text: 'Staff performance' },
					{ id: 'D', text: 'Marketing strategy' },
				],
				correctAnswer: 'A',
				hint: 'Are the books correct and fair?',
				topic: 'Auditing',
				subtopic: 'Reports',
				difficulty: 'medium',
			},
		],
	},
	'acc-p1-2022-nov': {
		title: 'NSC Accounting P1 November 2022',
		subject: 'Accounting',
		year: 2022,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'acc-2022-p1-q1',
				question: 'The Accounting Equation is:',
				options: [
					{ id: 'A', text: 'Assets = Liabilities + Equity' },
					{ id: 'B', text: 'Assets + Liabilities = Equity' },
					{ id: 'C', text: 'Assets - Liabilities = Revenue' },
					{ id: 'D', text: 'Income - Expenses = Profit' },
				],
				correctAnswer: 'A',
				hint: 'Fundamental accounting equation.',
				topic: 'Concepts',
				subtopic: 'Accounting Equation',
				difficulty: 'easy',
			},
			{
				id: 'acc-2022-p1-q2',
				question: 'Which is a fixed asset?',
				options: [
					{ id: 'A', text: 'Office equipment' },
					{ id: 'B', text: 'Inventory' },
					{ id: 'C', text: 'Bank balance' },
					{ id: 'D', text: 'Debtors' },
				],
				correctAnswer: 'A',
				hint: 'Long-term tangible assets.',
				topic: 'Financial Accounting',
				subtopic: 'Fixed Assets',
				difficulty: 'easy',
			},
			{
				id: 'acc-2022-p1-q3',
				question: 'The normal balance of a Debtors account is:',
				options: [
					{ id: 'A', text: 'Debit' },
					{ id: 'B', text: 'Credit' },
					{ id: 'C', text: 'Neither' },
					{ id: 'D', text: 'Depends on transaction' },
				],
				correctAnswer: 'A',
				hint: 'Debit increases assets.',
				topic: 'Financial Accounting',
				subtopic: 'Double Entry',
				difficulty: 'easy',
			},
			{
				id: 'acc-2022-p1-q4',
				question: 'A credit entry in Bank account represents:',
				options: [
					{ id: 'A', text: 'Payments made' },
					{ id: 'B', text: 'Receipts received' },
					{ id: 'C', text: 'Opening balance' },
					{ id: 'D', text: 'Debit losses' },
				],
				correctAnswer: 'A',
				hint: 'Bank owes us money (credit = increase).',
				topic: 'Financial Accounting',
				subtopic: 'Cash Book',
				difficulty: 'medium',
			},
			{
				id: 'acc-2022-p1-q5',
				question: 'The Acid Test Ratio excludes:',
				options: [
					{ id: 'A', text: 'Inventory' },
					{ id: 'B', text: 'Debtors' },
					{ id: 'C', text: 'Bank' },
					{ id: 'D', text: 'Creditors' },
				],
				correctAnswer: 'A',
				hint: 'Quick assets only.',
				topic: 'Financial Analysis',
				subtopic: 'Ratios',
				difficulty: 'medium',
			},
			{
				id: 'acc-2022-p1-q6',
				question: 'Which is NOT a source document?',
				options: [
					{ id: 'A', text: 'Trial Balance' },
					{ id: 'B', text: 'Invoice' },
					{ id: 'C', text: 'Receipt' },
					{ id: 'D', text: 'Cheque' },
				],
				correctAnswer: 'A',
				hint: 'Trial balance is a statement, not source.',
				topic: 'Financial Accounting',
				subtopic: 'Source Documents',
				difficulty: 'easy',
			},
			{
				id: 'acc-2022-p1-q7',
				question: 'Capital expenditure increases:',
				options: [
					{ id: 'A', text: 'Asset value' },
					{ id: 'B', text: 'Revenue' },
					{ id: 'C', text: 'Expenses' },
					{ id: 'D', text: 'Liabilities' },
				],
				correctAnswer: 'A',
				hint: 'Improves asset capacity.',
				topic: 'Financial Accounting',
				subtopic: 'Capital vs Revenue',
				difficulty: 'medium',
			},
			{
				id: 'acc-2022-p1-q8',
				question:
					'If Credit Sales = R50,000 and Credit Purchases = R30,000, and change in debtors = +R5,000, what is cash received?',
				options: [
					{ id: 'A', text: 'R45,000' },
					{ id: 'B', text: 'R55,000' },
					{ id: 'C', text: 'R50,000' },
					{ id: 'D', text: 'R30,000' },
				],
				correctAnswer: 'A',
				hint: 'Opening + Credit Sales - Closing = Receipt. Opening - 5000 + 50000 = ?',
				topic: 'Financial Accounting',
				subtopic: 'Debtors',
				difficulty: 'hard',
			},
			{
				id: 'acc-2022-p1-q9',
				question: 'Net Profit is calculated as:',
				options: [
					{ id: 'A', text: 'Gross Profit - Expenses' },
					{ id: 'B', text: 'Gross Profit + Expenses' },
					{ id: 'C', text: 'Sales - Cost of Sales' },
					{ id: 'D', text: 'Income - Capital' },
				],
				correctAnswer: 'A',
				hint: 'Revenue minus all expenses.',
				topic: 'Financial Accounting',
				subtopic: 'Income Statement',
				difficulty: 'easy',
			},
			{
				id: 'acc-2022-p1-q10',
				question: 'Provision for Bad Debts is a:',
				options: [
					{ id: 'A', text: 'Contra asset' },
					{ id: 'B', text: 'Liability' },
					{ id: 'C', text: 'Revenue' },
					{ id: 'D', text: 'Expense' },
				],
				correctAnswer: 'A',
				hint: 'Reduces debtors asset.',
				topic: 'Financial Accounting',
				subtopic: 'Adjustments',
				difficulty: 'medium',
			},
			{
				id: 'acc-2022-p1-q11',
				question: 'In manufacturing, Prime Cost includes:',
				options: [
					{ id: 'A', text: 'Direct Material + Direct Labour' },
					{ id: 'B', text: 'Direct Material + Factory Overhead' },
					{ id: 'C', text: 'All manufacturing costs' },
					{ id: 'D', text: 'Direct Labour + Overhead' },
				],
				correctAnswer: 'A',
				hint: 'Direct costs of production.',
				topic: 'Manufacturing',
				subtopic: 'Costing',
				difficulty: 'medium',
			},
			{
				id: 'acc-2022-p1-q12',
				question: 'Contribution Margin =',
				options: [
					{ id: 'A', text: 'Selling Price - Variable Cost' },
					{ id: 'B', text: 'Fixed Cost + Profit' },
					{ id: 'C', text: 'Total Revenue - All Costs' },
					{ id: 'D', text: 'Sales - Cost of Sales' },
				],
				correctAnswer: 'A',
				hint: 'Per unit contribution.',
				topic: 'Manufacturing',
				subtopic: 'Break-even',
				difficulty: 'medium',
			},
		],
	},
	'acc-p1-2021-nov': {
		title: 'NSC Accounting P1 November 2021',
		subject: 'Accounting',
		year: 2021,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'acc-2021-p1-q1',
				question: 'The Going Concern assumption assumes:',
				options: [
					{ id: 'A', text: 'Business will operate indefinitely' },
					{ id: 'B', text: 'Business will close soon' },
					{ id: 'C', text: 'Business is bankrupt' },
					{ id: 'D', text: 'Business is for sale' },
				],
				correctAnswer: 'A',
				hint: 'Assets recorded at historical cost.',
				topic: 'Concepts',
				subtopic: 'GAAP',
				difficulty: 'easy',
			},
			{
				id: 'acc-2021-p1-q2',
				question: 'Equipment with 5-year life, bought R60,000. Annual depreciation?',
				options: [
					{ id: 'A', text: 'R12,000' },
					{ id: 'B', text: 'R6,000' },
					{ id: 'C', text: 'R30,000' },
					{ id: 'D', text: 'R10,000' },
				],
				correctAnswer: 'A',
				hint: 'Straight line: Cost/Useful life = 60000/5 = 12000',
				topic: 'Financial Accounting',
				subtopic: 'Depreciation',
				difficulty: 'easy',
			},
			{
				id: 'acc-2021-p1-q3',
				question: 'Closing inventory is valued at:',
				options: [
					{ id: 'A', text: 'Lower of cost or net realisable value' },
					{ id: 'B', text: 'Highest price' },
					{ id: 'C', text: 'Selling price' },
					{ id: 'D', text: 'Cost price only' },
				],
				correctAnswer: 'A',
				hint: 'Lower of cost or NRV rule.',
				topic: 'Inventory',
				subtopic: 'Valuation',
				difficulty: 'medium',
			},
			{
				id: 'acc-2021-p1-q4',
				question: 'Rent paid in advance is:',
				options: [
					{ id: 'A', text: 'Prepaid expense (asset)' },
					{ id: 'B', text: 'Accrued expense' },
					{ id: 'C', text: 'Liability' },
					{ id: 'D', text: 'Revenue' },
				],
				correctAnswer: 'A',
				hint: 'Paid before benefit received.',
				topic: 'Financial Accounting',
				subtopic: 'Adjustments',
				difficulty: 'easy',
			},
			{
				id: 'acc-2021-p1-q5',
				question: 'Current Ratio = 2:1 means:',
				options: [
					{ id: 'A', text: '2 assets for every 1 liability' },
					{ id: 'B', text: '1 asset for every 2 liabilities' },
					{ id: 'C', text: '2 liabilities for every 1 asset' },
					{ id: 'D', text: 'Equal assets and liabilities' },
				],
				correctAnswer: 'A',
				hint: 'Current assets twice current liabilities.',
				topic: 'Financial Analysis',
				subtopic: 'Ratios',
				difficulty: 'easy',
			},
			{
				id: 'acc-2021-p1-q6',
				question: 'Which document authorizes payment?',
				options: [
					{ id: 'A', text: 'Cheque' },
					{ id: 'B', text: 'Invoice' },
					{ id: 'C', text: 'Credit note' },
					{ id: 'D', text: 'Statement' },
				],
				correctAnswer: 'A',
				hint: 'Order to bank to pay.',
				topic: 'Financial Accounting',
				subtopic: 'Source Documents',
				difficulty: 'easy',
			},
			{
				id: 'acc-2021-p1-q7',
				question: 'In Asset Disposal, proceeds less book value =',
				options: [
					{ id: 'A', text: 'Profit or Loss on sale' },
					{ id: 'B', text: 'Depreciation' },
					{ id: 'C', text: 'Cost of asset' },
					{ id: 'D', text: 'Capital gain' },
				],
				correctAnswer: 'A',
				hint: 'Profit if proceeds > book value.',
				topic: 'Financial Accounting',
				subtopic: 'Fixed Assets',
				difficulty: 'medium',
			},
			{
				id: 'acc-2021-p1-q8',
				question: 'VAT input is claimed on:',
				options: [
					{ id: 'A', text: 'Purchases for business' },
					{ id: 'B', text: 'Private drawings' },
					{ id: 'C', text: 'Entertainment' },
					{ id: 'D', text: 'Motor vehicles' },
				],
				correctAnswer: 'A',
				hint: 'For taxable supplies.',
				topic: 'VAT',
				subtopic: 'Input Tax',
				difficulty: 'medium',
			},
			{
				id: 'acc-2021-p1-q9',
				question: 'A partnership with 2 partners has:',
				options: [
					{ id: 'A', text: '2 Capital accounts' },
					{ id: 'B', text: '1 Capital account' },
					{ id: 'C', text: '3 Capital accounts' },
					{ id: 'D', text: 'No Capital account' },
				],
				correctAnswer: 'A',
				hint: 'Each partner has own capital.',
				topic: 'Partnerships',
				subtopic: 'Capital',
				difficulty: 'easy',
			},
			{
				id: 'acc-2021-p1-q10',
				question: 'Break-even quantity =',
				options: [
					{ id: 'A', text: 'Fixed Costs / Contribution per unit' },
					{ id: 'B', text: 'Total Costs / Price' },
					{ id: 'C', text: 'Variable Costs / Price' },
					{ id: 'D', text: 'Revenue / Variable cost' },
				],
				correctAnswer: 'A',
				hint: 'Units needed to cover fixed costs.',
				topic: 'Manufacturing',
				subtopic: 'Break-even',
				difficulty: 'medium',
			},
		],
	},
};
