import type { QuizData } from './types';

export const BUSINESS_STUDIES_QUIZ: QuizData = {
	'bus-p1-2023-nov': {
		title: 'NSC Business Studies P1 November 2023',
		subject: 'Business Studies',
		year: 2023,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'bus-2023-p1-q1',
				question: 'A sole proprietor has:',
				options: [
					{ id: 'A', text: 'Unlimited liability' },
					{ id: 'B', text: 'Limited liability' },
					{ id: 'C', text: 'No liability' },
					{ id: 'D', text: 'Shared liability' },
				],
				correctAnswer: 'A',
				hint: 'Personal assets at risk.',
				topic: 'Business Entities',
				subtopic: 'Sole Proprietor',
				difficulty: 'easy',
			},
			{
				id: 'bus-2023-p1-q2',
				question: 'The primary purpose of a business is to:',
				options: [
					{ id: 'A', text: 'Make profit' },
					{ id: 'B', text: 'Provide employment' },
					{ id: 'C', text: 'Pay taxes' },
					{ id: 'D', text: 'Import goods' },
				],
				correctAnswer: 'A',
				hint: 'Generate income for owners.',
				topic: 'Introduction',
				subtopic: 'Purpose',
				difficulty: 'easy',
			},
			{
				id: 'bus-2023-p1-q3',
				question: 'Good customer service leads to:',
				options: [
					{ id: 'A', text: 'Customer loyalty and repeat business' },
					{ id: 'B', text: 'Higher costs' },
					{ id: 'C', text: 'Lower prices' },
					{ id: 'D', text: 'Fewer customers' },
				],
				correctAnswer: 'A',
				hint: 'Satisfied customers return.',
				topic: 'Marketing',
				subtopic: 'Customer Service',
				difficulty: 'easy',
			},
			{
				id: 'bus-2023-p1-q4',
				question: 'Stakeholders are:',
				options: [
					{ id: 'A', text: 'People with interest in the business' },
					{ id: 'B', text: 'Only the owners' },
					{ id: 'C', text: 'Government only' },
					{ id: 'D', text: 'Competitors' },
				],
				correctAnswer: 'A',
				hint: 'Anyone affected by business.',
				topic: 'Business Environment',
				subtopic: 'Stakeholders',
				difficulty: 'easy',
			},
			{
				id: 'bus-2023-p1-q5',
				question: 'The balance sheet shows:',
				options: [
					{ id: 'A', text: 'Assets, liabilities and equity at a point in time' },
					{ id: 'B', text: 'Income and expenses' },
					{ id: 'C', text: 'Cash flow' },
					{ id: 'D', text: 'Sales revenue' },
				],
				correctAnswer: 'A',
				hint: 'Financial position statement.',
				topic: 'Financial Statements',
				subtopic: 'Balance Sheet',
				difficulty: 'medium',
			},
			{
				id: 'bus-2023-p1-q6',
				question: 'A healthy current ratio should be:',
				options: [
					{ id: 'A', text: 'At least 1:1' },
					{ id: 'B', text: 'Less than 1' },
					{ id: 'C', text: '0.5:1' },
					{ id: 'D', text: '0:1' },
				],
				correctAnswer: 'A',
				hint: 'Current assets cover current liabilities.',
				topic: 'Financial Analysis',
				subtopic: 'Ratios',
				difficulty: 'medium',
			},
			{
				id: 'bus-2023-p1-q7',
				question: 'The 4 Ps of marketing are:',
				options: [
					{ id: 'A', text: 'Product, Price, Place, Promotion' },
					{ id: 'B', text: 'People, Process, Physical evidence, Promotion' },
					{ id: 'C', text: 'Planning, Production, Price, Promotion' },
					{ id: 'D', text: 'Product, People, Profit, Position' },
				],
				correctAnswer: 'A',
				hint: 'Marketing mix elements.',
				topic: 'Marketing',
				subtopic: 'Marketing Mix',
				difficulty: 'easy',
			},
			{
				id: 'bus-2023-p1-q8',
				question: 'Management functions include:',
				options: [
					{ id: 'A', text: 'Planning, Organizing, Leading, Controlling' },
					{ id: 'B', text: 'Selling, Buying, Marketing, Advertising' },
					{ id: 'C', text: 'Hiring, Firing, Training, Paying' },
					{ id: 'D', text: 'Production, Inventory, Distribution, Sales' },
				],
				correctAnswer: 'A',
				hint: 'POLC framework.',
				topic: 'Management',
				subtopic: 'Functions',
				difficulty: 'easy',
			},
			{
				id: 'bus-2023-p1-q9',
				question: 'Delegation means:',
				options: [
					{ id: 'A', text: 'Assigning authority to subordinates' },
					{ id: 'B', text: 'Doing work yourself' },
					{ id: 'C', text: 'Taking credit for work' },
					{ id: 'D', text: 'Firing employees' },
				],
				correctAnswer: 'A',
				hint: 'Authority to act on behalf.',
				topic: 'Management',
				subtopic: 'Delegation',
				difficulty: 'easy',
			},
			{
				id: 'bus-2023-p1-q10',
				question: 'LED stands for:',
				options: [
					{ id: 'A', text: 'Local Economic Development' },
					{ id: 'B', text: 'Large Enterprise Development' },
					{ id: 'C', text: 'Labour Employment Department' },
					{ id: 'D', text: 'Legal Economic District' },
				],
				correctAnswer: 'A',
				hint: 'Promoting local business.',
				topic: 'Business Environment',
				subtopic: 'LED',
				difficulty: 'easy',
			},
			{
				id: 'bus-2023-p1-q11',
				question: 'The Employment Equity Act aims to:',
				options: [
					{ id: 'A', text: 'Promote equal opportunity and fair treatment' },
					{ id: 'B', text: 'Increase unemployment' },
					{ id: 'C', text: 'Discriminate based on race' },
					{ id: 'D', text: 'Reduce wages' },
				],
				correctAnswer: 'A',
				hint: 'Address past discrimination.',
				topic: 'Labour Relations',
				subtopic: 'Employment Equity',
				difficulty: 'easy',
			},
			{
				id: 'bus-2023-p1-q12',
				question: 'Basic conditions of Employment Act covers:',
				options: [
					{ id: 'A', text: 'Working hours, leave, termination' },
					{ id: 'B', text: 'Tax rates' },
					{ id: 'C', text: 'Export regulations' },
					{ id: 'D', text: 'Pricing of goods' },
				],
				correctAnswer: 'A',
				hint: 'Minimum employment standards.',
				topic: 'Labour Relations',
				subtopic: 'BCEA',
				difficulty: 'easy',
			},
			{
				id: 'bus-2023-p1-q13',
				question: 'A convertible debt is:',
				options: [
					{ id: 'A', text: 'Loan that can become share capital' },
					{ id: 'B', text: 'Immediate cash payment' },
					{ id: 'C', text: 'Type of grant' },
					{ id: 'D', text: 'Interest-free loan' },
				],
				correctAnswer: 'A',
				hint: 'Hybrid financing.',
				topic: 'Finance',
				subtopic: 'Sources of Capital',
				difficulty: 'medium',
			},
			{
				id: 'bus-2023-p1-q14',
				question: 'Viral marketing uses:',
				options: [
					{ id: 'A', text: 'Customers to spread the message' },
					{ id: 'B', text: 'Expensive TV ads' },
					{ id: 'C', text: 'Only newspapers' },
					{ id: 'D', text: 'Government campaigns' },
				],
				correctAnswer: 'A',
				hint: 'Word of mouth online.',
				topic: 'Marketing',
				subtopic: 'Digital Marketing',
				difficulty: 'medium',
			},
			{
				id: 'bus-2023-p1-q15',
				question: 'Conflict in the workplace should be:',
				options: [
					{ id: 'A', text: 'Resolved through proper channels' },
					{ id: 'B', text: 'Ignored' },
					{ id: 'C', text: 'Resolved through violence' },
					{ id: 'D', text: 'Always handled by court' },
				],
				correctAnswer: 'A',
				hint: 'Healthy resolution processes.',
				topic: 'Labour Relations',
				subtopic: 'Conflict Resolution',
				difficulty: 'easy',
			},
		],
	},
	'bus-p1-2022-nov': {
		title: 'NSC Business Studies P1 November 2022',
		subject: 'Business Studies',
		year: 2022,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'bus-2022-p1-q1',
				question: 'A partnership consists of:',
				options: [
					{ id: 'A', text: '2 to 20 partners' },
					{ id: 'B', text: 'Unlimited partners' },
					{ id: 'C', text: 'Only 1 person' },
					{ id: 'D', text: 'Only government' },
				],
				correctAnswer: 'A',
				hint: 'Maximum 20 in SA.',
				topic: 'Business Entities',
				subtopic: 'Partnership',
				difficulty: 'easy',
			},
			{
				id: 'bus-2022-p1-q2',
				question: 'The main documents for starting a business are:',
				options: [
					{ id: 'A', text: 'Registration, tax, licenses' },
					{ id: 'B', text: 'CV and ID' },
					{ id: 'C', text: 'Bank statement' },
					{ id: 'D', text: 'Shopping list' },
				],
				correctAnswer: 'A',
				hint: 'Legal requirements.',
				topic: 'Business Registration',
				subtopic: 'Requirements',
				difficulty: 'easy',
			},
			{
				id: 'bus-2022-p1-q3',
				question: 'The income statement shows:',
				options: [
					{ id: 'A', text: 'Revenue, expenses and profit/loss' },
					{ id: 'B', text: 'Assets and liabilities' },
					{ id: 'C', text: 'Cash flow' },
					{ id: 'D', text: 'Capital' },
				],
				correctAnswer: 'A',
				hint: 'Trading account results.',
				topic: 'Financial Statements',
				subtopic: 'Income Statement',
				difficulty: 'easy',
			},
			{
				id: 'bus-2022-p1-q4',
				question: 'Market segmentation is:',
				options: [
					{ id: 'A', text: 'Dividing market into distinct groups' },
					{ id: 'B', text: 'Selling everything cheap' },
					{ id: 'C', text: 'One product for all' },
					{ id: 'D', text: 'Finding competitors' },
				],
				correctAnswer: 'A',
				hint: 'Target specific customers.',
				topic: 'Marketing',
				subtopic: 'Segmentation',
				difficulty: 'medium',
			},
			{
				id: 'bus-2022-p1-q5',
				question: 'Leadership style where employees make decisions is:',
				options: [
					{ id: 'A', text: 'Democratic' },
					{ id: 'B', text: 'Autocratic' },
					{ id: 'C', text: 'Laissez-faire' },
					{ id: 'D', text: 'Strict' },
				],
				correctAnswer: 'A',
				hint: 'Participative.',
				topic: 'Management',
				subtopic: 'Leadership',
				difficulty: 'medium',
			},
			{
				id: 'bus-2022-p1-q6',
				question: 'A business plan should include:',
				options: [
					{ id: 'A', text: 'Vision, mission, strategies, financial projections' },
					{ id: 'B', text: 'Only products' },
					{ id: 'C', text: 'Just prices' },
					{ id: 'D', text: 'No planning' },
				],
				correctAnswer: 'A',
				hint: 'Complete business roadmap.',
				topic: 'Business Planning',
				subtopic: 'Business Plan',
				difficulty: 'easy',
			},
			{
				id: 'bus-2022-p1-q7',
				question: 'The CCMA handles:',
				options: [
					{ id: 'A', text: 'Labour disputes and arbitration' },
					{ id: 'B', text: 'Tax collection' },
					{ id: 'C', text: 'Export licenses' },
					{ id: 'D', text: 'Product pricing' },
				],
				correctAnswer: 'A',
				hint: 'Workplace conflict resolution.',
				topic: 'Labour Relations',
				subtopic: 'CCMA',
				difficulty: 'easy',
			},
			{
				id: 'bus-2022-p1-q8',
				question: 'A franchise gives:',
				options: [
					{ id: 'A', text: 'Right to use established brand' },
					{ id: 'B', text: 'Free money' },
					{ id: 'C', text: 'Government job' },
					{ id: 'D', text: 'Tax exemption' },
				],
				correctAnswer: 'A',
				hint: 'Licensed business format.',
				topic: 'Business Entities',
				subtopic: 'Franchising',
				difficulty: 'easy',
			},
			{
				id: 'bus-2022-p1-q9',
				question: 'Unsolicited bulk emails are called:',
				options: [
					{ id: 'A', text: 'Spam' },
					{ id: 'B', text: 'Letters' },
					{ id: 'C', text: 'Phone calls' },
					{ id: 'D', text: 'Meetings' },
				],
				correctAnswer: 'A',
				hint: 'Prohibited without consent.',
				topic: 'Marketing',
				subtopic: 'Spam',
				difficulty: 'easy',
			},
			{
				id: 'bus-2022-p1-q10',
				question: 'BBBEE stands for:',
				options: [
					{ id: 'A', text: 'Broad-Based Black Economic Empowerment' },
					{ id: 'B', text: 'Business Bureau of Business Excellence' },
					{ id: 'C', text: 'Basic Budget Business Empowerment' },
					{ id: 'D', text: 'Business Budgeting and Banking Evaluation' },
				],
				correctAnswer: 'A',
				hint: 'Promoting black business participation.',
				topic: 'Business Environment',
				subtopic: 'BBBEE',
				difficulty: 'easy',
			},
		],
	},
	'bus-p1-2021-nov': {
		title: 'NSC Business Studies P1 November 2021',
		subject: 'Business Studies',
		year: 2021,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'bus-2021-p1-q1',
				question: 'A company is owned by:',
				options: [
					{ id: 'A', text: 'Shareholders' },
					{ id: 'B', text: 'Employees only' },
					{ id: 'C', text: 'Government' },
					{ id: 'D', text: 'One person' },
				],
				correctAnswer: 'A',
				hint: 'Share capital holders.',
				topic: 'Business Entities',
				subtopic: 'Company',
				difficulty: 'easy',
			},
			{
				id: 'bus-2021-p1-q2',
				question: 'The 7 functions of business include:',
				options: [
					{ id: 'A', text: 'Marketing, Production, HR, Finance, Admin, Public Relations, IT' },
					{ id: 'B', text: 'Only Selling' },
					{ id: 'C', text: 'Just Accounting' },
					{ id: 'D', text: 'Only HR' },
				],
				correctAnswer: 'A',
				hint: 'All business operations.',
				topic: 'Business Functions',
				subtopic: 'Overview',
				difficulty: 'easy',
			},
			{
				id: 'bus-2021-p1-q3',
				question: 'SWOT analysis evaluates:',
				options: [
					{ id: 'A', text: 'Strengths, Weaknesses, Opportunities, Threats' },
					{ id: 'B', text: 'Sales only' },
					{ id: 'C', text: 'Staff only' },
					{ id: 'D', text: 'Prices only' },
				],
				correctAnswer: 'A',
				hint: 'Strategic planning tool.',
				topic: 'Strategic Planning',
				subtopic: 'SWOT',
				difficulty: 'easy',
			},
			{
				id: 'bus-2021-p1-q4',
				question: 'A public company can raise capital by:',
				options: [
					{ id: 'A', text: 'Selling shares to public' },
					{ id: 'B', text: 'One person loan' },
					{ id: 'C', text: 'Government grant only' },
					{ id: 'D', text: 'No funding options' },
				],
				correctAnswer: 'A',
				hint: 'JSE listing possible.',
				topic: 'Finance',
				subtopic: 'Shares',
				difficulty: 'medium',
			},
			{
				id: 'bus-2021-p1-q5',
				question: 'The Consumer Protection Act protects:',
				options: [
					{ id: 'A', text: 'Rights of consumers against unfair practices' },
					{ id: 'B', text: 'Businesses only' },
					{ id: 'C', text: 'Government' },
					{ id: 'D', text: 'Foreign investors' },
				],
				correctAnswer: 'A',
				hint: 'Fair trading.',
				topic: 'Business Law',
				subtopic: 'CPA',
				difficulty: 'easy',
			},
			{
				id: 'bus-2021-p1-q6',
				question: 'Recruitment involves:',
				options: [
					{ id: 'A', text: 'Finding and attracting suitable candidates' },
					{ id: 'B', text: 'Firing employees' },
					{ id: 'C', text: 'Paying salaries' },
					{ id: 'D', text: 'Selling products' },
				],
				correctAnswer: 'A',
				hint: 'Hiring process.',
				topic: 'Human Resources',
				subtopic: 'Recruitment',
				difficulty: 'easy',
			},
			{
				id: 'bus-2021-p1-q7',
				question: 'Negotiation skills help to:',
				options: [
					{ id: 'A', text: 'Reach mutually beneficial agreements' },
					{ id: 'B', text: 'Always get your way' },
					{ id: 'C', text: 'Avoid all communication' },
					{ id: 'D', text: 'Raise prices' },
				],
				correctAnswer: 'A',
				hint: 'Win-win outcomes.',
				topic: 'Management',
				subtopic: 'Negotiation',
				difficulty: 'easy',
			},
			{
				id: 'bus-2021-p1-q8',
				question: 'Vertical integration means:',
				options: [
					{ id: 'A', text: 'Controlling different stages of production/distribution' },
					{ id: 'B', text: 'Selling different products' },
					{ id: 'C', text: 'Hiring more staff' },
					{ id: 'D', text: 'Moving to new premises' },
				],
				correctAnswer: 'A',
				hint: 'Expand business chain.',
				topic: 'Business Strategy',
				subtopic: 'Integration',
				difficulty: 'medium',
			},
			{
				id: 'bus-2021-p1-q9',
				question: 'Total quality management focuses on:',
				options: [
					{ id: 'A', text: 'Continuous improvement in all areas' },
					{ id: 'B', text: 'Only product quality' },
					{ id: 'C', text: 'Reducing staff' },
					{ id: 'D', text: 'Cutting prices' },
				],
				correctAnswer: 'A',
				hint: 'Customer satisfaction.',
				topic: 'Quality Management',
				subtopic: 'TQM',
				difficulty: 'medium',
			},
			{
				id: 'bus-2021-p1-q10',
				question: 'The National Credit Act regulates:',
				options: [
					{ id: 'A', text: 'Credit and debt collection' },
					{ id: 'B', text: 'Product prices' },
					{ id: 'C', text: 'Export rules' },
					{ id: 'D', text: 'Staff numbers' },
				],
				correctAnswer: 'A',
				hint: 'Responsible lending.',
				topic: 'Business Law',
				subtopic: 'NCA',
				difficulty: 'easy',
			},
		],
	},
};
