import type { QuizData } from './types';

export const CHEMISTRY_QUIZ: QuizData = {
	'chem-p1-2023-nov': {
		title: 'NSC Chemistry P1 November 2023',
		subject: 'Chemistry',
		year: 2023,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'chem-2023-p1-q1',
				question: 'How many electrons are in the third shell of calcium (Z=20)?',
				options: [
					{ id: 'A', text: '8' },
					{ id: 'B', text: '2' },
					{ id: 'C', text: '10' },
					{ id: 'D', text: '18' },
				],
				correctAnswer: 'A',
				hint: 'Electron configuration: 2, 8, 8, 2.',
				topic: 'Atomic Structure',
				subtopic: 'Electron Configuration',
				difficulty: 'easy',
			},
			{
				id: 'chem-2023-p1-q2',
				question: 'Which compound has ionic bonding?',
				options: [
					{ id: 'A', text: 'NaCl' },
					{ id: 'B', text: 'HCl' },
					{ id: 'C', text: 'CO₂' },
					{ id: 'D', text: 'CH₄' },
				],
				correctAnswer: 'A',
				hint: 'NaCl forms between metal and non-metal.',
				topic: 'Chemical Bonding',
				subtopic: 'Ionic Bonds',
				difficulty: 'easy',
			},
			{
				id: 'chem-2023-p1-q3',
				question: 'The pH of a neutral solution is:',
				options: [
					{ id: 'A', text: '7' },
					{ id: 'B', text: '0' },
					{ id: 'C', text: '14' },
					{ id: 'D', text: '1' },
				],
				correctAnswer: 'A',
				hint: 'pH = 7 is neutral.',
				topic: 'Acids and Bases',
				subtopic: 'pH Scale',
				difficulty: 'easy',
			},
			{
				id: 'chem-2023-p1-q4',
				question: 'What is the oxidation state of carbon in CO₂?',
				options: [
					{ id: 'A', text: '+4' },
					{ id: 'B', text: '-4' },
					{ id: 'C', text: '0' },
					{ id: 'D', text: '+2' },
				],
				correctAnswer: 'A',
				hint: 'O is -2. x + 2(-2) = 0.',
				topic: 'Redox Reactions',
				subtopic: 'Oxidation States',
				difficulty: 'medium',
			},
			{
				id: 'chem-2023-p1-q5',
				question: 'Which gas is produced when zinc reacts with hydrochloric acid?',
				options: [
					{ id: 'A', text: 'Hydrogen' },
					{ id: 'B', text: 'Oxygen' },
					{ id: 'C', text: 'Chlorine' },
					{ id: 'D', text: 'Nitrogen' },
				],
				correctAnswer: 'A',
				hint: 'Zn + 2HCl → ZnCl₂ + H₂↑',
				topic: 'Chemical Reactions',
				subtopic: 'Metals and Acids',
				difficulty: 'easy',
			},
			{
				id: 'chem-2023-p1-q6',
				question: 'The chemical formula for potassium permanganate is:',
				options: [
					{ id: 'A', text: 'KMnO₄' },
					{ id: 'B', text: 'K₂MnO₄' },
					{ id: 'C', text: 'KMnO₃' },
					{ id: 'D', text: 'K₂MnO₃' },
				],
				correctAnswer: 'A',
				hint: 'K⁺ + MnO₄⁻ → KMnO₄',
				topic: 'Chemical Formulas',
				subtopic: 'Ionic Compounds',
				difficulty: 'easy',
			},
			{
				id: 'chem-2023-p1-q7',
				question: 'In an endothermic reaction:',
				options: [
					{ id: 'A', text: 'Heat is absorbed' },
					{ id: 'B', text: 'Heat is released' },
					{ id: 'C', text: 'Temperature decreases' },
					{ id: 'D', text: 'No heat change' },
				],
				correctAnswer: 'A',
				hint: 'Endothermic reactions absorb heat.',
				topic: 'Chemical Energy',
				subtopic: 'Endothermic/Exothermic',
				difficulty: 'easy',
			},
			{
				id: 'chem-2023-p1-q8',
				question: 'What is the percentage by mass of oxygen in H₂O? (H=1, O=16)',
				options: [
					{ id: 'A', text: '88.9%' },
					{ id: 'B', text: '11.1%' },
					{ id: 'C', text: '50%' },
					{ id: 'D', text: '33.3%' },
				],
				correctAnswer: 'A',
				hint: '16/18 × 100 = 88.9%',
				topic: 'Quantitative Chemistry',
				subtopic: 'Percentage Composition',
				difficulty: 'medium',
			},
			{
				id: 'chem-2023-p1-q9',
				question: 'Which element has the highest electronegativity?',
				options: [
					{ id: 'A', text: 'Fluorine' },
					{ id: 'B', text: 'Oxygen' },
					{ id: 'C', text: 'Nitrogen' },
					{ id: 'D', text: 'Chlorine' },
				],
				correctAnswer: 'A',
				hint: 'Fluorine is the most electronegative.',
				topic: 'Periodic Table',
				subtopic: 'Electronegativity',
				difficulty: 'easy',
			},
			{
				id: 'chem-2023-p1-q10',
				question: 'Balance: _Fe + _O2 -> Fe2O3',
				options: [
					{ id: 'A', text: '4, 3, 2' },
					{ id: 'B', text: '2, 3, 1' },
					{ id: 'C', text: '1, 1, 1' },
					{ id: 'D', text: '3, 2, 4' },
				],
				correctAnswer: 'A',
				hint: 'Answer: 4Fe + 3O2 -> 2Fe2O3',
				topic: 'Chemical Equations',
				subtopic: 'Balancing',
				difficulty: 'medium',
			},
			{
				id: 'chem-2023-p1-q11',
				question: 'A catalyst works by:',
				options: [
					{ id: 'A', text: 'Lowering activation energy' },
					{ id: 'B', text: 'Increasing activation energy' },
					{ id: 'C', text: 'Changing the reaction products' },
					{ id: 'D', text: 'Being consumed in reaction' },
				],
				correctAnswer: 'A',
				hint: 'Catalysts provide alternative pathway with lower activation energy.',
				topic: 'Chemical Kinetics',
				subtopic: 'Catalysts',
				difficulty: 'easy',
			},
			{
				id: 'chem-2023-p1-q12',
				question: 'How many moles are in 36g of water? (H=1, O=16)',
				options: [
					{ id: 'A', text: '2 mol' },
					{ id: 'B', text: '18 mol' },
					{ id: 'C', text: '1 mol' },
					{ id: 'D', text: '0.5 mol' },
				],
				correctAnswer: 'A',
				hint: 'Moles = mass/molar mass = 36/18 = 2 mol',
				topic: 'Quantitative Chemistry',
				subtopic: 'Moles',
				difficulty: 'medium',
			},
			{
				id: 'chem-2023-p1-q13',
				question: 'The particle that has the same number of electrons as Ca²⁺ is:',
				options: [
					{ id: 'A', text: 'Ar' },
					{ id: 'B', text: 'Na⁺' },
					{ id: 'C', text: 'Cl⁻' },
					{ id: 'D', text: 'Mg²⁺' },
				],
				correctAnswer: 'A',
				hint: 'Ca²⁺ has 18 electrons. Ar has 18 electrons.',
				topic: 'Atomic Structure',
				subtopic: 'Ions',
				difficulty: 'medium',
			},
			{
				id: 'chem-2023-p1-q14',
				question: 'Which type of reaction is: 2H₂ + O₂ → 2H₂O?',
				options: [
					{ id: 'A', text: 'Synthesis' },
					{ id: 'B', text: 'Decomposition' },
					{ id: 'C', text: 'Single replacement' },
					{ id: 'D', text: 'Combustion' },
				],
				correctAnswer: 'A',
				hint: 'Two reactants combine to form a single product.',
				topic: 'Chemical Reactions',
				subtopic: 'Reaction Types',
				difficulty: 'easy',
			},
			{
				id: 'chem-2023-p1-q15',
				question: 'What is the shape of a molecule with 4 electron pairs around the central atom?',
				options: [
					{ id: 'A', text: 'Tetrahedral' },
					{ id: 'B', text: 'Linear' },
					{ id: 'C', text: 'Trigonal planar' },
					{ id: 'D', text: 'Bent' },
				],
				correctAnswer: 'A',
				hint: '4 bonding pairs → tetrahedral geometry.',
				topic: 'Chemical Bonding',
				subtopic: 'VSEPR Theory',
				difficulty: 'medium',
			},
			{
				id: 'chem-2023-p1-q16',
				question: 'In electrolysis of water, what volumes of H₂ and O₂ are produced?',
				options: [
					{ id: 'A', text: '2:1 ratio' },
					{ id: 'B', text: '1:2 ratio' },
					{ id: 'C', text: '1:1 ratio' },
					{ id: 'D', text: '1:8 ratio' },
				],
				correctAnswer: 'A',
				hint: '2H₂O → 2H₂ + O₂.',
				topic: 'Electrochemistry',
				subtopic: 'Electrolysis',
				difficulty: 'medium',
			},
			{
				id: 'chem-2023-p1-q17',
				question: 'A solution with pH 4 has [H⁺] of:',
				options: [
					{ id: 'A', text: '1×10⁻⁴ M' },
					{ id: 'B', text: '1×10⁻⁷ M' },
					{ id: 'C', text: '1×10⁻¹⁰ M' },
					{ id: 'D', text: '4 M' },
				],
				correctAnswer: 'A',
				hint: '[H⁺] = 10^(-pH).',
				topic: 'Acids and Bases',
				subtopic: 'pH Calculations',
				difficulty: 'medium',
			},
			{
				id: 'chem-2023-p1-q19',
				question:
					'The rate of a reaction doubles when temperature increases by 10°C. This is due to:',
				options: [
					{ id: 'A', text: 'More particles with activation energy' },
					{ id: 'B', text: 'Lower activation energy' },
					{ id: 'C', text: 'Decreased collision frequency' },
					{ id: 'D', text: 'Catalyst presence' },
				],
				correctAnswer: 'A',
				hint: 'Higher temperature increases kinetic energy.',
				topic: 'Chemical Kinetics',
				subtopic: 'Temperature and Rate',
				difficulty: 'medium',
			},
			{
				id: 'chem-2023-p1-q20',
				question: 'In a redox reaction, the oxidizing agent is the substance that:',
				options: [
					{ id: 'A', text: 'Gains electrons' },
					{ id: 'B', text: 'Loses electrons' },
					{ id: 'C', text: 'Gains oxygen' },
					{ id: 'D', text: 'Loses oxygen' },
				],
				correctAnswer: 'A',
				hint: 'Oxidizing agent ACCEPT electrons (is reduced).',
				topic: 'Redox Reactions',
				subtopic: 'Oxidizing Agents',
				difficulty: 'medium',
			},
		],
	},
	'chem-p1-2022-nov': {
		title: 'NSC Chemistry P1 November 2022',
		subject: 'Chemistry',
		year: 2022,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'chem-2022-p1-q1',
				question: 'The electron configuration of element with atomic number 17 is:',
				options: [
					{ id: 'A', text: '2, 8, 7' },
					{ id: 'B', text: '2, 8, 8' },
					{ id: 'C', text: '2, 7, 8' },
					{ id: 'D', text: '2, 8, 1' },
				],
				correctAnswer: 'A',
				hint: '17 electrons fill shells: 2, 8, 7',
				topic: 'Atomic Structure',
				subtopic: 'Electron Configuration',
				difficulty: 'easy',
			},
			{
				id: 'chem-2022-p1-q2',
				question: 'Which compound has covalent bonding?',
				options: [
					{ id: 'A', text: 'H₂O' },
					{ id: 'B', text: 'NaCl' },
					{ id: 'C', text: 'MgO' },
					{ id: 'D', text: 'CaF₂' },
				],
				correctAnswer: 'A',
				hint: 'Non-metals share electrons.',
				topic: 'Chemical Bonding',
				subtopic: 'Covalent Bonds',
				difficulty: 'easy',
			},
			{
				id: 'chem-2022-p1-q3',
				question: 'The pH of a basic solution is:',
				options: [
					{ id: 'A', text: 'Greater than 7' },
					{ id: 'B', text: 'Less than 7' },
					{ id: 'C', text: 'Equal to 7' },
					{ id: 'D', text: 'Equal to 0' },
				],
				correctAnswer: 'A',
				hint: 'Basic solutions have excess OH⁻.',
				topic: 'Acids and Bases',
				subtopic: 'pH Scale',
				difficulty: 'easy',
			},
			{
				id: 'chem-2022-p1-q4',
				question: 'What is oxidation state of Na in NaCl?',
				options: [
					{ id: 'A', text: '+1' },
					{ id: 'B', text: '-1' },
					{ id: 'C', text: '0' },
					{ id: 'D', text: '+2' },
				],
				correctAnswer: 'A',
				hint: 'Group 1 metals are +1.',
				topic: 'Redox Reactions',
				subtopic: 'Oxidation States',
				difficulty: 'easy',
			},
			{
				id: 'chem-2022-p1-q5',
				question: 'Which gas is produced when copper reacts with dilute HNO₃?',
				options: [
					{ id: 'A', text: 'NO' },
					{ id: 'B', text: 'H₂' },
					{ id: 'C', text: 'O₂' },
					{ id: 'D', text: 'CO₂' },
				],
				correctAnswer: 'A',
				hint: 'Dilute HNO₃ produces NO.',
				topic: 'Chemical Reactions',
				subtopic: 'Metals and Acids',
				difficulty: 'medium',
			},
			{
				id: 'chem-2022-p1-q6',
				question: 'The molar mass of CO₂ is: (C=12, O=16)',
				options: [
					{ id: 'A', text: '44 g/mol' },
					{ id: 'B', text: '28 g/mol' },
					{ id: 'C', text: '32 g/mol' },
					{ id: 'D', text: '18 g/mol' },
				],
				correctAnswer: 'A',
				hint: '12 + 2(16) = 44 g/mol',
				topic: 'Quantitative Chemistry',
				subtopic: 'Molar Mass',
				difficulty: 'easy',
			},
			{
				id: 'chem-2022-p1-q7',
				question: 'In an exothermic reaction:',
				options: [
					{ id: 'A', text: 'Heat is released to surroundings' },
					{ id: 'B', text: 'Heat is absorbed from surroundings' },
					{ id: 'C', text: 'Temperature stays constant' },
					{ id: 'D', text: 'No heat change occurs' },
				],
				correctAnswer: 'A',
				hint: 'Exothermic = energy out.',
				topic: 'Chemical Energy',
				subtopic: 'Exothermic',
				difficulty: 'easy',
			},
			{
				id: 'chem-2022-p1-q8',
				question: 'Percentage composition of carbon in CH₄ is: (C=12, H=1)',
				options: [
					{ id: 'A', text: '75%' },
					{ id: 'B', text: '25%' },
					{ id: 'C', text: '50%' },
					{ id: 'D', text: '80%' },
				],
				correctAnswer: 'A',
				hint: '12/16 × 100 = 75%',
				topic: 'Quantitative Chemistry',
				subtopic: 'Percentage Composition',
				difficulty: 'medium',
			},
			{
				id: 'chem-2022-p1-q9',
				question: 'The element in Period 2, Group 17 is:',
				options: [
					{ id: 'A', text: 'Fluorine' },
					{ id: 'B', text: 'Chlorine' },
					{ id: 'C', text: 'Bromine' },
					{ id: 'D', text: 'Iodine' },
				],
				correctAnswer: 'A',
				hint: 'Period 2, Group 17 = F',
				topic: 'Periodic Table',
				subtopic: 'Groups and Periods',
				difficulty: 'easy',
			},
			{
				id: 'chem-2022-p1-q10',
				question: 'Balance: _Al + _O2 -> Al2O3',
				options: [
					{ id: 'A', text: '4, 3, 2' },
					{ id: 'B', text: '2, 3, 1' },
					{ id: 'C', text: '1, 1, 1' },
					{ id: 'D', text: '3, 2, 1' },
				],
				correctAnswer: 'A',
				hint: '4Al + 3O2 -> 2Al2O3',
				topic: 'Chemical Equations',
				subtopic: 'Balancing',
				difficulty: 'medium',
			},
			{
				id: 'chem-2022-p1-q11',
				question: 'The shape of CO₂ molecule is:',
				options: [
					{ id: 'A', text: 'Linear' },
					{ id: 'B', text: 'Bent' },
					{ id: 'C', text: 'Trigonal planar' },
					{ id: 'D', text: 'Tetrahedral' },
				],
				correctAnswer: 'A',
				hint: '2 bonding pairs, no lone pairs → linear',
				topic: 'Chemical Bonding',
				subtopic: 'VSEPR Theory',
				difficulty: 'medium',
			},
			{
				id: 'chem-2022-p1-q12',
				question: 'How many moles in 58.5g NaCl? (Na=23, Cl=35.5)',
				options: [
					{ id: 'A', text: '1 mol' },
					{ id: 'B', text: '0.5 mol' },
					{ id: 'C', text: '2 mol' },
					{ id: 'D', text: '58.5 mol' },
				],
				correctAnswer: 'A',
				hint: 'Molar mass = 58.5g/mol. Moles = 58.5/58.5 = 1 mol',
				topic: 'Quantitative Chemistry',
				subtopic: 'Moles',
				difficulty: 'easy',
			},
		],
	},
	'chem-p1-2021-nov': {
		title: 'NSC Chemistry P1 November 2021',
		subject: 'Chemistry',
		year: 2021,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'chem-2021-p1-q1',
				question: 'Atomic number of element with electron config 2,8,8,2 is:',
				options: [
					{ id: 'A', text: '20' },
					{ id: 'B', text: '18' },
					{ id: 'C', text: '22' },
					{ id: 'D', text: '12' },
				],
				correctAnswer: 'A',
				hint: 'Sum of electrons = 20 (Calcium)',
				topic: 'Atomic Structure',
				subtopic: 'Electron Configuration',
				difficulty: 'easy',
			},
			{
				id: 'chem-2021-p1-q2',
				question: 'What type of bond forms between Na and Cl?',
				options: [
					{ id: 'A', text: 'Ionic' },
					{ id: 'B', text: 'Covalent' },
					{ id: 'C', text: 'Metallic' },
					{ id: 'D', text: 'Hydrogen' },
				],
				correctAnswer: 'A',
				hint: 'Metal + Non-metal = ionic.',
				topic: 'Chemical Bonding',
				subtopic: 'Ionic Bonds',
				difficulty: 'easy',
			},
			{
				id: 'chem-2021-p1-q3',
				question: 'pH of 0.1M HCl is:',
				options: [
					{ id: 'A', text: '1' },
					{ id: 'B', text: '0' },
					{ id: 'C', text: '10' },
					{ id: 'D', text: '13' },
				],
				correctAnswer: 'A',
				hint: 'Strong acid pH = -log[H⁺] = 1',
				topic: 'Acids and Bases',
				subtopic: 'pH Calculations',
				difficulty: 'medium',
			},
			{
				id: 'chem-2021-p1-q4',
				question: 'In reaction Mg + 2HCl -> MgCl₂ + H₂, Mg is:',
				options: [
					{ id: 'A', text: 'Oxidized' },
					{ id: 'B', text: 'Reduced' },
					{ id: 'C', text: 'Catalyst' },
					{ id: 'D', text: 'Neutral' },
				],
				correctAnswer: 'A',
				hint: 'Mg loses electrons (0 to +2) → oxidized.',
				topic: 'Redox Reactions',
				subtopic: 'Oxidation',
				difficulty: 'medium',
			},
			{
				id: 'chem-2021-p1-q5',
				question: 'The conjugate base of H₂SO₄ is:',
				options: [
					{ id: 'A', text: 'HSO₄⁻' },
					{ id: 'B', text: 'SO₄²⁻' },
					{ id: 'C', text: 'H₃O⁺' },
					{ id: 'D', text: 'OH⁻' },
				],
				correctAnswer: 'A',
				hint: 'Remove H⁺ from acid → conjugate base.',
				topic: 'Acids and Bases',
				subtopic: 'Conjugate Pairs',
				difficulty: 'medium',
			},
			{
				id: 'chem-2021-p1-q6',
				question: 'Formula for copper(II) sulfate is:',
				options: [
					{ id: 'A', text: 'CuSO₄' },
					{ id: 'B', text: 'Cu₂SO₄' },
					{ id: 'C', text: 'CuSO₃' },
					{ id: 'D', text: 'Cu₂S' },
				],
				correctAnswer: 'A',
				hint: 'Cu²⁺ + SO₄²⁻ → CuSO₄',
				topic: 'Chemical Formulas',
				subtopic: 'Ionic Compounds',
				difficulty: 'easy',
			},
			{
				id: 'chem-2021-p1-q7',
				question: 'Reactants in rate equation have concentration exponents. This is:',
				options: [
					{ id: 'A', text: 'Order of reaction' },
					{ id: 'B', text: 'Molecularity' },
					{ id: 'C', text: 'Activation energy' },
					{ id: 'D', text: 'Equilibrium constant' },
				],
				correctAnswer: 'A',
				hint: 'Sum of exponents = order.',
				topic: 'Chemical Kinetics',
				subtopic: 'Reaction Order',
				difficulty: 'medium',
			},
			{
				id: 'chem-2021-p1-q8',
				question: 'To balance: H₂ + O₂ -> H₂O, what coefficients needed?',
				options: [
					{ id: 'A', text: '2, 1, 2' },
					{ id: 'B', text: '1, 1, 1' },
					{ id: 'C', text: '2, 2, 2' },
					{ id: 'D', text: '1, 2, 2' },
				],
				correctAnswer: 'A',
				hint: '2H₂ + O₂ -> 2H₂O',
				topic: 'Chemical Equations',
				subtopic: 'Balancing',
				difficulty: 'easy',
			},
			{
				id: 'chem-2021-p1-q9',
				question: 'Which gas will diffuse fastest? (at same conditions)',
				options: [
					{ id: 'A', text: 'H₂' },
					{ id: 'B', text: 'O₂' },
					{ id: 'C', text: 'N₂' },
					{ id: 'D', text: 'CO₂' },
				],
				correctAnswer: 'A',
				hint: 'Rate ∝ 1/√M. Lowest molar mass = fastest.',
				topic: 'States of Matter',
				subtopic: 'Gas Laws',
				difficulty: 'medium',
			},
			{
				id: 'chem-2021-p1-q10',
				question: 'What volume does 0.5 mol of gas occupy at STP?',
				options: [
					{ id: 'A', text: '11.2 L' },
					{ id: 'B', text: '22.4 L' },
					{ id: 'C', text: '5.6 L' },
					{ id: 'D', text: '44.8 L' },
				],
				correctAnswer: 'A',
				hint: 'At STP, 1 mol = 22.4L. 0.5 mol = 11.2L',
				topic: 'States of Matter',
				subtopic: 'Molar Volume',
				difficulty: 'easy',
			},
		],
	},
};
