import type { QuizData } from './types';

export const ECONOMICS_QUIZ: QuizData = {
	'econ-p1-2023-nov': {
		title: 'NSC Economics P1 November 2023',
		subject: 'Economics',
		year: 2023,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'econ-2023-p1-q1',
				question: 'The economic problem arises because:',
				options: [
					{ id: 'A', text: 'Resources are limited while wants are unlimited' },
					{ id: 'B', text: 'Resources are unlimited' },
					{ id: 'C', text: 'Wants are limited' },
					{ id: 'D', text: 'There is no scarcity' },
				],
				correctAnswer: 'A',
				hint: 'Scarcity is the fundamental problem.',
				topic: 'Introduction',
				subtopic: 'Scarcity',
				difficulty: 'easy',
			},
			{
				id: 'econ-2023-p1-q2',
				question: 'Which is a factor of production?',
				options: [
					{ id: 'A', text: 'Entrepreneurship' },
					{ id: 'B', text: 'Money' },
					{ id: 'C', text: 'Stocks' },
					{ id: 'D', text: 'Bonds' },
				],
				correctAnswer: 'A',
				hint: 'The organizing factor.',
				topic: 'Factors of Production',
				subtopic: 'Resources',
				difficulty: 'easy',
			},
			{
				id: 'econ-2023-p1-q3',
				question: 'The law of supply states that:',
				options: [
					{ id: 'A', text: 'When price increases, quantity supplied increases' },
					{ id: 'B', text: 'When price increases, quantity supplied decreases' },
					{ id: 'C', text: 'Price and quantity supplied are unrelated' },
					{ id: 'D', text: 'Supply is perfectly elastic' },
				],
				correctAnswer: 'A',
				hint: 'Direct relationship.',
				topic: 'Supply',
				subtopic: 'Law of Supply',
				difficulty: 'easy',
			},
			{
				id: 'econ-2023-p1-q4',
				question: 'When demand exceeds supply, there is:',
				options: [
					{ id: 'A', text: 'Excess demand' },
					{ id: 'B', text: 'Excess supply' },
					{ id: 'C', text: 'Equilibrium' },
					{ id: 'D', text: 'No change' },
				],
				correctAnswer: 'A',
				hint: 'Shortage in market.',
				topic: 'Demand and Supply',
				subtopic: 'Market Equilibrium',
				difficulty: 'easy',
			},
			{
				id: 'econ-2023-p1-q5',
				question: 'GDP stands for:',
				options: [
					{ id: 'A', text: 'Gross Domestic Product' },
					{ id: 'B', text: 'Gross Domestic Profit' },
					{ id: 'C', text: 'General Domestic Product' },
					{ id: 'D', text: 'Government Domestic Policy' },
				],
				correctAnswer: 'A',
				hint: 'Total value of goods produced in country.',
				topic: 'Macroeconomics',
				subtopic: 'GDP',
				difficulty: 'easy',
			},
			{
				id: 'econ-2023-p1-q6',
				question: 'The budget deficit occurs when:',
				options: [
					{ id: 'A', text: 'Government spends more than it collects' },
					{ id: 'B', text: 'Government spends less than it collects' },
					{ id: 'C', text: 'Taxes equal spending' },
					{ id: 'D', text: 'There is a surplus' },
				],
				correctAnswer: 'A',
				hint: 'More spending than revenue.',
				topic: 'Fiscal Policy',
				subtopic: 'Budget',
				difficulty: 'easy',
			},
			{
				id: 'econ-2023-p1-q7',
				question: 'Inflation reduces:',
				options: [
					{ id: 'A', text: 'Purchasing power of money' },
					{ id: 'B', text: 'Value of goods' },
					{ id: 'C', text: 'Unemployment' },
					{ id: 'D', text: 'Output' },
				],
				correctAnswer: 'A',
				hint: 'Money buys less.',
				topic: 'Macroeconomics',
				subtopic: 'Inflation',
				difficulty: 'easy',
			},
			{
				id: 'econ-2023-p1-q8',
				question: 'The SARB uses monetary policy to:',
				options: [
					{ id: 'A', text: 'Control money supply and interest rates' },
					{ id: 'B', text: 'Collect taxes' },
					{ id: 'C', text: 'Set prices' },
					{ id: 'D', text: 'Control exports' },
				],
				correctAnswer: 'A',
				hint: 'Central bank tools.',
				topic: 'Monetary Policy',
				subtopic: 'SARB',
				difficulty: 'easy',
			},
			{
				id: 'econ-2023-p1-q9',
				question: 'A tariff is a tax on:',
				options: [
					{ id: 'A', text: 'Imports' },
					{ id: 'B', text: 'Exports' },
					{ id: 'C', text: 'Production' },
					{ id: 'D', text: 'Sales' },
				],
				correctAnswer: 'A',
				hint: 'Protects local industry.',
				topic: 'International Trade',
				subtopic: 'Tariffs',
				difficulty: 'easy',
			},
			{
				id: 'econ-2023-p1-q10',
				question: 'Foreign direct investment involves:',
				options: [
					{ id: 'A', text: 'Long-term investment in another country' },
					{ id: 'B', text: 'Short-term loans' },
					{ id: 'C', text: 'Charity' },
					{ id: 'D', text: 'International aid only' },
				],
				correctAnswer: 'A',
				hint: 'Building factories, infrastructure.',
				topic: 'International Trade',
				subtopic: 'FDI',
				difficulty: 'medium',
			},
			{
				id: 'econ-2023-p1-q11',
				question: 'The multiplier effect shows that:',
				options: [
					{ id: 'A', text: 'Initial spending leads to greater income generation' },
					{ id: 'B', text: 'Spending has no impact' },
					{ id: 'C', text: 'Taxes reduce income' },
					{ id: 'D', text: 'Savings increase GDP' },
				],
				correctAnswer: 'A',
				hint: 'One person spending = another income.',
				topic: 'Macroeconomics',
				subtopic: 'Multiplier',
				difficulty: 'medium',
			},
			{
				id: 'econ-2023-p1-q12',
				question: 'A developed economy is characterized by:',
				options: [
					{ id: 'A', text: 'High GDP per capita, industrialization' },
					{ id: 'B', text: 'High unemployment, low GDP' },
					{ id: 'C', text: 'Agrarian society' },
					{ id: 'D', text: 'Mainly mining' },
				],
				correctAnswer: 'A',
				hint: 'Industrialized, high income.',
				topic: 'Economic Development',
				subtopic: 'Development',
				difficulty: 'medium',
			},
			{
				id: 'econ-2023-p1-q13',
				question: 'Unemployment rate is calculated as:',
				options: [
					{ id: 'A', text: 'Unemployed / Labour force × 100' },
					{ id: 'B', text: 'Unemployed / Total population × 100' },
					{ id: 'C', text: 'Employed / Total population × 100' },
					{ id: 'D', text: 'Labour force / Total × 100' },
				],
				correctAnswer: 'A',
				hint: 'Percentage of job seekers.',
				topic: 'Labour Market',
				subtopic: 'Unemployment',
				difficulty: 'medium',
			},
			{
				id: 'econ-2023-p1-q14',
				question: 'Public sector provides:',
				options: [
					{ id: 'A', text: 'Essential services like education and health' },
					{ id: 'B', text: 'Private goods only' },
					{ id: 'C', text: 'Luxury items' },
					{ id: 'D', text: 'Export goods' },
				],
				correctAnswer: 'A',
				hint: 'Merit and public goods.',
				topic: 'Role of Government',
				subtopic: 'Public Sector',
				difficulty: 'easy',
			},
			{
				id: 'econ-2023-p1-q15',
				question: 'Economic growth is measured by:',
				options: [
					{ id: 'A', text: 'Increase in real GDP' },
					{ id: 'B', text: 'Increase in population' },
					{ id: 'C', text: 'Decrease in prices' },
					{ id: 'D', text: 'More imports' },
				],
				correctAnswer: 'A',
				hint: 'Year-on-year GDP change.',
				topic: 'Macroeconomics',
				subtopic: 'Growth',
				difficulty: 'easy',
			},
		],
	},
	'econ-p1-2022-nov': {
		title: 'NSC Economics P1 November 2022',
		subject: 'Economics',
		year: 2022,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'econ-2022-p1-q1',
				question: 'Opportunity cost is:',
				options: [
					{ id: 'A', text: 'The next best alternative given up' },
					{ id: 'B', text: 'The total cost' },
					{ id: 'C', text: 'The price paid' },
					{ id: 'D', text: 'The revenue earned' },
				],
				correctAnswer: 'A',
				hint: 'What you give up.',
				topic: 'Introduction',
				subtopic: 'Opportunity Cost',
				difficulty: 'easy',
			},
			{
				id: 'econ-2022-p1-q2',
				question: 'Capital as a factor of production includes:',
				options: [
					{ id: 'A', text: 'Machinery and buildings' },
					{ id: 'B', text: 'Raw labor' },
					{ id: 'C', text: 'Natural resources' },
					{ id: 'D', text: 'Money' },
				],
				correctAnswer: 'A',
				hint: 'Man-made productive resources.',
				topic: 'Factors of Production',
				subtopic: 'Capital',
				difficulty: 'easy',
			},
			{
				id: 'econ-2022-p1-q3',
				question: 'The law of demand states that:',
				options: [
					{ id: 'A', text: 'Price and quantity demanded are inversely related' },
					{ id: 'B', text: 'Price and quantity demanded are directly related' },
					{ id: 'C', text: 'Demand is fixed' },
					{ id: 'D', text: 'Price never changes' },
				],
				correctAnswer: 'A',
				hint: 'Higher price = less demand.',
				topic: 'Demand',
				subtopic: 'Law of Demand',
				difficulty: 'easy',
			},
			{
				id: 'econ-2022-p1-q4',
				question: 'Price elasticity of demand measures:',
				options: [
					{ id: 'A', text: 'Responsiveness of quantity to price changes' },
					{ id: 'B', text: 'Change in income' },
					{ id: 'C', text: 'Total revenue' },
					{ id: 'D', text: 'Supply changes' },
				],
				correctAnswer: 'A',
				hint: '% change in Qd / % change in P.',
				topic: 'Elasticity',
				subtopic: 'Price Elasticity',
				difficulty: 'medium',
			},
			{
				id: 'econ-2022-p1-q5',
				question: 'A leftward shift in demand could be caused by:',
				options: [
					{ id: 'A', text: 'Decrease in consumer income' },
					{ id: 'B', text: 'Increase in price of substitute' },
					{ id: 'C', text: 'Increase in population' },
					{ id: 'D', text: 'Better weather' },
				],
				correctAnswer: 'A',
				hint: 'Less demand at each price.',
				topic: 'Demand',
				subtopic: 'Shifts',
				difficulty: 'medium',
			},
			{
				id: 'econ-2022-p1-q6',
				question: 'The fiscal policy is controlled by:',
				options: [
					{ id: 'A', text: 'Government' },
					{ id: 'B', text: 'Reserve Bank' },
					{ id: 'C', text: 'Private sector' },
					{ id: 'D', text: 'World Bank' },
				],
				correctAnswer: 'A',
				hint: 'Tax and spend.',
				topic: 'Fiscal Policy',
				subtopic: 'Government',
				difficulty: 'easy',
			},
			{
				id: 'econ-2022-p1-q7',
				question: 'A progressive tax means:',
				options: [
					{ id: 'A', text: 'Higher income pays higher percentage' },
					{ id: 'B', text: 'Everyone pays same percentage' },
					{ id: 'C', text: 'Higher income pays less' },
					{ id: 'D', text: 'No tax on low income' },
				],
				correctAnswer: 'A',
				hint: 'Based on ability to pay.',
				topic: 'Fiscal Policy',
				subtopic: 'Taxation',
				difficulty: 'medium',
			},
			{
				id: 'econ-2022-p1-q8',
				question: 'Types of unemployment include:',
				options: [
					{ id: 'A', text: 'Frictional, Structural, Cyclical' },
					{ id: 'B', text: 'Only cyclical' },
					{ id: 'C', text: 'Only seasonal' },
					{ id: 'D', text: 'No unemployment' },
				],
				correctAnswer: 'A',
				hint: 'Different causes.',
				topic: 'Labour Market',
				subtopic: 'Unemployment',
				difficulty: 'medium',
			},
			{
				id: 'econ-2022-p1-q9',
				question: 'A trade surplus means:',
				options: [
					{ id: 'A', text: 'Exports > Imports' },
					{ id: 'B', text: 'Imports > Exports' },
					{ id: 'C', text: 'Exports = Imports' },
					{ id: 'D', text: 'No trade' },
				],
				correctAnswer: 'A',
				hint: 'Positive balance.',
				topic: 'International Trade',
				subtopic: 'Balance of Trade',
				difficulty: 'easy',
			},
			{
				id: 'econ-2022-p1-q10',
				question: 'Development economics focuses on:',
				options: [
					{ id: 'A', text: 'Improving living standards in developing countries' },
					{ id: 'B', text: 'Rich country growth only' },
					{ id: 'C', text: 'Reducing all trade' },
					{ id: 'D', text: 'Maximizing profits' },
				],
				correctAnswer: 'A',
				hint: 'Poverty alleviation.',
				topic: 'Economic Development',
				subtopic: 'Development',
				difficulty: 'easy',
			},
		],
	},
	'econ-p1-2021-nov': {
		title: 'NSC Economics P1 November 2021',
		subject: 'Economics',
		year: 2021,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'econ-2021-p1-q1',
				question: 'Scarcity forces people to:',
				options: [
					{ id: 'A', text: 'Make choices' },
					{ id: 'B', text: 'Have unlimited goods' },
					{ id: 'C', text: 'Never choose' },
					{ id: 'D', text: 'Stop working' },
				],
				correctAnswer: 'A',
				hint: 'Trade-offs.',
				topic: 'Introduction',
				subtopic: 'Scarcity',
				difficulty: 'easy',
			},
			{
				id: 'econ-2021-p1-q2',
				question: 'Market equilibrium occurs where:',
				options: [
					{ id: 'A', text: 'Demand equals supply' },
					{ id: 'B', text: 'Price is highest' },
					{ id: 'C', text: 'Demand exceeds supply' },
					{ id: 'D', text: 'Supply exceeds demand' },
				],
				correctAnswer: 'A',
				hint: 'No tendency to change.',
				topic: 'Demand and Supply',
				subtopic: 'Equilibrium',
				difficulty: 'easy',
			},
			{
				id: 'econ-2021-p1-q3',
				question: 'A decrease in supply causes:',
				options: [
					{ id: 'A', text: 'Price to rise, quantity to fall' },
					{ id: 'B', text: 'Price to fall' },
					{ id: 'C', text: 'No change in price' },
					{ id: 'D', text: 'Quantity to increase' },
				],
				correctAnswer: 'A',
				hint: 'Less available = higher price.',
				topic: 'Supply',
				subtopic: 'Changes in Supply',
				difficulty: 'medium',
			},
			{
				id: 'econ-2021-p1-q4',
				question: 'The CPI measures:',
				options: [
					{ id: 'A', text: 'Changes in price levels' },
					{ id: 'B', text: 'GDP growth' },
					{ id: 'C', text: 'Unemployment rate' },
					{ id: 'D', text: 'Export values' },
				],
				correctAnswer: 'A',
				hint: 'Cost of living index.',
				topic: 'Macroeconomics',
				subtopic: 'CPI',
				difficulty: 'easy',
			},
			{
				id: 'econ-2021-p1-q5',
				question: 'The SARB is the:',
				options: [
					{ id: 'A', text: 'Central Bank of South Africa' },
					{ id: 'B', text: 'Government ministry' },
					{ id: 'C', text: 'Trade union' },
					{ id: 'D', text: 'Business association' },
				],
				correctAnswer: 'A',
				hint: 'Manages money supply.',
				topic: 'Monetary Policy',
				subtopic: 'SARB',
				difficulty: 'easy',
			},
			{
				id: 'econ-2021-p1-q6',
				question: 'A quota is a:',
				options: [
					{ id: 'A', text: 'Limit on quantity of imports' },
					{ id: 'B', text: 'Tax on exports' },
					{ id: 'C', text: 'Type of subsidy' },
					{ id: 'D', text: 'Free trade agreement' },
				],
				correctAnswer: 'A',
				hint: 'Quantitative restriction.',
				topic: 'International Trade',
				subtopic: 'Quotas',
				difficulty: 'easy',
			},
			{
				id: 'econ-2021-p1-q7',
				question: 'If currency appreciates, imports become:',
				options: [
					{ id: 'A', text: 'Cheaper' },
					{ id: 'B', text: 'More expensive' },
					{ id: 'C', text: 'Same price' },
					{ id: 'D', text: 'No imports' },
				],
				correctAnswer: 'A',
				hint: 'Rands buy more foreign goods.',
				topic: 'Exchange Rates',
				subtopic: 'Impact',
				difficulty: 'medium',
			},
			{
				id: 'econ-2021-p1-q8',
				question: 'Positive externalities mean:',
				options: [
					{ id: 'A', text: 'Benefits to third parties' },
					{ id: 'B', text: 'Costs to third parties' },
					{ id: 'C', text: 'No benefits' },
					{ id: 'D', text: 'Only private benefits' },
				],
				correctAnswer: 'A',
				hint: 'Spillover benefits.',
				topic: 'Market Failures',
				subtopic: 'Externalities',
				difficulty: 'medium',
			},
			{
				id: 'econ-2021-p1-q9',
				question: 'The national budget is presented by:',
				options: [
					{ id: 'A', text: 'Finance Minister in February' },
					{ id: 'B', text: 'President only' },
					{ id: 'C', text: 'SARB Governor' },
					{ id: 'D', text: 'Parliament' },
				],
				correctAnswer: 'A',
				hint: 'Annual statement.',
				topic: 'Fiscal Policy',
				subtopic: 'Budget',
				difficulty: 'easy',
			},
			{
				id: 'econ-2021-p1-q10',
				question: 'HDI measures:',
				options: [
					{ id: 'A', text: 'Human development level' },
					{ id: 'B', text: 'Industrial output' },
					{ id: 'C', text: 'Trade volume' },
					{ id: 'D', text: 'Military strength' },
				],
				correctAnswer: 'A',
				hint: 'Education, health, income.',
				topic: 'Economic Development',
				subtopic: 'HDI',
				difficulty: 'easy',
			},
		],
	},
};
