import type { QuizData } from './types';

export const GEOGRAPHY_QUIZ: QuizData = {
	'geog-p1-2023-nov': {
		title: 'NSC Geography P1 November 2023',
		subject: 'Geography',
		year: 2023,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'geog-2023-p1-q1',
				question: 'Mid-latitude cyclones move from:',
				options: [
					{ id: 'A', text: 'West to East' },
					{ id: 'B', text: 'East to West' },
					{ id: 'C', text: 'North to South' },
					{ id: 'D', text: 'South to North' },
				],
				correctAnswer: 'A',
				hint: 'Driven by the westerlies.',
				topic: 'Climatology',
				subtopic: 'Mid-latitude Cyclones',
				difficulty: 'easy',
			},
			{
				id: 'geog-2023-p1-q2',
				question: 'Which river exhibits a trellis drainage pattern?',
				options: [
					{ id: 'A', text: 'River flowing over alternating hard and soft rock' },
					{ id: 'B', text: 'River on a dome structure' },
					{ id: 'C', text: 'River on uniform rock' },
					{ id: 'D', text: 'River on a steep slope' },
				],
				correctAnswer: 'A',
				hint: 'Trellis patterns form in folded landscapes with ridges and valleys.',
				topic: 'Geomorphology',
				subtopic: 'Drainage Basins',
				difficulty: 'medium',
			},
			{
				id: 'geog-2023-p1-q3',
				question: 'The Berg Wind is a:',
				options: [
					{ id: 'A', text: 'Warm, dry wind' },
					{ id: 'B', text: 'Cold, wet wind' },
					{ id: 'C', text: 'Sea breeze' },
					{ id: 'D', text: 'Land breeze' },
				],
				correctAnswer: 'A',
				hint: 'It descends from the plateau, warming adiabatically.',
				topic: 'Climatology',
				subtopic: 'Local Winds',
				difficulty: 'easy',
			},
			{
				id: 'geog-2023-p1-q4',
				question: 'Laminar flow in a river occurs when:',
				options: [
					{ id: 'A', text: 'The river bed is smooth and level' },
					{ id: 'B', text: 'The river bed is rough' },
					{ id: 'C', text: 'Water velocity is high' },
					{ id: 'D', text: 'There are many obstacles' },
				],
				correctAnswer: 'A',
				hint: 'Laminar flow is smooth, sheet-like flow.',
				topic: 'Geomorphology',
				subtopic: 'Fluvial Processes',
				difficulty: 'medium',
			},
			{
				id: 'geog-2023-p1-q5',
				question: 'An urban heat island is caused by:',
				options: [
					{ id: 'A', text: 'Artificial surfaces and pollution' },
					{ id: 'B', text: 'Abundant vegetation' },
					{ id: 'C', text: 'Water bodies' },
					{ id: 'D', text: 'Low building density' },
				],
				correctAnswer: 'A',
				hint: 'Concrete and asphalt absorb heat.',
				topic: 'Climatology',
				subtopic: 'Urban Climate',
				difficulty: 'medium',
			},
			{
				id: 'geog-2023-p1-q6',
				question: 'Abstraction occurs when:',
				options: [
					{ id: 'A', text: 'One river captures another' },
					{ id: 'B', text: 'A river dries up' },
					{ id: 'C', text: 'Groundwater is polluted' },
					{ id: 'D', text: 'A delta forms' },
				],
				correctAnswer: 'A',
				hint: 'Also known as river capture.',
				topic: 'Geomorphology',
				subtopic: 'River Capture',
				difficulty: 'medium',
			},
			{
				id: 'geog-2023-p1-q7',
				question: 'El Niño events are associated with:',
				options: [
					{ id: 'A', text: 'Drought in South Africa' },
					{ id: 'B', text: 'Flooding in South Africa' },
					{ id: 'C', text: 'Normal rainfall' },
					{ id: 'D', text: 'Cold ocean currents' },
				],
				correctAnswer: 'A',
				hint: 'El Niño typically brings drier conditions to SA.',
				topic: 'Climatology',
				subtopic: 'Global Circulation',
				difficulty: 'medium',
			},
			{
				id: 'geog-2023-p1-q8',
				question: 'A rejuvenation point in a river is marked by:',
				options: [
					{ id: 'A', text: 'A knickpoint or waterfall' },
					{ id: 'B', text: 'A meander' },
					{ id: 'C', text: 'A floodplain' },
					{ id: 'D', text: 'A delta' },
				],
				correctAnswer: 'A',
				hint: 'Rejuvenation causes vertical erosion, creating a step.',
				topic: 'Geomorphology',
				subtopic: 'Rejuvenation',
				difficulty: 'medium',
			},
			{
				id: 'geog-2023-p1-q9',
				question: 'The eye of a tropical cyclone is characterized by:',
				options: [
					{ id: 'A', text: 'Calm, clear conditions' },
					{ id: 'B', text: 'Strongest winds' },
					{ id: 'C', text: 'Heavy rain' },
					{ id: 'D', text: 'Lightning' },
				],
				correctAnswer: 'A',
				hint: 'Descending air creates clear skies in the eye.',
				topic: 'Climatology',
				subtopic: 'Tropical Cyclones',
				difficulty: 'easy',
			},
			{
				id: 'geog-2023-p1-q10',
				question: 'Which slope is warmer in the Southern Hemisphere?',
				options: [
					{ id: 'A', text: 'North-facing slope' },
					{ id: 'B', text: 'South-facing slope' },
					{ id: 'C', text: 'East-facing slope' },
					{ id: 'D', text: 'West-facing slope' },
				],
				correctAnswer: 'A',
				hint: 'Equator is to the north.',
				topic: 'Climatology',
				subtopic: 'Microclimate',
				difficulty: 'easy',
			},
			{
				id: 'geog-2023-p1-q11',
				question: 'Mass movement is primarily driven by:',
				options: [
					{ id: 'A', text: 'Gravity' },
					{ id: 'B', text: 'Wind' },
					{ id: 'C', text: 'Running water' },
					{ id: 'D', text: 'Ice' },
				],
				correctAnswer: 'A',
				hint: 'Gravity pulls material downslope.',
				topic: 'Geomorphology',
				subtopic: 'Mass Movement',
				difficulty: 'easy',
			},
			{
				id: 'geog-2023-p1-q12',
				question: 'In a synoptic weather map, isobars close together indicate:',
				options: [
					{ id: 'A', text: 'Strong winds' },
					{ id: 'B', text: 'Calm conditions' },
					{ id: 'C', text: 'High temperature' },
					{ id: 'D', text: 'High humidity' },
				],
				correctAnswer: 'A',
				hint: 'Steep pressure gradient force.',
				topic: 'Climatology',
				subtopic: 'Synoptic Charts',
				difficulty: 'medium',
			},
			{
				id: 'geog-2023-p1-q13',
				question: 'A graded river profile is:',
				options: [
					{ id: 'A', text: 'Concave' },
					{ id: 'B', text: 'Convex' },
					{ id: 'C', text: 'Straight' },
					{ id: 'D', text: 'Irregular' },
				],
				correctAnswer: 'A',
				hint: 'Ideally smooth and concave curve.',
				topic: 'Geomorphology',
				subtopic: 'River Profiles',
				difficulty: 'medium',
			},
			{
				id: 'geog-2023-p1-q14',
				question: 'Which of the following is a high-pressure cell over the interior of SA?',
				options: [
					{ id: 'A', text: 'Kalahari High' },
					{ id: 'B', text: 'South Atlantic High' },
					{ id: 'C', text: 'South Indian High' },
					{ id: 'D', text: 'Equatorial Low' },
				],
				correctAnswer: 'A',
				hint: 'Dominates in winter.',
				topic: 'Climatology',
				subtopic: 'SA High Pressure Cells',
				difficulty: 'easy',
			},
			{
				id: 'geog-2023-p1-q15',
				question: 'Karst topography is associated with:',
				options: [
					{ id: 'A', text: 'Limestone' },
					{ id: 'B', text: 'Granite' },
					{ id: 'C', text: 'Basalt' },
					{ id: 'D', text: 'Sandstone' },
				],
				correctAnswer: 'A',
				hint: 'Chemical weathering of calcium carbonate.',
				topic: 'Geomorphology',
				subtopic: 'Topography',
				difficulty: 'easy',
			},
		],
	},
};
