import type { QuizData } from './types';

export const GEOGRAPHY_QUIZ: QuizData = {
	'geog-p1-2023-nov': {
		title: 'NSC Geography P1 November 2023',
		subject: 'Geography',
		year: 2023,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'geog-2023-p1-q1',
				question: 'Mid-latitude cyclones move from:',
				options: [
					{ id: 'A', text: 'West to East' },
					{ id: 'B', text: 'East to West' },
					{ id: 'C', text: 'North to South' },
					{ id: 'D', text: 'South to North' },
				],
				correctAnswer: 'A',
				hint: 'Driven by the westerlies.',
				topic: 'Climatology',
				subtopic: 'Mid-latitude Cyclones',
				difficulty: 'easy',
			},
			{
				id: 'geog-2023-p1-q2',
				question: 'Which river exhibits a trellis drainage pattern?',
				options: [
					{ id: 'A', text: 'River flowing over alternating hard and soft rock' },
					{ id: 'B', text: 'River on a dome structure' },
					{ id: 'C', text: 'River on uniform rock' },
					{ id: 'D', text: 'River on a steep slope' },
				],
				correctAnswer: 'A',
				hint: 'Trellis patterns form in folded landscapes with ridges and valleys.',
				topic: 'Geomorphology',
				subtopic: 'Drainage Basins',
				difficulty: 'medium',
			},
			{
				id: 'geog-2023-p1-q3',
				question: 'The Berg Wind is a:',
				options: [
					{ id: 'A', text: 'Warm, dry wind' },
					{ id: 'B', text: 'Cold, wet wind' },
					{ id: 'C', text: 'Sea breeze' },
					{ id: 'D', text: 'Land breeze' },
				],
				correctAnswer: 'A',
				hint: 'It descends from the plateau, warming adiabatically.',
				topic: 'Climatology',
				subtopic: 'Local Winds',
				difficulty: 'easy',
			},
			{
				id: 'geog-2023-p1-q4',
				question: 'Laminar flow in a river occurs when:',
				options: [
					{ id: 'A', text: 'The river bed is smooth and level' },
					{ id: 'B', text: 'The river bed is rough' },
					{ id: 'C', text: 'Water velocity is high' },
					{ id: 'D', text: 'There are many obstacles' },
				],
				correctAnswer: 'A',
				hint: 'Laminar flow is smooth, sheet-like flow.',
				topic: 'Geomorphology',
				subtopic: 'Fluvial Processes',
				difficulty: 'medium',
			},
			{
				id: 'geog-2023-p1-q5',
				question: 'An urban heat island is caused by:',
				options: [
					{ id: 'A', text: 'Artificial surfaces and pollution' },
					{ id: 'B', text: 'Abundant vegetation' },
					{ id: 'C', text: 'Water bodies' },
					{ id: 'D', text: 'Low building density' },
				],
				correctAnswer: 'A',
				hint: 'Concrete and asphalt absorb heat.',
				topic: 'Climatology',
				subtopic: 'Urban Climate',
				difficulty: 'medium',
			},
			{
				id: 'geog-2023-p1-q6',
				question: 'Abstraction occurs when:',
				options: [
					{ id: 'A', text: 'One river captures another' },
					{ id: 'B', text: 'A river dries up' },
					{ id: 'C', text: 'Groundwater is polluted' },
					{ id: 'D', text: 'A delta forms' },
				],
				correctAnswer: 'A',
				hint: 'Also known as river capture.',
				topic: 'Geomorphology',
				subtopic: 'River Capture',
				difficulty: 'medium',
			},
			{
				id: 'geog-2023-p1-q7',
				question: 'El Niño events are associated with:',
				options: [
					{ id: 'A', text: 'Drought in South Africa' },
					{ id: 'B', text: 'Flooding in South Africa' },
					{ id: 'C', text: 'Normal rainfall' },
					{ id: 'D', text: 'Cold ocean currents' },
				],
				correctAnswer: 'A',
				hint: 'El Niño typically brings drier conditions to SA.',
				topic: 'Climatology',
				subtopic: 'Global Circulation',
				difficulty: 'medium',
			},
			{
				id: 'geog-2023-p1-q8',
				question: 'A rejuvenation point in a river is marked by:',
				options: [
					{ id: 'A', text: 'A knickpoint or waterfall' },
					{ id: 'B', text: 'A meander' },
					{ id: 'C', text: 'A floodplain' },
					{ id: 'D', text: 'A delta' },
				],
				correctAnswer: 'A',
				hint: 'Rejuvenation causes vertical erosion, creating a step.',
				topic: 'Geomorphology',
				subtopic: 'Rejuvenation',
				difficulty: 'medium',
			},
			{
				id: 'geog-2023-p1-q9',
				question: 'The eye of a tropical cyclone is characterized by:',
				options: [
					{ id: 'A', text: 'Calm, clear conditions' },
					{ id: 'B', text: 'Strongest winds' },
					{ id: 'C', text: 'Heavy rain' },
					{ id: 'D', text: 'Lightning' },
				],
				correctAnswer: 'A',
				hint: 'Descending air creates clear skies in the eye.',
				topic: 'Climatology',
				subtopic: 'Tropical Cyclones',
				difficulty: 'easy',
			},
			{
				id: 'geog-2023-p1-q10',
				question: 'Which slope is warmer in the Southern Hemisphere?',
				options: [
					{ id: 'A', text: 'North-facing slope' },
					{ id: 'B', text: 'South-facing slope' },
					{ id: 'C', text: 'East-facing slope' },
					{ id: 'D', text: 'West-facing slope' },
				],
				correctAnswer: 'A',
				hint: 'Equator is to the north.',
				topic: 'Climatology',
				subtopic: 'Microclimate',
				difficulty: 'easy',
			},
			{
				id: 'geog-2023-p1-q11',
				question: 'Mass movement is primarily driven by:',
				options: [
					{ id: 'A', text: 'Gravity' },
					{ id: 'B', text: 'Wind' },
					{ id: 'C', text: 'Running water' },
					{ id: 'D', text: 'Ice' },
				],
				correctAnswer: 'A',
				hint: 'Gravity pulls material downslope.',
				topic: 'Geomorphology',
				subtopic: 'Mass Movement',
				difficulty: 'easy',
			},
			{
				id: 'geog-2023-p1-q12',
				question: 'In a synoptic weather map, isobars close together indicate:',
				options: [
					{ id: 'A', text: 'Strong winds' },
					{ id: 'B', text: 'Calm conditions' },
					{ id: 'C', text: 'High temperature' },
					{ id: 'D', text: 'High humidity' },
				],
				correctAnswer: 'A',
				hint: 'Steep pressure gradient force.',
				topic: 'Climatology',
				subtopic: 'Synoptic Charts',
				difficulty: 'medium',
			},
			{
				id: 'geog-2023-p1-q13',
				question: 'A graded river profile is:',
				options: [
					{ id: 'A', text: 'Concave' },
					{ id: 'B', text: 'Convex' },
					{ id: 'C', text: 'Straight' },
					{ id: 'D', text: 'Irregular' },
				],
				correctAnswer: 'A',
				hint: 'Ideally smooth and concave curve.',
				topic: 'Geomorphology',
				subtopic: 'River Profiles',
				difficulty: 'medium',
			},
			{
				id: 'geog-2023-p1-q14',
				question: 'Which of the following is a high-pressure cell over the interior of SA?',
				options: [
					{ id: 'A', text: 'Kalahari High' },
					{ id: 'B', text: 'South Atlantic High' },
					{ id: 'C', text: 'South Indian High' },
					{ id: 'D', text: 'Equatorial Low' },
				],
				correctAnswer: 'A',
				hint: 'Dominates in winter.',
				topic: 'Climatology',
				subtopic: 'SA High Pressure Cells',
				difficulty: 'easy',
			},
			{
				id: 'geog-2023-p1-q15',
				question: 'Karst topography is associated with:',
				options: [
					{ id: 'A', text: 'Limestone' },
					{ id: 'B', text: 'Granite' },
					{ id: 'C', text: 'Basalt' },
					{ id: 'D', text: 'Sandstone' },
				],
				correctAnswer: 'A',
				hint: 'Chemical weathering of calcium carbonate.',
				topic: 'Geomorphology',
				subtopic: 'Topography',
				difficulty: 'easy',
			},
		],
	},
	'geog-p1-2022-nov': {
		title: 'NSC Geography P1 November 2022',
		subject: 'Geography',
		year: 2022,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'geog-2022-p1-q1',
				question: 'The South Indian Ocean High Pressure cell dominates in:',
				options: [
					{ id: 'A', text: 'Summer' },
					{ id: 'B', text: 'Winter' },
					{ id: 'C', text: 'Autumn' },
					{ id: 'D', text: 'Spring' },
				],
				correctAnswer: 'A',
				hint: 'Strengthens in summer bringing moist maritime air.',
				topic: 'Climatology',
				subtopic: 'High Pressure Cells',
				difficulty: 'easy',
			},
			{
				id: 'geog-2022-p1-q2',
				question: 'Which drainage pattern forms on horizontal rock layers?',
				options: [
					{ id: 'A', text: 'Dendritic' },
					{ id: 'B', text: 'Trellis' },
					{ id: 'C', text: 'Radial' },
					{ id: 'D', text: 'Rectangular' },
				],
				correctAnswer: 'A',
				hint: 'Like tree branches on uniform rock.',
				topic: 'Geomorphology',
				subtopic: 'Drainage Patterns',
				difficulty: 'medium',
			},
			{
				id: 'geog-2022-p1-q3',
				question: 'The Oos River forms a:',
				options: [
					{ id: 'A', text: 'Delta' },
					{ id: 'B', text: 'Estuary' },
					{ id: 'C', text: 'Lagoon' },
					{ id: 'D', text: 'Mouth' },
				],
				correctAnswer: 'A',
				hint: 'River deposits sediment at mouth forming delta.',
				topic: 'Geomorphology',
				subtopic: 'Fluvial Landforms',
				difficulty: 'easy',
			},
			{
				id: 'geog-2022-p1-q4',
				question: 'Tropical cyclones in South Africa originate from:',
				options: [
					{ id: 'A', text: 'Indian Ocean' },
					{ id: 'B', text: 'Atlantic Ocean' },
					{ id: 'C', text: 'Pacific Ocean' },
					{ id: 'D', text: 'Mediterranean Sea' },
				],
				correctAnswer: 'A',
				hint: 'Form over warm Indian Ocean waters.',
				topic: 'Climatology',
				subtopic: 'Tropical Cyclones',
				difficulty: 'easy',
			},
			{
				id: 'geog-2022-p1-q5',
				question: 'A rejuvenated river profile shows:',
				options: [
					{ id: 'A', text: 'Knickpoints and terraces' },
					{ id: 'B', text: 'Meanders and floodplain' },
					{ id: 'C', text: 'Delta only' },
					{ id: 'D', text: 'Uniform gradient' },
				],
				correctAnswer: 'A',
				hint: 'New cycle of erosion creates steps.',
				topic: 'Geomorphology',
				subtopic: 'Rejuvenation',
				difficulty: 'medium',
			},
			{
				id: 'geog-2022-p1-q6',
				question: 'The Intertropical Convergence Zone (ITCZ) shifts:',
				options: [
					{ id: 'A', text: 'North in summer, south in winter' },
					{ id: 'B', text: 'South in summer, north in winter' },
					{ id: 'C', text: 'Stays in same position' },
					{ id: 'D', text: 'East-west only' },
				],
				correctAnswer: 'A',
				hint: 'Follows the sun.',
				topic: 'Climatology',
				subtopic: 'Global Circulation',
				difficulty: 'medium',
			},
			{
				id: 'geog-2022-p1-q7',
				question: 'Which slope receives more direct sunlight in SA?',
				options: [
					{ id: 'A', text: 'Northern' },
					{ id: 'B', text: 'Southern' },
					{ id: 'C', text: 'Both equally' },
					{ id: 'D', text: 'Neither' },
				],
				correctAnswer: 'A',
				hint: 'Northern slopes face equator.',
				topic: 'Climatology',
				subtopic: 'Aspect',
				difficulty: 'easy',
			},
			{
				id: 'geog-2022-p1-q8',
				question: 'Fluvial processes include:',
				options: [
					{ id: 'A', text: 'Erosion, transport, deposition' },
					{ id: 'B', text: 'Weathering only' },
					{ id: 'C', text: 'Volcanic activity' },
					{ id: 'D', text: 'Glaciation' },
				],
				correctAnswer: 'A',
				hint: 'All river processes.',
				topic: 'Geomorphology',
				subtopic: 'Fluvial Processes',
				difficulty: 'easy',
			},
			{
				id: 'geog-2022-p1-q9',
				question: 'Warm ocean current along east coast of SA is:',
				options: [
					{ id: 'A', text: 'Agulhas Current' },
					{ id: 'B', text: 'Benguela Current' },
					{ id: 'C', text: 'Mozambique Current' },
					{ id: 'D', text: 'Somali Current' },
				],
				correctAnswer: 'A',
				hint: 'Warm current from Indian Ocean.',
				topic: 'Oceanography',
				subtopic: 'Currents',
				difficulty: 'easy',
			},
			{
				id: 'geog-2022-p1-q10',
				question: 'Incast wind patterns are caused by:',
				options: [
					{ id: 'A', text: 'Differential heating of land and sea' },
					{ id: 'B', text: 'Global wind systems' },
					{ id: 'C', text: 'Ocean currents' },
					{ id: 'D', text: 'Mountain barriers' },
				],
				correctAnswer: 'A',
				hint: 'Land heats faster than sea.',
				topic: 'Climatology',
				subtopic: 'Local Winds',
				difficulty: 'medium',
			},
			{
				id: 'geog-2022-p1-q11',
				question: 'The adiabatic lapse rate for dry air is:',
				options: [
					{ id: 'A', text: '1°C per 100m' },
					{ id: 'B', text: '0.5°C per 100m' },
					{ id: 'C', text: '2°C per 100m' },
					{ id: 'D', text: '0.65°C per 100m' },
				],
				correctAnswer: 'A',
				hint: 'Standard dry adiabatic rate.',
				topic: 'Climatology',
				subtopic: 'Lapse Rates',
				difficulty: 'medium',
			},
			{
				id: 'geog-2022-p1-q12',
				question: 'Pioneer species in ecological succession are:',
				options: [
					{ id: 'A', text: 'Lichens and mosses' },
					{ id: 'B', text: 'Trees' },
					{ id: 'C', text: 'Grasses' },
					{ id: 'D', text: 'Shrubs' },
				],
				correctAnswer: 'A',
				hint: 'First colonizers on bare rock.',
				topic: 'Biogeography',
				subtopic: 'Succession',
				difficulty: 'easy',
			},
		],
	},
	'geog-p1-2021-nov': {
		title: 'NSC Geography P1 November 2021',
		subject: 'Geography',
		year: 2021,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'geog-2021-p1-q1',
				question: 'The Kalahari High Pressure system is strongest in:',
				options: [
					{ id: 'A', text: 'Winter' },
					{ id: 'B', text: 'Summer' },
					{ id: 'C', text: 'Spring' },
					{ id: 'D', text: 'Autumn' },
				],
				correctAnswer: 'A',
				hint: 'Cold, dry air dominates in winter.',
				topic: 'Climatology',
				subtopic: 'High Pressure',
				difficulty: 'easy',
			},
			{
				id: 'geog-2021-p1-q2',
				question: 'Which front is associated with mid-latitude cyclones?',
				options: [
					{ id: 'A', text: 'Warm front, Cold front, Occluded front' },
					{ id: 'B', text: 'Stationary front only' },
					{ id: 'C', text: 'No front' },
					{ id: 'D', text: 'Single front' },
				],
				correctAnswer: 'A',
				hint: 'Cyclones have multiple fronts.',
				topic: 'Climatology',
				subtopic: 'Mid-latitude Cyclones',
				difficulty: 'medium',
			},
			{
				id: 'geog-2021-p1-q3',
				question: 'A river catchment area is also called:',
				options: [
					{ id: 'A', text: 'Drainage basin' },
					{ id: 'B', text: 'Watershed' },
					{ id: 'C', text: 'Confluence' },
					{ id: 'D', text: 'Tributary' },
				],
				correctAnswer: 'A',
				hint: 'Area drained by river system.',
				topic: 'Geomorphology',
				subtopic: 'Drainage Basins',
				difficulty: 'easy',
			},
			{
				id: 'geog-2021-p1-q4',
				question: 'The eye of a tropical cyclone has:',
				options: [
					{ id: 'A', text: 'Low pressure and calm' },
					{ id: 'B', text: 'High pressure and storm' },
					{ id: 'C', text: 'No pressure change' },
					{ id: 'D', text: 'Variable pressure' },
				],
				correctAnswer: 'A',
				hint: 'Descending air creates calm center.',
				topic: 'Climatology',
				subtopic: 'Tropical Cyclones',
				difficulty: 'easy',
			},
			{
				id: 'geog-2021-p1-q5',
				question: 'Which process breaks down rock chemically?',
				options: [
					{ id: 'A', text: 'Hydrolysis' },
					{ id: 'B', text: 'Frost action' },
					{ id: 'C', text: 'Exfoliation' },
					{ id: 'D', text: 'Thermal expansion' },
				],
				correctAnswer: 'A',
				hint: 'Water reacts with minerals.',
				topic: 'Geomorphology',
				subtopic: 'Weathering',
				difficulty: 'easy',
			},
			{
				id: 'geog-2021-p1-q6',
				question: 'The gradient of a graded river is:',
				options: [
					{ id: 'A', text: 'Steep at source, gentle at mouth' },
					{ id: 'B', text: 'Uniform throughout' },
					{ id: 'C', text: 'Gentle at source, steep at mouth' },
					{ id: 'D', text: 'Vertical at mouth' },
				],
				correctAnswer: 'A',
				hint: 'Smooth concave profile.',
				topic: 'Geomorphology',
				subtopic: 'River Profile',
				difficulty: 'medium',
			},
			{
				id: 'geog-2021-p1-q7',
				question: 'Insolation is:',
				options: [
					{ id: 'A', text: 'Incoming solar radiation' },
					{ id: 'B', text: 'Reflected radiation' },
					{ id: 'C', text: 'Heat from Earth' },
					{ id: 'D', text: 'Wind energy' },
				],
				correctAnswer: 'A',
				hint: 'Solar energy reaching Earth.',
				topic: 'Climatology',
				subtopic: 'Energy Balance',
				difficulty: 'easy',
			},
			{
				id: 'geog-2021-p1-q8',
				question: 'When does El Niño typically occur?',
				options: [
					{ id: 'A', text: 'Every 3-7 years' },
					{ id: 'B', text: 'Every year' },
					{ id: 'C', text: 'Every 20 years' },
					{ id: 'D', text: 'Never in SA' },
				],
				correctAnswer: 'A',
				hint: 'Irregular cycle.',
				topic: 'Climatology',
				subtopic: 'El Niño',
				difficulty: 'easy',
			},
			{
				id: 'geog-2021-p1-q9',
				question: 'Mass movement is most likely on:',
				options: [
					{ id: 'A', text: 'Steep, unstable slopes' },
					{ id: 'B', text: 'Flat terrain' },
					{ id: 'C', text: 'Underground caves' },
					{ id: 'D', text: 'Ocean floors' },
				],
				correctAnswer: 'A',
				hint: 'Gravity pull on unstable material.',
				topic: 'Geomorphology',
				subtopic: 'Mass Movement',
				difficulty: 'easy',
			},
			{
				id: 'geog-2021-p1-q10',
				question: 'Fog forms when:',
				options: [
					{ id: 'A', text: 'Air cools to dew point near ground' },
					{ id: 'B', text: 'Air heats rapidly' },
					{ id: 'C', text: 'Wind speed increases' },
					{ id: 'D', text: 'Pressure increases' },
				],
				correctAnswer: 'A',
				hint: 'Stratus cloud at ground level.',
				topic: 'Climatology',
				subtopic: 'Fog',
				difficulty: 'medium',
			},
		],
	},
};
