import type { QuizData } from './types';

export const LIFE_SCIENCES_QUIZ: QuizData = {
	'life-p1-2023-nov': {
		title: 'NSC Life Sciences P1 November 2023',
		subject: 'Life Sciences',
		year: 2023,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'life-2023-p1-q1',
				question: 'Which organelle is responsible for cellular respiration?',
				options: [
					{ id: 'A', text: 'Mitochondria' },
					{ id: 'B', text: 'Ribosome' },
					{ id: 'C', text: 'Nucleus' },
					{ id: 'D', text: 'Chloroplast' },
				],
				correctAnswer: 'A',
				hint: 'Mitochondria produce ATP through respiration.',
				topic: 'Cell Biology',
				subtopic: 'Organelles',
				difficulty: 'easy',
			},
			{
				id: 'life-2023-p1-q2',
				question: 'DNA replication occurs during which phase of the cell cycle?',
				options: [
					{ id: 'A', text: 'S phase of interphase' },
					{ id: 'B', text: 'Prophase' },
					{ id: 'C', text: 'Metaphase' },
					{ id: 'D', text: 'Cytokinesis' },
				],
				correctAnswer: 'A',
				hint: 'DNA replicates during the S (synthesis) phase.',
				topic: 'Cell Biology',
				subtopic: 'Cell Division',
				difficulty: 'medium',
			},
			{
				id: 'life-2023-p1-q3',
				question: 'The basic structural unit of life is the:',
				options: [
					{ id: 'A', text: 'Cell' },
					{ id: 'B', text: 'Tissue' },
					{ id: 'C', text: 'Organ' },
					{ id: 'D', text: 'Atom' },
				],
				correctAnswer: 'A',
				hint: 'The cell is the smallest unit of life.',
				topic: 'Cell Biology',
				subtopic: 'Cell Theory',
				difficulty: 'easy',
			},
			{
				id: 'life-2023-p1-q4',
				question: 'Which blood vessels carry blood away from the heart?',
				options: [
					{ id: 'A', text: 'Arteries' },
					{ id: 'B', text: 'Veins' },
					{ id: 'C', text: 'Capillaries' },
					{ id: 'D', text: 'Lymph vessels' },
				],
				correctAnswer: 'A',
				hint: 'Arteries carry blood AWAY.',
				topic: 'Human Biology',
				subtopic: 'Circulatory System',
				difficulty: 'easy',
			},
			{
				id: 'life-2023-p1-q5',
				question: 'In meiosis, what is reduced:',
				options: [
					{ id: 'A', text: 'Chromosome number' },
					{ id: 'B', text: 'DNA content' },
					{ id: 'C', text: 'Cell size' },
					{ id: 'D', text: 'Nucleus number' },
				],
				correctAnswer: 'A',
				hint: 'Meiosis reduces chromosome number by half.',
				topic: 'Cell Biology',
				subtopic: 'Meiosis',
				difficulty: 'medium',
			},
			{
				id: 'life-2023-p1-q6',
				question: 'Which nitrogenous base is NOT found in DNA?',
				options: [
					{ id: 'A', text: 'Uracil' },
					{ id: 'B', text: 'Adenine' },
					{ id: 'C', text: 'Guanine' },
					{ id: 'D', text: 'Cytosine' },
				],
				correctAnswer: 'A',
				hint: 'Uracil is found in RNA.',
				topic: 'Genetics',
				subtopic: 'DNA Structure',
				difficulty: 'easy',
			},
			{
				id: 'life-2023-p1-q7',
				question: 'The largest organ in the human body is the:',
				options: [
					{ id: 'A', text: 'Skin' },
					{ id: 'B', text: 'Liver' },
					{ id: 'C', text: 'Brain' },
					{ id: 'D', text: 'Lungs' },
				],
				correctAnswer: 'A',
				hint: 'Skin is the largest organ.',
				topic: 'Human Biology',
				subtopic: 'Organs',
				difficulty: 'easy',
			},
			{
				id: 'life-2023-p1-q8',
				question: 'During photosynthesis, oxygen is released from:',
				options: [
					{ id: 'A', text: 'Water (photolysis)' },
					{ id: 'B', text: 'Carbon dioxide' },
					{ id: 'C', text: 'Glucose' },
					{ id: 'D', text: 'Chlorophyll' },
				],
				correctAnswer: 'A',
				hint: 'Photolysis of water splits H₂O.',
				topic: 'Plant Biology',
				subtopic: 'Photosynthesis',
				difficulty: 'medium',
			},
			{
				id: 'life-2023-p1-q9',
				question: 'A person with blood type AB can receive blood from:',
				options: [
					{ id: 'A', text: 'All blood types' },
					{ id: 'B', text: 'Only AB' },
					{ id: 'C', text: 'Only O' },
					{ id: 'D', text: 'A and B only' },
				],
				correctAnswer: 'A',
				hint: 'AB is universal recipient.',
				topic: 'Human Biology',
				subtopic: 'Blood Types',
				difficulty: 'medium',
			},
			{
				id: 'life-2023-p1-q10',
				question: 'The process where plants lose water vapor is called:',
				options: [
					{ id: 'A', text: 'Transpiration' },
					{ id: 'B', text: 'Respiration' },
					{ id: 'C', text: 'Photosynthesis' },
					{ id: 'D', text: 'Diffusion' },
				],
				correctAnswer: 'A',
				hint: 'Transpiration is water loss from stomata.',
				topic: 'Plant Biology',
				subtopic: 'Water Movement',
				difficulty: 'easy',
			},
			{
				id: 'life-2023-p1-q11',
				question: 'Which type of white blood cell produces antibodies?',
				options: [
					{ id: 'A', text: 'B lymphocytes' },
					{ id: 'B', text: 'T lymphocytes' },
					{ id: 'C', text: 'Neutrophils' },
					{ id: 'D', text: 'Erythrocytes' },
				],
				correctAnswer: 'A',
				hint: 'B lymphocytes produce antibodies.',
				topic: 'Human Biology',
				subtopic: 'Immune System',
				difficulty: 'medium',
			},
			{
				id: 'life-2023-p1-q12',
				question: 'In genetics, codominance occurs when:',
				options: [
					{ id: 'A', text: 'Both alleles are expressed' },
					{ id: 'B', text: 'One allele masks the other' },
					{ id: 'C', text: 'Alleles blend' },
					{ id: 'D', text: 'Only one allele is inherited' },
				],
				correctAnswer: 'A',
				hint: 'Codominance: both alleles show in phenotype.',
				diagram: 'punnett',
				topic: 'Genetics',
				subtopic: 'Inheritance Patterns',
				difficulty: 'medium',
			},
			{
				id: 'life-2023-p1-q13',
				question: 'The pancreas produces which hormone?',
				options: [
					{ id: 'A', text: 'Insulin' },
					{ id: 'B', text: 'Adrenaline' },
					{ id: 'C', text: 'Thyroxine' },
					{ id: 'D', text: 'Cortisol' },
				],
				correctAnswer: 'A',
				hint: 'Pancreas produces insulin.',
				topic: 'Human Biology',
				subtopic: 'Endocrine System',
				difficulty: 'easy',
			},
			{
				id: 'life-2023-p1-q14',
				question: 'What is the function of the kidneys?',
				options: [
					{ id: 'A', text: 'Filter blood and produce urine' },
					{ id: 'B', text: 'Digest food' },
					{ id: 'C', text: 'Pump blood' },
					{ id: 'D', text: 'Produce bile' },
				],
				correctAnswer: 'A',
				hint: 'Kidneys filter blood.',
				topic: 'Human Biology',
				subtopic: 'Excretory System',
				difficulty: 'easy',
			},
			{
				id: 'life-2023-p1-q15',
				question:
					'If a heterozygous tall plant (Tt) is crossed with a homozygous short plant (tt), what phenotypic ratio is expected?',
				options: [
					{ id: 'A', text: '1:1 (tall:short)' },
					{ id: 'B', text: '3:1 (tall:short)' },
					{ id: 'C', text: 'All tall' },
					{ id: 'D', text: 'All short' },
				],
				correctAnswer: 'A',
				hint: 'Tt × tt → 50% tall, 50% short.',
				diagram: 'punnett',
				topic: 'Genetics',
				subtopic: 'Monohybrid Cross',
				difficulty: 'medium',
			},
			{
				id: 'life-2023-p1-q16',
				question: 'Which gas do plants need for photosynthesis?',
				options: [
					{ id: 'A', text: 'Carbon dioxide' },
					{ id: 'B', text: 'Oxygen' },
					{ id: 'C', text: 'Nitrogen' },
					{ id: 'D', text: 'Hydrogen' },
				],
				correctAnswer: 'A',
				hint: 'Plants use CO₂.',
				topic: 'Plant Biology',
				subtopic: 'Photosynthesis',
				difficulty: 'easy',
			},
			{
				id: 'life-2023-p1-q17',
				question: 'The part of the brain that controls balance and coordination is the:',
				options: [
					{ id: 'A', text: 'Cerebellum' },
					{ id: 'B', text: 'Cerebrum' },
					{ id: 'C', text: 'Medulla oblongata' },
					{ id: 'D', text: 'Hypothalamus' },
				],
				correctAnswer: 'A',
				hint: 'Cerebellum coordinates movements.',
				topic: 'Human Biology',
				subtopic: 'Nervous System',
				difficulty: 'medium',
			},
			{
				id: 'life-2023-p1-q18',
				question: 'Evolution occurs through:',
				options: [
					{ id: 'A', text: 'Natural selection' },
					{ id: 'B', text: 'Artificial selection' },
					{ id: 'C', text: 'Selective breeding' },
					{ id: 'D', text: 'Genetic engineering' },
				],
				correctAnswer: 'A',
				hint: 'Natural selection.',
				topic: 'Evolution',
				subtopic: 'Natural Selection',
				difficulty: 'easy',
			},
			{
				id: 'life-2023-p1-q19',
				question: 'Which organelle is found in plant cells but NOT in animal cells?',
				options: [
					{ id: 'A', text: 'Chloroplast' },
					{ id: 'B', text: 'Mitochondria' },
					{ id: 'C', text: 'Nucleus' },
					{ id: 'D', text: 'Ribosome' },
				],
				correctAnswer: 'A',
				hint: 'Chloroplasts contain chlorophyll.',
				topic: 'Cell Biology',
				subtopic: 'Cell Differences',
				difficulty: 'easy',
			},
			{
				id: 'life-2023-p1-q20',
				question: 'During inhalation, the diaphragm:',
				options: [
					{ id: 'A', text: 'Contracts and flattens' },
					{ id: 'B', text: 'Relaxes and curves upward' },
					{ id: 'C', text: 'Does not move' },
					{ id: 'D', text: 'Expands to fill with blood' },
				],
				correctAnswer: 'A',
				hint: 'Diaphragm contracts and moves down.',
				topic: 'Human Biology',
				subtopic: 'Respiratory System',
				difficulty: 'easy',
			},
		],
	},
	'life-p1-2022-nov': {
		title: 'NSC Life Sciences P1 November 2022',
		subject: 'Life Sciences',
		year: 2022,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'life-2022-p1-q1',
				question: 'Which organelle contains genetic material?',
				options: [
					{ id: 'A', text: 'Nucleus' },
					{ id: 'B', text: 'Ribosome' },
					{ id: 'C', text: 'Mitochondria' },
					{ id: 'D', text: 'Golgi body' },
				],
				correctAnswer: 'A',
				hint: 'DNA is in the nucleus.',
				topic: 'Cell Biology',
				subtopic: 'Organelles',
				difficulty: 'easy',
			},
			{
				id: 'life-2022-p1-q2',
				question: 'Cell division that produces gametes is:',
				options: [
					{ id: 'A', text: 'Meiosis' },
					{ id: 'B', text: 'Mitosis' },
					{ id: 'C', text: 'Binary fission' },
					{ id: 'D', text: 'Budding' },
				],
				correctAnswer: 'A',
				hint: 'Meiosis produces sex cells with half chromosomes.',
				topic: 'Cell Biology',
				subtopic: 'Meiosis',
				difficulty: 'easy',
			},
			{
				id: 'life-2022-p1-q3',
				question: 'Which blood type is universal donor?',
				options: [
					{ id: 'A', text: 'O negative' },
					{ id: 'B', text: 'AB positive' },
					{ id: 'C', text: 'A positive' },
					{ id: 'D', text: 'O positive' },
				],
				correctAnswer: 'A',
				hint: 'O negative has no A, B or Rh antigens.',
				topic: 'Human Biology',
				subtopic: 'Blood Types',
				difficulty: 'easy',
			},
			{
				id: 'life-2022-p1-q4',
				question: 'The hormone insulin is produced by:',
				options: [
					{ id: 'A', text: 'Pancreas' },
					{ id: 'B', text: 'Thyroid' },
					{ id: 'C', text: 'Adrenal' },
					{ id: 'D', text: 'Pituitary' },
				],
				correctAnswer: 'A',
				hint: 'Beta cells in pancreas make insulin.',
				topic: 'Human Biology',
				subtopic: 'Endocrine System',
				difficulty: 'easy',
			},
			{
				id: 'life-2022-p1-q5',
				question: 'In DNA, adenine pairs with:',
				options: [
					{ id: 'A', text: 'Thymine' },
					{ id: 'B', text: 'Guanine' },
					{ id: 'C', text: 'Cytosine' },
					{ id: 'D', text: 'Uracil' },
				],
				correctAnswer: 'A',
				hint: 'A pairs with T (DNA). In RNA, A pairs with U.',
				topic: 'Genetics',
				subtopic: 'DNA Structure',
				difficulty: 'easy',
			},
			{
				id: 'life-2022-p1-q6',
				question: 'The Calvin cycle takes place in the:',
				options: [
					{ id: 'A', text: 'Stroma of chloroplast' },
					{ id: 'B', text: 'Thylakoid membrane' },
					{ id: 'C', text: 'Mitochondria' },
					{ id: 'D', text: 'Cytoplasm' },
				],
				correctAnswer: 'A',
				hint: 'Dark reactions in stroma.',
				topic: 'Plant Biology',
				subtopic: 'Photosynthesis',
				difficulty: 'medium',
			},
			{
				id: 'life-2022-p1-q7',
				question: 'Which part of brain controls breathing?',
				options: [
					{ id: 'A', text: 'Medulla oblongata' },
					{ id: 'B', text: 'Cerebrum' },
					{ id: 'C', text: 'Cerebellum' },
					{ id: 'D', text: 'Hypothalamus' },
				],
				correctAnswer: 'A',
				hint: 'Medulla controls autonomic functions.',
				topic: 'Human Biology',
				subtopic: 'Nervous System',
				difficulty: 'medium',
			},
			{
				id: 'life-2022-p1-q8',
				question: 'In incomplete dominance, the phenotype of heterozygote is:',
				options: [
					{ id: 'A', text: 'Blended' },
					{ id: 'B', text: 'Same as dominant' },
					{ id: 'C', text: 'Same as recessive' },
					{ id: 'D', text: 'Different from both' },
				],
				correctAnswer: 'A',
				hint: 'Example: snapdragon flower pink from red + white.',
				topic: 'Genetics',
				subtopic: 'Inheritance Patterns',
				difficulty: 'medium',
			},
			{
				id: 'life-2022-p1-q9',
				question: 'The xylem transports:',
				options: [
					{ id: 'A', text: 'Water and minerals' },
					{ id: 'B', text: 'Sugar/sap' },
					{ id: 'C', text: 'Blood' },
					{ id: 'D', text: 'Oxygen' },
				],
				correctAnswer: 'A',
				hint: 'Xylem carries water UP from roots.',
				topic: 'Plant Biology',
				subtopic: 'Transport',
				difficulty: 'easy',
			},
			{
				id: 'life-2022-p1-q10',
				question: 'In the lungs, oxygen moves into blood by:',
				options: [
					{ id: 'A', text: 'Diffusion' },
					{ id: 'B', text: 'Osmosis' },
					{ id: 'C', text: 'Active transport' },
					{ id: 'D', text: 'Phagocytosis' },
				],
				correctAnswer: 'A',
				hint: 'From high O₂ (alveoli) to low O₂ (blood).',
				topic: 'Human Biology',
				subtopic: 'Respiratory System',
				difficulty: 'easy',
			},
			{
				id: 'life-2022-p1-q11',
				question: 'A mutation is a change in:',
				options: [
					{ id: 'A', text: 'DNA sequence' },
					{ id: 'B', text: 'Ribosome' },
					{ id: 'C', text: 'Cell wall' },
					{ id: 'D', text: 'Cytoplasm' },
				],
				correctAnswer: 'A',
				hint: 'Changes in genetic code.',
				topic: 'Genetics',
				subtopic: 'Mutations',
				difficulty: 'easy',
			},
			{
				id: 'life-2022-p1-q12',
				question: 'Natural selection favors traits that:',
				options: [
					{ id: 'A', text: 'Improve survival and reproduction' },
					{ id: 'B', text: 'Are most colorful' },
					{ id: 'C', text: 'Are largest' },
					{ id: 'D', text: 'Are smallest' },
				],
				correctAnswer: 'A',
				hint: 'Survival of the fittest.',
				topic: 'Evolution',
				subtopic: 'Natural Selection',
				difficulty: 'easy',
			},
		],
	},
	'life-p1-2021-nov': {
		title: 'NSC Life Sciences P1 November 2021',
		subject: 'Life Sciences',
		year: 2021,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'life-2021-p1-q1',
				question: 'The powerhouse of the cell is:',
				options: [
					{ id: 'A', text: 'Mitochondria' },
					{ id: 'B', text: 'Nucleus' },
					{ id: 'C', text: 'Ribosome' },
					{ id: 'D', text: 'Chloroplast' },
				],
				correctAnswer: 'A',
				hint: 'Produces ATP for energy.',
				topic: 'Cell Biology',
				subtopic: 'Organelles',
				difficulty: 'easy',
			},
			{
				id: 'life-2021-p1-q2',
				question: 'Mitosis results in cells with:',
				options: [
					{ id: 'A', text: 'Same chromosome number as parent' },
					{ id: 'B', text: 'Half the chromosomes' },
					{ id: 'C', text: 'Double the chromosomes' },
					{ id: 'D', text: 'No chromosomes' },
				],
				correctAnswer: 'A',
				hint: 'Body cells have identical chromosomes.',
				topic: 'Cell Biology',
				subtopic: 'Mitosis',
				difficulty: 'easy',
			},
			{
				id: 'life-2021-p1-q3',
				question: 'Which blood cells fight infection?',
				options: [
					{ id: 'A', text: 'White blood cells' },
					{ id: 'B', text: 'Red blood cells' },
					{ id: 'C', text: 'Platelets' },
					{ id: 'D', text: 'Plasma' },
				],
				correctAnswer: 'A',
				hint: 'WBCs are immune cells.',
				topic: 'Human Biology',
				subtopic: 'Circulatory System',
				difficulty: 'easy',
			},
			{
				id: 'life-2021-p1-q4',
				question: 'During exhalation, the ribs move:',
				options: [
					{ id: 'A', text: 'Down and in' },
					{ id: 'B', text: 'Up and out' },
					{ id: 'C', text: 'Up and in' },
					{ id: 'D', text: 'Down and out' },
				],
				correctAnswer: 'A',
				hint: 'Volume decreases, pressure increases.',
				topic: 'Human Biology',
				subtopic: 'Respiratory System',
				difficulty: 'easy',
			},
			{
				id: 'life-2021-p1-q5',
				question: 'The male gamete is called:',
				options: [
					{ id: 'A', text: 'Sperm' },
					{ id: 'B', text: 'Egg' },
					{ id: 'C', text: 'Zygote' },
					{ id: 'D', text: 'Ovum' },
				],
				correctAnswer: 'A',
				hint: 'Male reproductive cell.',
				topic: 'Human Biology',
				subtopic: 'Reproduction',
				difficulty: 'easy',
			},
			{
				id: 'life-2021-p1-q6',
				question: 'The main function of the small intestine is:',
				options: [
					{ id: 'A', text: 'Absorption of nutrients' },
					{ id: 'B', text: 'Storage of food' },
					{ id: 'C', text: 'Production of bile' },
					{ id: 'D', text: 'Killing bacteria' },
				],
				correctAnswer: 'A',
				hint: 'Villi increase surface area.',
				topic: 'Human Biology',
				subtopic: 'Digestive System',
				difficulty: 'easy',
			},
			{
				id: 'life-2021-p1-q7',
				question: 'Inheritance of blood group is an example of:',
				options: [
					{ id: 'A', text: 'Codominance' },
					{ id: 'B', text: 'Incomplete dominance' },
					{ id: 'C', text: 'Polyploidy' },
					{ id: 'D', text: 'Linkage' },
				],
				correctAnswer: 'A',
				hint: 'A and B antigens both expressed in AB.',
				topic: 'Genetics',
				subtopic: 'Inheritance Patterns',
				difficulty: 'medium',
			},
			{
				id: 'life-2021-p1-q8',
				question: 'The pH of human blood is approximately:',
				options: [
					{ id: 'A', text: '7.4' },
					{ id: 'B', text: '4.0' },
					{ id: 'C', text: '9.0' },
					{ id: 'D', text: '1.0' },
				],
				correctAnswer: 'A',
				hint: 'Slightly alkaline.',
				topic: 'Human Biology',
				subtopic: 'Homeostasis',
				difficulty: 'easy',
			},
			{
				id: 'life-2021-p1-q9',
				question: 'Which organ removes urea from blood?',
				options: [
					{ id: 'A', text: 'Kidney' },
					{ id: 'B', text: 'Liver' },
					{ id: 'C', text: 'Heart' },
					{ id: 'D', text: 'Lungs' },
				],
				correctAnswer: 'A',
				hint: 'Nephrons filter blood.',
				topic: 'Human Biology',
				subtopic: 'Excretory System',
				difficulty: 'easy',
			},
			{
				id: 'life-2021-p1-q10',
				question: 'The scientific name for humans is:',
				options: [
					{ id: 'A', text: 'Homo sapiens' },
					{ id: 'B', text: 'Pan troglodytes' },
					{ id: 'C', text: 'Gorilla gorilla' },
					{ id: 'D', text: 'Australopithecus' },
				],
				correctAnswer: 'A',
				hint: 'Genus species naming.',
				topic: 'Evolution',
				subtopic: 'Classification',
				difficulty: 'easy',
			},
		],
	},
};
