import type { QuizData } from './types';

export const MATHEMATICS_QUIZ: QuizData = {
	'math-p1-2023-nov': {
		title: 'NSC Mathematics P1 November 2023',
		subject: 'Mathematics',
		year: 2023,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'math-2023-p1-q1',
				question: 'If f(x) = 2x² - 3x + 1, calculate f(-2).',
				options: [
					{ id: 'A', text: '15' },
					{ id: 'B', text: '11' },
					{ id: 'C', text: '7' },
					{ id: 'D', text: '3' },
				],
				correctAnswer: 'A',
				hint: 'Substitute x = -2: f(-2) = 2(-2)² - 3(-2) + 1 = 2(4) + 6 + 1 = 8 + 6 + 1 = 15',
				topic: 'Functions',
				subtopic: 'Evaluation',
				difficulty: 'easy',
			},
			{
				id: 'math-2023-p1-q2',
				question: 'Solve for x: x² - 7x + 12 = 0',
				options: [
					{ id: 'A', text: 'x = 3 or x = 4' },
					{ id: 'B', text: 'x = 2 or x = 6' },
					{ id: 'C', text: 'x = -3 or x = -4' },
					{ id: 'D', text: 'x = 1 or x = 12' },
				],
				correctAnswer: 'A',
				hint: 'Factor: (x - 3)(x - 4) = 0, so x = 3 or x = 4',
				topic: 'Equations',
				subtopic: 'Quadratic Equations',
				difficulty: 'easy',
			},
			{
				id: 'math-2023-p1-q3',
				question: 'Find the derivative of f(x) = 4x³ - 2x² + 5x - 3',
				options: [
					{ id: 'A', text: "f'(x) = 12x² - 4x + 5" },
					{ id: 'B', text: "f'(x) = 12x² - 4x + 5 - 3" },
					{ id: 'C', text: "f'(x) = 4x³ - 2x² + 5" },
					{ id: 'D', text: "f'(x) = 12x² - 2x + 5" },
				],
				correctAnswer: 'A',
				hint: "Use power rule: d/dx(axⁿ) = anxⁿ⁻¹. f'(x) = 12x² - 4x + 5",
				topic: 'Calculus',
				subtopic: 'Derivatives',
				difficulty: 'medium',
			},
			{
				id: 'math-2023-p1-q4',
				question: 'Evaluate: ∫(3x² + 2x - 1)dx',
				options: [
					{ id: 'A', text: 'x³ + x² - x + C' },
					{ id: 'B', text: '6x + 2 + C' },
					{ id: 'C', text: 'x³ + x² + C' },
					{ id: 'D', text: '6x² + 2x + C' },
				],
				correctAnswer: 'A',
				hint: 'Integrate each term: ∫3x²dx = x³, ∫2xdx = x², ∫-1dx = -x',
				topic: 'Calculus',
				subtopic: 'Integrals',
				difficulty: 'medium',
			},
			{
				id: 'math-2023-p1-q5',
				question: 'If g(x) = √(x + 5), find g⁻¹(x)',
				options: [
					{ id: 'A', text: 'x² - 5' },
					{ id: 'B', text: 'x² + 5' },
					{ id: 'C', text: '√x - 5' },
					{ id: 'D', text: 'x² - √5' },
				],
				correctAnswer: 'A',
				hint: 'Let y = √(x+5). Then y² = x + 5, so x = y² - 5. Replace y with x: g⁻¹(x) = x² - 5',
				topic: 'Functions',
				subtopic: 'Inverse Functions',
				difficulty: 'medium',
			},
			{
				id: 'math-2023-p1-q6',
				question: 'Solve: log₂(x + 3) = 5',
				options: [
					{ id: 'A', text: '29' },
					{ id: 'B', text: '32' },
					{ id: 'C', text: '31' },
					{ id: 'D', text: '28' },
				],
				correctAnswer: 'A',
				hint: '2⁵ = x + 3, so 32 = x + 3, therefore x = 29.',
				topic: 'Logarithms',
				subtopic: 'Exponential Equations',
				difficulty: 'medium',
			},
			{
				id: 'math-2023-p1-q7',
				question: 'The gradient of the tangent to y = x³ at x = 2 is:',
				options: [
					{ id: 'A', text: '12' },
					{ id: 'B', text: '8' },
					{ id: 'C', text: '6' },
					{ id: 'D', text: '4' },
				],
				correctAnswer: 'A',
				hint: 'dy/dx = 3x². At x = 2, gradient = 3(2)² = 3 × 4 = 12',
				topic: 'Calculus',
				subtopic: 'Tangents',
				difficulty: 'medium',
			},
			{
				id: 'math-2023-p1-q8',
				question: 'Find the area between y = x² and y = x from x = 0 to x = 1',
				options: [
					{ id: 'A', text: '1/6 square units' },
					{ id: 'B', text: '1/3 square units' },
					{ id: 'C', text: '1/2 square units' },
					{ id: 'D', text: '2/3 square units' },
				],
				correctAnswer: 'A',
				hint: 'Area = ∫₀¹(x - x²)dx = [x²/2 - x³/3]₀¹ = 1/2 - 1/3 = 3/6 - 2/6 = 1/6',
				topic: 'Calculus',
				subtopic: 'Area Under Curve',
				difficulty: 'hard',
			},
			{
				id: 'math-2023-p1-q9',
				question: 'Simplify: (2⁴ × 2⁶) ÷ 2⁷',
				options: [
					{ id: 'A', text: '2³' },
					{ id: 'B', text: '2⁵' },
					{ id: 'C', text: '2⁴' },
					{ id: 'D', text: '2²' },
				],
				correctAnswer: 'A',
				hint: '2⁴⁺⁶⁻⁷ = 2³ = 8',
				topic: 'Algebra',
				subtopic: 'Exponents',
				difficulty: 'easy',
			},
			{
				id: 'math-2023-p1-q10',
				question: "If f(x) = (2x - 1)³, find f'(1)",
				options: [
					{ id: 'A', text: '12' },
					{ id: 'B', text: '6' },
					{ id: 'C', text: '9' },
					{ id: 'D', text: '3' },
				],
				correctAnswer: 'B',
				hint: "Use chain rule: f'(x) = 3(2x - 1)² × 2 = 6(2x - 1)². At x = 1: 6(2-1)² = 6(1) = 6",
				diagram: 'parabola',
				topic: 'Calculus',
				subtopic: 'Chain Rule',
				difficulty: 'hard',
			},
			{
				id: 'math-2023-p1-q11',
				question: 'Solve: |2x - 5| = 7',
				options: [
					{ id: 'A', text: 'x = 6 or x = -1' },
					{ id: 'B', text: 'x = 6 or x = 1' },
					{ id: 'C', text: 'x = -6 or x = 1' },
					{ id: 'D', text: 'x = 5 or x = -2' },
				],
				correctAnswer: 'A',
				hint: '2x - 5 = 7 or 2x - 5 = -7. Case 1: 2x = 12 → x = 6. Case 2: 2x = -2 → x = -1',
				topic: 'Algebra',
				subtopic: 'Absolute Value',
				difficulty: 'medium',
			},
			{
				id: 'math-2023-p1-q12',
				question: 'Find the maximum value of f(x) = -2x² + 8x - 3',
				options: [
					{ id: 'A', text: '5' },
					{ id: 'B', text: '8' },
					{ id: 'C', text: '3' },
					{ id: 'D', text: '2' },
				],
				correctAnswer: 'A',
				hint: 'Vertex at x = -b/(2a) = -8/(2×-2) = -8/-4 = 2. f(2) = -2(4) + 16 - 3 = -8 + 16 - 3 = 5',
				topic: 'Functions',
				subtopic: 'Parabolas',
				difficulty: 'medium',
			},
			{
				id: 'math-2023-p1-q13',
				question: 'The second derivative of f(x) = 3x⁴ - 2x² + x is:',
				options: [
					{ id: 'A', text: "f''(x) = 36x² - 4" },
					{ id: 'B', text: "f''(x) = 12x³ - 4x + 1" },
					{ id: 'C', text: "f''(x) = 36x² - 4x" },
					{ id: 'D', text: "f''(x) = 12x² - 2" },
				],
				correctAnswer: 'A',
				hint: "f'(x) = 12x³ - 4x + 1. Then f''(x) = 36x² - 4",
				topic: 'Calculus',
				subtopic: 'Second Derivative',
				difficulty: 'hard',
			},
			{
				id: 'math-2023-p1-q14',
				question: 'Determine the y-intercept of g(x) = (x + 2)/(x - 1)',
				options: [
					{ id: 'A', text: '-2' },
					{ id: 'B', text: '2' },
					{ id: 'C', text: '-1' },
					{ id: 'D', text: '1' },
				],
				correctAnswer: 'A',
				hint: 'Set x = 0: g(0) = (0 + 2)/(0 - 1) = 2/(-1) = -2',
				topic: 'Functions',
				subtopic: 'Intercepts',
				difficulty: 'easy',
			},
			{
				id: 'math-2023-p1-q15',
				question: 'Find the sum of the arithmetic series: 2 + 5 + 8 + ... + 47',
				options: [
					{ id: 'A', text: '392' },
					{ id: 'B', text: '396' },
					{ id: 'C', text: '400' },
					{ id: 'D', text: '404' },
				],
				correctAnswer: 'A',
				hint: 'a₁ = 2, d = 3. aₙ = 47 = 2 + (n-1)(3), so 45 = 3(n-1), n = 16. S₁₆ = 16/2(2 + 47) = 8 × 49 = 392',
				topic: 'Sequences',
				subtopic: 'Arithmetic Series',
				difficulty: 'medium',
			},
			{
				id: 'math-2023-p1-q16',
				question: 'If 3ˣ = 81, find x',
				options: [
					{ id: 'A', text: '4' },
					{ id: 'B', text: '3' },
					{ id: 'C', text: '27' },
					{ id: 'D', text: '9' },
				],
				correctAnswer: 'A',
				hint: '81 = 3⁴, so x = 4',
				topic: 'Logarithms',
				subtopic: 'Exponential Equations',
				difficulty: 'easy',
			},
			{
				id: 'math-2023-p1-q17',
				question: 'Find the limit: lim(x→2) (x² - 4)/(x - 2)',
				options: [
					{ id: 'A', text: '4' },
					{ id: 'B', text: '0' },
					{ id: 'C', text: '2' },
					{ id: 'D', text: 'Does not exist' },
				],
				correctAnswer: 'A',
				hint: 'Factor: (x² - 4)/(x - 2) = (x-2)(x+2)/(x-2) = x+2. At x = 2, limit = 4',
				topic: 'Calculus',
				subtopic: 'Limits',
				difficulty: 'medium',
			},
			{
				id: 'math-2023-p1-q18',
				question: 'The roots of 2x² - 5x - 3 = 0 are:',
				options: [
					{ id: 'A', text: 'x = 3 or x = -1/2' },
					{ id: 'B', text: 'x = -3 or x = 1/2' },
					{ id: 'C', text: 'x = 5/2 or x = -3/2' },
					{ id: 'D', text: 'x = 1 or x = -3' },
				],
				correctAnswer: 'A',
				hint: 'Using quadratic formula: x = [5 ± √(25 + 24)]/4 = [5 ± √49]/4 = [5 ± 7]/4. x = 12/4 = 3 or x = -2/4 = -1/2',
				topic: 'Equations',
				subtopic: 'Quadratic Formula',
				difficulty: 'medium',
			},
			{
				id: 'math-2023-p1-q19',
				question: 'Find dy/dx if y = x² sin x',
				options: [
					{ id: 'A', text: '2x sin x + x² cos x' },
					{ id: 'B', text: '2x cos x' },
					{ id: 'C', text: 'x² cos x' },
					{ id: 'D', text: '2x sin x - x² cos x' },
				],
				correctAnswer: 'A',
				hint: 'Use product rule: dy/dx = (d/dx)(x²)·sin x + x²·(d/dx)(sin x) = 2x·sin x + x²·cos x',
				topic: 'Calculus',
				subtopic: 'Product Rule',
				difficulty: 'hard',
			},
			{
				id: 'math-2023-p1-q20',
				question: 'Simplify: (√3 + √2)²',
				options: [
					{ id: 'A', text: '5 + 2√6' },
					{ id: 'B', text: '5 + √6' },
					{ id: 'C', text: '5 - 2√6' },
					{ id: 'D', text: '25 + 2√6' },
				],
				correctAnswer: 'A',
				hint: '(√3 + √2)² = 3 + 2 + 2√6 = 5 + 2√6',
				topic: 'Algebra',
				subtopic: 'Surds',
				difficulty: 'medium',
			},
		],
	},
	'math-p2-2023-nov': {
		title: 'NSC Mathematics P2 November 2023',
		subject: 'Mathematics',
		year: 2023,
		session: 'November',
		paper: 2,
		questions: [
			{
				id: 'math-2023-p2-q1',
				question:
					'In ΔABC, angle A = 30°, angle B = 45°, and side a = 10. Find side b (to nearest whole number).',
				options: [
					{ id: 'A', text: '14' },
					{ id: 'B', text: '12' },
					{ id: 'C', text: '7' },
					{ id: 'D', text: '10' },
				],
				correctAnswer: 'A',
				hint: 'Using sine rule: a/sin A = b/sin B. 10/sin30° = b/sin45°. 10/0.5 = b/0.707. 20 = b/0.707. b = 20 × 0.707 = 14.14 ≈ 14',
				diagram: 'triangle',
				topic: 'Trigonometry',
				subtopic: 'Sine Rule',
				difficulty: 'medium',
			},
			{
				id: 'math-2023-p2-q2',
				question: 'The equation of a line passing through (2, 3) with gradient 4 is:',
				options: [
					{ id: 'A', text: 'y - 3 = 4(x - 2)' },
					{ id: 'B', text: 'y = 4x + 5' },
					{ id: 'C', text: 'y - 2 = 4(x - 3)' },
					{ id: 'D', text: 'y = 4x - 5' },
				],
				correctAnswer: 'A',
				hint: 'Point-gradient form: y - y₁ = m(x - x₁). y - 3 = 4(x - 2)',
				topic: 'Analytical Geometry',
				subtopic: 'Straight Lines',
				difficulty: 'easy',
			},
			{
				id: 'math-2023-p2-q3',
				question: 'Calculate the distance between points P(3, 4) and Q(-1, 0)',
				options: [
					{ id: 'A', text: '√32' },
					{ id: 'B', text: '√20' },
					{ id: 'C', text: '√16' },
					{ id: 'D', text: '√8' },
				],
				correctAnswer: 'A',
				hint: 'd = √[(x₂-x₁)² + (y₂-y₁)²] = √[(-1-3)² + (0-4)²] = √[(-4)² + (-4)²] = √(16+16) = √32.',
				topic: 'Analytical Geometry',
				subtopic: 'Distance Formula',
				difficulty: 'easy',
			},
			{
				id: 'math-2023-p2-q4',
				question: 'If sin θ = 3/5 and θ is in the first quadrant, find cos θ',
				options: [
					{ id: 'A', text: '4/5' },
					{ id: 'B', text: '5/3' },
					{ id: 'C', text: '3/4' },
					{ id: 'D', text: '√7/5' },
				],
				correctAnswer: 'A',
				hint: 'sin²θ + cos²θ = 1. (3/5)² + cos²θ = 1. 9/25 + cos²θ = 1. cos²θ = 16/25. cosθ = 4/5 (positive in Q1)',
				topic: 'Trigonometry',
				subtopic: 'Identities',
				difficulty: 'medium',
			},
			{
				id: 'math-2023-p2-q5',
				question: 'The midpoint of segment AB where A(2, -3) and B(4, 7) is:',
				options: [
					{ id: 'A', text: '(3, 2)' },
					{ id: 'B', text: '(3, -2)' },
					{ id: 'C', text: '(6, 4)' },
					{ id: 'D', text: '(2, 5)' },
				],
				correctAnswer: 'A',
				hint: 'M = ((x₁+x₂)/2, (y₁+y₂)/2) = ((2+4)/2, (-3+7)/2) = (6/2, 4/2) = (3, 2)',
				topic: 'Analytical Geometry',
				subtopic: 'Midpoint',
				difficulty: 'easy',
			},
			{
				id: 'math-2023-p2-q6',
				question: 'Solve for θ if cos θ = -1/2 and 0° ≤ θ ≤ 360°',
				options: [
					{ id: 'A', text: 'θ = 120° or 240°' },
					{ id: 'B', text: 'θ = 60° or 300°' },
					{ id: 'C', text: 'θ = 150° or 210°' },
					{ id: 'D', text: 'θ = 45° or 315°' },
				],
				correctAnswer: 'A',
				hint: 'cos⁻¹(1/2) = 60°. In QII and QIII where cos is negative: 180° - 60° = 120°, 180° + 60° = 240°',
				topic: 'Trigonometry',
				subtopic: 'Trigonometric Equations',
				difficulty: 'medium',
			},
			{
				id: 'math-2023-p2-q7',
				question: 'The equation of a circle with centre (2, -3) and radius 5 is:',
				options: [
					{ id: 'A', text: '(x - 2)² + (y + 3)² = 25' },
					{ id: 'B', text: '(x + 2)² + (y - 3)² = 25' },
					{ id: 'C', text: '(x - 2)² + (y + 3)² = 5' },
					{ id: 'D', text: '(x + 2)² + (y - 3)² = 5' },
				],
				correctAnswer: 'A',
				hint: 'Circle equation: (x - h)² + (y - k)² = r². (x - 2)² + (y - (-3))² = 5² = 25',
				topic: 'Analytical Geometry',
				subtopic: 'Circles',
				difficulty: 'medium',
			},
			{
				id: 'math-2023-p2-q8',
				question: 'Find the equation of the tangent to the circle x² + y² = 25 at point (3, 4)',
				options: [
					{ id: 'A', text: '3x + 4y = 25' },
					{ id: 'B', text: '3x - 4y = 25' },
					{ id: 'C', text: '4x + 3y = 25' },
					{ id: 'D', text: 'x + y = 7' },
				],
				correctAnswer: 'A',
				hint: 'For circle x² + y² = r², tangent at (x₁, y₁): xx₁ + yy₁ = r². 3x + 4y = 25',
				topic: 'Analytical Geometry',
				subtopic: 'Circle Tangents',
				difficulty: 'hard',
			},
			{
				id: 'math-2023-p2-q9',
				question: 'In how many ways can 4 students be arranged in a row?',
				options: [
					{ id: 'A', text: '24' },
					{ id: 'B', text: '12' },
					{ id: 'C', text: '16' },
					{ id: 'D', text: '8' },
				],
				correctAnswer: 'A',
				hint: 'Number of permutations = 4! = 4 × 3 × 2 × 1 = 24',
				topic: 'Combinatorics',
				subtopic: 'Permutations',
				difficulty: 'easy',
			},
			{
				id: 'math-2023-p2-q11',
				question: 'If tan θ = 1, find θ in degrees (0° < θ < 180°)',
				options: [
					{ id: 'A', text: '45°' },
					{ id: 'B', text: '90°' },
					{ id: 'C', text: '135°' },
					{ id: 'D', text: '45° or 135°' },
				],
				correctAnswer: 'A',
				hint: 'tan 45° = 1. tan 135° = -1. So only 45° gives tan = 1.',
				topic: 'Trigonometry',
				subtopic: 'Trigonometric Equations',
				difficulty: 'medium',
			},
			{
				id: 'math-2023-p2-q13',
				question: 'Find the angle between vectors u = (1, 2) and v = (2, 1)',
				options: [
					{ id: 'A', text: 'approximately 37°' },
					{ id: 'B', text: '45°' },
					{ id: 'C', text: 'approximately 53°' },
					{ id: 'D', text: '90°' },
				],
				correctAnswer: 'A',
				hint: 'cos θ = (u·v)/(|u||v|) = (1×2 + 2×1)/(√5 × √5) = 4/5 = 0.8. θ = cos⁻¹(0.8) ≈ 36.87° ≈ 37°',
				diagram: 'vector',
				topic: 'Vectors',
				subtopic: 'Angle Between Vectors',
				difficulty: 'medium',
			},
			{
				id: 'math-2023-p2-q16',
				question: 'Find the product of the roots of 3x² - 5x + 2 = 0',
				options: [
					{ id: 'A', text: '2/3' },
					{ id: 'B', text: '5/3' },
					{ id: 'C', text: '-5/3' },
					{ id: 'D', text: '-2/3' },
				],
				correctAnswer: 'A',
				hint: 'For ax² + bx + c = 0, product of roots = c/a = 2/3',
				topic: 'Algebra',
				subtopic: 'Quadratic Roots',
				difficulty: 'medium',
			},
			{
				id: 'math-2023-p2-q17',
				question: 'The gradient of the line perpendicular to y = 2x + 3 is:',
				options: [
					{ id: 'A', text: '-1/2' },
					{ id: 'B', text: '1/2' },
					{ id: 'C', text: '-2' },
					{ id: 'D', text: '2' },
				],
				correctAnswer: 'A',
				hint: 'Lines are perpendicular if m₁ × m₂ = -1. So m₂ = -1/2',
				topic: 'Analytical Geometry',
				subtopic: 'Perpendicular Lines',
				difficulty: 'easy',
			},
			{
				id: 'math-2023-p2-q18',
				question: 'How many different ways can the word "MATH" be arranged?',
				options: [
					{ id: 'A', text: '24' },
					{ id: 'B', text: '12' },
					{ id: 'C', text: '16' },
					{ id: 'D', text: '8' },
				],
				correctAnswer: 'A',
				hint: 'All 4 letters are distinct, so 4! = 24 arrangements',
				topic: 'Combinatorics',
				subtopic: 'Arrangements',
				difficulty: 'easy',
			},
			{
				id: 'math-2023-p2-q20',
				question: 'The focus of the parabola y² = 8x is:',
				options: [
					{ id: 'A', text: '(2, 0)' },
					{ id: 'B', text: '(4, 0)' },
					{ id: 'C', text: '(0, 2)' },
					{ id: 'D', text: '(0, 4)' },
				],
				correctAnswer: 'A',
				hint: 'For y² = 4ax, focus = (a, 0). Here 4a = 8, so a = 2. Focus = (2, 0)',
				topic: 'Analytical Geometry',
				subtopic: 'Parabola',
				difficulty: 'hard',
			},
		],
	},
	'math-p1-2022-nov': {
		title: 'NSC Mathematics P1 November 2022',
		subject: 'Mathematics',
		year: 2022,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'math-2022-p1-q1',
				question: 'If x² - 9x + 18 = 0, the roots are:',
				options: [
					{ id: 'A', text: 'x = 3 or x = 6' },
					{ id: 'B', text: 'x = 2 or x = 9' },
					{ id: 'C', text: 'x = -3 or x = -6' },
					{ id: 'D', text: 'x = 1 or x = 18' },
				],
				correctAnswer: 'A',
				hint: 'Factor: (x - 3)(x - 6) = 0',
				topic: 'Algebra',
				subtopic: 'Quadratic Equations',
				difficulty: 'easy',
			},
			{
				id: 'math-2022-p1-q2',
				question: 'Calculate: log₃(27)',
				options: [
					{ id: 'A', text: '3' },
					{ id: 'B', text: '9' },
					{ id: 'C', text: '81' },
					{ id: 'D', text: '1/3' },
				],
				correctAnswer: 'A',
				hint: '27 = 3³, so log₃(27) = 3',
				topic: 'Logarithms',
				subtopic: 'Basic Logs',
				difficulty: 'easy',
			},
			{
				id: 'math-2022-p1-q3',
				question: 'Find the derivative of f(x) = 5x⁴ - 3x³ + 2x - 7',
				options: [
					{ id: 'A', text: "f'(x) = 20x³ - 9x² + 2" },
					{ id: 'B', text: "f'(x) = 20x³ - 9x² + 2x" },
					{ id: 'C', text: "f'(x) = 5x⁴ - 3x³" },
					{ id: 'D', text: "f'(x) = 20x³ - 9x² + 2 - 7" },
				],
				correctAnswer: 'A',
				hint: 'Use power rule: d/dx(axⁿ) = anxⁿ⁻¹',
				topic: 'Calculus',
				subtopic: 'Derivatives',
				difficulty: 'medium',
			},
			{
				id: 'math-2022-p1-q4',
				question: 'Simplify: (x³)² × x⁴',
				options: [
					{ id: 'A', text: 'x¹⁰' },
					{ id: 'B', text: 'x⁹' },
					{ id: 'C', text: 'x⁶' },
					{ id: 'D', text: 'x⁸' },
				],
				correctAnswer: 'A',
				hint: '(x³)² = x⁶, then x⁶ × x⁴ = x¹⁰',
				topic: 'Algebra',
				subtopic: 'Exponents',
				difficulty: 'easy',
			},
			{
				id: 'math-2022-p1-q5',
				question: 'If f(x) = 2x + 3 and g(x) = x², find (f ∘ g)(2)',
				options: [
					{ id: 'A', text: '11' },
					{ id: 'B', text: '7' },
					{ id: 'C', text: '4' },
					{ id: 'D', text: '8' },
				],
				correctAnswer: 'A',
				hint: 'g(2) = 4, then f(4) = 2(4) + 3 = 11',
				topic: 'Functions',
				subtopic: 'Composite Functions',
				difficulty: 'medium',
			},
			{
				id: 'math-2022-p1-q6',
				question: 'Evaluate: ∫(4x³ - 2x)dx',
				options: [
					{ id: 'A', text: 'x⁴ - x² + C' },
					{ id: 'B', text: '12x² - 2 + C' },
					{ id: 'C', text: 'x⁴ + x² + C' },
					{ id: 'D', text: '4x⁴ - 2x² + C' },
				],
				correctAnswer: 'A',
				hint: '∫4x³dx = x⁴, ∫-2xdx = -x²',
				topic: 'Calculus',
				subtopic: 'Integrals',
				difficulty: 'medium',
			},
			{
				id: 'math-2022-p1-q7',
				question: 'The axis of symmetry for y = -2x² + 8x - 1 is:',
				options: [
					{ id: 'A', text: 'x = 2' },
					{ id: 'B', text: 'x = -2' },
					{ id: 'C', text: 'x = 4' },
					{ id: 'D', text: 'x = -4' },
				],
				correctAnswer: 'A',
				hint: 'x = -b/(2a) = -8/(2×-2) = -8/-4 = 2',
				topic: 'Functions',
				subtopic: 'Parabolas',
				difficulty: 'medium',
			},
			{
				id: 'math-2022-p1-q8',
				question: 'Solve for x: 3ˣ = 243',
				options: [
					{ id: 'A', text: '5' },
					{ id: 'B', text: '3' },
					{ id: 'C', text: '4' },
					{ id: 'D', text: '6' },
				],
				correctAnswer: 'A',
				hint: '243 = 3⁵, so x = 5',
				topic: 'Logarithms',
				subtopic: 'Exponential Equations',
				difficulty: 'easy',
			},
			{
				id: 'math-2022-p1-q9',
				question: 'Find the sum: 3 + 6 + 9 + ... + 60',
				options: [
					{ id: 'A', text: '630' },
					{ id: 'B', text: '620' },
					{ id: 'C', text: '640' },
					{ id: 'D', text: '650' },
				],
				correctAnswer: 'A',
				hint: 'a₁ = 3, d = 3, n = 20. S₂₀ = 20/2(3+60) = 10×63 = 630',
				topic: 'Sequences',
				subtopic: 'Arithmetic Series',
				difficulty: 'medium',
			},
			{
				id: 'math-2022-p1-q10',
				question: 'If f(x) = √(3x - 1), find the domain',
				options: [
					{ id: 'A', text: 'x ≥ 1/3' },
					{ id: 'B', text: 'x ≥ 1' },
					{ id: 'C', text: 'x ≥ 3' },
					{ id: 'D', text: 'x ≥ -1/3' },
				],
				correctAnswer: 'A',
				hint: '3x - 1 ≥ 0, so x ≥ 1/3',
				topic: 'Functions',
				subtopic: 'Domain',
				difficulty: 'medium',
			},
			{
				id: 'math-2022-p1-q11',
				question: 'Find the vertex of y = x² - 6x + 8',
				options: [
					{ id: 'A', text: '(3, -1)' },
					{ id: 'B', text: '(3, 1)' },
					{ id: 'C', text: '(6, 8)' },
					{ id: 'D', text: '(-3, -1)' },
				],
				correctAnswer: 'A',
				hint: 'Complete square: (x-3)² - 1. Vertex at (3, -1)',
				topic: 'Functions',
				subtopic: 'Parabolas',
				difficulty: 'medium',
			},
			{
				id: 'math-2022-p1-q12',
				question: 'Calculate the y-intercept of y = 3x² - 5x + 2',
				options: [
					{ id: 'A', text: '2' },
					{ id: 'B', text: '-5' },
					{ id: 'C', text: '3' },
					{ id: 'D', text: '0' },
				],
				correctAnswer: 'A',
				hint: 'Set x = 0: y = 2',
				topic: 'Functions',
				subtopic: 'Intercepts',
				difficulty: 'easy',
			},
			{
				id: 'math-2022-p1-q13',
				question: 'Simplify: (√5 + √3)(√5 - √3)',
				options: [
					{ id: 'A', text: '2' },
					{ id: 'B', text: '5 - 3' },
					{ id: 'C', text: '8' },
					{ id: 'D', text: '15' },
				],
				correctAnswer: 'A',
				hint: '(a+b)(a-b) = a² - b² = 5 - 3 = 2',
				topic: 'Algebra',
				subtopic: 'Surds',
				difficulty: 'medium',
			},
			{
				id: 'math-2022-p1-q14',
				question: 'Find the limit: lim(x→3) (x² - 9)/(x - 3)',
				options: [
					{ id: 'A', text: '6' },
					{ id: 'B', text: '3' },
					{ id: 'C', text: '0' },
					{ id: 'D', text: 'Does not exist' },
				],
				correctAnswer: 'A',
				hint: '(x²-9)/(x-3) = (x-3)(x+3)/(x-3) = x+3. At x=3: 6',
				topic: 'Calculus',
				subtopic: 'Limits',
				difficulty: 'medium',
			},
			{
				id: 'math-2022-p1-q15',
				question: 'The product of roots of x² + 5x + 6 = 0 is:',
				options: [
					{ id: 'A', text: '6' },
					{ id: 'B', text: '5' },
					{ id: 'C', text: '-6' },
					{ id: 'D', text: '-5' },
				],
				correctAnswer: 'A',
				hint: 'Product = c/a = 6/1 = 6',
				topic: 'Algebra',
				subtopic: 'Quadratic Roots',
				difficulty: 'easy',
			},
		],
	},
	'math-p2-2022-nov': {
		title: 'NSC Mathematics P2 November 2022',
		subject: 'Mathematics',
		year: 2022,
		session: 'November',
		paper: 2,
		questions: [
			{
				id: 'math-2022-p2-q1',
				question: 'In ΔXYZ, angle X = 40°, angle Y = 70°, side x = 8. Find side y',
				options: [
					{ id: 'A', text: '10.8' },
					{ id: 'B', text: '5.9' },
					{ id: 'C', text: '12.4' },
					{ id: 'D', text: '6.4' },
				],
				correctAnswer: 'A',
				hint: 'Using sine rule: x/sinX = y/sinY. 8/sin40° = y/sin70°',
				topic: 'Trigonometry',
				subtopic: 'Sine Rule',
				difficulty: 'medium',
			},
			{
				id: 'math-2022-p2-q2',
				question: 'Find the distance from point (2, 3) to line y = 2x + 1',
				options: [
					{ id: 'A', text: '√5' },
					{ id: 'B', text: '2√5' },
					{ id: 'C', text: '√20' },
					{ id: 'D', text: '5' },
				],
				correctAnswer: 'A',
				hint: 'Distance = |Ax + By + C|/√(A²+B²) = |4-6+1|/√5 = |(-1)|/√5 = 1/√5 = √5/5...',
				topic: 'Analytical Geometry',
				subtopic: 'Distance to Line',
				difficulty: 'hard',
			},
			{
				id: 'math-2022-p2-q3',
				question: 'If tan θ = 4/3 and θ is acute, find sin θ',
				options: [
					{ id: 'A', text: '4/5' },
					{ id: 'B', text: '3/5' },
					{ id: 'C', text: '5/4' },
					{ id: 'D', text: '3/4' },
				],
				correctAnswer: 'A',
				hint: 'sin² + cos² = 1. tan = sin/cos. sin = 4/5',
				topic: 'Trigonometry',
				subtopic: 'Identities',
				difficulty: 'medium',
			},
			{
				id: 'math-2022-p2-q4',
				question: 'The equation of a circle with centre (0, 0) and radius 4 is:',
				options: [
					{ id: 'A', text: 'x² + y² = 16' },
					{ id: 'B', text: 'x² + y² = 4' },
					{ id: 'C', text: '(x-4)² + (y-4)² = 16' },
					{ id: 'D', text: 'x² + y² = 8' },
				],
				correctAnswer: 'A',
				hint: '(x-h)² + (y-k)² = r². Here h=0, k=0, r=4',
				topic: 'Analytical Geometry',
				subtopic: 'Circles',
				difficulty: 'easy',
			},
			{
				id: 'math-2022-p2-q5',
				question: 'How many ways can 5 people be seated around a circular table?',
				options: [
					{ id: 'A', text: '24' },
					{ id: 'B', text: '120' },
					{ id: 'C', text: '60' },
					{ id: 'D', text: '12' },
				],
				correctAnswer: 'A',
				hint: '(n-1)! = (5-1)! = 4! = 24',
				topic: 'Combinatorics',
				subtopic: 'Circular Permutations',
				difficulty: 'medium',
			},
			{
				id: 'math-2022-p2-q6',
				question: 'Find the angle between lines y = 2x + 1 and y = -x + 3',
				options: [
					{ id: 'A', text: 'approximately 71.6°' },
					{ id: 'B', text: '45°' },
					{ id: 'C', text: '90°' },
					{ id: 'D', text: '18.4°' },
				],
				correctAnswer: 'A',
				hint: 'tan θ = |(m₁-m₂)/(1+m₁m₂)| = |(2-(-1))/(1+2(-1))| = |3/(-1)| = 3',
				topic: 'Analytical Geometry',
				subtopic: 'Angle Between Lines',
				difficulty: 'medium',
			},
			{
				id: 'math-2022-p2-q7',
				question: 'Simplify: sin²x + cos²x + tan²x',
				options: [
					{ id: 'A', text: 'sec²x' },
					{ id: 'B', text: '1' },
					{ id: 'C', text: '2' },
					{ id: 'D', text: '1 + tan²x' },
				],
				correctAnswer: 'A',
				hint: 'sin²x + cos²x = 1, so 1 + tan²x = sec²x',
				topic: 'Trigonometry',
				subtopic: 'Identities',
				difficulty: 'medium',
			},
			{
				id: 'math-2022-p2-q8',
				question: 'Calculate the area of triangle with vertices (0,0), (4,0), (0,3)',
				options: [
					{ id: 'A', text: '6 square units' },
					{ id: 'B', text: '12 square units' },
					{ id: 'C', text: '5 square units' },
					{ id: 'D', text: '7 square units' },
				],
				correctAnswer: 'A',
				hint: 'Area = ½ × base × height = ½ × 4 × 3 = 6',
				topic: 'Analytical Geometry',
				subtopic: 'Area of Triangle',
				difficulty: 'easy',
			},
			{
				id: 'math-2022-p2-q9',
				question: 'Find the focus of parabola y² = 12x',
				options: [
					{ id: 'A', text: '(3, 0)' },
					{ id: 'B', text: '(12, 0)' },
					{ id: 'C', text: '(0, 3)' },
					{ id: 'D', text: '(0, 12)' },
				],
				correctAnswer: 'A',
				hint: 'y² = 4ax, so 4a = 12, a = 3. Focus = (a, 0) = (3, 0)',
				topic: 'Analytical Geometry',
				subtopic: 'Parabola',
				difficulty: 'medium',
			},
			{
				id: 'math-2022-p2-q10',
				question: 'If P(A) = 0.3, P(B) = 0.4 and P(A∪B) = 0.6, find P(A∩B)',
				options: [
					{ id: 'A', text: '0.1' },
					{ id: 'B', text: '0.7' },
					{ id: 'C', text: '0.12' },
					{ id: 'D', text: '0' },
				],
				correctAnswer: 'A',
				hint: 'P(A∪B) = P(A) + P(B) - P(A∩B). 0.6 = 0.3 + 0.4 - x',
				topic: 'Probability',
				subtopic: 'Venn Diagrams',
				difficulty: 'medium',
			},
			{
				id: 'math-2022-p2-q11',
				question: 'The gradient of the line perpendicular to 3x + 2y = 8 is:',
				options: [
					{ id: 'A', text: '2/3' },
					{ id: 'B', text: '-3/2' },
					{ id: 'C', text: '-2/3' },
					{ id: 'D', text: '3/2' },
				],
				correctAnswer: 'A',
				hint: 'Original: 2y = -3x + 8, m = -3/2. Perpendicular: m = 2/3',
				topic: 'Analytical Geometry',
				subtopic: 'Perpendicular Lines',
				difficulty: 'medium',
			},
			{
				id: 'math-2022-p2-q12',
				question: 'In how many ways can 3 boys and 2 girls be arranged if boys must be together?',
				options: [
					{ id: 'A', text: '36' },
					{ id: 'B', text: '120' },
					{ id: 'C', text: '12' },
					{ id: 'D', text: '24' },
				],
				correctAnswer: 'A',
				hint: 'Treat 3 boys as 1 unit: 3! × 3! = 6 × 6 = 36',
				topic: 'Combinatorics',
				subtopic: 'Arrangements',
				difficulty: 'medium',
			},
		],
	},
	'math-p1-2021-nov': {
		title: 'NSC Mathematics P1 November 2021',
		subject: 'Mathematics',
		year: 2021,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'math-2021-p1-q1',
				question: 'Simplify: 2⁻³ × 2⁴',
				options: [
					{ id: 'A', text: '2' },
					{ id: 'B', text: '1/2' },
					{ id: 'C', text: '4' },
					{ id: 'D', text: '1/4' },
				],
				correctAnswer: 'A',
				hint: '2⁻³⁺⁴ = 2¹ = 2',
				topic: 'Algebra',
				subtopic: 'Exponents',
				difficulty: 'easy',
			},
			{
				id: 'math-2021-p1-q2',
				question: 'If f(x) = x² + 2x, find f(-3)',
				options: [
					{ id: 'A', text: '3' },
					{ id: 'B', text: '9' },
					{ id: 'C', text: '15' },
					{ id: 'D', text: '-3' },
				],
				correctAnswer: 'A',
				hint: 'f(-3) = (-3)² + 2(-3) = 9 - 6 = 3',
				topic: 'Functions',
				subtopic: 'Evaluation',
				difficulty: 'easy',
			},
			{
				id: 'math-2021-p1-q3',
				question: 'Solve: x² = 16',
				options: [
					{ id: 'A', text: 'x = ±4' },
					{ id: 'B', text: 'x = 4' },
					{ id: 'C', text: 'x = -4' },
					{ id: 'D', text: 'x = 8' },
				],
				correctAnswer: 'A',
				hint: 'x² = 16, so x = ±4',
				topic: 'Algebra',
				subtopic: 'Equations',
				difficulty: 'easy',
			},
			{
				id: 'math-2021-p1-q4',
				question: 'The turning point of y = x² - 4x + 3 is:',
				options: [
					{ id: 'A', text: '(2, -1)' },
					{ id: 'B', text: '(4, 3)' },
					{ id: 'C', text: '(2, 3)' },
					{ id: 'D', text: '(-2, -1)' },
				],
				correctAnswer: 'A',
				hint: 'x = -b/(2a) = 4/2 = 2. y = 4 - 8 + 3 = -1',
				topic: 'Functions',
				subtopic: 'Parabolas',
				difficulty: 'medium',
			},
			{
				id: 'math-2021-p1-q5',
				question: 'Find the x-intercepts of y = x² - 5x + 6',
				options: [
					{ id: 'A', text: 'x = 2 or x = 3' },
					{ id: 'B', text: 'x = -2 or x = -3' },
					{ id: 'C', text: 'x = 1 or x = 6' },
					{ id: 'D', text: 'x = 0 or x = 5' },
				],
				correctAnswer: 'A',
				hint: 'Factor: (x-2)(x-3) = 0',
				topic: 'Functions',
				subtopic: 'Intercepts',
				difficulty: 'easy',
			},
			{
				id: 'math-2021-p1-q6',
				question: 'Simplify: (x² - 4)/(x - 2)',
				options: [
					{ id: 'A', text: 'x + 2' },
					{ id: 'B', text: 'x - 2' },
					{ id: 'C', text: 'x² - 2' },
					{ id: 'D', text: 'x' },
				],
				correctAnswer: 'A',
				hint: '(x²-4) = (x-2)(x+2), cancel (x-2)',
				topic: 'Algebra',
				subtopic: 'Factorisation',
				difficulty: 'easy',
			},
			{
				id: 'math-2021-p1-q7',
				question: 'Calculate: log₁₀(1000)',
				options: [
					{ id: 'A', text: '3' },
					{ id: 'B', text: '10' },
					{ id: 'C', text: '100' },
					{ id: 'D', text: '1' },
				],
				correctAnswer: 'A',
				hint: '10³ = 1000, so log₁₀(1000) = 3',
				topic: 'Logarithms',
				subtopic: 'Basic Logs',
				difficulty: 'easy',
			},
			{
				id: 'math-2021-p1-q8',
				question: 'Find the 10th term of arithmetic sequence 2, 5, 8, ...',
				options: [
					{ id: 'A', text: '29' },
					{ id: 'B', text: '30' },
					{ id: 'C', text: '28' },
					{ id: 'D', text: '27' },
				],
				correctAnswer: 'A',
				hint: 'a₁ = 2, d = 3. a₁₀ = 2 + 9(3) = 2 + 27 = 29',
				topic: 'Sequences',
				subtopic: 'Arithmetic',
				difficulty: 'easy',
			},
			{
				id: 'math-2021-p1-q9',
				question: 'The average rate of change of f(x) = 3x² from x = 1 to x = 3 is:',
				options: [
					{ id: 'A', text: '12' },
					{ id: 'B', text: '6' },
					{ id: 'C', text: '24' },
					{ id: 'D', text: '9' },
				],
				correctAnswer: 'A',
				hint: '[f(3) - f(1)]/(3-1) = [27 - 3]/2 = 24/2 = 12',
				topic: 'Calculus',
				subtopic: 'Rate of Change',
				difficulty: 'medium',
			},
			{
				id: 'math-2021-p1-q10',
				question: 'If x² + kx + 9 = 0 has equal roots, find k',
				options: [
					{ id: 'A', text: 'k = ±6' },
					{ id: 'B', text: 'k = 6' },
					{ id: 'C', text: 'k = -6' },
					{ id: 'D', text: 'k = 3' },
				],
				correctAnswer: 'A',
				hint: 'Equal roots when discriminant = 0. k² - 36 = 0, k = ±6',
				topic: 'Algebra',
				subtopic: 'Quadratics',
				difficulty: 'medium',
			},
		],
	},
};
