import type { QuizData } from './types';

export const PRACTICE_QUIZ: QuizData = {
	'nsc-practice-2025': {
		title: 'NSC Practice Questions 2025',
		subject: 'Multiple',
		year: 2025,
		session: 'May/June',
		paper: 1,
		questions: [
			{
				id: 'math-seq-q1',
				question:
					'The first three terms of an arithmetic sequence are 2x + 1; 4x; and 5x + 3. Calculate the value of x.',
				options: [
					{ id: 'A', text: '4' },
					{ id: 'B', text: '3' },
					{ id: 'C', text: '2' },
					{ id: 'D', text: '5' },
				],
				correctAnswer: 'A',
				hint: 'In an arithmetic sequence, T2 - T1 = T3 - T2. So (4x) - (2x + 1) = (5x + 3) - (4x).',
				topic: 'Mathematics',
				subtopic: 'Arithmetic Sequences',
				difficulty: 'medium',
			},
			{
				id: 'math-seq-q2',
				question: 'Calculate the sum to infinity of the geometric series: 14 + 7 + 3.5 + ...',
				options: [
					{ id: 'A', text: '28' },
					{ id: 'B', text: '21' },
					{ id: 'C', text: '14' },
					{ id: 'D', text: 'Infinity' },
				],
				correctAnswer: 'A',
				hint: 'Sum to infinity S = a / (1 - r). Here a = 14 and r = 0.5.',
				topic: 'Mathematics',
				subtopic: 'Geometric Series',
				difficulty: 'medium',
			},
			{
				id: 'phys-mom-q1',
				question:
					'A car of mass m moving at velocity v stops in time t when the brakes are applied. Which expression represents the magnitude of the average net force?',
				options: [
					{ id: 'A', text: 'mv/t' },
					{ id: 'B', text: 'mvt' },
					{ id: 'C', text: 'mt/v' },
					{ id: 'D', text: 'mv' },
				],
				correctAnswer: 'A',
				hint: 'Use F_net = Delta p / Delta t. Since it stops, Delta p = mv.',
				topic: 'Physical Sciences',
				subtopic: 'Momentum',
				difficulty: 'medium',
			},
			{
				id: 'phys-mom-q2',
				question:
					'In a collision between two trolleys, the total kinetic energy before is 50J and after is 42J. Is this collision elastic or inelastic?',
				options: [
					{ id: 'A', text: 'Inelastic' },
					{ id: 'B', text: 'Elastic' },
					{ id: 'C', text: 'Perfectly Elastic' },
					{ id: 'D', text: 'Isolated' },
				],
				correctAnswer: 'A',
				hint: 'A collision is only elastic if kinetic energy is conserved (E_before = E_after).',
				topic: 'Physical Sciences',
				subtopic: 'Collisions',
				difficulty: 'easy',
			},
			{
				id: 'life-dna-q1',
				question: 'Which of the following components is NOT part of a DNA nucleotide?',
				options: [
					{ id: 'A', text: 'Ribose sugar' },
					{ id: 'B', text: 'Phosphate group' },
					{ id: 'C', text: 'Nitrogenous base' },
					{ id: 'D', text: 'Deoxyribose sugar' },
				],
				correctAnswer: 'A',
				hint: 'DNA uses Deoxyribose sugar; Ribose sugar is found in RNA.',
				topic: 'Life Sciences',
				subtopic: 'DNA Structure',
				difficulty: 'easy',
			},
			{
				id: 'life-dna-q2',
				question: 'During which phase of the cell cycle does DNA replication take place?',
				options: [
					{ id: 'A', text: 'Interphase' },
					{ id: 'B', text: 'Prophase' },
					{ id: 'C', text: 'Metaphase' },
					{ id: 'D', text: 'Anaphase' },
				],
				correctAnswer: 'A',
				hint: 'DNA replication occurs in the S-phase of Interphase before division begins.',
				topic: 'Life Sciences',
				subtopic: 'DNA Replication',
				difficulty: 'medium',
			},
		],
	},
	'humanities-comm-2025': {
		title: 'Commerce & Humanities NSC 2025',
		subject: 'Multiple',
		year: 2025,
		session: 'May/June',
		paper: 1,
		questions: [
			{
				id: 'acc-q1',
				question: 'What is the primary purpose of the Cash Flow Statement?',
				options: [
					{ id: 'A', text: 'To show historical changes in cash and equivalents' },
					{ id: 'B', text: 'To calculate the net profit for the year' },
					{ id: 'C', text: 'To list all fixed assets of the company' },
					{ id: 'D', text: "To record the owner's personal expenses" },
				],
				correctAnswer: 'A',
				hint: 'It classifies cash flows into operating, investing, and financing activities.',
				topic: 'Accounting',
				subtopic: 'Financial Statements',
				difficulty: 'easy',
			},
			{
				id: 'geo-q1',
				question: 'In which direction do Mid-latitude cyclones generally move across South Africa?',
				options: [
					{ id: 'A', text: 'West to East' },
					{ id: 'B', text: 'East to West' },
					{ id: 'C', text: 'North to South' },
					{ id: 'D', text: 'South to North' },
				],
				correctAnswer: 'A',
				hint: 'These systems are driven by the Westerly wind belt.',
				topic: 'Geography',
				subtopic: 'Climatology',
				difficulty: 'medium',
				diagram: 'synoptic',
			},
			{
				id: 'bs-q1',
				question: 'Distinguish between Autocratic and Democratic leadership styles.',
				options: [
					{
						id: 'A',
						text: 'Autocratic makes decisions alone; Democratic encourages participation',
					},
					{
						id: 'B',
						text: 'Democratic makes decisions alone; Autocratic encourages participation',
					},
					{ id: 'C', text: 'Both involve consulting all staff equally' },
					{ id: 'D', text: 'Neither involves making final decisions' },
				],
				correctAnswer: 'A',
				hint: 'Think about who holds the decision-making power in each style.',
				topic: 'Business Studies',
				subtopic: 'Leadership',
				difficulty: 'easy',
			},
			{
				id: 'his-q1',
				question: 'What was the primary purpose of the Truth and Reconciliation Commission (TRC)?',
				options: [
					{ id: 'A', text: 'To uncover the truth about human rights violations and promote unity' },
					{ id: 'B', text: 'To punish all apartheid officials with life imprisonment' },
					{ id: 'C', text: 'To establish a new military force for South Africa' },
					{ id: 'D', text: 'To draft the new 1996 Constitution' },
				],
				correctAnswer: 'A',
				hint: 'It focused on restorative justice rather than retributive justice.',
				topic: 'History',
				subtopic: 'South African History',
				difficulty: 'medium',
			},
		],
	},
	'eco-bs-2025': {
		title: 'Economics & Business NSC 2025',
		subject: 'Multiple',
		year: 2025,
		session: 'May/June',
		paper: 1,
		questions: [
			{
				id: 'eco-q1',
				question:
					'In the circular flow model, which sector is the owner of the factors of production?',
				options: [
					{ id: 'A', text: 'Households' },
					{ id: 'B', text: 'Businesses' },
					{ id: 'C', text: 'Government' },
					{ id: 'D', text: 'Foreign Sector' },
				],
				correctAnswer: 'A',
				hint: 'Households provide labor, land, capital, and entrepreneurship to firms.',
				topic: 'Economics',
				subtopic: 'Circular Flow',
				difficulty: 'easy',
			},
			{
				id: 'bs-q2',
				question:
					'Which leadership style is most effective during a crisis that requires immediate action?',
				options: [
					{ id: 'A', text: 'Autocratic' },
					{ id: 'B', text: 'Democratic' },
					{ id: 'C', text: 'Laissez-faire' },
					{ id: 'D', text: 'Charismatic' },
				],
				correctAnswer: 'A',
				hint: 'This style involves quick decision-making by a single leader.',
				topic: 'Business Studies',
				subtopic: 'Leadership Styles',
				difficulty: 'medium',
			},
			{
				id: 'eco-q3',
				question:
					'What happens to national income if injections (I+G+X) are greater than leakages (S+T+M)?',
				options: [
					{ id: 'A', text: 'It increases' },
					{ id: 'B', text: 'It decreases' },
					{ id: 'C', text: 'It remains constant' },
					{ id: 'D', text: 'It becomes zero' },
				],
				correctAnswer: 'A',
				hint: 'Higher injections stimulate economic growth and increase total output.',
				topic: 'Economics',
				subtopic: 'National Income',
				difficulty: 'medium',
			},
			{
				id: 'bs-q4',
				question: 'Which of the following is a component of the PESTLE analysis?',
				options: [
					{ id: 'A', text: 'Technological factors' },
					{ id: 'B', text: 'Strengths' },
					{ id: 'C', text: 'Weaknesses' },
					{ id: 'D', text: 'Product development' },
				],
				correctAnswer: 'A',
				hint: 'PESTLE stands for Political, Economic, Social, Technological, Legal, and Environmental.',
				topic: 'Business Studies',
				subtopic: 'Business Environments',
				difficulty: 'easy',
			},
		],
	},
	'geog-hist-2025': {
		title: 'Geography & History NSC 2025',
		subject: 'Multiple',
		year: 2025,
		session: 'May/June',
		paper: 1,
		questions: [
			{
				id: 'geo-q2',
				question: 'Which synoptic symbol represents a cold front?',
				options: [
					{ id: 'A', text: 'Line with blue triangles' },
					{ id: 'B', text: 'Line with red semi-circles' },
					{ id: 'C', text: 'Solid black circle' },
					{ id: 'D', text: 'H representing high pressure' },
				],
				correctAnswer: 'A',
				hint: 'Look for triangles pointing in the direction of movement.',
				topic: 'Geography',
				subtopic: 'Climatology',
				difficulty: 'easy',
				diagram: 'synoptic',
			},
			{
				id: 'his-q2',
				question: 'Who was the leader of the Black Consciousness Movement in South Africa?',
				options: [
					{ id: 'A', text: 'Steve Biko' },
					{ id: 'B', text: 'Nelson Mandela' },
					{ id: 'C', text: 'Desmond Tutu' },
					{ id: 'D', text: 'Robert Sobukwe' },
				],
				correctAnswer: 'A',
				hint: 'He focused on the psychological liberation of Black South Africans.',
				topic: 'History',
				subtopic: 'Civil Resistance',
				difficulty: 'medium',
			},
			{
				id: 'geo-q3',
				question:
					'What is the characteristic weather associated with a high-pressure system (Anticyclone)?',
				options: [
					{ id: 'A', text: 'Clear skies and dry conditions' },
					{ id: 'B', text: 'Heavy rain and thunderstorms' },
					{ id: 'C', text: 'Cold and snowy' },
					{ id: 'D', text: 'Tornadoes' },
				],
				correctAnswer: 'A',
				hint: 'High pressure involves descending air which prevents cloud formation.',
				topic: 'Geography',
				subtopic: 'Weather Systems',
				difficulty: 'medium',
			},
		],
	},
	'eng-lo-2025': {
		title: 'English & LO NSC 2025',
		subject: 'Multiple',
		year: 2025,
		session: 'May/June',
		paper: 1,
		questions: [
			{
				id: 'eng-q1',
				question: 'Identify the figure of speech: "The wind whispered through the trees."',
				options: [
					{ id: 'A', text: 'Personification' },
					{ id: 'B', text: 'Metaphor' },
					{ id: 'C', text: 'Simile' },
					{ id: 'D', text: 'Alliteration' },
				],
				correctAnswer: 'A',
				hint: 'Giving human qualities to non-human things.',
				topic: 'English FAL',
				subtopic: 'Language Structures',
				difficulty: 'easy',
			},
			{
				id: 'lo-q1',
				question: 'Which of the following is an example of an "Active Recall" study technique?',
				options: [
					{ id: 'A', text: 'Testing yourself with flashcards' },
					{ id: 'B', text: 'Re-reading a chapter 5 times' },
					{ id: 'C', text: 'Highlighting important sentences' },
					{ id: 'D', text: 'Listening to music while studying' },
				],
				correctAnswer: 'A',
				hint: 'Actively retrieving information from memory.',
				topic: 'Life Orientation',
				subtopic: 'Study Skills',
				difficulty: 'easy',
			},
		],
	},
	'acc-eng-2025': {
		title: 'Accounting & English NSC 2025',
		subject: 'Multiple',
		year: 2025,
		session: 'May/June',
		paper: 1,
		questions: [
			{
				id: 'acc-q2',
				question: 'Which of the following is an example of an Intangible Asset?',
				options: [
					{ id: 'A', text: 'Goodwill' },
					{ id: 'B', text: 'Inventory' },
					{ id: 'C', text: 'Cash in Bank' },
					{ id: 'D', text: 'Delivery Vehicle' },
				],
				correctAnswer: 'A',
				hint: 'Intangible assets are non-physical resources that have value.',
				topic: 'Accounting',
				subtopic: 'Fixed Assets',
				difficulty: 'easy',
			},
			{
				id: 'eng-q2',
				question:
					'What is the tone of the following sentence: "The candidate has consistently failed to meet minimum requirements despite numerous warnings."',
				options: [
					{ id: 'A', text: 'Formal and serious' },
					{ id: 'B', text: 'Humorous and lighthearted' },
					{ id: 'C', text: 'Sarcastic and playful' },
					{ id: 'D', text: 'Empathetic and kind' },
				],
				correctAnswer: 'A',
				hint: 'Consider the vocabulary used and the professional context.',
				topic: 'English FAL',
				subtopic: 'Comprehension & Tone',
				difficulty: 'medium',
			},
			{
				id: 'acc-q3',
				question: 'What is the effect of an entry on the DEBIT side of a Liability account?',
				options: [
					{ id: 'A', text: 'Decreases the liability' },
					{ id: 'B', text: 'Increases the liability' },
					{ id: 'C', text: 'Has no effect' },
					{ id: 'D', text: "Increases owner's equity" },
				],
				correctAnswer: 'A',
				hint: 'Remember the DEAD CLIC rule for debits and credits.',
				topic: 'Accounting',
				subtopic: 'Double Entry System',
				difficulty: 'medium',
			},
			{
				id: 'eng-q3',
				question: 'Change the following to Passive Voice: "The teacher marked the exam papers."',
				options: [
					{ id: 'A', text: 'The exam papers were marked by the teacher.' },
					{ id: 'B', text: 'The teacher has marked the exam papers.' },
					{ id: 'C', text: 'The exam papers are being marked by the teacher.' },
					{ id: 'D', text: 'Marking the exam papers is what the teacher did.' },
				],
				correctAnswer: 'A',
				hint: 'The object of the active sentence becomes the subject of the passive sentence.',
				topic: 'English FAL',
				subtopic: 'Grammar & Punctuation',
				difficulty: 'easy',
			},
		],
	},
};
