export type SubjectId =
	| 'mathematics'
	| 'physics'
	| 'chemistry'
	| 'life-sciences'
	| 'geography'
	| 'history'
	| 'english'
	| 'accounting';

export interface CommonQuestion {
	id: string;
	question: string;
	options: { id: string; text: string }[];
	correctAnswer: string;
	hint: string;
	explanation?: string;
	topic: string;
	subtopic: string;
	difficulty: 'easy' | 'medium' | 'hard';
	grades: number[];
	years: number[];
	subject: SubjectId;
	subjectLabel: string;
	fluentEmoji: string;
	color: string;
	bgColor: string;
}

export const SUBJECTS: {
	id: SubjectId;
	label: string;
	fluentEmoji: string;
	color: string;
	bgColor: string;
}[] = [
	{
		id: 'mathematics',
		label: 'Mathematics',
		fluentEmoji: '🧮',
		color: 'text-blue-500',
		bgColor: 'bg-blue-500',
	},
	{
		id: 'physics',
		label: 'Physics',
		fluentEmoji: '⚛️',
		color: 'text-purple-500',
		bgColor: 'bg-purple-500',
	},
	{
		id: 'chemistry',
		label: 'Chemistry',
		fluentEmoji: '🧪',
		color: 'text-green-500',
		bgColor: 'bg-green-500',
	},
	{
		id: 'life-sciences',
		label: 'Life Sciences',
		fluentEmoji: '🧬',
		color: 'text-emerald-500',
		bgColor: 'bg-emerald-500',
	},
	{
		id: 'geography',
		label: 'Geography',
		fluentEmoji: '🌍',
		color: 'text-amber-500',
		bgColor: 'bg-amber-500',
	},
	{
		id: 'history',
		label: 'History',
		fluentEmoji: '📜',
		color: 'text-red-500',
		bgColor: 'bg-red-500',
	},
	{
		id: 'english',
		label: 'English',
		fluentEmoji: '📚',
		color: 'text-indigo-500',
		bgColor: 'bg-indigo-500',
	},
	{
		id: 'accounting',
		label: 'Accounting',
		fluentEmoji: '💰',
		color: 'text-teal-500',
		bgColor: 'bg-teal-500',
	},
];

export const COMMON_QUESTIONS: CommonQuestion[] = [
	// ============================================================================
	// MATHEMATICS - Grade 10, 11, 12
	// ============================================================================
	{
		id: 'math-grade10-algebra-1',
		question: 'If 3x + 7 = 22, what is the value of x?',
		options: [
			{ id: 'A', text: 'x = 3' },
			{ id: 'B', text: 'x = 5' },
			{ id: 'C', text: 'x = 7' },
			{ id: 'D', text: 'x = 15' },
		],
		correctAnswer: 'B',
		hint: 'Subtract 7 from both sides: 3x = 15, then divide by 3',
		explanation: '3x + 7 = 22\n3x = 22 - 7 = 15\nx = 15/3 = 5',
		topic: 'Algebra',
		subtopic: 'Linear Equations',
		difficulty: 'easy',
		grades: [10],
		years: [2023, 2022, 2021],
		subject: 'mathematics',
		subjectLabel: 'Mathematics',
		fluentEmoji: '🧮',
		color: 'text-blue-500',
		bgColor: 'bg-blue-500',
	},
	{
		id: 'math-grade10-functions-1',
		question: 'Given f(x) = 2x - 3, find f(4).',
		options: [
			{ id: 'A', text: '5' },
			{ id: 'B', text: '8' },
			{ id: 'C', text: '11' },
			{ id: 'D', text: '-5' },
		],
		correctAnswer: 'A',
		hint: 'Substitute x = 4: f(4) = 2(4) - 3 = 8 - 3 = 5',
		explanation: 'f(4) = 2(4) - 3 = 8 - 3 = 5',
		topic: 'Functions',
		subtopic: 'Linear Functions',
		difficulty: 'easy',
		grades: [10],
		years: [2023, 2022],
		subject: 'mathematics',
		subjectLabel: 'Mathematics',
		fluentEmoji: '🧮',
		color: 'text-blue-500',
		bgColor: 'bg-blue-500',
	},
	{
		id: 'math-grade11-quadratics-1',
		question: 'Solve for x: x² - 5x + 6 = 0',
		options: [
			{ id: 'A', text: 'x = 2 or x = 3' },
			{ id: 'B', text: 'x = 1 or x = 6' },
			{ id: 'C', text: 'x = -2 or x = -3' },
			{ id: 'D', text: 'x = 0 or x = 5' },
		],
		correctAnswer: 'A',
		hint: 'Factor the quadratic: (x - 2)(x - 3) = 0',
		explanation: 'x² - 5x + 6 = 0\n(x - 2)(x - 3) = 0\nx = 2 or x = 3',
		topic: 'Algebra',
		subtopic: 'Quadratic Equations',
		difficulty: 'medium',
		grades: [11],
		years: [2023, 2022, 2021],
		subject: 'mathematics',
		subjectLabel: 'Mathematics',
		fluentEmoji: '🧮',
		color: 'text-blue-500',
		bgColor: 'bg-blue-500',
	},
	{
		id: 'math-grade11-trig-1',
		question: 'In a right triangle, if sin θ = 3/5, what is cos θ?',
		options: [
			{ id: 'A', text: '4/5' },
			{ id: 'B', text: '3/4' },
			{ id: 'C', text: '5/3' },
			{ id: 'D', text: '√3/2' },
		],
		correctAnswer: 'A',
		hint: 'Use the identity: sin²θ + cos²θ = 1',
		explanation:
			'sin²θ + cos²θ = 1\n(3/5)² + cos²θ = 1\n9/25 + cos²θ = 1\ncos²θ = 16/25\ncosθ = 4/5',
		topic: 'Trigonometry',
		subtopic: 'Right Triangles',
		difficulty: 'medium',
		grades: [11, 12],
		years: [2023, 2022],
		subject: 'mathematics',
		subjectLabel: 'Mathematics',
		fluentEmoji: '🧮',
		color: 'text-blue-500',
		bgColor: 'bg-blue-500',
	},
	{
		id: 'math-grade12-calculus-1',
		question: 'Find the derivative of f(x) = 3x³ - 2x² + 4x - 7',
		options: [
			{ id: 'A', text: "f'(x) = 9x² - 4x + 4" },
			{ id: 'B', text: "f'(x) = 9x² - 4x + 4 - 7" },
			{ id: 'C', text: "f'(x) = 3x³ - 2x² + 4" },
			{ id: 'D', text: "f'(x) = 9x² - 2x + 4" },
		],
		correctAnswer: 'A',
		hint: 'Use the power rule: d/dx(axⁿ) = anxⁿ⁻¹',
		explanation: "f'(x) = 3(3x²) - 2(2x) + 4\nf'(x) = 9x² - 4x + 4",
		topic: 'Calculus',
		subtopic: 'Derivatives',
		difficulty: 'medium',
		grades: [12],
		years: [2023, 2022, 2021],
		subject: 'mathematics',
		subjectLabel: 'Mathematics',
		fluentEmoji: '🧮',
		color: 'text-blue-500',
		bgColor: 'bg-blue-500',
	},
	{
		id: 'math-grade12-calculus-2',
		question: 'Evaluate: ∫(4x³ + 2x - 1)dx',
		options: [
			{ id: 'A', text: 'x⁴ + x² - x + C' },
			{ id: 'B', text: '12x² + 2 + C' },
			{ id: 'C', text: 'x⁴ + x² + C' },
			{ id: 'D', text: 'x⁴ + x² - x' },
		],
		correctAnswer: 'A',
		hint: 'Integrate each term: ∫4x³dx = x⁴, ∫2xdx = x², ∫-1dx = -x',
		explanation: '∫(4x³ + 2x - 1)dx = x⁴ + x² - x + C',
		topic: 'Calculus',
		subtopic: 'Integrals',
		difficulty: 'medium',
		grades: [12],
		years: [2023, 2022],
		subject: 'mathematics',
		subjectLabel: 'Mathematics',
		fluentEmoji: '🧮',
		color: 'text-blue-500',
		bgColor: 'bg-blue-500',
	},
	{
		id: 'math-grade12-seq-1',
		question: 'Find the 10th term of the arithmetic sequence: 2, 5, 8, 11, ...',
		options: [
			{ id: 'A', text: '29' },
			{ id: 'B', text: '30' },
			{ id: 'C', text: '32' },
			{ id: 'D', text: '35' },
		],
		correctAnswer: 'A',
		hint: 'Use the formula: aₙ = a₁ + (n-1)d, where d = 3',
		explanation: 'a₁ = 2, d = 3\na₁₀ = 2 + (10-1)(3) = 2 + 27 = 29',
		topic: 'Sequences',
		subtopic: 'Arithmetic',
		difficulty: 'medium',
		grades: [12],
		years: [2023, 2022],
		subject: 'mathematics',
		subjectLabel: 'Mathematics',
		fluentEmoji: '🧮',
		color: 'text-blue-500',
		bgColor: 'bg-blue-500',
	},

	// ============================================================================
	// PHYSICS - Grade 10, 11, 12
	// ============================================================================
	{
		id: 'phys-grade10-motion-1',
		question: 'A car accelerates from rest at 2 m/s². What is its velocity after 5 seconds?',
		options: [
			{ id: 'A', text: '10 m/s' },
			{ id: 'B', text: '7 m/s' },
			{ id: 'C', text: '2.5 m/s' },
			{ id: 'D', text: '0.4 m/s' },
		],
		correctAnswer: 'A',
		hint: 'Use v = u + at, where u = 0 (from rest)',
		explanation: 'v = u + at = 0 + (2)(5) = 10 m/s',
		topic: 'Kinematics',
		subtopic: 'Velocity',
		difficulty: 'easy',
		grades: [10],
		years: [2023, 2022],
		subject: 'physics',
		subjectLabel: 'Physics',
		fluentEmoji: '⚛️',
		color: 'text-purple-500',
		bgColor: 'bg-purple-500',
	},
	{
		id: 'phys-grade10-force-1',
		question: 'What is the weight of a 50 kg person on Earth? (g = 9.8 m/s²)',
		options: [
			{ id: 'A', text: '490 N' },
			{ id: 'B', text: '50 N' },
			{ id: 'C', text: '500 N' },
			{ id: 'D', text: '9.8 N' },
		],
		correctAnswer: 'A',
		hint: 'Weight = mass × gravitational acceleration',
		explanation: 'W = mg = 50 × 9.8 = 490 N',
		topic: 'Dynamics',
		subtopic: 'Weight',
		difficulty: 'easy',
		grades: [10],
		years: [2023, 2022, 2021],
		subject: 'physics',
		subjectLabel: 'Physics',
		fluentEmoji: '⚛️',
		color: 'text-purple-500',
		bgColor: 'bg-purple-500',
	},
	{
		id: 'phys-grade11-momentum-1',
		question: 'A 2 kg ball moves at 3 m/s. What is its momentum?',
		options: [
			{ id: 'A', text: '6 kg·m/s' },
			{ id: 'B', text: '1.5 kg·m/s' },
			{ id: 'C', text: '5 kg·m/s' },
			{ id: 'D', text: '6 kg·m/s²' },
		],
		correctAnswer: 'A',
		hint: 'Momentum = mass × velocity',
		explanation: 'p = mv = 2 × 3 = 6 kg·m/s',
		topic: 'Momentum',
		subtopic: 'Linear Momentum',
		difficulty: 'easy',
		grades: [11],
		years: [2023, 2022],
		subject: 'physics',
		subjectLabel: 'Physics',
		fluentEmoji: '⚛️',
		color: 'text-purple-500',
		bgColor: 'bg-purple-500',
	},
	{
		id: 'phys-grade11-work-1',
		question: 'A force of 20 N pushes an object 5 m. How much work is done?',
		options: [
			{ id: 'A', text: '100 J' },
			{ id: 'B', text: '4 J' },
			{ id: 'C', text: '25 J' },
			{ id: 'D', text: '100 N·m' },
		],
		correctAnswer: 'A',
		hint: 'Work = Force × Distance (in the direction of force)',
		explanation: 'W = F × d = 20 × 5 = 100 J',
		topic: 'Work & Energy',
		subtopic: 'Work',
		difficulty: 'easy',
		grades: [11],
		years: [2023, 2022],
		subject: 'physics',
		subjectLabel: 'Physics',
		fluentEmoji: '⚛️',
		color: 'text-purple-500',
		bgColor: 'bg-purple-500',
	},
	{
		id: 'phys-grade12-circuits-1',
		question:
			'Three resistors of 2Ω, 3Ω, and 6Ω are connected in parallel. What is the equivalent resistance?',
		options: [
			{ id: 'A', text: '1 Ω' },
			{ id: 'B', text: '11 Ω' },
			{ id: 'C', text: '36 Ω' },
			{ id: 'D', text: '2.5 Ω' },
		],
		correctAnswer: 'A',
		hint: 'For parallel: 1/R = 1/R₁ + 1/R₂ + 1/R₃',
		explanation: '1/R = 1/2 + 1/3 + 1/6 = 3/6 + 2/6 + 1/6 = 6/6 = 1\nR = 1 Ω',
		topic: 'Electricity',
		subtopic: 'Parallel Circuits',
		difficulty: 'medium',
		grades: [12],
		years: [2023, 2022],
		subject: 'physics',
		subjectLabel: 'Physics',
		fluentEmoji: '⚛️',
		color: 'text-purple-500',
		bgColor: 'bg-purple-500',
	},
	{
		id: 'phys-grade12-doppler-1',
		question:
			'A police siren has a frequency of 400 Hz. If the car is moving toward you at 30 m/s, what frequency do you hear? (Speed of sound = 340 m/s)',
		options: [
			{ id: 'A', text: '435 Hz' },
			{ id: 'B', text: '365 Hz' },
			{ id: 'C', text: '440 Hz' },
			{ id: 'D', text: '400 Hz' },
		],
		correctAnswer: 'A',
		hint: "Use Doppler effect: f' = f(v ± v₀)/(v ∓ vₛ)",
		explanation: "f' = f(v/(v - vₛ)) = 400(340/(340 - 30)) = 400(340/310) = 435 Hz",
		topic: 'Waves',
		subtopic: 'Doppler Effect',
		difficulty: 'hard',
		grades: [12],
		years: [2023, 2022, 2021],
		subject: 'physics',
		subjectLabel: 'Physics',
		fluentEmoji: '⚛️',
		color: 'text-purple-500',
		bgColor: 'bg-purple-500',
	},

	// ============================================================================
	// CHEMISTRY - Grade 10, 11, 12
	// ============================================================================
	{
		id: 'chem-grade10-atomic-1',
		question: 'How many protons does a carbon atom have?',
		options: [
			{ id: 'A', text: '6' },
			{ id: 'B', text: '12' },
			{ id: 'C', text: '8' },
			{ id: 'D', text: '4' },
		],
		correctAnswer: 'A',
		hint: 'The number of protons equals the atomic number',
		explanation: 'Carbon has atomic number 6, meaning it has 6 protons',
		topic: 'Atomic Structure',
		subtopic: 'Protons',
		difficulty: 'easy',
		grades: [10],
		years: [2023, 2022],
		subject: 'chemistry',
		subjectLabel: 'Chemistry',
		fluentEmoji: '⚛️',
		color: 'text-green-500',
		bgColor: 'bg-green-500',
	},
	{
		id: 'chem-grade11-balanced-1',
		question: 'Balance: _H₂ + _O₂ → _H₂O',
		options: [
			{ id: 'A', text: '2, 1, 2' },
			{ id: 'B', text: '1, 1, 1' },
			{ id: 'C', text: '2, 2, 2' },
			{ id: 'D', text: '1, 2, 2' },
		],
		correctAnswer: 'A',
		hint: 'Balance hydrogen first: 2H₂ + _O₂ → 2H₂O, then balance oxygen',
		explanation: '2H₂ + O₂ → 2H₂O (balanced)',
		topic: 'Chemical Reactions',
		subtopic: 'Balancing',
		difficulty: 'medium',
		grades: [11],
		years: [2023, 2022],
		subject: 'chemistry',
		subjectLabel: 'Chemistry',
		fluentEmoji: '⚛️',
		color: 'text-green-500',
		bgColor: 'bg-green-500',
	},
	{
		id: 'chem-grade12-equilibrium-1',
		question: 'For the reaction N₂ + 3H₂ ⇌ 2NH₃, what happens when pressure is increased?',
		options: [
			{ id: 'A', text: 'Shift to the right (more NH₃)' },
			{ id: 'B', text: 'Shift to the left (more N₂ and H₂)' },
			{ id: 'C', text: 'No change' },
			{ id: 'D', text: 'Reaction stops' },
		],
		correctAnswer: 'A',
		hint: "Use Le Chatelier's principle: increased pressure favors fewer gas moles",
		explanation:
			'4 moles gas → 2 moles gas. Higher pressure shifts equilibrium to the right (fewer moles)',
		topic: 'Chemical Equilibrium',
		subtopic: 'Le Chatelier',
		difficulty: 'medium',
		grades: [12],
		years: [2023, 2022],
		subject: 'chemistry',
		subjectLabel: 'Chemistry',
		fluentEmoji: '⚛️',
		color: 'text-green-500',
		bgColor: 'bg-green-500',
	},
	{
		id: 'chem-grade12-electro-1',
		question: 'In electrolysis of molten NaCl, what is produced at the cathode?',
		options: [
			{ id: 'A', text: 'Sodium metal (Na)' },
			{ id: 'B', text: 'Chlorine gas (Cl₂)' },
			{ id: 'C', text: 'Oxygen gas (O₂)' },
			{ id: 'D', text: 'Hydrogen gas (H₂)' },
		],
		correctAnswer: 'A',
		hint: 'Reduction occurs at the cathode',
		explanation: 'At cathode: Na⁺ + e⁻ → Na (reduction)',
		topic: 'Electrochemistry',
		subtopic: 'Electrolysis',
		difficulty: 'medium',
		grades: [12],
		years: [2023, 2022],
		subject: 'chemistry',
		subjectLabel: 'Chemistry',
		fluentEmoji: '⚛️',
		color: 'text-green-500',
		bgColor: 'bg-green-500',
	},

	// ============================================================================
	// LIFE SCIENCES - Grade 10, 11, 12
	// ============================================================================
	{
		id: 'life-grade10-cells-1',
		question: 'Which organelle is known as the "powerhouse" of the cell?',
		options: [
			{ id: 'A', text: 'Mitochondria' },
			{ id: 'B', text: 'Nucleus' },
			{ id: 'C', text: 'Ribosome' },
			{ id: 'D', text: 'Golgi apparatus' },
		],
		correctAnswer: 'A',
		hint: 'This organelle produces ATP through cellular respiration',
		explanation: "Mitochondria generate most of the cell's ATP through respiration",
		topic: 'Cell Biology',
		subtopic: 'Organelles',
		difficulty: 'easy',
		grades: [10],
		years: [2023, 2022],
		subject: 'life-sciences',
		subjectLabel: 'Life Sciences',
		fluentEmoji: '🧬',
		color: 'text-emerald-500',
		bgColor: 'bg-emerald-500',
	},
	{
		id: 'life-grade11-photosynthesis-1',
		question: 'What is the primary product of photosynthesis?',
		options: [
			{ id: 'A', text: 'Glucose' },
			{ id: 'B', text: 'Oxygen' },
			{ id: 'C', text: 'Carbon dioxide' },
			{ id: 'D', text: 'Water' },
		],
		correctAnswer: 'A',
		hint: 'Think about what plants make and store for energy',
		explanation: '6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂ (glucose is the main product)',
		topic: 'Photosynthesis',
		subtopic: 'Products',
		difficulty: 'easy',
		grades: [11],
		years: [2023, 2022],
		subject: 'life-sciences',
		subjectLabel: 'Life Sciences',
		fluentEmoji: '🧬',
		color: 'text-emerald-500',
		bgColor: 'bg-emerald-500',
	},
	{
		id: 'life-grade12-genetics-1',
		question:
			'If a heterozygous tall plant (Tt) is crossed with a homozygous short plant (tt), what percentage of offspring will be short?',
		options: [
			{ id: 'A', text: '50%' },
			{ id: 'B', text: '25%' },
			{ id: 'C', text: '75%' },
			{ id: 'D', text: '100%' },
		],
		correctAnswer: 'A',
		hint: 'Use a Punnett square: Tt × tt',
		explanation: 'Punnett square shows: Tt, Tt, tt, tt → 50% short (tt)',
		topic: 'Genetics',
		subtopic: 'Mendel',
		difficulty: 'medium',
		grades: [12],
		years: [2023, 2022],
		subject: 'life-sciences',
		subjectLabel: 'Life Sciences',
		fluentEmoji: '🧬',
		color: 'text-emerald-500',
		bgColor: 'bg-emerald-500',
	},
	{
		id: 'life-grade12-dna-1',
		question: 'DNA replication is described as:',
		options: [
			{ id: 'A', text: 'Semi-conservative' },
			{ id: 'B', text: 'Conservative' },
			{ id: 'C', text: 'Dispersive' },
			{ id: 'D', text: 'Destructive' },
		],
		correctAnswer: 'A',
		hint: 'Each new DNA molecule contains one old and one new strand',
		explanation: 'Meselson-Stahl experiment proved semi-conservative replication',
		topic: 'DNA',
		subtopic: 'Replication',
		difficulty: 'medium',
		grades: [12],
		years: [2023, 2022],
		subject: 'life-sciences',
		subjectLabel: 'Life Sciences',
		fluentEmoji: '🧬',
		color: 'text-emerald-500',
		bgColor: 'bg-emerald-500',
	},

	// ============================================================================
	// GEOGRAPHY - Grade 10, 11, 12
	// ============================================================================
	{
		id: 'geo-grade10-weathering-1',
		question: 'Which type of weathering is caused by the freezing and thawing of water?',
		options: [
			{ id: 'A', text: 'Frost weathering' },
			{ id: 'B', text: 'Oxidation' },
			{ id: 'C', text: 'Hydrolysis' },
			{ id: 'D', text: 'Carbonation' },
		],
		correctAnswer: 'A',
		hint: 'Think about what happens to water when it freezes',
		explanation: 'Frost weathering (freeze-thaw) occurs when water freezes in cracks and expands',
		topic: 'Geomorphology',
		subtopic: 'Weathering',
		difficulty: 'easy',
		grades: [10],
		years: [2023, 2022],
		subject: 'geography',
		subjectLabel: 'Geography',
		fluentEmoji: '🌍',
		color: 'text-amber-500',
		bgColor: 'bg-amber-500',
	},
	{
		id: 'geo-grade11-rivers-1',
		question:
			'Which river feature is formed where a fast-flowing river enters a slow-moving body of water?',
		options: [
			{ id: 'A', text: 'Delta' },
			{ id: 'B', text: 'V-shaped valley' },
			{ id: 'C', text: 'Waterfall' },
			{ id: 'D', text: 'Gorge' },
		],
		correctAnswer: 'A',
		hint: 'Think about river deposits at the mouth',
		explanation: 'Deltas form when rivers deposit sediment as they enter slower waters',
		topic: 'Fluvial Processes',
		subtopic: 'Depositional Features',
		difficulty: 'easy',
		grades: [11],
		years: [2023, 2022],
		subject: 'geography',
		subjectLabel: 'Geography',
		fluentEmoji: '🌍',
		color: 'text-amber-500',
		bgColor: 'bg-amber-500',
	},
	{
		id: 'geo-grade12-climate-1',
		question: 'The Indian Ocean Dipole (IOD) positively affects rainfall in:',
		options: [
			{ id: 'A', text: 'Eastern Southern Africa' },
			{ id: 'B', text: 'Western Australia' },
			{ id: 'C', text: 'India' },
			{ id: 'D', text: 'Indonesia' },
		],
		correctAnswer: 'A',
		hint: 'Positive IOD brings cooler ocean temperatures to eastern Africa',
		explanation: 'Positive IOD leads to increased rainfall in eastern southern Africa',
		topic: 'Climate',
		subtopic: 'Ocean Currents',
		difficulty: 'hard',
		grades: [12],
		years: [2023, 2022],
		subject: 'geography',
		subjectLabel: 'Geography',
		fluentEmoji: '🌍',
		color: 'text-amber-500',
		bgColor: 'bg-amber-500',
	},

	// ============================================================================
	// HISTORY - Grade 10, 11, 12
	// ============================================================================
	{
		id: 'hist-grade10-ww1-1',
		question: 'What was the immediate cause of World War I?',
		options: [
			{ id: 'A', text: 'Assassination of Archduke Franz Ferdinand' },
			{ id: 'B', text: 'Invasion of Poland' },
			{ id: 'C', text: 'Treaty of Versailles' },
			{ id: 'D', text: 'Russian Revolution' },
		],
		correctAnswer: 'A',
		hint: 'Think about the event that triggered the chain of alliances',
		explanation: 'June 28, 1914: assassination triggered a cascade of declarations of war',
		topic: 'World Wars',
		subtopic: 'WWI Causes',
		difficulty: 'easy',
		grades: [10],
		years: [2023, 2022],
		subject: 'history',
		subjectLabel: 'History',
		fluentEmoji: '📜',
		color: 'text-red-500',
		bgColor: 'bg-red-500',
	},
	{
		id: 'hist-grade11-apartheid-1',
		question: 'When did apartheid officially begin in South Africa?',
		options: [
			{ id: 'A', text: '1948' },
			{ id: 'B', text: '1994' },
			{ id: 'C', text: '1960' },
			{ id: 'D', text: '1976' },
		],
		correctAnswer: 'A',
		hint: 'The National Party came to power in this year',
		explanation: '1948: National Party elected and began implementing apartheid laws',
		topic: 'South Africa',
		subtopic: 'Apartheid',
		difficulty: 'easy',
		grades: [11],
		years: [2023, 2022, 2021],
		subject: 'history',
		subjectLabel: 'History',
		fluentEmoji: '📜',
		color: 'text-red-500',
		bgColor: 'bg-red-500',
	},
	{
		id: 'hist-grade12-coldwar-1',
		question: 'What was the period of détente in the Cold War?',
		options: [
			{ id: 'A', text: 'Relaxation of tensions between US and USSR (1969-1979)' },
			{ id: 'B', text: 'The Cuban Missile Crisis' },
			{ id: 'C', text: 'The fall of the Berlin Wall' },
			{ id: 'D', text: 'The Korean War' },
		],
		correctAnswer: 'A',
		hint: 'Think about the period of improved US-Soviet relations',
		explanation: 'Détente (1969-1979) saw reduced tensions and arms treaties',
		topic: 'Cold War',
		subtopic: 'International Relations',
		difficulty: 'medium',
		grades: [12],
		years: [2023, 2022],
		subject: 'history',
		subjectLabel: 'History',
		fluentEmoji: '📜',
		color: 'text-red-500',
		bgColor: 'bg-red-500',
	},

	// ============================================================================
	// ENGLISH - Grade 10, 11, 12
	// ============================================================================
	{
		id: 'eng-grade10-literary-1',
		question: '"The wind whispered through the trees" is an example of:',
		options: [
			{ id: 'A', text: 'Personification' },
			{ id: 'B', text: 'Simile' },
			{ id: 'C', text: 'Metaphor' },
			{ id: 'D', text: 'Hyperbole' },
		],
		correctAnswer: 'A',
		hint: 'Giving human qualities to something non-human',
		explanation: 'Personification gives human traits to non-human things (wind whispering)',
		topic: 'Literary Devices',
		subtopic: 'Figures of Speech',
		difficulty: 'easy',
		grades: [10],
		years: [2023, 2022],
		subject: 'english',
		subjectLabel: 'English',
		fluentEmoji: '📚',
		color: 'text-indigo-500',
		bgColor: 'bg-indigo-500',
	},
	{
		id: 'eng-grade11-essay-1',
		question: 'In an argumentative essay, the main argument is called the:',
		options: [
			{ id: 'A', text: 'Thesis statement' },
			{ id: 'B', text: 'Topic sentence' },
			{ id: 'C', text: 'Conclusion' },
			{ id: 'D', text: 'Transition' },
		],
		correctAnswer: 'A',
		hint: "This presents the writer's central claim",
		explanation: 'Thesis statement presents the main argument of the essay',
		topic: 'Essay Writing',
		subtopic: 'Structure',
		difficulty: 'easy',
		grades: [11],
		years: [2023, 2022],
		subject: 'english',
		subjectLabel: 'English',
		fluentEmoji: '📚',
		color: 'text-indigo-500',
		bgColor: 'bg-indigo-500',
	},
	{
		id: 'eng-grade12-poetry-1',
		question: 'The poem "Still I Rise" by Maya Angelou is primarily about:',
		options: [
			{ id: 'A', text: 'Resilience and overcoming oppression' },
			{ id: 'B', text: 'Nature and beauty' },
			{ id: 'C', text: 'Love and loss' },
			{ id: 'D', text: 'War and conflict' },
		],
		correctAnswer: 'A',
		hint: 'Think about the repeated phrase in the title',
		explanation: '"Still I Rise" celebrates African American resilience despite oppression',
		topic: 'Poetry Analysis',
		subtopic: 'Themes',
		difficulty: 'medium',
		grades: [12],
		years: [2023, 2022],
		subject: 'english',
		subjectLabel: 'English',
		fluentEmoji: '📚',
		color: 'text-indigo-500',
		bgColor: 'bg-indigo-500',
	},

	// ============================================================================
	// ACCOUNTING - Grade 10, 11, 12
	// ============================================================================
	{
		id: 'acc-grade10-equation-1',
		question: 'The basic accounting equation is:',
		options: [
			{ id: 'A', text: 'Assets = Liabilities + Equity' },
			{ id: 'B', text: 'Income = Expenses + Profit' },
			{ id: 'C', text: 'Debit = Credit' },
			{ id: 'D', text: 'Revenue = Sales' },
		],
		correctAnswer: 'A',
		hint: 'This equation must always balance',
		explanation: "Assets = Liabilities + Owner's Equity (the fundamental accounting equation)",
		topic: 'Fundamentals',
		subtopic: 'Accounting Equation',
		difficulty: 'easy',
		grades: [10],
		years: [2023, 2022],
		subject: 'accounting',
		subjectLabel: 'Accounting',
		fluentEmoji: '💰',
		color: 'text-teal-500',
		bgColor: 'bg-teal-500',
	},
	{
		id: 'acc-grade11-depreciation-1',
		question:
			'Using straight-line depreciation, what is the annual depreciation for equipment costing R50,000 with a salvage value of R10,000 over 5 years?',
		options: [
			{ id: 'A', text: 'R8,000 per year' },
			{ id: 'B', text: 'R10,000 per year' },
			{ id: 'C', text: 'R50,000 per year' },
			{ id: 'D', text: 'R12,500 per year' },
		],
		correctAnswer: 'A',
		hint: 'Depreciation = (Cost - Salvage Value) / Useful life',
		explanation: '(R50,000 - R10,000) / 5 = R40,000 / 5 = R8,000 per year',
		topic: 'Fixed Assets',
		subtopic: 'Depreciation',
		difficulty: 'medium',
		grades: [11],
		years: [2023, 2022],
		subject: 'accounting',
		subjectLabel: 'Accounting',
		fluentEmoji: '💰',
		color: 'text-teal-500',
		bgColor: 'bg-teal-500',
	},
	{
		id: 'acc-grade12-vat-1',
		question: 'If a business sells goods for R1,150 including 15% VAT, what is the VAT amount?',
		options: [
			{ id: 'A', text: 'R150' },
			{ id: 'B', text: 'R172.50' },
			{ id: 'C', text: 'R115' },
			{ id: 'D', text: 'R1,000' },
		],
		correctAnswer: 'A',
		hint: 'VAT is included in the price. Calculate: Price × VAT rate / (1 + VAT rate)',
		explanation: 'R1,150 × 15/115 = R1,150 × 0.1304 = R150',
		topic: 'VAT',
		subtopic: 'Calculations',
		difficulty: 'medium',
		grades: [12],
		years: [2023, 2022],
		subject: 'accounting',
		subjectLabel: 'Accounting',
		fluentEmoji: '💰',
		color: 'text-teal-500',
		bgColor: 'bg-teal-500',
	},
];
