import type { BattleSite, Biome, ClimateRegion, ConservationArea, MapMarker } from '@/types/map';

export const SOUTH_AFRICA_CENTER: [number, number] = [-30.5595, 22.9375];
export const DEFAULT_ZOOM = 6;
export const REGIONAL_ZOOM = 8;
export const DETAILED_ZOOM = 12;

export const CLIMATE_REGIONS: ClimateRegion[] = [
	{
		id: 'mediterranean',
		name: 'Mediterranean Climate',
		description: 'Hot, dry summers and mild, wet winters',
		characteristics: ['Winter rainfall', 'Summer drought', 'Fynbos region'],
		color: '#fbbf24',
	},
	{
		id: 'subtropical',
		name: 'Subtropical Climate',
		description: 'Hot summers and mild winters with summer rainfall',
		characteristics: ['Summer rainfall', 'Humid', 'Savanna region'],
		color: '#f97316',
	},
	{
		id: 'temperate',
		name: 'Temperate Climate',
		description: 'Moderate rainfall throughout the year',
		characteristics: ['Year-round rainfall', 'Mild temperatures', 'Grassland region'],
		color: '#22c55e',
	},
	{
		id: 'semi-arid',
		name: 'Semi-Arid Climate',
		description: 'Low rainfall with high temperature variation',
		characteristics: ['Low rainfall', 'High evaporation', 'Karoo region'],
		color: '#eab308',
	},
	{
		id: 'arid',
		name: 'Arid Climate',
		description: 'Very low rainfall, extreme temperatures',
		characteristics: ['Minimal rainfall', 'Extreme heat', 'Namib desert'],
		color: '#ef4444',
	},
];

export const BATTLE_SITES: BattleSite[] = [
	{
		id: 'battle-of-blood-river',
		name: 'Battle of Blood River',
		year: 1838,
		position: [-28.7558, 30.2897],
		conflict: 'The Great Trek',
		outcome: 'Zulu defeat',
	},
	{
		id: 'battle-isandlwana',
		name: 'Battle of Isandlwana',
		year: 1879,
		position: [-28.3542, 30.8125],
		conflict: 'Anglo-Zulu War',
		outcome: 'Zulu victory',
	},
	{
		id: 'battle-of-rorkes-drift',
		name: "Battle of Rorke's Drift",
		year: 1879,
		position: [-28.3527, 30.7708],
		conflict: 'Anglo-Zulu War',
		outcome: 'British victory',
	},
	{
		id: 'battle-of-spion-kop',
		name: 'Battle of Spion Kop',
		year: 1900,
		position: [-28.6147, 30.3083],
		conflict: 'Second Boer War',
		outcome: 'British victory',
	},
	{
		id: 'battle-of-paardeberg',
		name: 'Battle of Paardeberg',
		year: 1900,
		position: [-28.7167, 24.5833],
		conflict: 'Second Boer War',
		outcome: 'British victory',
	},
	{
		id: 'battle-of-magersfontein',
		name: 'Battle of Magersfontein',
		year: 1899,
		position: [-28.9167, 24.8333],
		conflict: 'Second Boer War',
		outcome: 'Boer victory',
	},
];

export const BIOMES: Biome[] = [
	{
		id: 'fynbos',
		name: 'Fynbos',
		description: 'Mediterranean shrubland with diverse flora',
		vegetation: ['Proteas', 'Restios', 'Ericas'],
		color: '#a855f7',
	},
	{
		id: 'savanna',
		name: 'Savanna',
		description: 'Grassland with scattered trees',
		vegetation: ['Acacia', 'Baobab', 'Mopane'],
		color: '#84cc16',
	},
	{
		id: 'grassland',
		name: 'Grassland',
		description: 'Temperate grassland with tall grasses',
		vegetation: ['Red grass', 'Blue grass', 'Sage'],
		color: '#22c55e',
	},
	{
		id: 'succulent-karoo',
		name: 'Succulent Karoo',
		description: 'Desert with succulent plants',
		vegetation: ['Aloe', 'Mesembryanthemum', 'Crassula'],
		color: '#f59e0b',
	},
	{
		id: 'forest',
		name: 'Forest',
		description: 'Indigenous forest patches',
		vegetation: ['Yellowwood', 'Stinkwood', 'White stinkwood'],
		color: '#166534',
	},
];

export const CONSERVATION_AREAS: ConservationArea[] = [
	{
		id: 'kruger',
		name: 'Kruger National Park',
		position: [-24.0117, 31.4854],
		type: 'national-park',
		established: 1926,
	},
	{
		id: 'table-mountain',
		name: 'Table Mountain National Park',
		position: [-33.9633, 18.4098],
		type: 'national-park',
		established: 1998,
	},
	{
		id: 'tsingwe',
		name: 'Addo Elephant National Park',
		position: [-33.5833, 25.75],
		type: 'national-park',
		established: 1931,
	},
	{
		id: 'ugadu',
		name: 'iSimangaliso Wetland Park',
		position: [-28.2, 32.5833],
		type: 'national-park',
		established: 1999,
	},
	{
		id: 'augrabies',
		name: 'Augrabies Falls National Park',
		position: [-28.5917, 20.3333],
		type: 'national-park',
		established: 1966,
	},
	{
		id: 'karoo',
		name: 'Karoo National Park',
		position: [-32.4833, 22.5667],
		type: 'national-park',
		established: 1979,
	},
	{
		id: 'mokala',
		name: 'Mokala National Park',
		position: [-32.6667, 24.05],
		type: 'national-park',
		established: 2007,
	},
	{
		id: 'kgalagadi',
		name: 'Kgalagadi Transfrontier Park',
		position: [-26.4667, 20.6],
		type: 'national-park',
		established: 2000,
	},
];

export const TIMELINE_EVENTS: MapMarker[] = [
	{
		id: '1652-dutch-arrival',
		title: 'Dutch Arrival',
		description: 'Jan van Riebeeck arrives at the Cape',
		position: [-33.9217, 18.4247],
		year: 1652,
		category: 'colonial',
	},
	{
		id: '1657-first-settlers',
		title: 'First Free Settlers',
		description: 'First free burghers granted land',
		position: [-33.9217, 18.4247],
		year: 1657,
		category: 'colonial',
	},
	{
		id: '1688-huguenots',
		title: 'Huguenot Arrival',
		description: 'French Huguenots arrive at the Cape',
		position: [-33.8833, 19.0833],
		year: 1688,
		category: 'colonial',
	},
	{
		id: '1795-british-cape',
		title: 'British Takeover',
		description: 'British occupies the Cape Colony',
		position: [-33.9217, 18.4247],
		year: 1795,
		category: 'colonial',
	},
	{
		id: '1806-second-british',
		title: 'Second British Occupation',
		description: 'British reoccupies the Cape',
		position: [-33.9217, 18.4247],
		year: 1806,
		category: 'colonial',
	},
	{
		id: '1835-great-trek',
		title: 'Great Trek Begins',
		description: 'Afrikaner voortrekkers begin journey inland',
		position: [-29.1167, 26.1667],
		year: 1835,
		category: 'colonial',
	},
	{
		id: '1910-union',
		title: 'Union of South Africa',
		description: 'Four colonies unite to form South Africa',
		position: [-25.7461, 28.1881],
		year: 1910,
		category: 'political',
	},
	{
		id: '1913-land-act',
		title: 'Land Act',
		description: 'Native Land Act restricts black land ownership',
		position: [-26.203, 28.0446],
		year: 1913,
		category: 'political',
	},
	{
		id: '1948-apartheid',
		title: 'Apartheid Begins',
		description: 'National Party implements apartheid policies',
		position: [-25.7461, 28.1881],
		year: 1948,
		category: 'political',
	},
	{
		id: '1960-republic',
		title: 'Republic Established',
		description: 'South Africa becomes a republic',
		position: [-25.7461, 28.1881],
		year: 1960,
		category: 'political',
	},
	{
		id: '1976-soweto',
		title: 'Soweto Uprising',
		description: 'Student protests against forced education',
		position: [-26.2639, 27.9658],
		year: 1976,
		category: 'resistance',
	},
	{
		id: '1990-release-mandela',
		title: 'Mandela Released',
		description: 'Nelson Mandela freed after 27 years',
		position: [-33.9217, 18.4247],
		year: 1990,
		category: 'resistance',
	},
	{
		id: '1994-democracy',
		title: 'First Democratic Elections',
		description: 'First one-person-one-vote election',
		position: [-25.7461, 28.1881],
		year: 1994,
		category: 'political',
	},
];

export const TOPOGRAPHIC_FEATURES: MapMarker[] = [
	{
		id: 'table-mountain',
		title: 'Table Mountain',
		description: 'Flat-topped mountain in Cape Town',
		position: [-33.9633, 18.4098],
		category: 'mountain',
	},
	{
		id: 'drakensberg',
		title: 'Drakensberg Mountains',
		description: 'Highest mountain range in South Africa',
		position: [-29.0, 29.5],
		category: 'mountain',
	},
	{
		id: 'magaliesberg',
		title: 'Magaliesberg Range',
		description: 'Mountain range near Johannesburg',
		position: [-25.8667, 27.55],
		category: 'mountain',
	},
	{
		id: 'orange-river',
		title: 'Orange River',
		description: 'Major river flowing west to Atlantic',
		position: [-28.75, 21.25],
		category: 'river',
	},
	{
		id: 'limpopo-river',
		title: 'Limpopo River',
		description: 'Major river forming northern border',
		position: [-24.1667, 25.9333],
		category: 'river',
	},
	{
		id: 'vaal-river',
		title: 'Vaal River',
		description: 'Major tributary of the Orange River',
		position: [-26.7833, 27.4],
		category: 'river',
	},
];
