export const SUBJECTS = [
	{
		id: 'math',
		name: 'Mathematics',
		topics: 'Calculus, Euclidean Geometry, Trig',
		icon: 'Calculator',
		color: 'text-brand-blue',
		bg: 'bg-brand-blue/10',
		path: '/quiz',
		image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=400',
	},
	{
		id: 'physics',
		name: 'Physical Sciences',
		topics: 'Newtonian Laws, Electrodynamics, Organic',
		icon: 'Atom',
		color: 'text-brand-purple',
		bg: 'bg-brand-purple/10',
		path: '/physics',
		image: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?auto=format&fit=crop&q=80&w=400',
	},
	{
		id: 'chemistry',
		name: 'Chemistry',
		topics: 'Rate of Reaction, Organic Molecules',
		icon: 'FlaskConical',
		color: 'text-brand-amber',
		bg: 'bg-brand-amber/10',
		path: '/quiz',
		image: 'https://images.unsplash.com/photo-1532187875605-1ef6c237f142?auto=format&fit=crop&q=80&w=400',
	},
	{
		id: 'life',
		name: 'Life Sciences',
		topics: 'Genetics, Evolution, DNA',
		icon: 'Microscope',
		color: 'text-brand-green',
		bg: 'bg-brand-green/10',
		path: '/quiz',
		image: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&q=80&w=400',
	},
];

export const PAST_PAPERS = [
	{
		id: 'phys-p1-2025-may',
		year: 2025,
		subject: 'Physical Sciences',
		paper: 'P1',
		month: 'May/June',
		marks: 150,
		time: '3 Hours',
		downloadUrl: 'https://drive.google.com/uc?export=download&id=1cP0lx69tfb7iZOtWP_8wG-BUiv1nS85i',
	},
	{
		id: 'math-p1-2025-may',
		year: 2025,
		subject: 'Mathematics',
		paper: 'P1',
		month: 'May/June',
		marks: 150,
		time: '3 Hours',
		downloadUrl: 'https://www.education.gov.za/LinkClick.aspx?link=5475&tabid=593&portalid=0&mid=1741',
	},
	{
		id: 'math-p1-2024-nov',
		year: 2024,
		subject: 'Mathematics',
		paper: 'P1',
		month: 'November',
		marks: 150,
		time: '3 Hours',
		downloadUrl: 'https://www.education.gov.za/LinkClick.aspx?link=https://www.education.gov.za/2024NSCNovemberpastpapers.aspx',
	},
	{
		id: 'math-p2-2024-nov',
		year: 2024,
		subject: 'Mathematics',
		paper: 'P2',
		month: 'November',
		marks: 150,
		time: '3 Hours',
		downloadUrl: '#',
	},
	{
		id: 'phys-p1-2024-nov',
		year: 2024,
		subject: 'Physical Sciences',
		paper: 'P1',
		month: 'November',
		marks: 150,
		time: '3 Hours',
		downloadUrl: '#',
	},
	{
		id: 'math-p1-2023-nov',
		year: 2023,
		subject: 'Mathematics',
		paper: 'P1',
		month: 'November',
		marks: 150,
		time: '3 Hours',
		downloadUrl: '#',
	},
	{
		id: 'math-p1-2022-nov',
		year: 2022,
		subject: 'Mathematics',
		paper: 'P1',
		month: 'November',
		marks: 150,
		time: '3 Hours',
		downloadUrl: '#',
	},
	{
		id: 'math-p1-2021-nov',
		year: 2021,
		subject: 'Mathematics',
		paper: 'P1',
		month: 'November',
		marks: 150,
		time: '3 Hours',
		downloadUrl: '#',
	},
	{
		id: 'math-p1-2020-nov',
		year: 2020,
		subject: 'Mathematics',
		paper: 'P1',
		month: 'November',
		marks: 150,
		time: '3 Hours',
		downloadUrl: '#',
	},
];

export const CURRENT_GOAL = {
	title: 'Calculus: Optimization',
	subtitle: 'Next: Stationary Points & Maxima',
	progress: 60,
	step: 'Quiz 3/5',
	icon: '🚀',
};

export const WEEKLY_JOURNEY = [
	{ day: 'TUE', date: 10, status: 'complete' },
	{ day: 'WED', date: 11, status: 'complete' },
	{ day: 'THU', date: 12, status: 'active' },
	{ day: 'FRI', date: 13, status: 'upcoming' },
	{ day: 'SAT', date: 14, status: 'upcoming' },
	{ day: 'SUN', date: 15, status: 'upcoming' },
];

export const RECOMMENDED_CHALLENGES = [
	{
		title: 'Rate of Reaction',
		topic: 'Chemistry',
		time: '12m',
		difficulty: 'Medium',
		color: 'bg-brand-amber/10 text-brand-amber',
		icon: '🧪',
	},
	{
		title: 'Organic Molecules',
		topic: 'Chemistry',
		time: '15m',
		difficulty: 'Easy',
		color: 'bg-brand-amber/10 text-brand-amber',
		icon: '⬢',
	},
	{
		title: 'Doppler Effect',
		topic: 'Physics',
		time: '20m',
		difficulty: 'Hard',
		color: 'bg-brand-purple/10 text-brand-purple',
		icon: '🔊',
	},
];
