import { SUBJECTS as CENTRAL_SUBJECTS } from './subjects';

export const SUBJECTS = [
	{
		...CENTRAL_SUBJECTS.mathematics,
		id: 'math',
		topics: 'Calculus, Euclidean Geometry, Trig',
		path: '/quiz',
		bg: 'bg-subject-math',
		image:
			'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=400',
	},
	{
		...CENTRAL_SUBJECTS.physics,
		id: 'physics',
		name: 'Physical Sciences',
		topics: 'Newtonian Laws, Electrodynamics, Organic',
		path: '/physics',
		bg: 'bg-subject-physics',
		image:
			'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?auto=format&fit=crop&q=80&w=400',
	},
	{
		...CENTRAL_SUBJECTS.chemistry,
		id: 'chemistry',
		topics: 'Rate of Reaction, Organic Molecules',
		path: '/quiz',
		bg: 'bg-subject-physics-soft',
		image:
			'https://images.unsplash.com/photo-1532187875605-1ef6c237f142?auto=format&fit=crop&q=80&w=400',
	},
	{
		...CENTRAL_SUBJECTS['life-sciences'],
		id: 'life',
		topics: 'Genetics, Evolution, DNA',
		path: '/quiz',
		bg: 'bg-subject-life',
		image:
			'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&q=80&w=400',
	},
];

export const PAST_PAPERS = [
	{
		id: 'phys-p1-2025-may',
		year: 2025,
		subject: 'Physical Sciences',
		paper: 'P1',
		month: 'May/June',
		marks: 150,
		time: '3 Hours',
		downloadUrl: 'https://drive.google.com/uc?export=download&id=1cP0lx69tfb7iZOtWP_8wG-BUiv1nS85i',
	},
	{
		id: 'acc-p1-2025-may',
		year: 2025,
		subject: 'Accounting',
		paper: 'P1',
		month: 'May/June',
		marks: 150,
		time: '2 Hours',
		downloadUrl: 'https://drive.google.com/uc?export=download&id=1dAj0R1EGuRCrcqvZ9jWbngV8uvHVvaur',
	},
	{
		id: 'acc-p2-2025-may',
		year: 2025,
		subject: 'Accounting',
		paper: 'P2',
		month: 'May/June',
		marks: 150,
		time: '2 Hours',
		downloadUrl: 'https://drive.google.com/uc?export=download&id=1kfmuwClPFo0OJBRQ0efUpVu_2f0Ox61x',
	},
	{
		id: 'geo-p1-2025-may',
		year: 2025,
		subject: 'Geography',
		paper: 'P1',
		month: 'May/June',
		marks: 150,
		time: '3 Hours',
		downloadUrl: 'https://drive.google.com/uc?export=download&id=1LNu76D16j5Tg3um-6uaCzsnyMSZKRsCu',
	},
	{
		id: 'geo-p2-2025-may',
		year: 2025,
		subject: 'Geography',
		paper: 'P2',
		month: 'May/June',
		marks: 150,
		time: '3 Hours',
		downloadUrl: 'https://drive.google.com/uc?export=download&id=1hUUsiGflYS0Jb8JK9dtP_RQUmgC3MVy_',
	},
	{
		id: 'life-p1-2025-may',
		year: 2025,
		subject: 'Life Sciences',
		paper: 'P1',
		month: 'May/June',
		marks: 150,
		time: '2.5 Hours',
		downloadUrl: 'https://drive.google.com/uc?export=download&id=1vQcby-s4vQdAyroxiJDC4npJVYlp8yKD',
	},
	{
		id: 'life-p2-2025-may',
		year: 2025,
		subject: 'Life Sciences',
		paper: 'P2',
		month: 'May/June',
		marks: 150,
		time: '2.5 Hours',
		downloadUrl: 'https://drive.google.com/uc?export=download&id=1x6cPXzy145QmwfEaG0L-Y-RVl5KEbTHY',
	},
	{
		id: 'math-p1-2025-may',
		year: 2025,
		subject: 'Mathematics',
		paper: 'P1',
		month: 'May/June',
		marks: 150,
		time: '3 Hours',
		downloadUrl: 'https://drive.google.com/uc?export=download&id=1RAYF526HEecxQCiECGn2kBFg1yy3ppVS',
	},
	{
		id: 'math-p2-2025-may',
		year: 2025,
		subject: 'Mathematics',
		paper: 'P2',
		month: 'May/June',
		marks: 150,
		time: '3 Hours',
		downloadUrl: 'https://drive.google.com/uc?export=download&id=1ZTIR5A2Jd_pZEEOUq9kESdzFfmoxJf',
	},
	{
		id: 'eng-p1-2025-may',
		year: 2025,
		subject: 'English HL',
		paper: 'P1',
		month: 'May/June',
		marks: 70,
		time: '2 Hours',
		downloadUrl: 'https://drive.google.com/uc?export=download&id=1-dd5utD14SICRu21MnGsax54De1emspI',
	},
	{
		id: 'eng-p2-2025-may',
		year: 2025,
		subject: 'English HL',
		paper: 'P2',
		month: 'May/June',
		marks: 80,
		time: '2.5 Hours',
		downloadUrl: 'https://drive.google.com/uc?export=download&id=12E6VNwp-zT1Z9rkFI1lugI5xVXZ5oU2F',
	},
	{
		id: 'eng-p3-2025-may',
		year: 2025,
		subject: 'English HL',
		paper: 'P3',
		month: 'May/June',
		marks: 100,
		time: '2.5 Hours',
		downloadUrl: 'https://drive.google.com/uc?export=download&id=1MUqDgQhWqqzPBws2j-57EzD6zmd_1jJp',
	},
	{
		id: 'math-p1-2024-nov',
		year: 2024,
		subject: 'Mathematics',
		paper: 'P1',
		month: 'November',
		marks: 150,
		time: '3 Hours',
		downloadUrl:
			'https://www.education.gov.za/LinkClick.aspx?link=https://www.education.gov.za/2024NSCNovemberpastpapers.aspx',
	},
	{
		id: 'math-p2-2024-nov',
		year: 2024,
		subject: 'Mathematics',
		paper: 'P2',
		month: 'November',
		marks: 150,
		time: '3 Hours',
		downloadUrl: '#',
	},
	{
		id: 'phys-p1-2024-nov',
		year: 2024,
		subject: 'Physical Sciences',
		paper: 'P1',
		month: 'November',
		marks: 150,
		time: '3 Hours',
		downloadUrl: '#',
	},
	{
		id: 'math-p1-2023-nov',
		year: 2023,
		subject: 'Mathematics',
		paper: 'P1',
		month: 'November',
		marks: 150,
		time: '3 Hours',
		downloadUrl: '#',
	},
	{
		id: 'math-p1-2022-nov',
		year: 2022,
		subject: 'Mathematics',
		paper: 'P1',
		month: 'November',
		marks: 150,
		time: '3 Hours',
		downloadUrl: '#',
	},
	{
		id: 'math-p1-2021-nov',
		year: 2021,
		subject: 'Mathematics',
		paper: 'P1',
		month: 'November',
		marks: 150,
		time: '3 Hours',
		downloadUrl: '#',
	},
	{
		id: 'math-p1-2020-nov',
		year: 2020,
		subject: 'Mathematics',
		paper: 'P1',
		month: 'November',
		marks: 150,
		time: '3 Hours',
		downloadUrl: '#',
	},
];

export const CURRENT_GOAL = {
	title: 'Calculus: Optimization',
	subtitle: 'Next: Stationary Points & Maxima',
	progress: 60,
	step: 'Quiz 3/5',
	icon: '🚀',
};

export const WEEKLY_JOURNEY = [
	{ day: 'TUE', date: 10, status: 'complete' },
	{ day: 'WED', date: 11, status: 'complete' },
	{ day: 'THU', date: 12, status: 'active' },
	{ day: 'FRI', date: 13, status: 'upcoming' },
	{ day: 'SAT', date: 14, status: 'upcoming' },
	{ day: 'SUN', date: 15, status: 'upcoming' },
];

export const RECOMMENDED_CHALLENGES = [
	{
		title: 'Rate of Reaction',
		topic: 'Chemistry',
		time: '12m',
		difficulty: 'Medium',
		color: 'bg-brand-amber/10 text-brand-amber',
		icon: '🧪',
	},
	{
		title: 'Organic Molecules',
		topic: 'Chemistry',
		time: '15m',
		difficulty: 'Easy',
		color: 'bg-brand-amber/10 text-brand-amber',
		icon: '⬢',
	},
	{
		title: 'Doppler Effect',
		topic: 'Physics',
		time: '20m',
		difficulty: 'Hard',
		color: 'bg-brand-purple/10 text-brand-purple',
		icon: '🔊',
	},
];
