import type { QuizData } from './types';

export const SHORT_ANSWER_QUIZ: QuizData = {
	'math-short-answer-2024': {
		title: 'Mathematics Short Answer Practice 2024',
		subject: 'Mathematics',
		year: 2024,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'math-sa-2024-q1',
				type: 'shortAnswer',
				question: 'Solve for x: 2x + 5 = 13',
				correctAnswer: 'x = 4',
				acceptableAnswers: ['4', 'x=4', 'x = 4'],
				maxMarks: 2,
				gradingType: 'exact',
				hint: 'Subtract 5 from both sides, then divide by 2.',
				topic: 'Linear Equations',
				subtopic: 'Solving Equations',
				difficulty: 'easy',
			},
			{
				id: 'math-sa-2024-q2',
				type: 'shortAnswer',
				question: 'Factorise fully: x² - 9',
				correctAnswer: '(x - 3)(x + 3)',
				acceptableAnswers: ['(x-3)(x+3)', '(x+3)(x-3)', 'difference of squares'],
				maxMarks: 2,
				gradingType: 'exact',
				hint: 'This is a difference of two squares: a² - b² = (a - b)(a + b).',
				topic: 'Algebra',
				subtopic: 'Factorisation',
				difficulty: 'easy',
			},
			{
				id: 'math-sa-2024-q3',
				type: 'shortAnswer',
				question: 'Calculate the derivative of f(x) = 3x⁴ - 2x² + 7',
				correctAnswer: "f'(x) = 12x³ - 4x",
				keywords: ['12x³', '4x', 'derivative', 'power rule'],
				maxMarks: 3,
				gradingType: 'keywords',
				hint: 'Apply the power rule: bring down the exponent and reduce it by 1.',
				topic: 'Calculus',
				subtopic: 'Differentiation',
				difficulty: 'medium',
			},
			{
				id: 'math-sa-2024-q4',
				type: 'shortAnswer',
				question: 'Find the sum of the interior angles of a hexagon.',
				correctAnswer: '720 degrees',
				acceptableAnswers: ['720°', '720', 'seven hundred and twenty degrees'],
				maxMarks: 2,
				gradingType: 'exact',
				hint: 'Use the formula: (n - 2) × 180°, where n is the number of sides.',
				topic: 'Geometry',
				subtopic: 'Angle Sum',
				difficulty: 'easy',
			},
			{
				id: 'math-sa-2024-q5',
				type: 'shortAnswer',
				question: 'Simplify: √48',
				correctAnswer: '4√3',
				acceptableAnswers: ['4√3', '4root3', '4*sqrt(3)'],
				maxMarks: 2,
				gradingType: 'exact',
				hint: 'Find the largest perfect square that divides 48: 48 = 16 × 3.',
				topic: 'Number Theory',
				subtopic: 'Surds',
				difficulty: 'easy',
			},
			{
				id: 'math-sa-2024-q6',
				type: 'shortAnswer',
				question: 'Write the equation of the line passing through (2, 3) with gradient 4.',
				correctAnswer: 'y = 4x - 5',
				keywords: ['y = 4x - 5', '4x - 5', 'y - 3 = 4(x - 2)'],
				maxMarks: 3,
				gradingType: 'keywords',
				hint: 'Use point-gradient form: y - y₁ = m(x - x₁), then simplify.',
				topic: 'Functions',
				subtopic: 'Linear Functions',
				difficulty: 'medium',
			},
			{
				id: 'math-sa-2024-q7',
				type: 'shortAnswer',
				question:
					'Determine the area of a circle with radius 7 cm, leaving your answer in terms of π.',
				correctAnswer: '49π cm²',
				acceptableAnswers: ['49π cm²', '49π', '49 pi'],
				maxMarks: 2,
				gradingType: 'exact',
				hint: 'Area = πr². Substitute r = 7.',
				topic: 'Geometry',
				subtopic: 'Circles',
				difficulty: 'easy',
			},
			{
				id: 'math-sa-2024-q8',
				type: 'shortAnswer',
				question: 'Solve for x: x² - 5x + 6 = 0',
				correctAnswer: 'x = 2 or x = 3',
				acceptableAnswers: ['2 and 3', 'x=2, x=3', 'x=2 or x=3'],
				maxMarks: 3,
				gradingType: 'exact',
				hint: 'Factorise: look for two numbers that multiply to 6 and add to -5.',
				topic: 'Equations',
				subtopic: 'Quadratic Equations',
				difficulty: 'easy',
			},
			{
				id: 'math-sa-2024-q9',
				type: 'shortAnswer',
				question: 'Calculate the gradient of the line passing through (1, 2) and (4, 8).',
				correctAnswer: '2',
				acceptableAnswers: ['2', 'm=2', 'gradient = 2'],
				maxMarks: 2,
				gradingType: 'exact',
				hint: 'Gradient = (y₂ - y₁) / (x₂ - x₁).',
				topic: 'Functions',
				subtopic: 'Gradient',
				difficulty: 'easy',
			},
			{
				id: 'math-sa-2024-q10',
				type: 'shortAnswer',
				question: 'Evaluate: log₂(32)',
				correctAnswer: '5',
				acceptableAnswers: ['5', 'log₂(32) = 5'],
				maxMarks: 2,
				gradingType: 'exact',
				hint: '32 = 2⁵, so log₂(32) = 5.',
				topic: 'Functions',
				subtopic: 'Logarithms',
				difficulty: 'easy',
			},
		],
	},
	'physics-short-answer-2024': {
		title: 'Physical Sciences Short Answer Practice 2024',
		subject: 'Physical Sciences',
		year: 2024,
		session: 'November',
		paper: 1,
		questions: [
			{
				id: 'phys-sa-2024-q1',
				type: 'shortAnswer',
				question: "State Newton's Second Law of Motion.",
				correctAnswer:
					'The acceleration of an object is directly proportional to the net force acting on it and inversely proportional to its mass.',
				keywords: ['directly proportional', 'net force', 'inversely proportional', 'mass'],
				maxMarks: 4,
				gradingType: 'keywords',
				hint: 'Think about the relationship between force, mass, and acceleration.',
				topic: 'Mechanics',
				subtopic: "Newton's Laws",
				difficulty: 'easy',
			},
			{
				id: 'phys-sa-2024-q2',
				type: 'shortAnswer',
				question:
					'A ball is thrown vertically upward with a velocity of 20 m/s. Calculate the maximum height reached. (g = 10 m/s²)',
				correctAnswer: '20 m',
				acceptableAnswers: ['20 m', '20 meters', '20m'],
				maxMarks: 4,
				gradingType: 'exact',
				hint: 'Use v² = u² - 2gh. At maximum height, final velocity v = 0.',
				topic: 'Mechanics',
				subtopic: 'Projectile Motion',
				difficulty: 'medium',
			},
			{
				id: 'phys-sa-2024-q3',
				type: 'shortAnswer',
				question: 'Define the term "momentum".',
				correctAnswer: "Momentum is the product of an object's mass and velocity.",
				keywords: ['product', 'mass', 'velocity', 'momentum'],
				maxMarks: 2,
				gradingType: 'keywords',
				hint: 'Momentum depends on two quantities.',
				topic: 'Mechanics',
				subtopic: 'Momentum',
				difficulty: 'easy',
			},
			{
				id: 'phys-sa-2024-q4',
				type: 'shortAnswer',
				question: 'Calculate the kinetic energy of a 2 kg object moving at 5 m/s.',
				correctAnswer: '25 J',
				acceptableAnswers: ['25 J', '25J', '25 joules', '25'],
				maxMarks: 3,
				gradingType: 'exact',
				hint: 'KE = ½mv². Substitute m = 2 kg and v = 5 m/s.',
				topic: 'Mechanical Energy',
				subtopic: 'Kinetic Energy',
				difficulty: 'easy',
			},
			{
				id: 'phys-sa-2024-q5',
				type: 'shortAnswer',
				question: 'State the First Law of Thermodynamics.',
				correctAnswer:
					'Energy cannot be created or destroyed, only transformed from one form to another.',
				keywords: ['energy', 'created', 'destroyed', 'transformed', 'conservation'],
				maxMarks: 4,
				gradingType: 'keywords',
				hint: 'Think about the conservation of energy.',
				topic: 'Thermodynamics',
				subtopic: 'Laws of Thermodynamics',
				difficulty: 'medium',
			},
			{
				id: 'phys-sa-2024-q6',
				type: 'shortAnswer',
				question:
					'A circuit has a 12 V battery and a 4 Ω resistor. Calculate the current flowing through the circuit.',
				correctAnswer: '3 A',
				acceptableAnswers: ['3 A', '3A', '3 amperes', '3'],
				maxMarks: 3,
				gradingType: 'exact',
				hint: "Use Ohm's Law: V = IR. Rearrange to find I.",
				topic: 'Electricity',
				subtopic: 'Circuits',
				difficulty: 'easy',
			},
			{
				id: 'phys-sa-2024-q7',
				type: 'shortAnswer',
				question: 'What is the wavelength of a wave with frequency 500 Hz and speed 340 m/s?',
				correctAnswer: '0.68 m',
				acceptableAnswers: ['0.68 m', '0.68m', '68 cm'],
				maxMarks: 3,
				gradingType: 'exact',
				hint: 'Use v = fλ. Rearrange to find λ = v/f.',
				topic: 'Waves',
				subtopic: 'Wave Properties',
				difficulty: 'easy',
			},
			{
				id: 'phys-sa-2024-q8',
				type: 'shortAnswer',
				question: 'Define "photoelectric effect".',
				correctAnswer:
					'The emission of electrons from a metal surface when light of sufficient frequency shines on it.',
				keywords: ['electrons', 'emission', 'metal', 'light', 'frequency'],
				maxMarks: 4,
				gradingType: 'keywords',
				hint: 'Think about what happens when light hits a metal.',
				topic: 'Modern Physics',
				subtopic: 'Photoelectric Effect',
				difficulty: 'medium',
			},
			{
				id: 'phys-sa-2024-q9',
				type: 'shortAnswer',
				question:
					'Calculate the gravitational potential energy of a 5 kg mass at a height of 10 m above the ground. (g = 10 m/s²)',
				correctAnswer: '500 J',
				acceptableAnswers: ['500 J', '500J', '500 joules'],
				maxMarks: 3,
				gradingType: 'exact',
				hint: 'GPE = mgh. Substitute m = 5 kg, g = 10 m/s², h = 10 m.',
				topic: 'Mechanical Energy',
				subtopic: 'Potential Energy',
				difficulty: 'easy',
			},
			{
				id: 'phys-sa-2024-q10',
				type: 'shortAnswer',
				question: 'State the law of conservation of charge.',
				correctAnswer:
					'Charge cannot be created or destroyed, only transferred from one object to another.',
				keywords: ['charge', 'created', 'destroyed', 'transferred', 'conservation'],
				maxMarks: 3,
				gradingType: 'keywords',
				hint: 'Think about what happens to electrons during charging.',
				topic: 'Electricity',
				subtopic: 'Electric Charge',
				difficulty: 'easy',
			},
		],
	},
};
