import { integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const accounts = sqliteTable('accounts', {
	id: text().primaryKey().notNull(),
	accountId: text().notNull(),
	providerId: text().notNull(),
	userId: text().notNull(),
	accessToken: text(),
	refreshToken: text(),
	idToken: text(),
	accessTokenExpiresAt: text(),
	refreshTokenExpiresAt: text(),
	scope: text(),
	password: text(),
	createdAt: text().notNull(),
	updatedAt: text().notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const aiConversations = sqliteTable('ai_conversations', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	title: text().notNull(),
	subject: text(),
	messages: text().notNull(),
	messageCount: integer('message_count').default(0).notNull(),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const apsMilestones = sqliteTable('aps_milestones', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	universityTargetId: text('university_target_id'),
	title: text().notNull(),
	description: text(),
	subject: text(),
	topic: text(),
	apsPotentialPoints: integer('aps_potential_points').default(1).notNull(),
	status: text().default('pending').notNull(),
	completedAt: text('completed_at'),
	dueDate: text('due_date'),
	createdAt: text('created_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const bookmarks = sqliteTable('bookmarks', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	bookmarkType: text('bookmark_type').notNull(),
	referenceId: text('reference_id').notNull(),
	note: text(),
	createdAt: text('created_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const buddyRequests = sqliteTable('buddy_requests', {
	id: text().primaryKey().notNull(),
	fromUserId: text('from_user_id').notNull(),
	toUserId: text('to_user_id').notNull(),
	message: text(),
	status: text().default('pending').notNull(),
	createdAt: text('created_at').notNull(),
	respondedAt: text('responded_at'),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const calendarEvents = sqliteTable('calendar_events', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	title: text().notNull(),
	description: text(),
	eventType: text('event_type').notNull(),
	subjectId: integer('subject_id'),
	startTime: text('start_time').notNull(),
	endTime: text('end_time').notNull(),
	isAllDay: integer('is_all_day').default(false).notNull(),
	location: text(),
	reminderMinutes: text('reminder_minutes'),
	recurrenceRule: text('recurrence_rule'),
	examId: text('exam_id'),
	lessonId: integer('lesson_id'),
	studyPlanId: text('study_plan_id'),
	isCompleted: integer('is_completed').default(false).notNull(),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const channelMembers = sqliteTable('channel_members', {
	channelId: text('channel_id').notNull(),
	userId: text('user_id').notNull(),
	role: text().default('member').notNull(),
	joinedAt: text('joined_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const channels = sqliteTable('channels', {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	description: text(),
	subjectId: integer('subject_id'),
	createdBy: text('created_by').notNull(),
	isPublic: integer('is_public').default(true).notNull(),
	memberCount: integer('member_count').default(1).notNull(),
	createdAt: text('created_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const commentVotes = sqliteTable('comment_votes', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	commentId: text('comment_id').notNull(),
	voteType: text('vote_type').notNull(),
	createdAt: text('created_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const comments = sqliteTable('comments', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	content: text().notNull(),
	resourceType: text('resource_type').notNull(),
	resourceId: text('resource_id').notNull(),
	parentId: text('parent_id'),
	isEdited: integer('is_edited').default(false).notNull(),
	isFlagged: integer('is_flagged').default(false).notNull(),
	flagReason: text('flag_reason'),
	upvotes: integer().default(0).notNull(),
	downvotes: integer().default(0).notNull(),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const conceptStruggles = sqliteTable('concept_struggles', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	concept: text().notNull(),
	struggleCount: integer('struggle_count').default(1).notNull(),
	lastStruggleAt: text('last_struggle_at').notNull(),
	isResolved: integer('is_resolved').default(false).notNull(),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const contentFlags = sqliteTable('content_flags', {
	id: text().primaryKey().notNull(),
	reporterId: text('reporter_id').notNull(),
	contentType: text('content_type').notNull(),
	contentId: text('content_id').notNull(),
	contentPreview: text('content_preview'),
	flagReason: text('flag_reason').notNull(),
	flagDetails: text('flag_details'),
	status: text().default('pending').notNull(),
	reviewedBy: text('reviewed_by'),
	reviewedAt: text('reviewed_at'),
	createdAt: text('created_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const flashcardDecks = sqliteTable('flashcard_decks', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	name: text().notNull(),
	description: text(),
	subjectId: integer('subject_id'),
	cardCount: integer('card_count').default(0).notNull(),
	isPublic: integer('is_public').default(false).notNull(),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const flashcardReviews = sqliteTable('flashcard_reviews', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	flashcardId: text('flashcard_id').notNull(),
	rating: integer().notNull(),
	intervalBefore: integer('interval_before'),
	intervalAfter: integer('interval_after').notNull(),
	easeFactorBefore: text('ease_factor_before'),
	easeFactorAfter: text('ease_factor_after').notNull(),
	reviewedAt: text('reviewed_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const flashcards = sqliteTable('flashcards', {
	id: text().primaryKey().notNull(),
	deckId: text('deck_id').notNull(),
	front: text().notNull(),
	back: text().notNull(),
	imageUrl: text('image_url'),
	difficulty: text().default('medium').notNull(),
	timesReviewed: integer('times_reviewed').default(0).notNull(),
	timesCorrect: integer('times_correct').default(0).notNull(),
	easeFactor: text('ease_factor').default('2.5').notNull(),
	intervalDays: integer('interval_days').default(1).notNull(),
	repetitions: integer().default(0).notNull(),
	nextReview: text('next_review'),
	lastReview: text('last_review'),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const leaderboardEntries = sqliteTable('leaderboard_entries', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	periodType: text('period_type').notNull(),
	periodStart: text('period_start').notNull(),
	totalPoints: integer('total_points').default(0).notNull(),
	rank: integer(),
	questionsCompleted: integer('questions_completed').default(0).notNull(),
	accuracyPercentage: integer('accuracy_percentage'),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const notifications = sqliteTable('notifications', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	type: text().notNull(),
	title: text().notNull(),
	message: text().notNull(),
	data: text(),
	isRead: integer('is_read').default(false).notNull(),
	readAt: text('read_at'),
	createdAt: text('created_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const options = sqliteTable('options', {
	id: text().primaryKey().notNull(),
	questionId: text('question_id').notNull(),
	optionText: text('option_text').notNull(),
	isCorrect: integer('is_correct').default(false).notNull(),
	optionLetter: text('option_letter').notNull(),
	explanation: text(),
	isActive: integer('is_active').default(true).notNull(),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const pastPaperQuestions = sqliteTable('past_paper_questions', {
	id: text().primaryKey().notNull(),
	paperId: text('paper_id'),
	questionText: text('question_text').notNull(),
	answerText: text('answer_text'),
	year: integer().notNull(),
	subject: text().notNull(),
	paper: text(),
	month: text(),
	topic: text(),
	marks: integer(),
	questionNumber: integer('question_number'),
	createdAt: text('created_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const pastPapers = sqliteTable(
	'past_papers',
	{
		id: text().primaryKey().notNull(),
		paperId: text('paper_id').notNull(),
		originalPdfUrl: text('original_pdf_url').notNull(),
		storedPdfUrl: text('stored_pdf_url'),
		markdownFileUrl: text('markdown_file_url'),
		subject: text().notNull(),
		paper: text().notNull(),
		year: integer().notNull(),
		month: text().notNull(),
		isExtracted: integer('is_extracted').default(false).notNull(),
		extractedQuestions: text('extracted_questions'),
		instructions: text(),
		totalMarks: integer('total_marks'),
		createdAt: text('created_at').notNull(),
		updatedAt: text('updated_at').notNull(),
		syncVersion: integer('sync_version').default(1).notNull(),
		lastModifiedAt: text('last_modified_at').notNull(),
		localUpdatedAt: text('local_updated_at').notNull(),
		syncStatus: text('sync_status').default('synced').notNull(),
	},
	(table) => [uniqueIndex('past_papers_paper_id_unique').on(table.paperId)]
);

export const payments = sqliteTable('payments', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	subscriptionId: text('subscription_id'),
	amount: integer().notNull(),
	currency: text().default('ZAR').notNull(),
	status: text().notNull(),
	paystackReference: text('paystack_reference'),
	paystackCustomerCode: text('paystack_customer_code'),
	paymentMethod: text('payment_method'),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const questionAttempts = sqliteTable('question_attempts', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	questionId: text('question_id').notNull(),
	topic: text().notNull(),
	isCorrect: integer('is_correct').notNull(),
	responseTimeMs: integer('response_time_ms'),
	nextReviewAt: text('next_review_at'),
	intervalDays: integer('interval_days').default(1).notNull(),
	easeFactor: text('ease_factor').default('2.5').notNull(),
	attemptedAt: text('attempted_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const questions = sqliteTable('questions', {
	id: text().primaryKey().notNull(),
	subjectId: integer('subject_id').notNull(),
	questionText: text('question_text').notNull(),
	imageUrl: text('image_url'),
	gradeLevel: integer('grade_level').notNull(),
	topic: text().notNull(),
	difficulty: text().default('medium').notNull(),
	marks: integer().default(2).notNull(),
	hint: text(),
	isActive: integer('is_active').default(true).notNull(),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const quizResults = sqliteTable('quiz_results', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	quizId: text('quiz_id').notNull(),
	subjectId: integer('subject_id'),
	topic: text('topic'),
	score: integer().notNull(),
	totalQuestions: integer('total_questions').notNull(),
	percentage: text().notNull(),
	timeTaken: integer('time_taken').notNull(),
	completedAt: text('completed_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const searchHistory = sqliteTable('search_history', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	query: text().notNull(),
	createdAt: text('created_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const sessions = sqliteTable(
	'sessions',
	{
		id: text().primaryKey().notNull(),
		expiresAt: text().notNull(),
		token: text().notNull(),
		createdAt: text().notNull(),
		updatedAt: text().notNull(),
		ipAddress: text(),
		userAgent: text(),
		userId: text().notNull(),
		syncVersion: integer('sync_version').default(1).notNull(),
		lastModifiedAt: text('last_modified_at').notNull(),
		localUpdatedAt: text('local_updated_at').notNull(),
		syncStatus: text('sync_status').default('synced').notNull(),
	},
	(table) => [uniqueIndex('sessions_token_unique').on(table.token)]
);

export const studyBuddies = sqliteTable('study_buddies', {
	id: text().primaryKey().notNull(),
	userId1: text('user_id_1').notNull(),
	userId2: text('user_id_2').notNull(),
	createdAt: text('created_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const studyBuddyProfiles = sqliteTable(
	'study_buddy_profiles',
	{
		id: text().primaryKey().notNull(),
		userId: text('user_id').notNull(),
		bio: text(),
		studyGoals: text('study_goals'),
		preferredSubjects: text('preferred_subjects'),
		studySchedule: text('study_schedule'),
		lookingFor: text('looking_for'),
		isVisible: integer('is_visible').default(true).notNull(),
		matchPreferences: text('match_preferences'),
		personality: text().default('mentor').notNull(),
		createdAt: text('created_at').notNull(),
		updatedAt: text('updated_at').notNull(),
		syncVersion: integer('sync_version').default(1).notNull(),
		lastModifiedAt: text('last_modified_at').notNull(),
		localUpdatedAt: text('local_updated_at').notNull(),
		syncStatus: text('sync_status').default('synced').notNull(),
	},
	(table) => [uniqueIndex('study_buddy_profiles_user_id_unique').on(table.userId)]
);

export const studyBuddyRequests = sqliteTable('study_buddy_requests', {
	id: text().primaryKey().notNull(),
	requesterId: text('requester_id').notNull(),
	recipientId: text('recipient_id').notNull(),
	status: text().default('pending').notNull(),
	message: text(),
	createdAt: text('created_at').notNull(),
	respondedAt: text('responded_at'),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const studyPlans = sqliteTable('study_plans', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	title: text().notNull(),
	targetExamDate: text('target_exam_date'),
	focusAreas: text('focus_areas'),
	weeklyGoals: text('weekly_goals'),
	isActive: integer('is_active').default(true).notNull(),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const studySessions = sqliteTable('study_sessions', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	subjectId: integer('subject_id'),
	sessionType: text('session_type').notNull(),
	topic: text(),
	durationMinutes: integer('duration_minutes'),
	questionsAttempted: integer('questions_attempted').default(0).notNull(),
	correctAnswers: integer('correct_answers').default(0).notNull(),
	marksEarned: integer('marks_earned').default(0).notNull(),
	startedAt: text('started_at').notNull(),
	completedAt: text('completed_at'),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const subjects = sqliteTable(
	'subjects',
	{
		id: integer().primaryKey({ autoIncrement: true }).notNull(),
		name: text().notNull(),
		description: text(),
		curriculumCode: text('curriculum_code').notNull(),
		isActive: integer('is_active').default(true).notNull(),
		createdAt: text('created_at').notNull(),
		updatedAt: text('updated_at').notNull(),
		syncVersion: integer('sync_version').default(1).notNull(),
		lastModifiedAt: text('last_modified_at').notNull(),
		localUpdatedAt: text('local_updated_at').notNull(),
		syncStatus: text('sync_status').default('synced').notNull(),
		slug: text().notNull(),
		displayName: text('display_name').notNull(),
		emoji: text(),
		fluentEmoji: text('fluent_emoji'),
		imgSrc: text('img_src'),
		color: text(),
		bgColor: text('bg_color'),
		icon: text(),
		fontFamily: text('font_family'),
		gradientPrimary: text('gradient_primary'),
		gradientSecondary: text('gradient_secondary'),
		gradientAccent: text('gradient_accent'),
		isSupported: integer('is_supported').default(true).notNull(),
		displayOrder: integer('display_order').default(0).notNull(),
	},
	(table) => [
		uniqueIndex('subjects_slug_unique').on(table.slug),
		uniqueIndex('subjects_name_unique').on(table.name),
	]
);

export const subscriptionPlans = sqliteTable('subscription_plans', {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	description: text(),
	priceZar: text('price_zar').notNull(),
	billingInterval: text('billing_interval').default('monthly').notNull(),
	features: text(),
	isActive: integer('is_active').default(true).notNull(),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const syncLog = sqliteTable('sync_log', {
	id: text().primaryKey().notNull(),
	tableName: text('table_name').notNull(),
	operation: text().notNull(),
	recordId: text('record_id').notNull(),
	timestamp: integer().notNull(),
	direction: text().notNull(),
	status: text().notNull(),
	errorMessage: text('error_message'),
	localVersion: integer('local_version'),
	remoteVersion: integer('remote_version'),
});

export const syncMetadata = sqliteTable('sync_metadata', {
	tableName: text('table_name').primaryKey().notNull(),
	lastSyncTimestamp: integer('last_sync_timestamp'),
	lastSyncVersion: integer('last_sync_version'),
	syncDirection: text('sync_direction'),
	updatedAt: text('updated_at'),
});

export const syncQueue = sqliteTable('sync_queue', {
	id: text().primaryKey().notNull(),
	tableName: text('table_name').notNull(),
	operation: text().notNull(),
	recordId: text('record_id').notNull(),
	data: text().notNull(),
	timestamp: integer().notNull(),
	retryCount: integer('retry_count').default(0).notNull(),
	status: text().default('pending').notNull(),
});

export const topicConfidence = sqliteTable('topic_confidence', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	topic: text().notNull(),
	subject: text().notNull(),
	confidenceScore: text('confidence_score').default('0.5').notNull(),
	timesCorrect: integer('times_correct').default(0).notNull(),
	timesAttempted: integer('times_attempted').default(0).notNull(),
	lastAttemptAt: text('last_attempt_at'),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const topicMastery = sqliteTable('topic_mastery', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	subjectId: integer('subject_id').notNull(),
	topic: text().notNull(),
	masteryLevel: text('mastery_level').default('0').notNull(),
	questionsAttempted: integer('questions_attempted').default(0).notNull(),
	questionsCorrect: integer('questions_correct').default(0).notNull(),
	averageTimeSeconds: integer('average_time_seconds'),
	lastPracticed: text('last_practiced'),
	nextReview: text('next_review'),
	consecutiveCorrect: integer('consecutive_correct').default(0).notNull(),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const topicWeightages = sqliteTable('topic_weightages', {
	id: text().primaryKey().notNull(),
	subject: text().notNull(),
	topic: text().notNull(),
	weightagePercent: integer('weightage_percent').notNull(),
	examPaper: text('exam_paper'),
	lastUpdated: text('last_updated').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const universityTargets = sqliteTable('university_targets', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	universityName: text('university_name').notNull(),
	faculty: text().notNull(),
	targetAps: integer('target_aps').notNull(),
	requiredSubjects: text('required_subjects'),
	recommendedStudyPath: text('recommended_study_path'),
	roadmapGeneratedAt: text('roadmap_generated_at'),
	lastMilestoneId: text('last_milestone_id'),
	isActive: integer('is_active').default(true).notNull(),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const userAchievements = sqliteTable('user_achievements', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	achievementId: text('achievement_id').notNull(),
	title: text().notNull(),
	description: text(),
	icon: text(),
	unlockedAt: text('unlocked_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const userApsScores = sqliteTable('user_aps_scores', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	subject: text().notNull(),
	currentGrade: text('current_grade').notNull(),
	apsPoints: integer('aps_points').notNull(),
	lastAssessmentType: text('last_assessment_type'),
	lastAssessmentScore: integer('last_assessment_score'),
	lastUpdatedAt: text('last_updated_at').notNull(),
	createdAt: text('created_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const userProgress = sqliteTable('user_progress', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	subjectId: integer('subject_id'),
	topic: text(),
	totalQuestionsAttempted: integer('total_questions_attempted').default(0).notNull(),
	totalCorrect: integer('total_correct').default(0).notNull(),
	totalMarksEarned: integer('total_marks_earned').default(0).notNull(),
	streakDays: integer('streak_days').default(0).notNull(),
	bestStreak: integer('best_streak').default(0).notNull(),
	streakFreezes: integer('streak_freezes').default(0).notNull(),
	lastLoginBonusAt: text('last_login_bonus_at'),
	consecutiveLoginDays: integer('consecutive_login_days').default(0).notNull(),
	totalLoginBonusesClaimed: integer('total_login_bonuses_claimed').default(0).notNull(),
	lastActivityAt: text('last_activity_at').notNull(),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const userSettings = sqliteTable('user_settings', {
	userId: text('user_id').primaryKey().notNull(),
	emailNotifications: integer('email_notifications').default(true).notNull(),
	pushNotifications: integer('push_notifications').default(true).notNull(),
	pushSubscription: text('push_subscription'),
	studyReminders: integer('study_reminders').default(true).notNull(),
	achievementAlerts: integer('achievement_alerts').default(true).notNull(),
	whatsappNotifications: integer('whatsapp_notifications').default(false).notNull(),
	profileVisibility: integer('profile_visibility').default(true).notNull(),
	showOnLeaderboard: integer('show_on_leaderboard').default(true).notNull(),
	analyticsTracking: integer('analytics_tracking').default(true).notNull(),
	language: text().default('en').notNull(),
	theme: text().default('system').notNull(),
	curriculum: text().default('NSC').notNull(),
	homeLanguage: text('home_language'),
	preferredLanguage: text('preferred_language').default('en').notNull(),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const userSubscriptions = sqliteTable('user_subscriptions', {
	id: text().primaryKey().notNull(),
	userId: text('user_id').notNull(),
	planId: text('plan_id').notNull(),
	paystackCustomerCode: text('paystack_customer_code'),
	paystackSubscriptionCode: text('paystack_subscription_code'),
	paystackEmailToken: text('paystack_email_token'),
	status: text().default('active').notNull(),
	currentPeriodStart: text('current_period_start').notNull(),
	currentPeriodEnd: text('current_period_end').notNull(),
	cancelAtPeriodEnd: integer('cancel_at_period_end').default(false).notNull(),
	isFreeTrial: integer('is_free_trial').default(false).notNull(),
	trialEndDate: text('trial_end_date'),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});

export const users = sqliteTable(
	'users',
	{
		id: text().primaryKey().notNull(),
		name: text().notNull(),
		email: text().notNull(),
		emailVerified: integer().default(false).notNull(),
		image: text(),
		role: text().default('user').notNull(),
		isBlocked: integer().default(false).notNull(),
		twoFactorEnabled: integer().default(false).notNull(),
		hasCompletedOnboarding: integer('has_completed_onboarding').default(false).notNull(),
		school: text(),
		avatarId: text('avatar_id'),
		deletedAt: text('deleted_at'),
		createdAt: text().notNull(),
		updatedAt: text().notNull(),
		syncVersion: integer('sync_version').default(1).notNull(),
		lastModifiedAt: text('last_modified_at').notNull(),
		localUpdatedAt: text('local_updated_at').notNull(),
		syncStatus: text('sync_status').default('synced').notNull(),
	},
	(table) => [uniqueIndex('users_email_unique').on(table.email)]
);

export const verifications = sqliteTable('verifications', {
	id: text().primaryKey().notNull(),
	identifier: text().notNull(),
	value: text().notNull(),
	expiresAt: text().notNull(),
	createdAt: text('created_at'),
	syncVersion: integer('sync_version').default(1).notNull(),
	lastModifiedAt: text('last_modified_at').notNull(),
	localUpdatedAt: text('local_updated_at').notNull(),
	syncStatus: text('sync_status').default('synced').notNull(),
});
