import { type NextRequest, NextResponse } from 'next/server';
import { isMockDataEnabled } from '@/lib/feature-flags';
import { createMockDataGeneratorV2 } from '@/lib/mock-data/generator-v2';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

/**
 * GET /api/activity/[userId]/timeline
 *
 * Returns the activity timeline for a specific user, generated by MockDataGeneratorV2.
 * This is the data source for all 7 enriched dashboard components:
 *   - ActivityHeatmap
 *   - StreakTracker
 *   - SubjectBreakdown
 *   - AccuracyTrends
 *   - WeakTopicsTable
 *   - CohortComparison
 *   - RecentActivityFeed
 *
 * If mock data is disabled, returns 403.
 */
export async function GET(
	_request: NextRequest,
	{ params }: { params: Promise<{ userId: string }> }
) {
	try {
		if (!isMockDataEnabled()) {
			return NextResponse.json({ error: 'Mock data generation is disabled' }, { status: 403 });
		}

		const { userId } = await params;

		if (!userId) {
			return NextResponse.json({ error: 'Missing userId parameter' }, { status: 400 });
		}

		const seed = hashUserIdToSeed(userId);
		const generator = createMockDataGeneratorV2(undefined, { seed });

		// Generate all data needed for the timeline response
		const timeline = generator.generateActivityTimeline(userId, 6);
		const quizResults = generator.generateQuizResultsForProfile(userId, 6);
		const topicMasteries = generator.generateTopicMastery(userId, 1, 'mathematics');

		// Build heatmap: array of { date, count } from timeline entries
		const heatmap = buildHeatmap(timeline);

		// Build streak data
		const streak = calculateStreak(timeline);

		// Build subject breakdown
		const subjects = buildSubjectBreakdown(timeline);

		// Build accuracy trends
		const accuracyTrends = buildAccuracyTrends(quizResults);

		// Build weak topics
		const weakTopics = buildWeakTopics(topicMasteries);

		// Build cohort comparison
		const cohortComparison = buildCohortComparison(quizResults);

		// Build recent activity (last 20 entries)
		const recentActivity = timeline.slice(0, 20).map((entry) => ({
			id: entry.id,
			type: entry.type,
			date: entry.date.toISOString(),
			subject: entry.subject,
			topic: entry.topic,
			score: entry.score,
			totalQuestions: entry.totalQuestions,
			percentage: entry.percentage,
			durationMinutes: entry.durationMinutes,
			cardsReviewed: entry.cardsReviewed,
			averageRating: entry.averageRating,
			questionsAttempted: entry.questionsAttempted,
			correctAnswers: entry.correctAnswers,
		}));

		return NextResponse.json({
			userId,
			heatmap,
			streak,
			subjects,
			accuracyTrends,
			weakTopics,
			cohortComparison,
			recentActivity,
		});
	} catch (error) {
		return NextResponse.json(
			{
				error: 'Timeline generation failed',
				details: error instanceof Error ? error.message : String(error),
			},
			{ status: 500 }
		);
	}
}

// ============================================================================
// HELPER: Deterministic seed from userId string
// ============================================================================

function hashUserIdToSeed(userId: string): number {
	let hash = 0;
	for (let i = 0; i < userId.length; i++) {
		const char = userId.charCodeAt(i);
		hash = ((hash << 5) - hash + char) | 0;
	}
	return Math.abs(hash);
}

// ============================================================================
// HELPER: Build heatmap from timeline
// ============================================================================

interface HeatmapEntry {
	date: string;
	count: number;
}

function buildHeatmap(
	timeline: ReturnType<ReturnType<typeof createMockDataGeneratorV2>['generateActivityTimeline']>
): HeatmapEntry[] {
	const dateCounts = new Map<string, number>();
	for (const entry of timeline) {
		const dateKey = entry.date.toISOString().split('T')[0];
		dateCounts.set(dateKey, (dateCounts.get(dateKey) ?? 0) + 1);
	}

	return Array.from(dateCounts.entries())
		.map(([date, count]) => ({ date, count }))
		.sort((a, b) => a.date.localeCompare(b.date));
}

// ============================================================================
// HELPER: Calculate streak
// ============================================================================

interface StreakData {
	current: number;
	best: number;
}

function calculateStreak(
	timeline: ReturnType<ReturnType<typeof createMockDataGeneratorV2>['generateActivityTimeline']>
): StreakData {
	const activeDates = new Set(timeline.map((e) => e.date.toISOString().split('T')[0]));
	const today = new Date();
	today.setHours(0, 0, 0, 0);

	// Current streak: count consecutive days backward from today
	let current = 0;
	const checkDate = new Date(today);
	while (activeDates.has(checkDate.toISOString().split('T')[0])) {
		current++;
		checkDate.setDate(checkDate.getDate() - 1);
	}

	// Best streak: longest consecutive run in the data
	const sortedDates = Array.from(activeDates).sort();
	let best = 0;
	let run = 0;
	let prevDate: Date | null = null;

	for (const dateStr of sortedDates) {
		const date = new Date(dateStr);
		if (prevDate) {
			const diffDays = Math.round((date.getTime() - prevDate.getTime()) / (1000 * 60 * 60 * 24));
			if (diffDays === 1) {
				run++;
			} else {
				run = 1;
			}
		} else {
			run = 1;
		}
		best = Math.max(best, run);
		prevDate = date;
	}

	return { current, best: Math.max(best, current) };
}

// ============================================================================
// HELPER: Subject breakdown
// ============================================================================

interface SubjectEntry {
	subject: string;
	count: number;
	averageAccuracy: number;
}

function buildSubjectBreakdown(
	timeline: ReturnType<ReturnType<typeof createMockDataGeneratorV2>['generateActivityTimeline']>
): SubjectEntry[] {
	const subjectMap = new Map<string, { count: number; totalAccuracy: number; quizCount: number }>();

	for (const entry of timeline) {
		if (entry.subject) {
			const existing = subjectMap.get(entry.subject) ?? {
				count: 0,
				totalAccuracy: 0,
				quizCount: 0,
			};
			existing.count++;
			if (entry.percentage !== undefined) {
				existing.totalAccuracy += entry.percentage;
				existing.quizCount++;
			}
			subjectMap.set(entry.subject, existing);
		}
	}

	return Array.from(subjectMap.entries())
		.map(([subject, data]) => ({
			subject,
			count: data.count,
			averageAccuracy:
				data.quizCount > 0 ? Math.round((data.totalAccuracy / data.quizCount) * 10) / 10 : 0,
		}))
		.sort((a, b) => b.count - a.count);
}

// ============================================================================
// HELPER: Accuracy trends (over time)
// ============================================================================

interface AccuracyTrendEntry {
	date: string;
	accuracy: number;
	cumulativeAccuracy: number;
}

function buildAccuracyTrends(
	quizResults: { percentage: number; completedAt: Date }[]
): AccuracyTrendEntry[] {
	const sorted = [...quizResults].sort((a, b) => a.completedAt.getTime() - b.completedAt.getTime());

	let totalScore = 0;
	let totalQuestions = 0;

	return sorted.map((quiz, _index) => {
		totalScore += quiz.percentage;
		totalQuestions++;
		return {
			date: quiz.completedAt.toISOString().split('T')[0],
			accuracy: Math.round(quiz.percentage * 10) / 10,
			cumulativeAccuracy: Math.round((totalScore / totalQuestions) * 10) / 10,
		};
	});
}

// ============================================================================
// HELPER: Weak topics
// ============================================================================

interface WeakTopicEntry {
	topic: string;
	masteryLevel: number;
	questionsAttempted: number;
	accuracy: number;
}

function buildWeakTopics(
	topicMasteries: {
		topic: string;
		masteryLevel: number;
		questionsAttempted: number;
		questionsCorrect: number;
	}[]
): WeakTopicEntry[] {
	return topicMasteries
		.map((m) => ({
			topic: m.topic,
			masteryLevel: Math.round(m.masteryLevel * 10) / 10,
			questionsAttempted: m.questionsAttempted,
			accuracy:
				m.questionsAttempted > 0
					? Math.round((m.questionsCorrect / m.questionsAttempted) * 100 * 10) / 10
					: 0,
		}))
		.sort((a, b) => a.masteryLevel - b.masteryLevel)
		.slice(0, 10);
}

// ============================================================================
// HELPER: Cohort comparison
// ============================================================================

interface CohortComparison {
	userAccuracy: number;
	cohortAverage: number;
	percentile: number;
}

function buildCohortComparison(quizResults: { percentage: number }[]): CohortComparison {
	if (quizResults.length === 0) {
		return { userAccuracy: 0, cohortAverage: 0, percentile: 0 };
	}

	const userAccuracy =
		Math.round((quizResults.reduce((sum, q) => sum + q.percentage, 0) / quizResults.length) * 10) /
		10;

	// Simulate cohort: normal distribution around 60% accuracy
	const cohortAverage = 60;
	const percentile = Math.min(99, Math.max(1, Math.round(((userAccuracy - 30) / 50) * 100)));

	return { userAccuracy, cohortAverage, percentile };
}
