import { and, eq } from 'drizzle-orm';
import { type NextRequest, NextResponse } from 'next/server';
import { getAuth } from '@/lib/auth';
import { refreshAccessToken } from '@/lib/calendar/google';
import { dbManager } from '@/lib/db';
import { calendarConnections, calendarEvents, syncedEvents } from '@/lib/db/schema';

const GOOGLE_CALENDAR_API = 'https://www.googleapis.com/calendar/v3';

type CalendarConnection = {
	refreshTokenEncrypted: string | null;
	accessTokenEncrypted: string | null;
};

async function getValidAccessToken(connection: CalendarConnection | null): Promise<string | null> {
	if (!connection) return null;

	const refreshToken = connection.refreshTokenEncrypted;
	if (!refreshToken) return null;

	const tokens = await refreshAccessToken(refreshToken);
	return tokens?.access_token ?? null;
}

async function pushEventToGoogleCalendar(
	accessToken: string,
	event: {
		id: string;
		title: string;
		startTime: Date;
		endTime: Date;
		description?: string | null;
		location?: string | null;
	}
) {
	const startTime = new Date(event.startTime);
	const endTime = new Date(event.endTime);

	const payload = {
		summary: `📚 ${event.title}`,
		description: event.description || 'Study session generated by MatricMaster AI',
		location: event.location || '',
		start: {
			dateTime: startTime.toISOString(),
			timeZone: 'Africa/Johannesburg',
		},
		end: {
			dateTime: endTime.toISOString(),
			timeZone: 'Africa/Johannesburg',
		},
		reminders: {
			useDefault: false,
			overrides: [
				{ method: 'popup', minutes: 15 },
				{ method: 'email', minutes: 60 },
			],
		},
		colorId: '9',
	};

	const response = await fetch(`${GOOGLE_CALENDAR_API}/calendars/primary/events`, {
		method: 'POST',
		headers: {
			Authorization: `Bearer ${accessToken}`,
			'Content-Type': 'application/json',
		},
		body: JSON.stringify(payload),
	});

	if (!response.ok) {
		const error = await response.text();
		console.error('Failed to push event to Google Calendar:', error);
		throw new Error(`Google Calendar API error: ${response.status}`);
	}

	return response.json();
}

export async function POST(request: NextRequest) {
	try {
		const auth = await getAuth();
		const session = await auth.api.getSession({ headers: request.headers });

		if (!session?.user?.id) {
			return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
		}

		const db = await dbManager.getDb();
		const connection = await db.query.calendarConnections.findFirst({
			where: and(
				eq(calendarConnections.userId, session.user.id),
				eq(calendarConnections.provider, 'google')
			),
		});

		if (!connection) {
			return NextResponse.json({ error: 'No calendar connection found' }, { status: 404 });
		}

		if (!connection.syncEnabled) {
			return NextResponse.json({ error: 'Sync is disabled' }, { status: 400 });
		}

		const accessToken = await getValidAccessToken(connection);

		const isMockMode = !accessToken || connection.refreshTokenEncrypted?.startsWith('mock_');

		const body = await request.json();
		const { eventIds } = body;

		let eventsToSync: Awaited<ReturnType<typeof db.query.calendarEvents.findMany>> = [];
		if (eventIds && eventIds.length > 0) {
			eventsToSync = await db.query.calendarEvents.findMany({
				where: and(
					eq(calendarEvents.userId, session.user.id),
					eq(calendarEvents.isCompleted, false)
				),
			});
		} else {
			eventsToSync = await db.query.calendarEvents.findMany({
				where: and(
					eq(calendarEvents.userId, session.user.id),
					eq(calendarEvents.isCompleted, false)
				),
				orderBy: (events) => [events.startTime],
				limit: 50,
			});
		}

		const existingSyncs = await db.query.syncedEvents.findMany({
			where: eq(syncedEvents.userId, session.user.id),
		});
		const syncedExternalIds = new Set(existingSyncs.map((s) => s.externalEventId));

		const pushedEvents = [];
		const errors: string[] = [];

		for (const event of eventsToSync) {
			const externalId = `mm-${event.id}`;
			if (syncedExternalIds.has(externalId)) continue;

			try {
				if (isMockMode) {
					pushedEvents.push({
						id: event.id,
						title: event.title,
						startTime: event.startTime,
						endTime: event.endTime,
						googleEventId: `mock_${event.id}`,
					});
				} else if (accessToken) {
					const googleEvent = await pushEventToGoogleCalendar(accessToken, {
						id: event.id,
						title: event.title,
						startTime: event.startTime,
						endTime: event.endTime,
						description: event.description,
						location: event.location,
					});
					pushedEvents.push({
						id: event.id,
						title: event.title,
						startTime: event.startTime,
						endTime: event.endTime,
						googleEventId: googleEvent.id,
					});
				}

				await db.insert(syncedEvents).values({
					userId: session.user.id,
					externalEventId: externalId,
					internalEventId: event.id,
					lastSyncedAt: new Date(),
				});
			} catch (err) {
				const errorMessage = err instanceof Error ? err.message : 'Unknown error';
				errors.push(`${event.title}: ${errorMessage}`);
				console.error(`Failed to sync event ${event.id}:`, err);
			}
		}

		if (connection.calendarId) {
			await db
				.update(calendarConnections)
				.set({ lastSyncAt: new Date() })
				.where(eq(calendarConnections.id, connection.id));
		}

		return NextResponse.json({
			success: true,
			data: {
				pushedCount: pushedEvents.length,
				events: pushedEvents,
				errors: errors.length > 0 ? errors : undefined,
				isMockMode,
			},
		});
	} catch (error) {
		console.error('Error pushing events to calendar:', error);
		return NextResponse.json({ error: 'Failed to push events' }, { status: 500 });
	}
}
