export const appConfig = {
	name: 'MatricMaster',
	shortName: 'MatricMaster',
	description:
		"Reach your True Peak. Practice NSC past papers, get expert guidance, and crush your Matric goals.",
	version: {
		current: '1.0.0',
		build: process.env.NEXT_PUBLIC_BUILD_VERSION || 'dev',
		commit: process.env.NEXT_PUBLIC_COMMIT_HASH || 'unknown',
		timestamp: process.env.NEXT_PUBLIC_BUILD_TIMESTAMP || new Date().toISOString(),
	},
	links: {
		website: 'https://matricmaster.co.za',
		support: 'https://matricmaster.co.za/support',
		privacy: 'https://matricmaster.co.za/privacy',
		terms: 'https://matricmaster.co.za/terms',
		feedback: 'https://matricmaster.co.za/feedback',
	},
	contact: {
		email: 'hello@matricmaster.co.za',
		supportEmail: 'support@matricmaster.co.za',
		phone: '+27 21 123 4567',
		whatsapp: '+27 82 123 4567',
		hours: 'Mon-Fri: 9AM-6PM SAST',
	},
	social: {
		facebook: 'https://facebook.com/matricmaster',
		twitter: 'https://twitter.com/matricmaster',
		instagram: 'https://instagram.com/matricmaster',
		youtube: 'https://youtube.com/@matricmaster',
	},
	features: {
		pastPapers: true,
		tutor: true,
		flashcards: true,
		studyPlanner: true,
		progressTracking: true,
		spacedRepetition: true,
	},
	nsc: {
		minAps: 20,
		maxAps: 50,
		defaultTargetAps: 42,
	},
	paths: {
		dashboard: '/dashboard',
		quiz: '/quiz',
		flashcards: '/flashcards',
		pastPapers: '/past-papers',
		curriculumMap: '/curriculum-map',
		tutor: '/tutor',
		snapAndSolve: '/snap-and-solve',
		studyPlan: '/study-plan',
		settings: '/settings',
	},
};
