import { headers } from 'next/headers';
import { type NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { getAuth } from '@/lib/auth';
import { getDb } from '@/lib/db';
import {
	addFlashcardToDeck,
	createFlashcardDeck,
	getUserDecks,
} from '@/lib/db/review-queue-actions';
import { flashcardDecks, questions, subjects } from '@/lib/db/schema';

const generateFlashcardsSchema = z.object({
	questionId: z.string().uuid('Invalid questionId format'),
	explanation: z.string().min(1, 'Explanation is required'),
	quizId: z.string().optional(),
	deckId: z.string().uuid().optional(),
	deckName: z.string().max(200).optional(),
});

async function getQuestionTerm(questionId: string): Promise<{
	questionText: string;
	topic: string;
	subjectId: number | null;
} | null> {
	const db = await getDb();

	const [question] = await db
		.select({
			questionText: questions.questionText,
			topic: questions.topic,
			subjectId: questions.subjectId,
		})
		.from(questions)
		.where(
			// @ts-expect-error - drizzle ORM inference
			questions.id.eq(questionId)
		)
		.limit(1);

	return question || null;
}

async function findOrCreateDeck(
	userId: string,
	subjectId: number | null,
	deckId?: string,
	deckName?: string
): Promise<{ id: string; name: string } | null> {
	const db = await getDb();

	if (deckId) {
		const [existing] = await db
			.select({
				id: flashcardDecks.id,
				name: flashcardDecks.name,
			})
			.from(flashcardDecks)
			.where(
				// @ts-expect-error - drizzle ORM inference
				flashcardDecks.id.eq(deckId)
			)
			.limit(1);

		if (existing?.id) {
			return { id: existing.id as string, name: existing.name as string };
		}
		return null;
	}

	const finalDeckName = deckName || 'Flashcards from Quiz';

	const existingDecks = await getUserDecks(userId);
	const existingDeck = existingDecks.find(
		(d) => d.name && d.name.toLowerCase() === finalDeckName.toLowerCase()
	);

	if (existingDeck?.id && existingDeck.name) {
		return { id: existingDeck.id as string, name: existingDeck.name as string };
	}

	const subjectName = subjectId
		? (
				await db
					.select({ name: subjects.name })
					.from(subjects)
					.where(
						// @ts-expect-error - drizzle ORM inference
						subjects.id.eq(subjectId)
					)
					.limit(1)
			)?.[0]?.name
		: null;

	const result = await createFlashcardDeck(
		userId,
		finalDeckName,
		`Auto-generated flashcards from learning loop: ${subjectName || 'General'}`,
		subjectId ?? undefined
	);

	if (result.success && result.deck?.id && result.deck.name) {
		return { id: result.deck.id, name: result.deck.name };
	}

	return null;
}

export async function POST(request: NextRequest) {
	try {
		const auth = await getAuth();
		const session = await auth.api.getSession({
			headers: await headers(),
		});

		if (!session?.user?.id) {
			return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
		}

		const body = await request.json();
		const validation = generateFlashcardsSchema.safeParse(body);

		if (!validation.success) {
			return NextResponse.json(
				{ error: 'Validation failed', details: validation.error.flatten().fieldErrors },
				{ status: 400 }
			);
		}

		const { questionId, explanation, quizId, deckId, deckName } = validation.data;
		const userId = session.user.id;

		console.debug('[generate-flashcards] Processing:', {
			questionId,
			hasExplanation: !!explanation,
			userId,
		});

		const questionData = await getQuestionTerm(questionId);

		if (!questionData) {
			return NextResponse.json({ error: 'Question not found' }, { status: 404 });
		}

		const deck = await findOrCreateDeck(userId, questionData.subjectId, deckId, deckName);

		if (!deck) {
			return NextResponse.json({ error: 'Failed to create or find deck' }, { status: 500 });
		}

		const term = questionData.topic || questionData.questionText.slice(0, 100);
		const definition = explanation;

		const result = await addFlashcardToDeck(deck.id, term, definition, 'medium');

		if (!result.success || !result.flashcard) {
			return NextResponse.json(
				{ error: result.error || 'Failed to create flashcard' },
				{ status: 500 }
			);
		}

		console.debug('[generate-flashcards] Created flashcard:', result.flashcard.id);

		return NextResponse.json({
			success: true,
			flashcard: {
				id: result.flashcard.id,
				front: term,
				back: definition,
				deckId: deck.id,
				deckName: deck.name,
				autoGeneratedFrom: quizId,
			},
		});
	} catch (error) {
		console.debug('[generate-flashcards] Error:', error);
		return NextResponse.json(
			{ error: error instanceof Error ? error.message : 'Failed to generate flashcard' },
			{ status: 500 }
		);
	}
}
