import { dbManager } from '../index';
import { achievementDefinitions, gamificationConfig, subjectMetadata } from '../schema';

const SUBJECTS_DATA = [
	{
		subjectId: 'mathematics',
		displayName: 'Mathematics',
		emoji: '🧮',
		color: 'text-mathematics',
		bgColor: 'bg-mathematics',
		icon: 'Calculator',
		fluentEmoji: '🧮',
		fontFamily: 'var(--font-noto-sans-math)',
		gradientPrimary: '#667eea',
		gradientSecondary: '#764ba2',
		gradientAccent: '#a855f7',
		isSupported: true,
		displayOrder: 1,
	},
	{
		subjectId: 'physics',
		displayName: 'Physics',
		emoji: '⚛️',
		color: 'text-physics',
		bgColor: 'bg-physics',
		icon: 'Atom',
		fluentEmoji: '⚛️',
		fontFamily: 'var(--font-noto-sans-math)',
		gradientPrimary: '#11998e',
		gradientSecondary: '#38ef7d',
		gradientAccent: '#34d399',
		isSupported: true,
		displayOrder: 2,
	},
	{
		subjectId: 'chemistry',
		displayName: 'Chemistry',
		emoji: '🧪',
		color: 'text-chemistry',
		bgColor: 'bg-chemistry',
		icon: 'FlaskConical',
		fluentEmoji: '🧪',
		fontFamily: 'var(--font-noto-sans-math)',
		gradientPrimary: '#fc4a1a',
		gradientSecondary: '#f7b733',
		gradientAccent: '#fb923c',
		isSupported: true,
		displayOrder: 3,
	},
	{
		subjectId: 'life-sciences',
		displayName: 'Life Sciences',
		emoji: '🧬',
		color: 'text-life-sciences',
		bgColor: 'bg-life-sciences',
		icon: 'Microscope',
		fluentEmoji: '🧬',
		fontFamily: 'var(--font-source-serif4)',
		gradientPrimary: '#56ab2f',
		gradientSecondary: '#a8e063',
		gradientAccent: '#84cc16',
		isSupported: true,
		displayOrder: 4,
	},
	{
		subjectId: 'english',
		displayName: 'English',
		emoji: '📚',
		color: 'text-english',
		bgColor: 'bg-english',
		icon: 'BookOpen',
		fluentEmoji: '📚',
		fontFamily: 'var(--font-literata)',
		gradientPrimary: '#c9d6ff',
		gradientSecondary: '#e2e2e2',
		gradientAccent: '#94a3b8',
		isSupported: true,
		displayOrder: 5,
	},
	{
		subjectId: 'afrikaans',
		displayName: 'Afrikaans',
		emoji: '🌍',
		color: 'text-afrikaans',
		bgColor: 'bg-afrikaans',
		icon: 'BookOpen',
		fluentEmoji: '🌍',
		fontFamily: 'var(--font-literata)',
		gradientPrimary: '#22c55e',
		gradientSecondary: '#16a34a',
		gradientAccent: '#4ade80',
		isSupported: true,
		displayOrder: 6,
	},
	{
		subjectId: 'geography',
		displayName: 'Geography',
		emoji: '🌍',
		color: 'text-geography',
		bgColor: 'bg-geography',
		icon: 'Globe',
		fluentEmoji: '🌍',
		fontFamily: 'var(--font-dm-sans)',
		gradientPrimary: '#8e2de2',
		gradientSecondary: '#4a00e0',
		gradientAccent: '#a855f7',
		isSupported: true,
		displayOrder: 7,
	},
	{
		subjectId: 'history',
		displayName: 'History',
		emoji: '📜',
		color: 'text-history',
		bgColor: 'bg-history',
		icon: 'Scroll',
		fluentEmoji: '📜',
		fontFamily: 'var(--font-crimson-pro)',
		gradientPrimary: '#cb2d3e',
		gradientSecondary: '#ef473a',
		gradientAccent: '#f87171',
		isSupported: true,
		displayOrder: 8,
	},
	{
		subjectId: 'accounting',
		displayName: 'Accounting',
		emoji: '💰',
		color: 'text-accounting',
		bgColor: 'bg-accounting',
		icon: 'Calculator',
		fluentEmoji: '💰',
		fontFamily: 'var(--font-jetbrains-mono)',
		gradientPrimary: '#0f4c75',
		gradientSecondary: '#3282b8',
		gradientAccent: '#60a5fa',
		isSupported: true,
		displayOrder: 9,
	},
	{
		subjectId: 'economics',
		displayName: 'Economics',
		emoji: '📈',
		color: 'text-economics',
		bgColor: 'bg-economics',
		icon: 'ChartLine',
		fluentEmoji: '📈',
		fontFamily: 'var(--font-dm-sans)',
		gradientPrimary: '#f59e0b',
		gradientSecondary: '#d97706',
		gradientAccent: '#fbbf24',
		isSupported: true,
		displayOrder: 10,
	},
	{
		subjectId: 'lo',
		displayName: 'Life Orientation',
		emoji: '💚',
		color: 'text-lo',
		bgColor: 'bg-lo',
		icon: 'Heart',
		fluentEmoji: '💚',
		fontFamily: 'var(--font-dm-sans)',
		gradientPrimary: '#10b981',
		gradientSecondary: '#059669',
		gradientAccent: '#34d399',
		isSupported: true,
		displayOrder: 11,
	},
	{
		subjectId: 'business-studies',
		displayName: 'Business Studies',
		emoji: '💼',
		color: 'text-business-studies',
		bgColor: 'bg-business-studies',
		icon: 'Briefcase',
		fluentEmoji: '💼',
		fontFamily: 'var(--font-dm-sans)',
		gradientPrimary: '#6366f1',
		gradientSecondary: '#4f46e5',
		gradientAccent: '#818cf8',
		isSupported: true,
		displayOrder: 12,
	},
];

const GAMIFICATION_CONFIG = [
	{
		key: 'max_level',
		value: '100',
		description: 'Maximum achievable level',
	},
	{
		key: 'xp_base',
		value: '50',
		description: 'Base XP multiplier (level * level * this)',
	},
	{
		key: 'xp_per_question',
		value: '10',
		description: 'XP earned per correct answer',
	},
	{
		key: 'xp_per_quiz',
		value: '50',
		description: 'XP bonus for completing a quiz',
	},
	{
		key: 'xp_streak_multiplier_base',
		value: '1.25',
		description: 'Base multiplier for streak bonuses',
	},
	{
		key: 'points_per_streak_day',
		value: '5',
		description: 'Bonus points per streak day',
	},
];

const ACHIEVEMENTS_DATA = [
	{
		id: 'first_quiz',
		name: 'First Steps',
		description: 'Complete your first quiz',
		icon: '🎯',
		iconBg: '#e6f7f0',
		category: 'all',
		requirementType: 'quizzes_completed',
		requirementValue: 1,
		points: 10,
		displayOrder: 1,
	},
	{
		id: 'quiz_10',
		name: 'Getting Started',
		description: 'Complete 10 quizzes',
		icon: '📝',
		iconBg: '#f0f4f8',
		category: 'all',
		requirementType: 'quizzes_completed',
		requirementValue: 10,
		points: 50,
		displayOrder: 2,
	},
	{
		id: 'quiz_50',
		name: 'Quiz Enthusiast',
		description: 'Complete 50 quizzes',
		icon: '🧠',
		iconBg: '#fef3c7',
		category: 'all',
		requirementType: 'quizzes_completed',
		requirementValue: 50,
		points: 200,
		displayOrder: 3,
	},
	{
		id: 'quiz_100',
		name: 'Quiz Master',
		description: 'Complete 100 quizzes',
		icon: '🏆',
		iconBg: '#fce4ec',
		category: 'all',
		requirementType: 'quizzes_completed',
		requirementValue: 100,
		points: 500,
		displayOrder: 4,
	},
	{
		id: 'streak_3',
		name: 'Consistent',
		description: 'Maintain a 3-day streak',
		icon: '🔥',
		iconBg: '#fff7ed',
		category: 'streak',
		requirementType: 'streak_days',
		requirementValue: 3,
		points: 30,
		displayOrder: 5,
	},
	{
		id: 'streak_7',
		name: 'Week Warrior',
		description: 'Maintain a 7-day streak',
		icon: '⚡',
		iconBg: '#fef08a',
		category: 'streak',
		requirementType: 'streak_days',
		requirementValue: 7,
		points: 100,
		displayOrder: 6,
	},
	{
		id: 'streak_30',
		name: 'Monthly Champion',
		description: 'Maintain a 30-day streak',
		icon: '🌟',
		iconBg: '#e0e7ff',
		category: 'streak',
		requirementType: 'streak_days',
		requirementValue: 30,
		points: 500,
		displayOrder: 7,
	},
	{
		id: 'streak_100',
		name: 'Unstoppable',
		description: 'Maintain a 100-day streak',
		icon: '💎',
		iconBg: '#cffafe',
		category: 'streak',
		requirementType: 'streak_days',
		requirementValue: 100,
		points: 2000,
		displayOrder: 8,
	},
	{
		id: 'questions_100',
		name: 'Question Answerer',
		description: 'Answer 100 questions',
		icon: '❓',
		iconBg: '#f3e8ff',
		category: 'all',
		requirementType: 'questions_answered',
		requirementValue: 100,
		points: 100,
		displayOrder: 9,
	},
	{
		id: 'questions_500',
		name: 'Question Pro',
		description: 'Answer 500 questions',
		icon: '🎓',
		iconBg: '#ecfeff',
		category: 'all',
		requirementType: 'questions_answered',
		requirementValue: 500,
		points: 400,
		displayOrder: 10,
	},
	{
		id: 'questions_1000',
		name: 'Knowledge Seeker',
		description: 'Answer 1000 questions',
		icon: '📚',
		iconBg: '#ffedd5',
		category: 'all',
		requirementType: 'questions_answered',
		requirementValue: 1000,
		points: 1000,
		displayOrder: 11,
	},
	{
		id: 'perfect_first',
		name: 'Perfect Start',
		description: 'Get your first perfect score',
		icon: '✨',
		iconBg: '#f0fdfa',
		category: 'all',
		requirementType: 'perfect_score',
		requirementValue: 1,
		points: 50,
		displayOrder: 12,
	},
	{
		id: 'perfect_10',
		name: 'Perfectionist',
		description: 'Get 10 perfect scores',
		icon: '💯',
		iconBg: '#faf5ff',
		category: 'all',
		requirementType: 'perfect_score',
		requirementValue: 10,
		points: 300,
		displayOrder: 13,
	},
	{
		id: 'physics_master',
		name: 'Physics Master',
		description: 'Answer 50 Physics questions correctly',
		icon: '⚛️',
		iconBg: '#f0f9ff',
		category: 'science',
		requirementType: 'subject_mastery',
		requirementValue: 50,
		requirementSubjectId: 1,
		points: 200,
		displayOrder: 14,
	},
	{
		id: 'math_master',
		name: 'Math Wizard',
		description: 'Answer 50 Mathematics questions correctly',
		icon: '🔢',
		iconBg: '#fef3c7',
		category: 'math',
		requirementType: 'subject_mastery',
		requirementValue: 50,
		requirementSubjectId: 2,
		points: 200,
		displayOrder: 15,
	},
	{
		id: 'bookmark_5',
		name: 'Saver',
		description: 'Save 5 bookmarks',
		icon: '🔖',
		iconBg: '#fef2f2',
		category: 'all',
		requirementType: 'bookmarks',
		requirementValue: 5,
		points: 25,
		displayOrder: 16,
	},
	{
		id: 'bookmark_25',
		name: 'Collector',
		description: 'Save 25 bookmarks',
		icon: '📌',
		iconBg: '#f0fdf4',
		category: 'all',
		requirementType: 'bookmarks',
		requirementValue: 25,
		points: 100,
		displayOrder: 17,
	},
	{
		id: 'study_10h',
		name: 'Dedicated Student',
		description: 'Study for 10 hours total',
		icon: '⏰',
		iconBg: '#f5f3ff',
		category: 'all',
		requirementType: 'time_spent',
		requirementValue: 600,
		points: 200,
		displayOrder: 18,
	},
	{
		id: 'study_50h',
		name: 'Scholar',
		description: 'Study for 50 hours total',
		icon: '📖',
		iconBg: '#fff7ed',
		category: 'all',
		requirementType: 'time_spent',
		requirementValue: 3000,
		points: 1000,
		displayOrder: 19,
	},
];

export async function seedCurriculumData() {
	const db = await dbManager.getDb();

	console.log('Seeding subject metadata...');
	for (const subject of SUBJECTS_DATA) {
		await db.insert(subjectMetadata).values(subject).onConflictDoUpdate({
			target: subjectMetadata.subjectId,
			set: subject,
		});
	}
	console.log(`Seeded ${SUBJECTS_DATA.length} subjects`);

	console.log('Seeding gamification config...');
	for (const config of GAMIFICATION_CONFIG) {
		await db.insert(gamificationConfig).values(config).onConflictDoUpdate({
			target: gamificationConfig.key,
			set: config,
		});
	}
	console.log(`Seeded ${GAMIFICATION_CONFIG.length} gamification configs`);

	console.log('Seeding achievement definitions...');
	for (const achievement of ACHIEVEMENTS_DATA) {
		await db.insert(achievementDefinitions).values(achievement).onConflictDoUpdate({
			target: achievementDefinitions.id,
			set: achievement,
		});
	}
	console.log(`Seeded ${ACHIEVEMENTS_DATA.length} achievements`);

	console.log('✅ Curriculum data seeding complete');
}
