export const pastPapersDataExtended = [
	// ============================================================================
	// MATHEMATICS 2021-2023 ADDITIONAL PAPERS
	// ============================================================================
	// June Papers (Mid-year)
	{
		paperId: 'math-p2-2021-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/214396',
		subject: 'Mathematics',
		paper: 'P2',
		year: 2021,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2021 Mathematics Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'math-p1-2020-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/194541',
		subject: 'Mathematics',
		paper: 'P1',
		year: 2020,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2020 Mathematics Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'math-p2-2020-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/194551',
		subject: 'Mathematics',
		paper: 'P2',
		year: 2020,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2020 Mathematics Paper 2',
		isExtracted: false,
	},

	// ============================================================================
	// PHYSICAL SCIENCES 2021-2025 - ADDING MISSING P2 PAPERS
	// ============================================================================
	// 2025
	{
		paperId: 'phys-p1-2025-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/257156',
		subject: 'Physical Sciences',
		paper: 'P1',
		year: 2025,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2025 Physical Sciences Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'phys-p2-2025-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/257166',
		subject: 'Physical Sciences',
		paper: 'P2',
		year: 2025,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions. Periodic table provided.',
		summary: 'NSC May/June 2025 Physical Sciences Paper 2',
		isExtracted: false,
	},
	// 2024
	{
		paperId: 'phys-p2-2024-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/256176',
		subject: 'Physical Sciences',
		paper: 'P2',
		year: 2024,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2024 Physical Sciences Paper 2',
		isExtracted: false,
	},
	// 2023
	{
		paperId: 'phys-p1-2023-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/235641',
		subject: 'Physical Sciences',
		paper: 'P1',
		year: 2023,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2023 Physical Sciences Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'phys-p2-2023-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/235651',
		subject: 'Physical Sciences',
		paper: 'P2',
		year: 2023,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2023 Physical Sciences Paper 2',
		isExtracted: false,
	},
	// 2022
	{
		paperId: 'phys-p2-2022-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/224771',
		subject: 'Physical Sciences',
		paper: 'P2',
		year: 2022,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2022 Physical Sciences Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'phys-p1-2022-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/220681',
		subject: 'Physical Sciences',
		paper: 'P1',
		year: 2022,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2022 Physical Sciences Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'phys-p2-2022-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/220691',
		subject: 'Physical Sciences',
		paper: 'P2',
		year: 2022,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2022 Physical Sciences Paper 2',
		isExtracted: false,
	},
	// 2021 - CRITICAL MISSING
	{
		paperId: 'phys-p2-2021-nov',
		originalPdfUrl: 'https://www.wcedeportal.co.za/eresource/212516',
		subject: 'Physical Sciences',
		paper: 'P2',
		year: 2021,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions. Periodic table provided.',
		summary: 'NSC November 2021 Physical Sciences Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'phys-p1-2021-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/207611',
		subject: 'Physical Sciences',
		paper: 'P1',
		year: 2021,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2021 Physical Sciences Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'phys-p2-2021-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/207621',
		subject: 'Physical Sciences',
		paper: 'P2',
		year: 2021,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2021 Physical Sciences Paper 2',
		isExtracted: false,
	},
	// 2020
	{
		paperId: 'phys-p2-2020-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/194731',
		subject: 'Physical Sciences',
		paper: 'P2',
		year: 2020,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2020 Physical Sciences Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'phys-p1-2020-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/194741',
		subject: 'Physical Sciences',
		paper: 'P1',
		year: 2020,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2020 Physical Sciences Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'phys-p2-2020-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/194751',
		subject: 'Physical Sciences',
		paper: 'P2',
		year: 2020,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2020 Physical Sciences Paper 2',
		isExtracted: false,
	},

	// ============================================================================
	// LIFE SCIENCES 2020-2025 - ADDING MISSING PAPERS
	// ============================================================================
	// 2025
	{
		paperId: 'life-p1-2025-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/257276',
		subject: 'Life Sciences',
		paper: 'P1',
		year: 2025,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2025 Life Sciences Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'life-p2-2025-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/257286',
		subject: 'Life Sciences',
		paper: 'P2',
		year: 2025,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2025 Life Sciences Paper 2',
		isExtracted: false,
	},
	// 2024
	{
		paperId: 'life-p2-2024-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/256236',
		subject: 'Life Sciences',
		paper: 'P2',
		year: 2024,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2024 Life Sciences Paper 2',
		isExtracted: false,
	},
	// 2023
	{
		paperId: 'life-p1-2023-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/235821',
		subject: 'Life Sciences',
		paper: 'P1',
		year: 2023,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2023 Life Sciences Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'life-p2-2023-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/235831',
		subject: 'Life Sciences',
		paper: 'P2',
		year: 2023,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2023 Life Sciences Paper 2',
		isExtracted: false,
	},
	// 2022
	{
		paperId: 'life-p2-2022-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/224991',
		subject: 'Life Sciences',
		paper: 'P2',
		year: 2022,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2022 Life Sciences Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'life-p1-2022-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/221081',
		subject: 'Life Sciences',
		paper: 'P1',
		year: 2022,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2022 Life Sciences Paper 1',
		isExtracted: false,
	},
	// 2021 - MISSING P2
	{
		paperId: 'life-p2-2021-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/210281',
		subject: 'Life Sciences',
		paper: 'P2',
		year: 2021,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2021 Life Sciences Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'life-p1-2021-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/207831',
		subject: 'Life Sciences',
		paper: 'P1',
		year: 2021,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2021 Life Sciences Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'life-p2-2021-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/207841',
		subject: 'Life Sciences',
		paper: 'P2',
		year: 2021,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2021 Life Sciences Paper 2',
		isExtracted: false,
	},
	// 2020
	{
		paperId: 'life-p2-2020-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/194931',
		subject: 'Life Sciences',
		paper: 'P2',
		year: 2020,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2020 Life Sciences Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'life-p1-2020-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/194941',
		subject: 'Life Sciences',
		paper: 'P1',
		year: 2020,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2020 Life Sciences Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'life-p2-2020-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/194951',
		subject: 'Life Sciences',
		paper: 'P2',
		year: 2020,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2020 Life Sciences Paper 2',
		isExtracted: false,
	},

	// ============================================================================
	// ACCOUNTING 2020-2025 - ADDING MISSING P2 PAPERS
	// ============================================================================
	// 2025
	{
		paperId: 'acc-p1-2025-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/257116',
		subject: 'Accounting',
		paper: 'P1',
		year: 2025,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2025 Accounting Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'acc-p2-2025-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/257126',
		subject: 'Accounting',
		paper: 'P2',
		year: 2025,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2025 Accounting Paper 2',
		isExtracted: false,
	},
	// 2024
	{
		paperId: 'acc-p2-2024-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/255821',
		subject: 'Accounting',
		paper: 'P2',
		year: 2024,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2024 Accounting Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'acc-p2-2024-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/262956',
		subject: 'Accounting',
		paper: 'P2',
		year: 2024,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2024 Accounting Paper 2',
		isExtracted: false,
	},
	// 2023
	{
		paperId: 'acc-p1-2023-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/235481',
		subject: 'Accounting',
		paper: 'P1',
		year: 2023,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2023 Accounting Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'acc-p2-2023-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/235491',
		subject: 'Accounting',
		paper: 'P2',
		year: 2023,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2023 Accounting Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'acc-p2-2023-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/248041',
		subject: 'Accounting',
		paper: 'P2',
		year: 2023,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2023 Accounting Paper 2',
		isExtracted: false,
	},
	// 2022 - MISSING P2
	{
		paperId: 'acc-p2-2022-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/225431',
		subject: 'Accounting',
		paper: 'P2',
		year: 2022,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2022 Accounting Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'acc-p1-2022-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/220731',
		subject: 'Accounting',
		paper: 'P1',
		year: 2022,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2022 Accounting Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'acc-p2-2022-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/220741',
		subject: 'Accounting',
		paper: 'P2',
		year: 2022,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2022 Accounting Paper 2',
		isExtracted: false,
	},
	// 2021 - MISSING P2
	{
		paperId: 'acc-p2-2021-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/210741',
		subject: 'Accounting',
		paper: 'P2',
		year: 2021,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2021 Accounting Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'acc-p1-2021-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/207931',
		subject: 'Accounting',
		paper: 'P1',
		year: 2021,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2021 Accounting Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'acc-p2-2021-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/207941',
		subject: 'Accounting',
		paper: 'P2',
		year: 2021,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2021 Accounting Paper 2',
		isExtracted: false,
	},
	// 2020 - MISSING P2
	{
		paperId: 'acc-p2-2020-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/195341',
		subject: 'Accounting',
		paper: 'P2',
		year: 2020,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2020 Accounting Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'acc-p1-2020-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/195351',
		subject: 'Accounting',
		paper: 'P1',
		year: 2020,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2020 Accounting Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'acc-p2-2020-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/195361',
		subject: 'Accounting',
		paper: 'P2',
		year: 2020,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2020 Accounting Paper 2',
		isExtracted: false,
	},

	// ============================================================================
	// GEOGRAPHY 2020-2025 - ADDING MISSING PAPERS
	// ============================================================================
	// 2025
	{
		paperId: 'geog-p1-2025-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/257336',
		subject: 'Geography',
		paper: 'P1',
		year: 2025,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2025 Geography Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'geog-p2-2025-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/257346',
		subject: 'Geography',
		paper: 'P2',
		year: 2025,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions. Topographic maps provided.',
		summary: 'NSC May/June 2025 Geography Paper 2',
		isExtracted: false,
	},
	// 2024
	{
		paperId: 'geog-p2-2024-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/255991',
		subject: 'Geography',
		paper: 'P2',
		year: 2024,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2024 Geography Paper 2',
		isExtracted: false,
	},
	// 2023
	{
		paperId: 'geog-p1-2023-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/235661',
		subject: 'Geography',
		paper: 'P1',
		year: 2023,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2023 Geography Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'geog-p2-2023-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/235671',
		subject: 'Geography',
		paper: 'P2',
		year: 2023,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2023 Geography Paper 2',
		isExtracted: false,
	},
	// 2022
	{
		paperId: 'geog-p2-2022-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/225731',
		subject: 'Geography',
		paper: 'P2',
		year: 2022,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2022 Geography Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'geog-p1-2022-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/221521',
		subject: 'Geography',
		paper: 'P1',
		year: 2022,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2022 Geography Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'geog-p2-2022-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/221531',
		subject: 'Geography',
		paper: 'P2',
		year: 2022,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2022 Geography Paper 2',
		isExtracted: false,
	},
	// 2021 - MISSING P2
	{
		paperId: 'geog-p2-2021-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/211051',
		subject: 'Geography',
		paper: 'P2',
		year: 2021,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2021 Geography Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'geog-p1-2021-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/208231',
		subject: 'Geography',
		paper: 'P1',
		year: 2021,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2021 Geography Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'geog-p2-2021-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/208241',
		subject: 'Geography',
		paper: 'P2',
		year: 2021,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2021 Geography Paper 2',
		isExtracted: false,
	},
	// 2020 - MISSING P2
	{
		paperId: 'geog-p2-2020-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/195641',
		subject: 'Geography',
		paper: 'P2',
		year: 2020,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2020 Geography Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'geog-p1-2020-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/195651',
		subject: 'Geography',
		paper: 'P1',
		year: 2020,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2020 Geography Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'geog-p2-2020-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/195661',
		subject: 'Geography',
		paper: 'P2',
		year: 2020,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2020 Geography Paper 2',
		isExtracted: false,
	},

	// ============================================================================
	// ENGLISH HOME LANGUAGE 2020-2025 - ADDING MISSING PAPERS
	// ============================================================================
	// 2025
	{
		paperId: 'eng-hl-p2-2025-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/267241',
		subject: 'English Home Language',
		paper: 'P2',
		year: 2025,
		month: 'June',
		totalMarks: 100,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2025 English Home Language Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'eng-hl-p3-2025-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/267251',
		subject: 'English Home Language',
		paper: 'P3',
		year: 2025,
		month: 'June',
		totalMarks: 70,
		instructions: 'Answer the essay and contextual questions.',
		summary: 'NSC May/June 2025 English Home Language Paper 3',
		isExtracted: false,
	},
	// 2024
	{
		paperId: 'eng-hl-p2-2024-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/263041',
		subject: 'English Home Language',
		paper: 'P2',
		year: 2024,
		month: 'June',
		totalMarks: 100,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2024 English Home Language Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'eng-hl-p3-2024-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/263051',
		subject: 'English Home Language',
		paper: 'P3',
		year: 2024,
		month: 'June',
		totalMarks: 70,
		instructions: 'Answer the essay and contextual questions.',
		summary: 'NSC May/June 2024 English Home Language Paper 3',
		isExtracted: false,
	},
	// 2023
	{
		paperId: 'eng-hl-p2-2023-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/248361',
		subject: 'English Home Language',
		paper: 'P2',
		year: 2023,
		month: 'November',
		totalMarks: 100,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2023 English Home Language Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'eng-hl-p1-2023-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/235751',
		subject: 'English Home Language',
		paper: 'P1',
		year: 2023,
		month: 'June',
		totalMarks: 80,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2023 English Home Language Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'eng-hl-p2-2023-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/235761',
		subject: 'English Home Language',
		paper: 'P2',
		year: 2023,
		month: 'June',
		totalMarks: 100,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2023 English Home Language Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'eng-hl-p3-2023-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/235771',
		subject: 'English Home Language',
		paper: 'P3',
		year: 2023,
		month: 'June',
		totalMarks: 70,
		instructions: 'Answer the essay and contextual questions.',
		summary: 'NSC May/June 2023 English Home Language Paper 3',
		isExtracted: false,
	},
	// 2022
	{
		paperId: 'eng-hl-p2-2022-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/225941',
		subject: 'English Home Language',
		paper: 'P2',
		year: 2022,
		month: 'November',
		totalMarks: 100,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2022 English Home Language Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'eng-hl-p3-2022-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/225951',
		subject: 'English Home Language',
		paper: 'P3',
		year: 2022,
		month: 'November',
		totalMarks: 70,
		instructions: 'Answer the essay and contextual questions.',
		summary: 'NSC November 2022 English Home Language Paper 3',
		isExtracted: false,
	},
	{
		paperId: 'eng-hl-p1-2022-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/220931',
		subject: 'English Home Language',
		paper: 'P1',
		year: 2022,
		month: 'June',
		totalMarks: 80,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2022 English Home Language Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'eng-hl-p2-2022-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/220941',
		subject: 'English Home Language',
		paper: 'P2',
		year: 2022,
		month: 'June',
		totalMarks: 100,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2022 English Home Language Paper 2',
		isExtracted: false,
	},
	// 2021 - MISSING P2, P3
	{
		paperId: 'eng-hl-p2-2021-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/211251',
		subject: 'English Home Language',
		paper: 'P2',
		year: 2021,
		month: 'November',
		totalMarks: 100,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2021 English Home Language Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'eng-hl-p3-2021-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/211261',
		subject: 'English Home Language',
		paper: 'P3',
		year: 2021,
		month: 'November',
		totalMarks: 70,
		instructions: 'Answer the essay and contextual questions.',
		summary: 'NSC November 2021 English Home Language Paper 3',
		isExtracted: false,
	},
	{
		paperId: 'eng-hl-p1-2021-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/208331',
		subject: 'English Home Language',
		paper: 'P1',
		year: 2021,
		month: 'June',
		totalMarks: 80,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2021 English Home Language Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'eng-hl-p2-2021-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/208341',
		subject: 'English Home Language',
		paper: 'P2',
		year: 2021,
		month: 'June',
		totalMarks: 100,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2021 English Home Language Paper 2',
		isExtracted: false,
	},
	// 2020 - MISSING P2, P3
	{
		paperId: 'eng-hl-p2-2020-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/195841',
		subject: 'English Home Language',
		paper: 'P2',
		year: 2020,
		month: 'November',
		totalMarks: 100,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2020 English Home Language Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'eng-hl-p3-2020-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/195851',
		subject: 'English Home Language',
		paper: 'P3',
		year: 2020,
		month: 'November',
		totalMarks: 70,
		instructions: 'Answer the essay and contextual questions.',
		summary: 'NSC November 2020 English Home Language Paper 3',
		isExtracted: false,
	},

	// ============================================================================
	// ECONOMICS 2020-2025 - ADDING MISSING PAPERS
	// ============================================================================
	// 2025
	{
		paperId: 'econ-p1-2025-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/267331',
		subject: 'Economics',
		paper: 'P1',
		year: 2025,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2025 Economics Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'econ-p2-2025-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/267341',
		subject: 'Economics',
		paper: 'P2',
		year: 2025,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2025 Economics Paper 2',
		isExtracted: false,
	},
	// 2024
	{
		paperId: 'econ-p2-2024-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/263111',
		subject: 'Economics',
		paper: 'P2',
		year: 2024,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2024 Economics Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'econ-p2-2024-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/263101',
		subject: 'Economics',
		paper: 'P2',
		year: 2024,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2024 Economics Paper 2',
		isExtracted: false,
	},
	// 2023
	{
		paperId: 'econ-p1-2023-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/235871',
		subject: 'Economics',
		paper: 'P1',
		year: 2023,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2023 Economics Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'econ-p2-2023-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/235881',
		subject: 'Economics',
		paper: 'P2',
		year: 2023,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2023 Economics Paper 2',
		isExtracted: false,
	},
	// 2022 - MISSING P2
	{
		paperId: 'econ-p2-2022-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/226141',
		subject: 'Economics',
		paper: 'P2',
		year: 2022,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2022 Economics Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'econ-p1-2022-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/221831',
		subject: 'Economics',
		paper: 'P1',
		year: 2022,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2022 Economics Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'econ-p2-2022-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/221841',
		subject: 'Economics',
		paper: 'P2',
		year: 2022,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2022 Economics Paper 2',
		isExtracted: false,
	},
	// 2021 - MISSING P2
	{
		paperId: 'econ-p2-2021-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/211451',
		subject: 'Economics',
		paper: 'P2',
		year: 2021,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2021 Economics Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'econ-p1-2021-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/208531',
		subject: 'Economics',
		paper: 'P1',
		year: 2021,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2021 Economics Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'econ-p2-2021-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/208541',
		subject: 'Economics',
		paper: 'P2',
		year: 2021,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2021 Economics Paper 2',
		isExtracted: false,
	},
	// 2020 - MISSING P2
	{
		paperId: 'econ-p2-2020-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/196041',
		subject: 'Economics',
		paper: 'P2',
		year: 2020,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2020 Economics Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'econ-p1-2020-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/196051',
		subject: 'Economics',
		paper: 'P1',
		year: 2020,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2020 Economics Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'econ-p2-2020-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/196061',
		subject: 'Economics',
		paper: 'P2',
		year: 2020,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2020 Economics Paper 2',
		isExtracted: false,
	},

	// ============================================================================
	// BUSINESS STUDIES 2020-2025 - ADDING MISSING PAPERS
	// ============================================================================
	// 2025
	{
		paperId: 'bus-p1-2025-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/267421',
		subject: 'Business Studies',
		paper: 'P1',
		year: 2025,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2025 Business Studies Paper 1',
		isExtracted: false,
	},
	// 2024
	{
		paperId: 'bus-p1-2024-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/263201',
		subject: 'Business Studies',
		paper: 'P1',
		year: 2024,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2024 Business Studies Paper 1',
		isExtracted: false,
	},
	// 2023
	{
		paperId: 'bus-p1-2023-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/248671',
		subject: 'Business Studies',
		paper: 'P1',
		year: 2023,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2023 Business Studies Paper 1',
		isExtracted: false,
	},
	// 2022
	{
		paperId: 'bus-p1-2022-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/226341',
		subject: 'Business Studies',
		paper: 'P1',
		year: 2022,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2022 Business Studies Paper 1',
		isExtracted: false,
	},
	// 2021
	{
		paperId: 'bus-p1-2021-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/208831',
		subject: 'Business Studies',
		paper: 'P1',
		year: 2021,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2021 Business Studies Paper 1',
		isExtracted: false,
	},
	// 2020
	{
		paperId: 'bus-p1-2020-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/196241',
		subject: 'Business Studies',
		paper: 'P1',
		year: 2020,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2020 Business Studies Paper 1',
		isExtracted: false,
	},

	// ============================================================================
	// HISTORY 2020-2025 - ADDING MISSING PAPERS
	// ============================================================================
	// 2025
	{
		paperId: 'hist-p2-2025-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/267531',
		subject: 'History',
		paper: 'P2',
		year: 2025,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2025 History Paper 2',
		isExtracted: false,
	},
	// 2024
	{
		paperId: 'hist-p2-2024-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/263301',
		subject: 'History',
		paper: 'P2',
		year: 2024,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2024 History Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'hist-p1-2024-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/263311',
		subject: 'History',
		paper: 'P1',
		year: 2024,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2024 History Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'hist-p2-2024-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/263321',
		subject: 'History',
		paper: 'P2',
		year: 2024,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2024 History Paper 2',
		isExtracted: false,
	},
	// 2023
	{
		paperId: 'hist-p2-2023-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/248761',
		subject: 'History',
		paper: 'P2',
		year: 2023,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2023 History Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'hist-p1-2023-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/235961',
		subject: 'History',
		paper: 'P1',
		year: 2023,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2023 History Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'hist-p2-2023-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/235971',
		subject: 'History',
		paper: 'P2',
		year: 2023,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2023 History Paper 2',
		isExtracted: false,
	},
	// 2022 - MISSING P2
	{
		paperId: 'hist-p2-2022-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/226541',
		subject: 'History',
		paper: 'P2',
		year: 2022,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2022 History Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'hist-p1-2022-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/222131',
		subject: 'History',
		paper: 'P1',
		year: 2022,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2022 History Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'hist-p2-2022-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/222141',
		subject: 'History',
		paper: 'P2',
		year: 2022,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2022 History Paper 2',
		isExtracted: false,
	},
	// 2021 - MISSING P2
	{
		paperId: 'hist-p2-2021-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/211851',
		subject: 'History',
		paper: 'P2',
		year: 2021,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2021 History Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'hist-p1-2021-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/209131',
		subject: 'History',
		paper: 'P1',
		year: 2021,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2021 History Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'hist-p2-2021-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/209141',
		subject: 'History',
		paper: 'P2',
		year: 2021,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2021 History Paper 2',
		isExtracted: false,
	},
	// 2020 - MISSING P2
	{
		paperId: 'hist-p2-2020-nov',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/196441',
		subject: 'History',
		paper: 'P2',
		year: 2020,
		month: 'November',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC November 2020 History Paper 2',
		isExtracted: false,
	},
	{
		paperId: 'hist-p1-2020-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/196451',
		subject: 'History',
		paper: 'P1',
		year: 2020,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2020 History Paper 1',
		isExtracted: false,
	},
	{
		paperId: 'hist-p2-2020-june',
		originalPdfUrl: 'https://wcedeportal.co.za/eresource/196461',
		subject: 'History',
		paper: 'P2',
		year: 2020,
		month: 'June',
		totalMarks: 150,
		instructions: 'Answer all questions.',
		summary: 'NSC May/June 2020 History Paper 2',
		isExtracted: false,
	},
] as const;

export type PastPaperDataExtended = (typeof pastPapersDataExtended)[number];
