import { type ElementDetail, generateProperties } from './metadata';

export const GROUP_3_4_ELEMENTS: Record<number, ElementDetail> = {
	21: {
		num: 21,
		sym: 'Sc',
		name: 'Scandium',
		mass: '44.96',
		group: 'transition',
		category: 'Transition Metal',
		description: 'Scandium is a lightweight transition metal used in aerospace alloys.',
		discovery: 'Lars Fredrik Nilson, 1879',
		uses: ['Aerospace alloys', 'Sports equipment', 'Lighting', 'Lasers'],
		electronConfig: '[Ar] 3d¹ 4s²',
		electronegativity: 1.36,
		density: '2.989 g/cm³',
		meltingPoint: '1541°C',
		boilingPoint: '2830°C',
		oxidationStates: '+3',
		period: 4,
		groupNumber: 3,
		atomicRadius: 184,
		ionizationEnergy: 633,
		practiceQuestions: [
			{
				question: 'Scandium is used to make lightweight alloys for what industry?',
				options: ['Automotive', 'Aerospace', 'Construction', 'Electronics'],
				answer: 1,
			},
			{
				question: 'What is scandium in the periodic table?',
				options: ['Alkali metal', 'Transition metal', 'Halogen', 'Noble gas'],
				answer: 1,
			},
		],
		properties: generateProperties(
			21,
			'44.96',
			4,
			3,
			'[Ar] 3d¹ 4s²',
			1.36,
			'2.989 g/cm³',
			'1541°C',
			'2830°C',
			'+3'
		),
	},
	22: {
		num: 22,
		sym: 'Ti',
		name: 'Titanium',
		mass: '47.87',
		group: 'transition',
		category: 'Transition Metal',
		description: 'Titanium is known for its high strength-to-weight ratio.',
		discovery: 'William Gregor, 1791',
		uses: ['Aerospace', 'Medical implants', 'Sporting goods', 'Jewelry'],
		electronConfig: '[Ar] 3d² 4s²',
		electronegativity: 1.54,
		density: '4.54 g/cm³',
		meltingPoint: '1668°C',
		boilingPoint: '3287°C',
		oxidationStates: '+2, +3, +4',
		period: 4,
		groupNumber: 4,
		atomicRadius: 176,
		ionizationEnergy: 659,
		practiceQuestions: [
			{
				question: 'Titanium is known for what property?',
				options: [
					'Low density and high strength',
					'Low melting point',
					'Brittleness',
					'Poor corrosion resistance',
				],
				answer: 0,
			},
			{
				question: 'What is the most common oxidation state of titanium?',
				options: ['+2', '+3', '+4', '+1'],
				answer: 2,
			},
		],
		properties: generateProperties(
			22,
			'47.87',
			4,
			4,
			'[Ar] 3d² 4s²',
			1.54,
			'4.54 g/cm³',
			'1668°C',
			'3287°C',
			'+2, +3, +4'
		),
	},
	23: {
		num: 23,
		sym: 'V',
		name: 'Vanadium',
		mass: '50.94',
		group: 'transition',
		category: 'Transition Metal',
		description: 'Vanadium is used to make strong steel alloys.',
		discovery: 'Andrés Manuel del Río, 1801',
		uses: ['Steel alloys', 'Batteries (vanadium redox)', 'Tools', 'Springs'],
		electronConfig: '[Ar] 3d³ 4s²',
		electronegativity: 1.63,
		density: '6.11 g/cm³',
		meltingPoint: '1910°C',
		boilingPoint: '3407°C',
		oxidationStates: '+2, +3, +4, +5',
		period: 4,
		groupNumber: 5,
		atomicRadius: 171,
		ionizationEnergy: 651,
		practiceQuestions: [
			{
				question: 'Vanadium is primarily used to produce what?',
				options: ['Copper wires', 'Strong steel', 'Aluminum foil', 'Plastic containers'],
				answer: 1,
			},
			{
				question: 'How many valence electrons does vanadium have?',
				options: ['2', '3', '5', '7'],
				answer: 2,
			},
		],
		properties: generateProperties(
			23,
			'50.94',
			4,
			5,
			'[Ar] 3d³ 4s²',
			1.63,
			'6.11 g/cm³',
			'1910°C',
			'3407°C',
			'+2, +3, +4, +5'
		),
	},
	24: {
		num: 24,
		sym: 'Cr',
		name: 'Chromium',
		mass: '52.00',
		group: 'transition',
		category: 'Transition Metal',
		description: 'Chromium is known for its shiny appearance and corrosion resistance.',
		discovery: 'Louis Nicolas Vauquelin, 1797',
		uses: ['Stainless steel', 'Chrome plating', 'Dyes and pigments', 'Leather tanning'],
		electronConfig: '[Ar] 3d⁵ 4s¹',
		electronegativity: 1.66,
		density: '7.15 g/cm³',
		meltingPoint: '1907°C',
		boilingPoint: '2671°C',
		oxidationStates: '+2, +3, +6',
		period: 4,
		groupNumber: 6,
		atomicRadius: 166,
		ionizationEnergy: 653,
		practiceQuestions: [
			{
				question: 'What gives stainless steel its corrosion resistance?',
				options: ['Iron', 'Chromium', 'Nickel', 'Carbon'],
				answer: 1,
			},
			{
				question: 'Chromium gets its name from what Greek word?',
				options: ['Chrome', 'Color', 'Crystal', 'Chrome'],
				answer: 1,
			},
		],
		properties: generateProperties(
			24,
			'52.00',
			4,
			6,
			'[Ar] 3d⁵ 4s¹',
			1.66,
			'7.15 g/cm³',
			'1907°C',
			'2671°C',
			'+2, +3, +6'
		),
	},
	25: {
		num: 25,
		sym: 'Mn',
		name: 'Manganese',
		mass: '54.94',
		group: 'transition',
		category: 'Transition Metal',
		description: 'Manganese is essential for steel production and batteries.',
		discovery: 'Carl Wilhelm Scheele, 1774',
		uses: ['Steel production', 'Batteries', 'Aluminum alloys', 'Glass decolorizer'],
		electronConfig: '[Ar] 3d⁵ 4s²',
		electronegativity: 1.55,
		density: '7.44 g/cm³',
		meltingPoint: '1246°C',
		boilingPoint: '2061°C',
		oxidationStates: '+2, +3, +4, +6, +7',
		period: 4,
		groupNumber: 7,
		atomicRadius: 161,
		ionizationEnergy: 717,
		practiceQuestions: [
			{
				question: 'Manganese is essential in the production of what?',
				options: ['Copper', 'Steel', 'Aluminum', 'Gold'],
				answer: 1,
			},
			{
				question: 'What type of battery commonly uses manganese?',
				options: ['Lead-acid', 'Lithium-ion', 'Alkaline', 'Nickel-cadmium'],
				answer: 2,
			},
		],
		properties: generateProperties(
			25,
			'54.94',
			4,
			7,
			'[Ar] 3d⁵ 4s²',
			1.55,
			'7.44 g/cm³',
			'1246°C',
			'2061°C',
			'+2, +3, +4, +6, +7'
		),
	},
	39: {
		num: 39,
		sym: 'Y',
		name: 'Yttrium',
		mass: '88.91',
		group: 'transition',
		category: 'Transition Metal',
		description: 'Yttrium is used in LEDs and superconductors.',
		discovery: 'Johan Gadolin, 1794',
		uses: ['LEDs', 'Superconductors', 'Lasers', 'Cancer treatment'],
		electronConfig: '[Kr] 4d¹ 5s²',
		electronegativity: 1.22,
		density: '4.469 g/cm³',
		meltingPoint: '1522°C',
		boilingPoint: '3345°C',
		oxidationStates: '+3',
		period: 5,
		groupNumber: 3,
		atomicRadius: 212,
		ionizationEnergy: 600,
		practiceQuestions: [
			{
				question: 'Yttrium is used in what type of lighting?',
				options: ['Incandescent bulbs', 'LEDs', 'Neon signs', 'Halogen lamps'],
				answer: 1,
			},
			{
				question: 'Yttrium is found in which mineral group?',
				options: ['Sulfides', 'Oxides', 'Silicates', 'Phosphates'],
				answer: 1,
			},
		],
		properties: generateProperties(
			39,
			'88.91',
			5,
			3,
			'[Kr] 4d¹ 5s²',
			1.22,
			'4.469 g/cm³',
			'1522°C',
			'3345°C',
			'+3'
		),
	},
	40: {
		num: 40,
		sym: 'Zr',
		name: 'Zirconium',
		mass: '91.22',
		group: 'transition',
		category: 'Transition Metal',
		description: 'Zirconium is highly resistant to corrosion.',
		discovery: 'Martin Heinrich Klaproth, 1789',
		uses: ['Nuclear reactors', 'Ceramics', 'Dental implants', 'Aerospace'],
		electronConfig: '[Kr] 4d² 5s²',
		electronegativity: 1.33,
		density: '6.506 g/cm³',
		meltingPoint: '1855°C',
		boilingPoint: '4409°C',
		oxidationStates: '+4',
		period: 5,
		groupNumber: 4,
		atomicRadius: 206,
		ionizationEnergy: 640,
		practiceQuestions: [
			{
				question: 'Zirconium is used in nuclear reactors because it:',
				options: ['Absorbs neutrons', 'Does not absorb neutrons', 'Is radioactive', 'Is toxic'],
				answer: 1,
			},
			{
				question: 'What is the most common compound of zirconium?',
				options: [
					'Zirconium chloride',
					'Zirconium oxide',
					'Zirconium nitrate',
					'Zirconium sulfate',
				],
				answer: 1,
			},
		],
		properties: generateProperties(
			40,
			'91.22',
			5,
			4,
			'[Kr] 4d² 5s²',
			1.33,
			'6.506 g/cm³',
			'1855°C',
			'4409°C',
			'+4'
		),
	},
	41: {
		num: 41,
		sym: 'Nb',
		name: 'Niobium',
		mass: '92.91',
		group: 'transition',
		category: 'Transition Metal',
		description: 'Niobium is used in superconducting magnets and alloys.',
		discovery: 'Charles Hatchett, 1801',
		uses: ['Superconducting magnets', 'Steel alloys', 'Jewelry', 'Nuclear reactors'],
		electronConfig: '[Kr] 4d⁴ 5s¹',
		electronegativity: 1.6,
		density: '8.57 g/cm³',
		meltingPoint: '2477°C',
		boilingPoint: '4744°C',
		oxidationStates: '+3, +5',
		period: 5,
		groupNumber: 5,
		atomicRadius: 198,
		ionizationEnergy: 652,
		practiceQuestions: [
			{
				question: 'Niobium is commonly used in what technology?',
				options: ['Solar panels', 'Superconducting magnets', 'Fuel cells', 'LEDs'],
				answer: 1,
			},
			{
				question: 'What was niobium originally called?',
				options: ['Columbium', 'Tantalum', 'Titanium', 'Vanadium'],
				answer: 0,
			},
		],
		properties: generateProperties(
			41,
			'92.91',
			5,
			5,
			'[Kr] 4d⁴ 5s¹',
			1.6,
			'8.57 g/cm³',
			'2477°C',
			'4744°C',
			'+3, +5'
		),
	},
	42: {
		num: 42,
		sym: 'Mo',
		name: 'Molybdenum',
		mass: '95.95',
		group: 'transition',
		category: 'Transition Metal',
		description: 'Molybdenum has one of the highest melting points.',
		discovery: 'Carl Wilhelm Scheele, 1778',
		uses: ['Steel alloys', 'Catalysts', 'Lubricants', 'Electronics'],
		electronConfig: '[Kr] 4d⁵ 5s¹',
		electronegativity: 2.16,
		density: '10.22 g/cm³',
		meltingPoint: '2623°C',
		boilingPoint: '4639°C',
		oxidationStates: '+4, +6',
		period: 5,
		groupNumber: 6,
		atomicRadius: 190,
		ionizationEnergy: 684,
		practiceQuestions: [
			{
				question: 'Molybdenum is essential for which enzyme?',
				options: ['Amylase', 'Nitrate reductase', 'Lipase', 'Protease'],
				answer: 1,
			},
			{
				question: 'What is molybdenum in the periodic table?',
				options: ['Alkali metal', 'Transition metal', 'Metalloid', 'Nonmetal'],
				answer: 1,
			},
		],
		properties: generateProperties(
			42,
			'95.95',
			5,
			6,
			'[Kr] 4d⁵ 5s¹',
			2.16,
			'10.22 g/cm³',
			'2623°C',
			'4639°C',
			'+4, +6'
		),
	},
	43: {
		num: 43,
		sym: 'Tc',
		name: 'Technetium',
		mass: '98.00',
		group: 'transition',
		category: 'Transition Metal',
		description: 'Technetium was the first artificially produced element.',
		discovery: 'Emilio Segrè & Carlo Perrier, 1937',
		uses: ['Medical imaging', 'Nuclear medicine', 'Research'],
		electronConfig: '[Kr] 4d⁵ 5s²',
		electronegativity: 1.9,
		density: '11.5 g/cm³',
		meltingPoint: '2157°C',
		boilingPoint: '4265°C',
		oxidationStates: '+4, +7',
		period: 5,
		groupNumber: 7,
		atomicRadius: 183,
		ionizationEnergy: 702,
		practiceQuestions: [
			{
				question: 'Technetium is used in medicine for what purpose?',
				options: ['Cancer treatment', 'Medical imaging', 'Sterilization', 'Drug synthesis'],
				answer: 1,
			},
			{
				question: 'What makes technetium unique among elements 1-92?',
				options: ['Most radioactive', 'First synthetic element', 'Most expensive', 'Rarest'],
				answer: 1,
			},
		],
		properties: generateProperties(
			43,
			'98.00',
			5,
			7,
			'[Kr] 4d⁵ 5s²',
			1.9,
			'11.5 g/cm³',
			'2157°C',
			'4265°C',
			'+4, +7'
		),
	},
};
