import { type ElementDetail, generateProperties } from './metadata';

export const GROUP_1_2_ELEMENTS: Record<number, ElementDetail> = {
	1: {
		num: 1,
		sym: 'H',
		name: 'Hydrogen',
		mass: '1.008',
		group: 'nonmetal',
		category: 'Diatomic Nonmetal',
		description: 'Hydrogen is the lightest and most abundant element in the universe.',
		discovery: 'Henry Cavendish, 1766',
		uses: ['Ammonia production (fertilizers)', 'Rocket fuel', 'Fuel cells', 'Petroleum refining'],
		electronConfig: '1s¹',
		electronegativity: 2.2,
		density: '0.00009 g/cm³',
		meltingPoint: '-259.14°C',
		boilingPoint: '-252.87°C',
		oxidationStates: '-1, +1',
		period: 1,
		groupNumber: 1,
		atomicRadius: 53,
		ionizationEnergy: 1312,
		practiceQuestions: [
			{
				question: 'Hydrogen is the lightest element. What is its atomic number?',
				options: ['1', '2', '0', '3'],
				answer: 0,
			},
			{
				question: 'Which type of bond does hydrogen form with non-metals?',
				options: ['Ionic', 'Covalent', 'Metallic', 'Hydrogen'],
				answer: 1,
			},
			{
				question: 'In the Haber process, hydrogen is combined with what to make ammonia?',
				options: ['Oxygen', 'Nitrogen', 'Carbon', 'Sulfur'],
				answer: 1,
			},
			{
				question: 'What is the electron configuration of hydrogen?',
				options: ['1s¹', '1s²', '2s¹', '1s² 2s¹'],
				answer: 0,
			},
		],
		properties: generateProperties(
			1,
			'1.008',
			1,
			1,
			'1s¹',
			2.2,
			'0.00009 g/cm³',
			'-259.14°C',
			'-252.87°C',
			'-1, +1'
		),
	},
	2: {
		num: 2,
		sym: 'He',
		name: 'Helium',
		mass: '4.003',
		group: 'noble',
		category: 'Noble Gas',
		description: 'Helium is a colorless, odorless, inert noble gas.',
		discovery: 'Jules Janssen & Norman Lockyer, 1868',
		uses: ['Cryogenics (MRI magnets)', 'Balloons', 'Deep-sea diving', 'Welding'],
		electronConfig: '1s²',
		electronegativity: null,
		density: '0.00018 g/cm³',
		meltingPoint: '-272.2°C',
		boilingPoint: '-268.9°C',
		oxidationStates: '0',
		period: 1,
		groupNumber: 18,
		atomicRadius: 31,
		ionizationEnergy: 2372,
		practiceQuestions: [
			{
				question: 'Helium is a noble gas. What is its electron configuration?',
				options: ['1s¹', '1s²', '2s¹', '2s²'],
				answer: 1,
			},
			{
				question: 'Why is helium used in balloons instead of hydrogen?',
				options: ['Cheaper', 'Non-flammable', 'Heavier', 'Rarer'],
				answer: 1,
			},
			{
				question: 'Which group are helium and neon in?',
				options: ['1', '2', '17', '18'],
				answer: 3,
			},
		],
		properties: generateProperties(
			2,
			'4.003',
			1,
			18,
			'1s²',
			null,
			'0.00018 g/cm³',
			'-272.2°C',
			'-268.9°C',
			'0'
		),
	},
	3: {
		num: 3,
		sym: 'Li',
		name: 'Lithium',
		mass: '6.94',
		group: 'alkali',
		category: 'Alkali Metal',
		description: 'Lithium is the lightest metal. Reacts vigorously with water.',
		discovery: 'Johan August Arfwedson, 1817',
		uses: ['Lithium-ion batteries', 'Psychiatric medication', 'Lubricating greases', 'Ceramics'],
		electronConfig: '[He] 2s¹',
		electronegativity: 0.98,
		density: '0.534 g/cm³',
		meltingPoint: '180.54°C',
		boilingPoint: '1342°C',
		oxidationStates: '+1',
		period: 2,
		groupNumber: 1,
		atomicRadius: 167,
		ionizationEnergy: 520,
		practiceQuestions: [
			{
				question: 'Lithium reacts vigorously with water. What happens?',
				options: ['Sinks quietly', 'Floats and fizzes', 'Explodes immediately', 'Dissolves'],
				answer: 1,
			},
			{
				question: 'What ion does lithium form?',
				options: ['Li²⁺', 'Li⁺', 'Li⁻', 'Li⁰'],
				answer: 1,
			},
			{
				question: 'Lithium is used in batteries. What type?',
				options: ['Lead-acid', 'Lithium-ion', 'Nickel-cadmium', 'Fuel cells'],
				answer: 1,
			},
		],
		properties: generateProperties(
			3,
			'6.94',
			2,
			1,
			'[He] 2s¹',
			0.98,
			'0.534 g/cm³',
			'180.54°C',
			'1342°C',
			'+1'
		),
	},
	4: {
		num: 4,
		sym: 'Be',
		name: 'Beryllium',
		mass: '9.012',
		group: 'alkaline',
		category: 'Alkaline Earth Metal',
		description: 'Beryllium is a steel-gray, lightweight metal.',
		discovery: 'Louis Nicolas Vauquelin, 1798',
		uses: ['Aerospace components', 'X-ray windows', 'Nuclear reactors', 'Gyroscopes'],
		electronConfig: '[He] 2s²',
		electronegativity: 1.57,
		density: '1.85 g/cm³',
		meltingPoint: '1287°C',
		boilingPoint: '2469°C',
		oxidationStates: '+2',
		period: 2,
		groupNumber: 2,
		atomicRadius: 112,
		ionizationEnergy: 900,
		practiceQuestions: [
			{
				question: 'Beryllium is in Group 2. What charge does its ion have?',
				options: ['+1', '+2', '+3', '0'],
				answer: 1,
			},
			{
				question: 'What is the electron configuration of beryllium?',
				options: ['1s²', '1s² 2s¹', '1s² 2s²', '1s² 2p¹'],
				answer: 2,
			},
		],
		properties: generateProperties(
			4,
			'9.012',
			2,
			2,
			'[He] 2s²',
			1.57,
			'1.85 g/cm³',
			'1287°C',
			'2469°C',
			'+2'
		),
	},
	11: {
		num: 11,
		sym: 'Na',
		name: 'Sodium',
		mass: '22.990',
		group: 'alkali',
		category: 'Alkali Metal',
		description: 'Sodium is a soft, silvery-white, highly reactive metal.',
		discovery: 'Humphry Davy, 1807',
		uses: ['Table salt (NaCl)', 'Street lights', 'Soaps', 'Chemical manufacturing'],
		electronConfig: '[Ne] 3s¹',
		electronegativity: 0.93,
		density: '0.971 g/cm³',
		meltingPoint: '97.72°C',
		boilingPoint: '883°C',
		oxidationStates: '+1',
		period: 3,
		groupNumber: 1,
		atomicRadius: 190,
		ionizationEnergy: 496,
		practiceQuestions: [
			{
				question: 'What happens when sodium reacts with water?',
				options: ['Sinks', 'Floats and fizzes', 'Turns blue', 'Explodes silently'],
				answer: 1,
			},
			{
				question: 'What is the formula for table salt?',
				options: ['NaO', 'NaCl', 'Na₂O', 'NaOH'],
				answer: 1,
			},
			{ question: 'What ion does sodium form?', options: ['Na⁺', 'Na²⁺', 'Na⁻', 'Na⁰'], answer: 0 },
		],
		properties: generateProperties(
			11,
			'22.990',
			3,
			1,
			'[Ne] 3s¹',
			0.93,
			'0.971 g/cm³',
			'97.72°C',
			'883°C',
			'+1'
		),
	},
	12: {
		num: 12,
		sym: 'Mg',
		name: 'Magnesium',
		mass: '24.305',
		group: 'alkaline',
		category: 'Alkaline Earth Metal',
		description: 'Magnesium burns with a bright white flame.',
		discovery: 'Humphry Davy, 1808',
		uses: ['Lightweight alloys', 'Fireworks', 'Medicine', 'Steel desulfurization'],
		electronConfig: '[Ne] 3s²',
		electronegativity: 1.31,
		density: '1.738 g/cm³',
		meltingPoint: '650°C',
		boilingPoint: '1090°C',
		oxidationStates: '+2',
		period: 3,
		groupNumber: 2,
		atomicRadius: 145,
		ionizationEnergy: 738,
		practiceQuestions: [
			{
				question: 'Magnesium burns with what color flame?',
				options: ['Red', 'Blue', 'White', 'Green'],
				answer: 2,
			},
			{
				question: 'Magnesium is in Group 2. What charge?',
				options: ['+1', '+2', '+3', '0'],
				answer: 1,
			},
		],
		properties: generateProperties(
			12,
			'24.305',
			3,
			2,
			'[Ne] 3s²',
			1.31,
			'1.738 g/cm³',
			'650°C',
			'1090°C',
			'+2'
		),
	},
	19: {
		num: 19,
		sym: 'K',
		name: 'Potassium',
		mass: '39.098',
		group: 'alkali',
		category: 'Alkali Metal',
		description: 'Potassium is essential for nerve function and muscle contraction.',
		discovery: 'Humphry Davy, 1807',
		uses: ['Fertilizers', 'Soap', 'Glass making', 'Explosives'],
		electronConfig: '[Ar] 4s¹',
		electronegativity: 0.82,
		density: '0.862 g/cm³',
		meltingPoint: '63.38°C',
		boilingPoint: '759°C',
		oxidationStates: '+1',
		period: 4,
		groupNumber: 1,
		atomicRadius: 243,
		ionizationEnergy: 419,
		practiceQuestions: [
			{
				question: 'What color flame does potassium produce?',
				options: ['Red', 'Blue', 'Purple/Violet', 'Green'],
				answer: 2,
			},
			{
				question: 'When potassium reacts with water it:',
				options: ['Sinks quietly', 'Floats and fizzes', 'Turns blue', 'Explodes'],
				answer: 1,
			},
		],
		properties: generateProperties(
			19,
			'39.098',
			4,
			1,
			'[Ar] 4s¹',
			0.82,
			'0.862 g/cm³',
			'63.38°C',
			'759°C',
			'+1'
		),
	},
	20: {
		num: 20,
		sym: 'Ca',
		name: 'Calcium',
		mass: '40.078',
		group: 'alkaline',
		category: 'Alkaline Earth Metal',
		description: 'Calcium is essential for bones and teeth.',
		discovery: 'Humphry Davy, 1808',
		uses: ['Cement', 'Steel making', 'Cheese', 'Supplements'],
		electronConfig: '[Ar] 4s²',
		electronegativity: 1.0,
		density: '1.54 g/cm³',
		meltingPoint: '842°C',
		boilingPoint: '1484°C',
		oxidationStates: '+2',
		period: 4,
		groupNumber: 2,
		atomicRadius: 194,
		ionizationEnergy: 590,
		practiceQuestions: [
			{
				question: 'What is calcium carbonate formula?',
				options: ['CaO', 'CaCO₃', 'Ca(OH)₂', 'CaCl₂'],
				answer: 1,
			},
			{
				question: 'Calcium belongs to which group?',
				options: ['Alkali', 'Alkaline earth', 'Transition', 'Halogens'],
				answer: 1,
			},
		],
		properties: generateProperties(
			20,
			'40.078',
			4,
			2,
			'[Ar] 4s²',
			1.0,
			'1.54 g/cm³',
			'842°C',
			'1484°C',
			'+2'
		),
	},
	37: {
		num: 37,
		sym: 'Rb',
		name: 'Rubidium',
		mass: '85.47',
		group: 'alkali',
		category: 'Alkali Metal',
		description: 'Rubidium is a soft, silvery-white metallic element.',
		discovery: 'Robert Bunsen & Gustav Kirchhoff, 1861',
		uses: ['Atomic clocks', 'Photocells', 'Research', 'Fireworks (purple)'],
		electronConfig: '[Kr] 5s¹',
		electronegativity: 0.82,
		density: '1.532 g/cm³',
		meltingPoint: '39.31°C',
		boilingPoint: '688°C',
		oxidationStates: '+1',
		period: 5,
		groupNumber: 1,
		atomicRadius: 265,
		ionizationEnergy: 403,
		practiceQuestions: [
			{
				question: 'Rubidium is in which group?',
				options: ['Alkali metals', 'Alkaline earth metals', 'Halogens', 'Noble gases'],
				answer: 0,
			},
			{
				question: 'What happens when rubidium reacts with water?',
				options: ['Sinks quietly', 'Explodes immediately', 'Floats and fizzes', 'No reaction'],
				answer: 1,
			},
		],
		properties: generateProperties(
			37,
			'85.47',
			5,
			1,
			'[Kr] 5s¹',
			0.82,
			'1.532 g/cm³',
			'39.31°C',
			'688°C',
			'+1'
		),
	},
	38: {
		num: 38,
		sym: 'Sr',
		name: 'Strontium',
		mass: '87.62',
		group: 'alkaline',
		category: 'Alkaline Earth Metal',
		description: 'Strontium produces a brilliant red flame in fireworks.',
		discovery: 'William Cruickshank, 1787',
		uses: ['Fireworks (red)', 'Flares', 'Glow paints', 'Toothpaste for sensitive teeth'],
		electronConfig: '[Kr] 5s²',
		electronegativity: 0.95,
		density: '2.64 g/cm³',
		meltingPoint: '777°C',
		boilingPoint: '1382°C',
		oxidationStates: '+2',
		period: 5,
		groupNumber: 2,
		atomicRadius: 219,
		ionizationEnergy: 550,
		practiceQuestions: [
			{
				question: 'What color flame does strontium produce?',
				options: ['Green', 'Blue', 'Red', 'Yellow'],
				answer: 2,
			},
			{
				question: 'Strontium is in Group 2. What charge does it form?',
				options: ['+1', '+2', '+3', '+4'],
				answer: 1,
			},
		],
		properties: generateProperties(
			38,
			'87.62',
			5,
			2,
			'[Kr] 5s²',
			0.95,
			'2.64 g/cm³',
			'777°C',
			'1382°C',
			'+2'
		),
	},
	55: {
		num: 55,
		sym: 'Cs',
		name: 'Caesium',
		mass: '132.91',
		group: 'alkali',
		category: 'Alkali Metal',
		description: 'Caesium is the most electropositive stable element.',
		discovery: 'Robert Bunsen & Gustav Kirchhoff, 1860',
		uses: ['Atomic clocks', 'Drilling fluids', 'Photoelectric cells', 'Ion propulsion systems'],
		electronConfig: '[Xe] 6s¹',
		electronegativity: 0.79,
		density: '1.873 g/cm³',
		meltingPoint: '28.44°C',
		boilingPoint: '671°C',
		oxidationStates: '+1',
		period: 6,
		groupNumber: 1,
		atomicRadius: 298,
		ionizationEnergy: 376,
		practiceQuestions: [
			{
				question: 'Caesium is used in what precision instrument?',
				options: ['Thermometer', 'Barometer', 'Atomic clock', 'Galvanometer'],
				answer: 2,
			},
			{
				question: 'How many valence electrons does caesium have?',
				options: ['1', '2', '8', '18'],
				answer: 0,
			},
		],
		properties: generateProperties(
			55,
			'132.91',
			6,
			1,
			'[Xe] 6s¹',
			0.79,
			'1.873 g/cm³',
			'28.44°C',
			'671°C',
			'+1'
		),
	},
	56: {
		num: 56,
		sym: 'Ba',
		name: 'Barium',
		mass: '137.33',
		group: 'alkaline',
		category: 'Alkaline Earth Metal',
		description: 'Barium produces a green flame and is used in medical imaging.',
		discovery: 'Carl Wilhelm Scheele, 1772',
		uses: [
			'Medical imaging (barium swallow)',
			'Fireworks (green)',
			'Drilling fluids',
			'Glass making',
		],
		electronConfig: '[Xe] 6s²',
		electronegativity: 0.89,
		density: '3.594 g/cm³',
		meltingPoint: '727°C',
		boilingPoint: '1870°C',
		oxidationStates: '+2',
		period: 6,
		groupNumber: 2,
		atomicRadius: 253,
		ionizationEnergy: 503,
		practiceQuestions: [
			{
				question: 'What color flame does barium produce?',
				options: ['Red', 'Blue', 'Green', 'Yellow'],
				answer: 2,
			},
			{
				question: 'Barium sulfate is used in medicine for what procedure?',
				options: ['X-ray of stomach', 'Blood test', 'MRI scan', 'Ultrasound'],
				answer: 0,
			},
		],
		properties: generateProperties(
			56,
			'137.33',
			6,
			2,
			'[Xe] 6s²',
			0.89,
			'3.594 g/cm³',
			'727°C',
			'1870°C',
			'+2'
		),
	},
	87: {
		num: 87,
		sym: 'Fr',
		name: 'Francium',
		mass: '223.0',
		group: 'alkali',
		category: 'Alkali Metal',
		description: 'Francium is the most unstable naturally occurring element.',
		discovery: 'Marguerite Perey, 1939',
		uses: ['Research purposes only'],
		electronConfig: '[Rn] 7s¹',
		electronegativity: 0.7,
		density: '1.87 g/cm³',
		meltingPoint: '27°C',
		boilingPoint: '677°C',
		oxidationStates: '+1',
		period: 7,
		groupNumber: 1,
		atomicRadius: 348,
		ionizationEnergy: 380,
		practiceQuestions: [
			{
				question: 'Francium is the most reactive of which group?',
				options: ['Noble gases', 'Alkali metals', 'Halogens', 'Alkaline earth metals'],
				answer: 1,
			},
			{
				question: 'Why is francium rarely used?',
				options: [
					'Too expensive',
					'Highly radioactive and unstable',
					'Not found in nature',
					'Toxic',
				],
				answer: 1,
			},
		],
		properties: generateProperties(
			87,
			'223.0',
			7,
			1,
			'[Rn] 7s¹',
			0.7,
			'1.87 g/cm³',
			'27°C',
			'677°C',
			'+1'
		),
	},
	88: {
		num: 88,
		sym: 'Ra',
		name: 'Radium',
		mass: '226.0',
		group: 'alkaline',
		category: 'Alkaline Earth Metal',
		description: 'Radium is a radioactive alkaline earth metal that glows.',
		discovery: 'Marie & Pierre Curie, 1898',
		uses: ['Cancer treatment (historical)', 'Luminescent paints (historical)', 'Research'],
		electronConfig: '[Rn] 7s²',
		electronegativity: 0.9,
		density: '5.5 g/cm³',
		meltingPoint: '696°C',
		boilingPoint: '1500°C',
		oxidationStates: '+2',
		period: 7,
		groupNumber: 2,
		atomicRadius: 283,
		ionizationEnergy: 509,
		practiceQuestions: [
			{
				question: 'Radium glows due to what property?',
				options: ['Phosphorescence', 'Radioactivity', 'Chemiluminescence', 'Fluorescence'],
				answer: 1,
			},
			{
				question: 'Who discovered radium?',
				options: ['Marie & Pierre Curie', 'Henry Becquerel', 'Ernest Rutherford', 'Niels Bohr'],
				answer: 0,
			},
		],
		properties: generateProperties(
			88,
			'226.0',
			7,
			2,
			'[Rn] 7s²',
			0.9,
			'5.5 g/cm³',
			'696°C',
			'1500°C',
			'+2'
		),
	},
};
