import { type ElementDetail, generateProperties } from './metadata';

export const NONMETALS_ELEMENTS: Record<number, ElementDetail> = {
	5: {
		num: 5,
		sym: 'B',
		name: 'Boron',
		mass: '10.81',
		group: 'metalloid',
		category: 'Metalloid',
		description: 'Boron is a metalloid essential to plant growth.',
		discovery: 'Gay-Lussac & Thénard, 1808',
		uses: ['Glass & ceramics', 'Detergents', 'Semiconductors', 'Nuclear control rods'],
		electronConfig: '[He] 2s² 2p¹',
		electronegativity: 2.04,
		density: '2.34 g/cm³',
		meltingPoint: '2076°C',
		boilingPoint: '3927°C',
		oxidationStates: '+3',
		period: 2,
		groupNumber: 13,
		atomicRadius: 87,
		ionizationEnergy: 801,
		practiceQuestions: [
			{
				question: 'Boron is classified as what?',
				options: ['Metal', 'Non-metal', 'Metalloid', 'Gas'],
				answer: 2,
			},
			{
				question: 'What type of oxide does boron form?',
				options: ['Basic', 'Acidic', 'Amphoteric', 'Neutral'],
				answer: 1,
			},
		],
		properties: generateProperties(
			5,
			'10.81',
			2,
			13,
			'[He] 2s² 2p¹',
			2.04,
			'2.34 g/cm³',
			'2076°C',
			'3927°C',
			'+3'
		),
	},
	6: {
		num: 6,
		sym: 'C',
		name: 'Carbon',
		mass: '12.011',
		group: 'nonmetal',
		category: 'Polyatomic Nonmetal',
		description: 'Carbon is the basis of all known life.',
		discovery: 'Known since ancient times',
		uses: ['Steel production', 'Fuels', 'Plastics', 'Diamonds', 'Graphite'],
		electronConfig: '[He] 2s² 2p²',
		electronegativity: 2.55,
		density: '2.267 g/cm³',
		meltingPoint: '3550°C',
		boilingPoint: '4027°C',
		oxidationStates: '-4, +4',
		period: 2,
		groupNumber: 14,
		atomicRadius: 67,
		ionizationEnergy: 1086,
		practiceQuestions: [
			{
				question: 'Which is NOT an allotrope of carbon?',
				options: ['Diamond', 'Graphite', 'Fullerene', 'Quartz'],
				answer: 3,
			},
			{
				question: 'How many covalent bonds can carbon form?',
				options: ['2', '3', '4', '6'],
				answer: 2,
			},
			{
				question: 'Carbon is the basis of what type of chemistry?',
				options: ['Inorganic', 'Organic', 'Physical', 'Analytical'],
				answer: 1,
			},
		],
		properties: generateProperties(
			6,
			'12.011',
			2,
			14,
			'[He] 2s² 2p²',
			2.55,
			'2.267 g/cm³',
			'3550°C',
			'4027°C',
			'-4, +4'
		),
	},
	7: {
		num: 7,
		sym: 'N',
		name: 'Nitrogen',
		mass: '14.007',
		group: 'nonmetal',
		category: 'Diatomic Nonmetal',
		description: "Nitrogen makes up 78% of Earth's atmosphere.",
		discovery: 'Daniel Rutherford, 1772',
		uses: ['Ammonia (fertilizers)', 'Explosives', 'Food preservation', 'Cryogenics'],
		electronConfig: '[He] 2s² 2p³',
		electronegativity: 3.04,
		density: '0.00125 g/cm³',
		meltingPoint: '-210°C',
		boilingPoint: '-195.79°C',
		oxidationStates: '-3, +3, +5',
		period: 2,
		groupNumber: 15,
		atomicRadius: 56,
		ionizationEnergy: 1402,
		practiceQuestions: [
			{
				question: "What percentage of Earth's atmosphere is nitrogen?",
				options: ['21%', '78%', '1%', '50%'],
				answer: 1,
			},
			{
				question: 'Which process converts atmospheric nitrogen to ammonia?',
				options: ['Electrolysis', 'Haber-Bosch', 'Fractional distillation', 'Photosynthesis'],
				answer: 1,
			},
			{
				question: 'Nitrogen is essential for what in living things?',
				options: ['Bones', 'DNA/RNA', 'Muscles', 'Skin'],
				answer: 1,
			},
		],
		properties: generateProperties(
			7,
			'14.007',
			2,
			15,
			'[He] 2s² 2p³',
			3.04,
			'0.00125 g/cm³',
			'-210°C',
			'-195.79°C',
			'-3, +3, +5'
		),
	},
	8: {
		num: 8,
		sym: 'O',
		name: 'Oxygen',
		mass: '15.999',
		group: 'nonmetal',
		category: 'Diatomic Nonmetal',
		description: 'Oxygen is essential for respiration and combustion.',
		discovery: 'Carl Wilhelm Scheele & Joseph Priestley, 1770s',
		uses: ['Respiration', 'Steel production', 'Water treatment', 'Medical therapy'],
		electronConfig: '[He] 2s² 2p⁴',
		electronegativity: 3.44,
		density: '0.00143 g/cm³',
		meltingPoint: '-218.79°C',
		boilingPoint: '-182.95°C',
		oxidationStates: '-2',
		period: 2,
		groupNumber: 16,
		atomicRadius: 48,
		ionizationEnergy: 1314,
		practiceQuestions: [
			{
				question: "What percentage of Earth's atmosphere is oxygen?",
				options: ['21%', '78%', '1%', '50%'],
				answer: 0,
			},
			{
				question: 'What gas do plants release during photosynthesis?',
				options: ['Nitrogen', 'Oxygen', 'Carbon dioxide', 'Hydrogen'],
				answer: 1,
			},
			{
				question: 'Oxygen has what electronegativity value?',
				options: ['2.1', '3.0', '3.44', '4.0'],
				answer: 2,
			},
		],
		properties: generateProperties(
			8,
			'15.999',
			2,
			16,
			'[He] 2s² 2p⁴',
			3.44,
			'0.00143 g/cm³',
			'-218.79°C',
			'-182.95°C',
			'-2'
		),
	},
	9: {
		num: 9,
		sym: 'F',
		name: 'Fluorine',
		mass: '18.998',
		group: 'halogen',
		category: 'Halogen',
		description: 'Fluorine is the most electronegative element.',
		discovery: 'Henri Moissan, 1886',
		uses: ['Toothpaste', 'Water fluoridation', 'Teflon', 'Refrigerants'],
		electronConfig: '[He] 2s² 2p⁵',
		electronegativity: 3.98,
		density: '0.0017 g/cm³',
		meltingPoint: '-219.62°C',
		boilingPoint: '-188.12°C',
		oxidationStates: '-1',
		period: 2,
		groupNumber: 17,
		atomicRadius: 42,
		ionizationEnergy: 1681,
		practiceQuestions: [
			{
				question: "What is fluorine's electronegativity?",
				options: ['2.1', '3.0', '3.98', '4.5'],
				answer: 2,
			},
			{
				question: 'Fluorine is the most reactive element. Which group?',
				options: ['Alkali metals', 'Noble gases', 'Halogens', 'Oxygen group'],
				answer: 2,
			},
		],
		properties: generateProperties(
			9,
			'18.998',
			2,
			17,
			'[He] 2s² 2p⁵',
			3.98,
			'0.0017 g/cm³',
			'-219.62°C',
			'-188.12°C',
			'-1'
		),
	},
	10: {
		num: 10,
		sym: 'Ne',
		name: 'Neon',
		mass: '20.180',
		group: 'noble',
		category: 'Noble Gas',
		description: 'Neon glows reddish-orange in discharge tubes.',
		discovery: 'William Ramsay & Morris Travers, 1898',
		uses: ['Neon signs', 'Lasers', 'Lightning arresters', 'Cryogenic refrigerant'],
		electronConfig: '[He] 2s² 2p⁶',
		electronegativity: null,
		density: '0.0009 g/cm³',
		meltingPoint: '-248.59°C',
		boilingPoint: '-246.08°C',
		oxidationStates: '0',
		period: 2,
		groupNumber: 18,
		atomicRadius: 38,
		ionizationEnergy: 2081,
		practiceQuestions: [
			{
				question: 'Neon has a full outer shell. How many electrons?',
				options: ['2', '8', '10', '18'],
				answer: 1,
			},
			{
				question: 'What color does neon glow?',
				options: ['Blue', 'Green', 'Reddish-orange', 'Yellow'],
				answer: 2,
			},
		],
		properties: generateProperties(
			10,
			'20.180',
			2,
			18,
			'[He] 2s² 2p⁶',
			null,
			'0.0009 g/cm³',
			'-248.59°C',
			'-246.08°C',
			'0'
		),
	},
	13: {
		num: 13,
		sym: 'Al',
		name: 'Aluminium',
		mass: '26.982',
		group: 'metal',
		category: 'Post-Transition Metal',
		description: "Aluminium is the most abundant metal in Earth's crust.",
		discovery: 'Hans Christian Ørsted, 1825',
		uses: ['Aircraft', 'Packaging', 'Construction', 'Electrical wiring'],
		electronConfig: '[Ne] 3s² 3p¹',
		electronegativity: 1.61,
		density: '2.698 g/cm³',
		meltingPoint: '660.32°C',
		boilingPoint: '2519°C',
		oxidationStates: '+3',
		period: 3,
		groupNumber: 13,
		atomicRadius: 118,
		ionizationEnergy: 578,
		practiceQuestions: [
			{
				question: 'What is the main ore of aluminium?',
				options: ['Iron ore', 'Bauxite', 'Copper ore', 'Zinc ore'],
				answer: 1,
			},
			{
				question: 'Aluminium has how many valence electrons?',
				options: ['1', '2', '3', '4'],
				answer: 2,
			},
		],
		properties: generateProperties(
			13,
			'26.982',
			3,
			13,
			'[Ne] 3s² 3p¹',
			1.61,
			'2.698 g/cm³',
			'660.32°C',
			'2519°C',
			'+3'
		),
	},
	14: {
		num: 14,
		sym: 'Si',
		name: 'Silicon',
		mass: '28.086',
		group: 'metalloid',
		category: 'Metalloid',
		description: 'Silicon is the basis of the semiconductor industry.',
		discovery: 'Jöns Jacob Berzelius, 1824',
		uses: ['Computer chips', 'Solar cells', 'Glass', 'Concrete'],
		electronConfig: '[Ne] 3s² 3p²',
		electronegativity: 1.9,
		density: '2.33 g/cm³',
		meltingPoint: '1414°C',
		boilingPoint: '3265°C',
		oxidationStates: '-4, +4',
		period: 3,
		groupNumber: 14,
		atomicRadius: 111,
		ionizationEnergy: 786,
		practiceQuestions: [
			{
				question: 'Silicon is used in what modern technology?',
				options: ['Building', 'Computer chips', 'Paint', 'Fertilizers'],
				answer: 1,
			},
			{
				question: 'Silicon dioxide is commonly known as?',
				options: ['Salt', 'Sand', 'Sugar', 'Lime'],
				answer: 1,
			},
		],
		properties: generateProperties(
			14,
			'28.086',
			3,
			14,
			'[Ne] 3s² 3p²',
			1.9,
			'2.33 g/cm³',
			'1414°C',
			'3265°C',
			'-4, +4'
		),
	},
	15: {
		num: 15,
		sym: 'P',
		name: 'Phosphorus',
		mass: '30.974',
		group: 'nonmetal',
		category: 'Polyatomic Nonmetal',
		description: 'Phosphorus is essential for life (DNA, RNA, ATP, bones).',
		discovery: 'Hennig Brand, 1669',
		uses: ['Fertilizers', 'Matches', 'Detergents', 'Steel production'],
		electronConfig: '[Ne] 3s² 3p³',
		electronegativity: 2.19,
		density: '1.82 g/cm³',
		meltingPoint: '44.15°C',
		boilingPoint: '280.5°C',
		oxidationStates: '-3, +3, +5',
		period: 3,
		groupNumber: 15,
		atomicRadius: 98,
		ionizationEnergy: 1012,
		practiceQuestions: [
			{
				question: 'Phosphorus is essential for life. Where is it found?',
				options: ['Blood', 'Bones and teeth', 'Skin', 'Hair'],
				answer: 1,
			},
			{
				question: 'White phosphorus must be stored under water because it:',
				options: ['Dissolves', 'Too heavy', 'Catches fire in air', 'Radioactive'],
				answer: 2,
			},
		],
		properties: generateProperties(
			15,
			'30.974',
			3,
			15,
			'[Ne] 3s² 3p³',
			2.19,
			'1.82 g/cm³',
			'44.15°C',
			'280.5°C',
			'-3, +3, +5'
		),
	},
	16: {
		num: 16,
		sym: 'S',
		name: 'Sulfur',
		mass: '32.06',
		group: 'nonmetal',
		category: 'Polyatomic Nonmetal',
		description: 'Sulfur is a bright yellow crystalline solid.',
		discovery: 'Known since ancient times',
		uses: ['Sulfuric acid', 'Fertilizers', 'Vulcanization of rubber', 'Gunpowder'],
		electronConfig: '[Ne] 3s² 3p⁴',
		electronegativity: 2.58,
		density: '2.067 g/cm³',
		meltingPoint: '115.21°C',
		boilingPoint: '444.72°C',
		oxidationStates: '-2, +4, +6',
		period: 3,
		groupNumber: 16,
		atomicRadius: 88,
		ionizationEnergy: 1000,
		practiceQuestions: [
			{
				question: 'Which amino acids contain sulfur?',
				options: [
					'Glycine & Alanine',
					'Cysteine & Methionine',
					'Lysine & Arginine',
					'Serine & Threonine',
				],
				answer: 1,
			},
			{
				question: 'Sulfur has what odor?',
				options: ['Rotten eggs', 'Roses', 'Ammonia', 'Vinegar'],
				answer: 0,
			},
		],
		properties: generateProperties(
			16,
			'32.06',
			3,
			16,
			'[Ne] 3s² 3p⁴',
			2.58,
			'2.067 g/cm³',
			'115.21°C',
			'444.72°C',
			'-2, +4, +6'
		),
	},
	17: {
		num: 17,
		sym: 'Cl',
		name: 'Chlorine',
		mass: '35.45',
		group: 'halogen',
		category: 'Halogen',
		description: 'Chlorine is a yellow-green gas with a pungent odor.',
		discovery: 'Carl Wilhelm Scheele, 1774',
		uses: ['Water purification', 'PVC production', 'Bleach', 'Disinfectants'],
		electronConfig: '[Ne] 3s² 3p⁵',
		electronegativity: 3.16,
		density: '0.00321 g/cm³',
		meltingPoint: '-101.5°C',
		boilingPoint: '-34.04°C',
		oxidationStates: '-1, +1, +3, +5, +7',
		period: 3,
		groupNumber: 17,
		atomicRadius: 79,
		ionizationEnergy: 1251,
		practiceQuestions: [
			{
				question: 'What ion does chlorine form?',
				options: ['Cation (+)', 'Anion (-)', 'Neutral', 'No ion'],
				answer: 1,
			},
			{
				question: "What is table salt's formula?",
				options: ['NaCl', 'KCl', 'CaCl₂', 'MgCl₂'],
				answer: 0,
			},
			{
				question: 'Chlorine gas has what color?',
				options: ['Red', 'Yellow-green', 'Blue', 'Purple'],
				answer: 1,
			},
		],
		properties: generateProperties(
			17,
			'35.45',
			3,
			17,
			'[Ne] 3s² 3p⁵',
			3.16,
			'0.00321 g/cm³',
			'-101.5°C',
			'-34.04°C',
			'-1, +1, +3, +5, +7'
		),
	},
	18: {
		num: 18,
		sym: 'Ar',
		name: 'Argon',
		mass: '39.948',
		group: 'noble',
		category: 'Noble Gas',
		description: "Argon makes up 0.93% of Earth's atmosphere.",
		discovery: 'Lord Rayleigh & William Ramsay, 1894',
		uses: ['Welding', 'Light bulbs', 'Cryosurgery', 'Fire extinguishers'],
		electronConfig: '[Ne] 3s² 3p⁶',
		electronegativity: null,
		density: '0.00178 g/cm³',
		meltingPoint: '-189.34°C',
		boilingPoint: '-185.85°C',
		oxidationStates: '0',
		period: 3,
		groupNumber: 18,
		atomicRadius: 71,
		ionizationEnergy: 1521,
		practiceQuestions: [
			{
				question: 'Argon is used in welding. Why?',
				options: ['Burns', 'Inert', 'Cheap', 'Reactive'],
				answer: 1,
			},
			{
				question: 'What percent of atmosphere is argon?',
				options: ['0.03%', '0.93%', '5%', '21%'],
				answer: 1,
			},
		],
		properties: generateProperties(
			18,
			'39.948',
			3,
			18,
			'[Ne] 3s² 3p⁶',
			null,
			'0.00178 g/cm³',
			'-189.34°C',
			'-185.85°C',
			'0'
		),
	},
	33: {
		num: 33,
		sym: 'As',
		name: 'Arsenic',
		mass: '74.92',
		group: 'metalloid',
		category: 'Metalloid',
		description: 'Arsenic is a metalloid known for its toxicity.',
		discovery: 'Albertus Magnus, 1250',
		uses: ['Semiconductors', 'Wood preservation', 'Pesticides', 'Medical treatments'],
		electronConfig: '[Ar] 3d¹⁰ 4s² 4p³',
		electronegativity: 2.18,
		density: '5.776 g/cm³',
		meltingPoint: '817°C',
		boilingPoint: '614°C',
		oxidationStates: '-3, +3, +5',
		period: 4,
		groupNumber: 15,
		atomicRadius: 114,
		ionizationEnergy: 947,
		practiceQuestions: [
			{
				question: 'Arsenic is classified as:',
				options: ['Metal', 'Nonmetal', 'Metalloid', 'Noble gas'],
				answer: 2,
			},
			{
				question: 'Arsenic is known for being:',
				options: ['Essential nutrient', 'Highly toxic', 'Radioactive', 'Magnetic'],
				answer: 1,
			},
		],
		properties: generateProperties(
			33,
			'74.92',
			4,
			15,
			'[Ar] 3d¹⁰ 4s² 4p³',
			2.18,
			'5.776 g/cm³',
			'817°C',
			'614°C',
			'-3, +3, +5'
		),
	},
	34: {
		num: 34,
		sym: 'Se',
		name: 'Selenium',
		mass: '78.97',
		group: 'nonmetal',
		category: 'Polyatomic Nonmetal',
		description: 'Selenium is essential in small amounts for cellular function.',
		discovery: 'Jöns Jacob Berzelius, 1817',
		uses: ['Glass production', 'Electronics', 'Photocells', 'Dietary supplements'],
		electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁴',
		electronegativity: 2.55,
		density: '4.809 g/cm³',
		meltingPoint: '221°C',
		boilingPoint: '685°C',
		oxidationStates: '-2, +4, +6',
		period: 4,
		groupNumber: 16,
		atomicRadius: 103,
		ionizationEnergy: 941,
		practiceQuestions: [
			{
				question: 'Selenium is essential for:',
				options: ['Bone growth', 'Antioxidant defense', 'Water balance', 'Nerve function'],
				answer: 1,
			},
			{
				question: 'Selenium is used in photocells because it:',
				options: [
					'Conducts heat well',
					'Conducts electricity when exposed to light',
					'Is magnetic',
					'Is toxic',
				],
				answer: 1,
			},
		],
		properties: generateProperties(
			34,
			'78.97',
			4,
			16,
			'[Ar] 3d¹⁰ 4s² 4p⁴',
			2.55,
			'4.809 g/cm³',
			'221°C',
			'685°C',
			'-2, +4, +6'
		),
	},
	35: {
		num: 35,
		sym: 'Br',
		name: 'Bromine',
		mass: '79.904',
		group: 'halogen',
		category: 'Halogen',
		description: 'Bromine is one of two liquid elements at room temperature.',
		discovery: 'Carl Jacob Löwig, 1826',
		uses: ['Flame retardants', 'Pesticides', 'Photography', 'Water treatment'],
		electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁵',
		electronegativity: 2.96,
		density: '3.122 g/cm³',
		meltingPoint: '-7.2°C',
		boilingPoint: '58.8°C',
		oxidationStates: '-1, +1, +3, +5',
		period: 4,
		groupNumber: 17,
		atomicRadius: 94,
		ionizationEnergy: 1140,
		practiceQuestions: [
			{
				question: 'Bromine is a liquid at room temperature. What is its symbol?',
				options: ['Br', 'Bm', 'Bo', 'Bn'],
				answer: 0,
			},
			{
				question: 'What state is bromine at room temp?',
				options: ['Solid', 'Liquid', 'Gas', 'Plasma'],
				answer: 1,
			},
		],
		properties: generateProperties(
			35,
			'79.904',
			4,
			17,
			'[Ar] 3d¹⁰ 4s² 4p⁵',
			2.96,
			'3.122 g/cm³',
			'-7.2°C',
			'58.8°C',
			'-1, +1, +3, +5'
		),
	},
	36: {
		num: 36,
		sym: 'Kr',
		name: 'Krypton',
		mass: '83.80',
		group: 'noble',
		category: 'Noble Gas',
		description: 'Krypton is a noble gas used in lighting.',
		discovery: 'William Ramsay & Morris Travers, 1898',
		uses: ['Lighting', 'Lasers', 'Photography', 'Insulated windows'],
		electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁶',
		electronegativity: 3.0,
		density: '0.003733 g/cm³',
		meltingPoint: '-157.36°C',
		boilingPoint: '-153.22°C',
		oxidationStates: '0',
		period: 4,
		groupNumber: 18,
		atomicRadius: 88,
		ionizationEnergy: 1351,
		practiceQuestions: [
			{
				question: 'Krypton is used in what type of light bulb?',
				options: ['Incandescent', 'Fluorescent', 'High-intensity discharge', 'LED'],
				answer: 2,
			},
			{
				question: 'Krypton is classified as:',
				options: ['Alkali metal', 'Noble gas', 'Halogen', 'Transition metal'],
				answer: 1,
			},
		],
		properties: generateProperties(
			36,
			'83.80',
			4,
			18,
			'[Ar] 3d¹⁰ 4s² 4p⁶',
			3.0,
			'0.003733 g/cm³',
			'-157.36°C',
			'-153.22°C',
			'0'
		),
	},
	51: {
		num: 51,
		sym: 'Sb',
		name: 'Antimony',
		mass: '121.8',
		group: 'metalloid',
		category: 'Metalloid',
		description: 'Antimony is used in flame retardants and alloys.',
		discovery: 'Known since ancient times',
		uses: ['Flame retardants', 'Batteries', 'Alloys', 'Semiconductors'],
		electronConfig: '[Kr] 4d¹⁰ 5s² 5p³',
		electronegativity: 2.05,
		density: '6.685 g/cm³',
		meltingPoint: '630.63°C',
		boilingPoint: '1587°C',
		oxidationStates: '-3, +3, +5',
		period: 5,
		groupNumber: 15,
		atomicRadius: 133,
		ionizationEnergy: 834,
		practiceQuestions: [
			{
				question: 'Antimony is classified as a:',
				options: ['Metal', 'Nonmetal', 'Metalloid', 'Noble gas'],
				answer: 2,
			},
			{
				question: 'Antimony is used in:',
				options: ['Paint', 'Flame retardants', 'Food preservation', 'Water treatment'],
				answer: 1,
			},
		],
		properties: generateProperties(
			51,
			'121.8',
			5,
			15,
			'[Kr] 4d¹⁰ 5s² 5p³',
			2.05,
			'6.685 g/cm³',
			'630.63°C',
			'1587°C',
			'-3, +3, +5'
		),
	},
	52: {
		num: 52,
		sym: 'Te',
		name: 'Tellurium',
		mass: '127.6',
		group: 'metalloid',
		category: 'Metalloid',
		description: 'Tellurium is a brittle metalloid.',
		discovery: 'Franz-Joseph Müller von Reichenstein, 1782',
		uses: ['Solar cells', 'Thermoelectric devices', 'Alloys', 'Rubber production'],
		electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁴',
		electronegativity: 2.1,
		density: '6.232 g/cm³',
		meltingPoint: '449.51°C',
		boilingPoint: '988°C',
		oxidationStates: '-2, +4, +6',
		period: 5,
		groupNumber: 16,
		atomicRadius: 123,
		ionizationEnergy: 869,
		practiceQuestions: [
			{
				question: 'Tellurium is classified as a:',
				options: ['Metal', 'Nonmetal', 'Metalloid', 'Halogen'],
				answer: 2,
			},
			{
				question: 'Tellurium is used in:',
				options: ['Solar cells', 'Explosives', 'Medicines', 'Cosmetics'],
				answer: 0,
			},
		],
		properties: generateProperties(
			52,
			'127.6',
			5,
			16,
			'[Kr] 4d¹⁰ 5s² 5p⁴',
			2.1,
			'6.232 g/cm³',
			'449.51°C',
			'988°C',
			'-2, +4, +6'
		),
	},
	53: {
		num: 53,
		sym: 'I',
		name: 'Iodine',
		mass: '126.90',
		group: 'halogen',
		category: 'Halogen',
		description: 'Iodine is essential for thyroid function.',
		discovery: 'Bernard Courtois, 1811',
		uses: ['Antiseptics', 'Thyroid medication', 'Photography', 'Disinfectants'],
		electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁵',
		electronegativity: 2.66,
		density: '4.93 g/cm³',
		meltingPoint: '113.7°C',
		boilingPoint: '184.3°C',
		oxidationStates: '-1, +1, +5, +7',
		period: 5,
		groupNumber: 17,
		atomicRadius: 115,
		ionizationEnergy: 1008,
		practiceQuestions: [
			{
				question: 'Iodine is essential for:',
				options: ['Bone health', 'Thyroid function', 'Blood clotting', 'Muscle growth'],
				answer: 1,
			},
			{
				question: 'Iodine turns blue-black when it contacts:',
				options: ['Water', 'Starch', 'Oil', 'Salt'],
				answer: 1,
			},
		],
		properties: generateProperties(
			53,
			'126.90',
			5,
			17,
			'[Kr] 4d¹⁰ 5s² 5p⁵',
			2.66,
			'4.93 g/cm³',
			'113.7°C',
			'184.3°C',
			'-1, +1, +5, +7'
		),
	},
	54: {
		num: 54,
		sym: 'Xe',
		name: 'Xenon',
		mass: '131.3',
		group: 'noble',
		category: 'Noble Gas',
		description: 'Xenon is a noble gas used in lighting and anesthesia.',
		discovery: 'William Ramsay & Morris Travers, 1898',
		uses: ['Lighting', 'Anesthesia', 'Medical imaging', 'Ion propulsion'],
		electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁶',
		electronegativity: 2.6,
		density: '0.005887 g/cm³',
		meltingPoint: '-111.8°C',
		boilingPoint: '-108.1°C',
		oxidationStates: '0',
		period: 5,
		groupNumber: 18,
		atomicRadius: 108,
		ionizationEnergy: 1170,
		practiceQuestions: [
			{
				question: 'Xenon can form compounds. True or false?',
				options: ['True', 'False'],
				answer: 0,
			},
			{
				question: 'Xenon is used in:',
				options: ['Refrigeration', 'Anesthesia', 'Water treatment', 'Solar panels'],
				answer: 1,
			},
		],
		properties: generateProperties(
			54,
			'131.3',
			5,
			18,
			'[Kr] 4d¹⁰ 5s² 5p⁶',
			2.6,
			'0.005887 g/cm³',
			'-111.8°C',
			'-108.1°C',
			'0'
		),
	},
	85: {
		num: 85,
		sym: 'At',
		name: 'Astatine',
		mass: '210.0',
		group: 'halogen',
		category: 'Halogen',
		description: 'Astatine is the rarest naturally occurring element.',
		discovery: 'Dale R. Corson, Kenneth Ross MacKenzie & Emilio Segrè, 1940',
		uses: ['Cancer treatment (research)', 'Radiotherapy research'],
		electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵',
		electronegativity: 2.2,
		density: '7 g/cm³',
		meltingPoint: '302°C',
		boilingPoint: '337°C',
		oxidationStates: '-1, +1',
		period: 6,
		groupNumber: 17,
		atomicRadius: 127,
		ionizationEnergy: 890,
		practiceQuestions: [
			{
				question: 'Astatine is the rarest naturally occurring element. True or false?',
				options: ['True', 'False'],
				answer: 0,
			},
			{
				question: 'Astatine belongs to which group?',
				options: ['Alkali metals', 'Halogens', 'Noble gases', 'Chalcogens'],
				answer: 1,
			},
		],
		properties: generateProperties(
			85,
			'210.0',
			6,
			17,
			'[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵',
			2.2,
			'7 g/cm³',
			'302°C',
			'337°C',
			'-1, +1'
		),
	},
	86: {
		num: 86,
		sym: 'Rn',
		name: 'Radon',
		mass: '222.0',
		group: 'noble',
		category: 'Noble Gas',
		description: 'Radon is a radioactive noble gas.',
		discovery: 'Friedrich Ernst Dorn, 1900',
		uses: ['Cancer treatment (historical)', 'Earthquake prediction research'],
		electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶',
		electronegativity: null,
		density: '0.00973 g/cm³',
		meltingPoint: '-71°C',
		boilingPoint: '-61.7°C',
		oxidationStates: '0',
		period: 6,
		groupNumber: 18,
		atomicRadius: 120,
		ionizationEnergy: 1037,
		practiceQuestions: [
			{
				question: 'Radon is a radioactive noble gas. True or false?',
				options: ['True', 'False'],
				answer: 0,
			},
			{
				question: 'Radon can accumulate in:',
				options: ['Outer space', 'Buildings', 'Oceans', 'Atmosphere'],
				answer: 1,
			},
		],
		properties: generateProperties(
			86,
			'222.0',
			6,
			18,
			'[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶',
			null,
			'0.00973 g/cm³',
			'-71°C',
			'-61.7°C',
			'0'
		),
	},
};
